### ISSUE TITLE
Python2 Support(?)

### ISSUE THREAD

**Issue by Naville** [lief-project/LIEF#10]
I was trying out the python2 version and print (binary) doesn't work due to ASCII encoding issues.
Seems like 

```
import sys
reload(sys)
sys.setdefaultencoding('utf8')
```
can solve this (at least for me on MacOS  X). Thus I opened a issue here so fellow users might find this useful

maybe it's better to add this to README (or python code) to warn py2 users?

**Comment by Naville** [comment]
also which part of the C++ source should I modify to include new LCs?

**Comment by romainthomas** [comment]
@Naville for which kind of binary it occurs (ELF, PE, Mach-O) ? 

> to include new LCs?

I'm not sure to understand

**Comment by Naville** [comment]
it's just print(binary) . Python2 defaults to ASCII (I believe) and results in that error. run  those three lines of python code can solve this.

As for the latter question. What I mean is that I noticed some LoadCommands for MachO is currently not supported and I'd like to help contribute. However I currently don't know which part of the code should I modify to achieve this

**Comment by romainthomas** [comment]
Ok I will look on the encoding.

To parse new ``LoadCommand`` for the Mach-O format you can look at:

* [MachO::BinaryParser::parse_load_commands](https://github.com/lief-project/LIEF/blob/master/src/MachO/BinaryParser.tcc#L30)
* [UUID command](https://github.com/lief-project/LIEF/blob/master/src/MachO/BinaryParser.tcc#L103)

I will be glad to accept your PR !
