### ISSUE TITLE
Version mismatch: 0.7.0 / 0.8.0

### ISSUE THREAD

**Issue by wagner-certat** [lief-project/LIEF#100]
The files attached to release/tag version [0.8.0](https://github.com/lief-project/LIEF/releases/tag/0.8.0) have the version specifier 0.7.0:

> LIEF-0.7.0-Darwin.tar.gz
> LIEF-0.7.0-Linux.tar.gz
> lief-0.7.0-py2.7-linux.egg
> lief-0.7.0-py2.7-osx.egg
> lief-0.7.0-py2.7-windows_x32.egg
> lief-0.7.0-py2.7-windows_x64.egg
> lief-0.7.0-py3.5-linux.egg
> lief-0.7.0-py3.5-osx.egg
> lief-0.7.0-py3.5-windows_x32.egg
> lief-0.7.0-py3.5-windows_x64.egg
> lief-0.7.0-py3.6-linux.egg
> lief-0.7.0-py3.6-osx.egg
> lief-0.7.0-py3.6-windows_x32.egg
> lief-0.7.0-py3.6-windows_x64.egg
> LIEF-0.7.0-win32.zip
> LIEF-0.7.0-win64.zip
> pylief-0.7.0.zip

**Comment by romainthomas** [comment]
Yes it was a build error. v0.8.0 is coming soon

**Comment by wagner-certat** [comment]
Ok, thanks!
