### ISSUE TITLE
RISC-V Support for Writing 

### ISSUE THREAD

**Issue by romainthomas** [lief-project/LIEF#1001]
LIEF should be able to write-back RISC-V binaries while currently it only supports parsing.

**Comment by byronwatt** [comment]
I'm trying to modify some symbols in a riscv elf file using [WrapMaster.py](https://github.com/wafgo/WrapMaster/blob/master/WrapMaster.py),

but after rewriting the .o files the linker is complaining with:

sample.c:(.text.sample+0x32): dangerous relocation: %pcrel_lo missing matching %pcrel_hi

i was hoping the RISC-V binary problem was only regarding adding new sections, but does it also just not work for modifying symbols ?

**Comment by romainthomas** [comment]
Should be available now
