### ISSUE TITLE
Relocation R32 not supported!  x86 Android ELF

### ISSUE THREAD

**Issue by antipatico** [lief-project/LIEF#1003]
**Describe the bug**
When trying to save an x86 modified binary using LIEF, the following error/warning occurs many many times:

```
Relocation R32 not supported!
Relocation R32 not supported!
Relocation R32 not supported!
Relocation R32 not supported!
[...]
```

**To Reproduce**
Download the attached library and run the following python script
```python
lib = 'libc++_shared.so' # Download this and put in your cwd

print(f"lief parse {lib}", file=sys.stderr, flush=True)
elf = lief.parse(f"{lib}")
if elf is None:
    raise Exception()
print(f"lief add_library {lib}", file=sys.stderr, flush=True)
elf.add_library('libgadget.so')
print(f"lief write {lib}", file=sys.stderr, flush=True)
elf.write(f"{lib}.patched")
print(f"lief done", file=sys.stderr, flush=True)
```

**Expected behavior**
The library should be result in a patched library (`libc++_shared.so.patched`) without error on STDERR.

**Environment (please complete the following information):**
 - System and Version : Debian 12 x86_64
 - Target format ELF
 - LIEF commit version: 0.13.2-2d9855fc
**Additional context**
I am attaching the offending library + and the full output log.
It is worth to note that the patched binary seems to have the new library in the ELF:
```
$ readelf -d libc++_shared.so  | rg NEEDED
 0x00000001 (NEEDED)                     Shared library: [libgadget.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so]
 0x00000001 (NEEDED)                     Shared library: [libdl.so]
```
Unfortunately, I am having problems with Android x86 emulator and I cannot test if the library correctly loads after the patch.
Moreover, I did not test on other ELF files, it may be worth a shot.
I tried to look in the codebase to locate the error/warning without luck.

**Attachments**
[libc++_shared.zip](https://github.com/lief-project/LIEF/files/13627451/libc%2B%2B_shared.zip)
[log.txt](https://github.com/lief-project/LIEF/files/13627452/log.txt)

**Comment by romainthomas** [comment]
Thank you @antipatico for opening this issue. The `R32` should be supported by LIEF and I'll fix that soon. 
Thank you as well for your sponsorship. Feel to drop a DM if you need any special support or help!
