### ISSUE TITLE
support relocation for PE

### ISSUE THREAD

**Issue by ParkHanbum** [lief-project/LIEF#101]
hello, is there any plan for supporting relocation?
cause, relocation is big part of security at binary level. 
as you know, ASLR need it.

I was implement that like this: 

    code = ("push 0;"   # UINT    uType
            "push {};"   # LPCTSTR lpCaption,
            "push {};"   # LPCTSTR lpText,
            "push 0;"   # HWND    hWnd
            "call [{}];").format(allocation_va + caption_start_pos,
                                 allocation_va + text_start_pos,
                                 fn_va)
    code_rva = pe_instrument.append_code(code)

    # TODO : need a way for does not calculate the relocation address directly.
    pe_manager.register_rva_to_relocation(code_rva
                                          + 3   # push 0; push
                                          )
    pe_manager.register_rva_to_relocation(code_rva
                                          + 3   # push 0; push
                                          + 5   # lpCaption;push
                                          )
    pe_manager.register_rva_to_relocation(code_rva
                                          + 3   # push 0; push
                                          + 5   # lpCaption;push
                                          + 4   # lptext
                                          + 2   # push 0;
                                          + 2   # call
                                          )

but still need more practice for abstract and usability.

**Comment by romainthomas** [comment]
What about [add_relocation](https://lief.quarkslab.com/doc/api/python/pe.html#lief.PE.Binary.add_relocation) with 
[lief.PE.Builder.build_relocations](https://lief.quarkslab.com/doc/api/python/pe.html#lief.PE.Builder.build_relocations) set to true ?

**Comment by ParkHanbum** [comment]
@romainthomas thank you. I was miss it!
