### ISSUE TITLE
ELF .bss section is expanded on rebuild

### ISSUE THREAD

**Issue by tezeb** [lief-project/LIEF#1010]
**Describe the bug**
When rebuilding an ELF with a big .bss section, it is expanded to it's "size", while in original binary it does not occupy space. The space is filled with zeros.

**To Reproduce**
```c
struct {
  char arr[16][1000000];
} bigOne;

int main() {
  return 0;
}
```
Compile:
`gcc -o t test.c`
Try modifying with:
```python
import lief

elf = lief.parse("t")
elf.add_library('libmods.so')
elf.write("t_mod")
```

Output:
```
-rwxr-xr-x 1 user user    15256 Jan  7 22:31 t
-rw-r--r-- 1 user user 16021408 Jan  7 22:31 t_mod
```

**Expected behavior**
.bss section should not be expanded

**Environment (please complete the following information):**
 - System and Version : Arch
 - Target format : ELF
 - LIEF commit version: 0.13.2-2d9855fc

**Comment by romainthomas** [comment]
https://github.com/lief-project/LIEF/issues/973#issuecomment-1738390993

**Comment by tezeb** [comment]
@romainthomas thank you for the answer, but I don't really understand it. While expanding .bss may make sense during rebuilding, it should not be kept while saving the file. The expanded section is not even included in the segment, as it's FileSize stays unmodified. 
Not only that, but it also seems that storing section marked as `NOBITS` is not correct from [the documentation perspective](https://refspecs.linuxbase.org/elf/elf.pdf).
I would be happy to suggest a fix for this, but the complexity of the codebase is quite overwhelming. Would you mind pointing me into right direction?

**Comment by romainthomas** [comment]
Hi @tezeb 

You can find the code that manages this bss-extension here:

https://github.com/lief-project/LIEF/blob/bcd9b27df37a740c85b60704da2b1f048fefc392/src/ELF/Binary.cpp#L2993-L3179

> Not only that, but it also seems that storing section marked as NOBITS is not correct from [the documentation perspective](https://refspecs.linuxbase.org/elf/elf.pdf).

Humm LIEF does not perform this kind of change, it comes the compiler. 

I'll be happy to integrate your PR if you find a better solution to handle this case!
