### ISSUE TITLE
Request for C++ Code Example to Extract PDB from PE File

### ISSUE THREAD

**Issue by Alesan** [lief-project/LIEF#1012]
Dear LIEF Team,

My name is Alejandro, and I am seeking a C++ code example to extract the PDB from a PE file. Could you please provide a simple example?

Thank you for your attention, and I look forward to your prompt response.

Best regards,
Alejandro

**Comment by ZehMatt** [comment]
The data is within the debug directory. So grab the RVA of that directory, convert that to offset, read the contents of IMAGE_DEBUG_DIRECTORY, check the Type field and if its IMAGE_DEBUG_TYPE_CODEVIEW use the AddressOfRawData to obtain CV_INFO_PDB70 by AddressOfRawData

An example how to read this can be found here https://jpassing.com/2009/04/22/uniquely-identifying-a-modules-build/, it doesn't use LIEF but the principle is the same.

**Comment by romainthomas** [comment]
As @ZehMatt mention + the API is here: https://github.com/lief-project/LIEF/blob/58f499a22221cee7ab6682986b1504b90acd8556/include/LIEF/PE/debug/CodeViewPDB.hpp#L54-L56
