### ISSUE TITLE
Regression in LIEF::ELF::SymbolVersionDefinition::symbols_aux

### ISSUE THREAD

**Issue by adamjseitz** [lief-project/LIEF#1014]
**Describe the bug**

The function `LIEF::ELF::SymbolVersionDefinition::symbols_aux` appears to return incorrect info starting in 0.14.0.

**To Reproduce**

Use LIEF to iterate each `SymbolVersionDefinition` and each `symbols_aux` from the attached binary:

```cpp
#include <LIEF/LIEF.hpp>
#include <iostream>

int main(void)
{
    std::string Path = "./libfoo.so";
    std::unique_ptr<LIEF::ELF::Binary> Elf = LIEF::ELF::Parser::parse(Path);

    for(LIEF::ELF::SymbolVersionDefinition &Def : Elf->symbols_version_definition())
    {
        std::cout << "SymVerDef " << Def.ndx() << "\n";
        for(LIEF::ELF::SymbolVersionAux &SymAux : Def.symbols_aux())
        {
            std::cout << "\t" << SymAux.name() << "\n";
        }
    }

    return 0;
}
```

[libfoo.so.gz](https://github.com/lief-project/LIEF/files/14015905/libfoo.so.gz)

This program prints the following: 

```
SymVerDef 1
        libfoo.so
SymVerDef 2
        LIBFOO_1.0
SymVerDef 3
        LIBFOO_2.0
        LIBFOO_2.0
SymVerDef 4
        LIBFOO_3.0
        LIBFOO_3.0
SymVerDef 5
        LIBBAR_1.0
SymVerDef 6
        LIBBAR_2.0
        LIBBAR_2.0
```

Notice the repeated names for each symver aux entry.

**Expected behavior**

With LIEF 0.13.2 and older, this program printed the name for the symbol version definition, followed by the name of its predecessor versions:

```
SymVerDef 1
        libfoo.so
SymVerDef 2
        LIBFOO_1.0
SymVerDef 3
        LIBFOO_2.0
        LIBFOO_1.0
SymVerDef 4
        LIBFOO_3.0
        LIBFOO_2.0
SymVerDef 5
        LIBBAR_1.0
SymVerDef 6
        LIBBAR_2.0
        LIBBAR_1.0
```

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04
 - Target format ELF
 - LIEF commit version: `0.14.0-16962f2f`

**Additional context**

Here's `readelf` of the `.gnu.version_d` section:

```
Version definition section '.gnu.version_d' contains 6 entries:
 Addr: 0x00000000000005a0  Offset: 0x0005a0  Link: 5 (.dynstr)
  000000: Rev: 1  Flags: BASE  Index: 1  Cnt: 1  Name: libfoo.so
  0x001c: Rev: 1  Flags: none  Index: 2  Cnt: 1  Name: LIBFOO_1.0
  0x0038: Rev: 1  Flags: none  Index: 3  Cnt: 2  Name: LIBFOO_2.0
  0x0054: Parent 1: LIBFOO_1.0
  0x005c: Rev: 1  Flags: none  Index: 4  Cnt: 2  Name: LIBFOO_3.0
  0x0078: Parent 1: LIBFOO_2.0
  0x0080: Rev: 1  Flags: WEAK  Index: 5  Cnt: 1  Name: LIBBAR_1.0
  0x009c: Rev: 1  Flags: WEAK  Index: 6  Cnt: 2  Name: LIBBAR_2.0
  0x00b8: Parent 1: LIBBAR_1.0
```

Relevant spec: https://refspecs.linuxfoundation.org/LSB_3.0.0/LSB-PDA/LSB-PDA.junk/symversion.html

**Comment by romainthomas** [comment]
Thanks @adamjseitz for reporting this regression I'll fix it ASAP!
