### ISSUE TITLE
pyright typing error: "ELF" is not a known member of module "lief" (reportAttributeAccessIssue)

### ISSUE THREAD

**Issue by adamjseitz** [lief-project/LIEF#1017]
**Describe the bug**
When type-checking Python code that imports `lief.ELF`, pyright generates the following error:

```
"ELF" is not a known member of module "lief" (reportAttributeAccessIssue)
```

**To Reproduce**

```
$ cat test.py
import lief

lief.ELF.parse("/usr/bin/ls")

$ pyright test.py
/home/aseitz/lief-typing-test/test.py
  /home/aseitz/lief-typing-test/test.py:3:6 - error: "ELF" is not a known member of module "lief" (reportAttributeAccessIssue)
1 error, 0 warnings, 0 informations
```

**Expected behavior**
pyright should not generate any errors.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04
 - Target format : ELF
 - LIEF commit version: `0.14.0-16962f2f`

**Additional context**
This is a regression in 0.14.0. Pyright generates no errors for the same script with lief 0.13.2.

**Comment by genbtc** [comment]
If I had to guess I would say its this commit right here:
https://github.com/lief-project/LIEF/commit/529d5a8679c7da94954ea1369875707c57d89155#diff-52d61b00d409b2196330cc6abe8036885d26f9d2eb36d8d8f070134b5e92e302

**Comment by romainthomas** [comment]
On going fix.
