### ISSUE TITLE
support instrument to code.

### ISSUE THREAD

**Issue by ParkHanbum** [lief-project/LIEF#102]
According to Tutorial 6,
When we need code to instrument in the code section, we assemble the code to be instrumented and get the compiled hex code. By the way, how can I instrument a compiled hex code?

so, I have a question for it.
is LIEF have plan for support to instrument and manipulate instructions at code section?

I have some experience with it. 

1. support assembly with keystone. like this,

```
def simple_instrument_return_address_at_after_branch(instruction):
    code = ("prefetch [{0}]".format(instruction.address
                                    + instruction.size
                                    + 0x1000))
    hex_code = binascii.hexlify(code).decode('hex')
    try:
        # Initialize engine in X86-32bit mode
        ks = Ks(KS_ARCH_X86, KS_MODE_32)
        encoding, count = ks.asm(hex_code)
        return encoding, count
    except KsError as ex:
        print("ERROR: %s" % ex)
    return None, 0

```

2. insert hexa-code at code section by given relative address. like this,

```
void Binary::instrument_address(uint64_t address, std:vector<uint8_t>& instrument_value, size_t size) {
  if (size > sizeof(patch_value)) {
    throw std::runtime_error("Invalid size (" + std::to_string(size) + ")");
  }

  Section& section_topatch = this->section_from_rva(address);
  const uint64_t offset = address - section_topatch.virtual_address();
  std::vector<uint8_t>& content = section_topatch.content();
  std::vector<uint8_t>::iterator iter;
  iter = content.begin();
  content.insert(it + offset, instrument_begin(), instrument.end());
}
```

3. adjust all direct and indirect branches, also point of data, resource, and so on. this can be done with using relocation section. if file doesn't support relocation, this couldn't possible. (restrict) for support this, we need powerful disassembler. I used capstone, and it support variable architecture. 

keystone & capstone support C, C++ and other many script languages. also can be compile with windows, linux.

how do you think?

**Comment by romainthomas** [comment]
Well I want to keep LIEF focusing on executable formats **only**. Thus there won't be a assembler/disassembler in this project. It's a design choice and not a problem of support (language/platform)
