### ISSUE TITLE
Mach-O: iteration of `binary.relocations` is very slow in version 0.14.0

### ISSUE THREAD

**Issue by sledgeh4w** [lief-project/LIEF#1022]
**Describe the bug**
I use `binary.relocations` to progress Mach-O file. After I upgraded to version 0.14.0 (from 0.13.2), I found that its speed became unusually slow, but I found that the speed of `binary.segment.relocations` was normal.

**To Reproduce**
```python
import lief

# A binary file from iOS application with 500,000 relocations.
binary = lief.parse("zsch")

# Fast
for segment in binary.segments:
    for _ in segment.relocations:
        pass

# Very slow, running for over a few tens of minutes.
# From my observation, as this iteration progresses, the speed continues to decrease.
for _ in binary.relocations:
    pass

# In version 0.13.2, both of the above are very fast.
```

**Expected behavior**
This iteration should end in a very short period of time.

**Environment (please complete the following information):**
 - System and Version: Windows 11
 - Target format:  Mach-O
 - LIEF commit version: 0.14.0-16962f2f

**Additional context**
The binary file.
[zsch.zip](https://github.com/lief-project/LIEF/files/14213292/zsch.zip)

**Comment by romainthomas** [comment]
I confirm this issue, thanks a bunch @sledgeh4w for identifying this regression !
