### ISSUE TITLE
get_content_from_virtual_address returns wrong checked_size value

### ISSUE THREAD

**Issue by RomainBrault** [lief-project/LIEF#1023]
**Describe the bug**
```get_content_from_virtual_address```' s variable ```checked_size``` can be negative before static cast in LIEF/src/ELF/Binary.cpp line 1736.f

My guess on what's happening:

in

```cpp
  if ((offset + checked_size) > content.size()) {
    checked_size = checked_size - (offset + checked_size - content.size());
  }
```
the wrap ```(offset + checked_size - content.size())```  can be greater than ```check_size``` since ```content.size()``` returns the size of the segment on the file and not the virtual size of the segment (plus the fact that offset is actually a difference of virtual addresses and not file offset).

```get_content_from_virtual_address``` should use ```content.virtual_size()```

**To Reproduce**
any binary where the segment size on the file is smaller than the virtual size and use get_content_from_virtual_address on an address greater than the segment file size but smaller than the virtual size.

**Expected behavior**
checked_size should always be positive at any time

**Environment (please complete the following information):**
 - System and Version : Ubuntu 23.10
 - Target format: ELF,  possibly Mach-O
 - LIEF commit version: 0.14.1-bae887e0

**Additional context**

**Comment by RomainBrault** [comment]
And i believe also return a zero filled span if offset > content.size.

**Comment by romainthomas** [comment]
Hi @RomainBrault you are completely right!

Actually this case happens when you try to read an address that is in the `.bss`-like area. 
The bss area is known to be set at 0 when loaded but don't have a representation in the file.

I'll see to address this problem.
