### ISSUE TITLE
Does lief support unlinked object files for static libraries in ELF format

### ISSUE THREAD

**Issue by Joshua-Schroijen** [lief-project/LIEF#1027]
Hello everyone,

I am relatively new to using LIEF, but loving it so far! I was just wondering whether LIEF explicitly supports reading ELF object files representing static libraries that are not (fully) linked yet. These files have no program header and only have defined sections, not segments (as one can see with readelf -S -l when using the GNU Binutils).

The reason I am asking is that I want to extract functions' code from these files and emulate them in a CI/CD pipeline, and hence I need to be able to really rely on parsing object files to be done correctly.

Thank you in advance and best regards,  
Joshua SCHROIJEN

**Comment by romainthomas** [comment]
Hi @Joshua-Schroijen 

As of now, LIEF does not support reading/writing static libraries. You should first extract the object files from the library and then process them with LIEF.
