### ISSUE TITLE
MachO: Support for overlay

### ISSUE THREAD

**Issue by prabhu** [lief-project/LIEF#1028]
*Please describe what you would like to have in LIEF*.
Binaries produced from dotnet have useful dependency dll information under the overlay.

For PE and ELF, we can access this attribute and retrieve the information. I am unable to find this attribute for MachO, so I was wondering if this is missing or if the information is available elsewhere.

**Note: If the feature is not precise or if you want to have feedback first, you can open a [discussion](https://github.com/lief-project/LIEF/discussions).**

**Comment by romainthomas** [comment]
I'll take a look at this overlay support in Mach-O. Thank you @prabhu for raising this point.

**Comment by romainthomas** [comment]
Hi @prabhu 
Do you have an example of Mach-O binary that would have an overlay?

**Comment by prabhu** [comment]
@romainthomas any dotnet executable can be used. Below are couple of binaries. Please feel free to use them for testing purposes.

https://github.com/owasp-dep-scan/dosai/releases/download/v0.1.1/Dosai-osx-arm64
https://github.com/owasp-dep-scan/dosai/releases/download/v0.1.1/Dosai-osx-x64

In addition to adding overlays, I would appreciate it if you could offer a convenient API to extract the information. Currently, my project does some [hacks](https://github.com/owasp-dep-scan/blint/blob/main/blint/binary.py#L902) to extract the json.

Thank you in advance!
