### ISSUE TITLE
A bug in lief.PE.parse()

### ISSUE THREAD

**Issue by BlackIce417** [lief-project/LIEF#1030]
**Describe the bug**
A bug in lief.PE.parse()
```python
import lief
file_path = r"xxxxx"
pe = lief.PE.parse(file_path)
```
If Chinese worlds exist in the file path, lief.PE.parse() can't open the file

**Expected behavior**
Please support utf-8

**Environment (please complete the following information):**
 - System and Version : Windows11 23H2
 - Target format PE
 - LIEF commit version: 0.14.1-bae887e0
**Additional context**
builder.write() has the bug maybe for the same reason.
I guess all functions about file_path may have the same bug.

**NOTICE**

If the issue does not contain enough information to be reproduced,
it will be flagged as [incomplete](https://github.com/lief-project/LIEF/issues?q=is%3Aissue+is%3Aclosed+label%3AIncomplete)
and closed.

**/NOTICE**

**Comment by romainthomas** [comment]
Hi @BlackIce417,

LIEF Python's parser functions are supporting the Python's `io` interface you can use for path names with special characters.
