### ISSUE TITLE
Regression: MemoryError: std::bad_alloc after v0.12.3

### ISSUE THREAD

**Issue by mxschmitt** [lief-project/LIEF#1039]
**Describe the bug**

When doing `str(binary)` of a larger binary, it used to work. In >v0.12.3 it ends up in a OOM error.

**To Reproduce**

```bash
curl -O https://nodejs.org/dist/v20.12.0/node-v20.12.0-linux-arm64.tar.xz
tar -xf node-v20.12.0-linux-arm64.tar.xz

python -c 'import lief; binary = lief.parse("node-v20.12.0-linux-arm64/bin/node"); print(str(binary))'
```

**Expected behavior**

Some stringified value.

**Actual behavior**

MemoryError: std::bad_alloc 

**Environment (please complete the following information):**
 - System and Version : Ubuntu 22.04
 - Target format (PE, ELF, Mach-O): ELF I believe
 - LIEF commit version: v0.14.1

**Additional context**

Upstream issue: https://github.com/conda/conda-build/issues/5267

Might be similar to https://github.com/lief-project/LIEF/issues/1038?

**Comment by romainthomas** [comment]
Hi @mxschmitt

It seems that this issue is already fixed in the master branch as of 307e113f8e00b034f0a5f1baa33e54d636c52ea3.

**Comment by romainthomas** [comment]
Closing since it's fixed on master. Feel free to re-open if you identify the issue.

**Comment by sscherfke** [comment]
If I’m not wrong, this fix hasn’t been released yet.  Is there an ETA for the next release?  No preasure, just want to know if it makes more sense to wait for the update or to downgrade to an older version for now. :-)

**Comment by romainthomas** [comment]
Hi! I think the next release will come around July so depending on your need/priority you might downgrade or use a nightly version.
