### ISSUE TITLE
Protections numbers meaning in Mach-O

### ISSUE THREAD

**Issue by mustaphaezzali** [lief-project/LIEF#1045]
**Describe the bug**
I could not find the meaning of protections numbers (0,1,3,5,7) of Mach-O segments in lief documentation.

**Environment (please complete the following information):**
 - System and Version :  Ubuntu 16.04 , version = 0.12.3
 - Target format : Mach-O

**Comment by romainthomas** [comment]
These numbers represent the classical protection flags:

- `X` = 1
- `W` = 2
- `R` = 4

Thus, `7` is `R | W | X`

**Comment by mustaphaezzali** [comment]
thanks! but in **Mach-O** segments the protections i found are (0,1,3,5,7)
