### ISSUE TITLE
Symbol lookup error when swapping symbols name

### ISSUE THREAD

**Issue by jfgauron** [lief-project/LIEF#1050]
**Describe the bug**

I'm doing the LIEF tutorial. I'm at [03 - Play with Elf](https://lief.re/doc/latest/tutorials/03_elf_change_symbols.html), but after swapping the symbol names in the main executable and trying to run it I get:

`./bin/hashme.obf: symbol lookup error: ./bin/hashme.obf: undefined symbol: cos, version GLIBC_2.2`

**To Reproduce**

I have created a [minimal reproducible example](https://github.com/jfgauron/lief_03_play_with_elf) with a .devcontainer. But the python script is basically just a copy/paste from the tutorial:

```python
#!/usr/bin/env python3
import lief

hashme = lief.parse("bin/hashme")
libm  = lief.parse("/usr/lib/x86_64-linux-gnu/libm.so.6")

def swap(obj, a, b):
    symbol_a = next(i for i in obj.dynamic_symbols if i.name == a)
    symbol_b = next(i for i in obj.dynamic_symbols if i.name == b)
    b_name = symbol_b.name
    symbol_b.name = symbol_a.name
    symbol_a.name = b_name

hashme_pow_sym = next(i for i in hashme.imported_symbols if i.name == "pow")
hashme_log_sym = next(i for i in hashme.imported_symbols if i.name == "log")

hashme_pow_sym.name = "cos"
hashme_log_sym.name = "sin"


swap(libm, "log", "sin")
swap(libm, "pow", "cos")

hashme.write("bin/hashme.obf")
libm.write("bin/libm.so.6")
```

main executable:

```c
// gcc main.c -o bin/hashme -lm

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

double hashme(double input) {
  return pow(input, 4) + log(input + 3);
}

int main(int argc, char** argv) {
  if (argc != 2) {
    printf("Usage: %s N\n", argv[0]);
    return EXIT_FAILURE;
  }

  double N = (double)atoi(argv[1]);
  double hash = hashme(N);
  printf("%f\n", hash);

  return EXIT_SUCCESS;
}
```

1) Build the main executable: `gcc main.c -o bin/hashme -lm`
2) Run the infect script (might have to adjust for libm location): `python infect.py`
3) Make hashme.obf executable: `chmod +x bin/hashme.obf`
4) Run `bin/hashme.obf`
5) Observe the error: `bin/hashme.obf: symbol lookup error: bin/hashme.obf: undefined symbol: cos, version GLIBC_2.29`

~When opening the `bin/hashme.obf` file in IDA I get the following warning:~

~Unexpected entries in the PLT stub.
The file might have been modified after linking.~

EDIT: Turns out this error is displayed in IDA even when opening the normal (unmodified) `hashme` executable, so it is unrelated to LIEF. Not sure why I get that warning but that doesn't seem relevant to the issue I have.

**Expected behavior**

I should still be able to run the main executable, as the tutorial shows.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 22.04 in Docker, running on WLS2
 - Target format : ELF
 - LIEF commit version: 0.15.0-54d0a72c

**Comment by romainthomas** [comment]
Hi! Yes this example requires an older version of Linux (running on a `ubuntu:18.04` should be ok). 
Otherwise, you can try with `logl,powl,cosl,sinl`:


```python
import lief

hashme = lief.parse("hashme")
libm   = lief.parse("/usr/lib/x86_64-linux-gnu/libm.so.6")


def swap(obj, a, b):
    symbol_a = next(filter(lambda e : e.name == a, obj.dynamic_symbols))
    symbol_b = next(filter(lambda e : e.name == b, obj.dynamic_symbols))
    b_name = symbol_b.name
    symbol_b.name = symbol_a.name
    symbol_a.name = b_name

hashme_log_sym = next(filter(lambda e : e.name == "logl", hashme.imported_symbols))
hashme_pow_sym = next(filter(lambda e : e.name == "powl", hashme.imported_symbols))

hashme_pow_sym.name = "cosl"
hashme_log_sym.name = "sinl"

swap(libm, "logl", "sinl")
swap(libm, "powl", "cosl")

hashme.add(lief.ELF.DynamicEntryRpath("."))
hashme.write("hashme.obf")
libm.write("libm.so.6")

print("done")
```
