### ISSUE TITLE
Test binaries are not available

### ISSUE THREAD

**Issue by ezhikus** [lief-project/LIEF#1051]
Repository https://github.com/lief-project/samples and file `dl_samples.py` mention this URL with test binaries: https://data.romainthomas.fr/lief_tests.zip
However, this URL is not available (error 404). 

So, where can I find this file to run tests?

**Comment by romainthomas** [comment]
https://github.com/lief-project/LIEF/blob/f7698825a7717aa1b6f43d046b04d06713c4d4f4/tests/dl_samples.py#L9
