### ISSUE TITLE
error: no declaration matches ‘LIEF::read_out_of_bound::read_out_of_bound(uint64_t)

### ISSUE THREAD

**Issue by MrBruz** [lief-project/LIEF#1052]
**Describe the bug**
LIEF Fails to compile on Arch Linux.

**To Reproduce**
```
❯ pipx install kavanoz
Fatal error from pip prevented installation. Full pip output in file:
    /home/MrBruz/.local/pipx/logs/cmd_2024-05-03_12.42.23_pip_errors.log

pip failed to build package:
    lief

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    /tmp/pip-install-ze1eafkr/lief_864b594f593846e0976dce6722e252f1/include/LIEF/exception.hpp:75:38: error: expected ‘)’ before ‘offset’
    /tmp/pip-install-ze1eafkr/lief_864b594f593846e0976dce6722e252f1/include/LIEF/exception.hpp:76:38: error: expected ‘)’ before ‘offset’
    /tmp/pip-install-ze1eafkr/lief_864b594f593846e0976dce6722e252f1/src/exception.cpp:50:1: error: no declaration matches ‘LIEF::read_out_of_bound::read_out_of_bound(uint64_t, uint64_t)’
    /tmp/pip-install-ze1eafkr/lief_864b594f593846e0976dce6722e252f1/src/exception.cpp:58:1: error: no declaration matches ‘LIEF::read_out_of_bound::read_out_of_bound(uint64_t)’
    subprocess.CalledProcessError: Command '['make', '-j', '1', 'pyLIEF']' returned non-zero exit status 2.

Error installing kavanoz.
```

**Expected behavior**
LIEF compiles and installs successfully 

**Environment (please complete the following information):**
OS: Arch Linux x86_64 
Host: Lemur Pro lemp12 
Kernel: 6.8.8-arch1-1

**Comment by romainthomas** [comment]
Hi @MrBruz 

I guess that you are using a version of Python for which there were no pre-compiled wheels. 
I would also recommend updating you toolchain or at least providing more information about which compiler you use.

In any case, this issue is not reproducible with the latest version of LIEF. Feel free to re-open the issue if the problem is still there (with the latest release of LIEF)

**Comment by Ghost53574** [comment]
The version 0.12.1 setup.py build fails with the error:
lief-0.12.1/include/LIEF/exception.hpp:75:38: error expected ')' before 'offset'
75 | explicit read_out_of_bound(uint64_t offset);
     |                                                          ^~~~~
     |                                                           )
lief-0.12.1/include/LIEF/exception.hpp:76:38: error expected ')' before 'offset'
76 | explicit read_out_of_bound(uint64_t offset, uint64_t size);
     |                                                          ^~~~~
     |                                                           )
     
     cmake version 3.29.6
     g++ 13.3.0
     
It seems that there is an error with the overloading of the constructor for read_out_of_bound, but I don't understand why. Using the latest version of lief isn't an option.
