### ISSUE TITLE
Support for Rust demangle

### ISSUE THREAD

**Issue by prabhu** [lief-project/LIEF#1054]
Would it be possible to add support for [Rust](https://rust-lang.github.io/rfcs/2603-rust-symbol-name-mangling-v0.html) demangler?

https://github.com/llvm/llvm-project/blob/main/llvm/lib/Demangle/RustDemangle.cpp

**Comment by romainthomas** [comment]
Yes it should come with an *extended* version of LIEF.

**Comment by prabhu** [comment]
What is extended version?

**Comment by romainthomas** [comment]
@prabhu Please check: https://lief.re//doc/latest/extended/intro.html for the extended version
