### ISSUE TITLE
More pre-compilation targets for rust bindings

### ISSUE THREAD

**Issue by branchseer** [lief-project/LIEF#1057]
First of all, thank you for making the rust binding!

Would you consider adding more pre-compilation targets? Personally I'd love to have `aarch64-unknown-linux-gnu`.

I'd happy to submit a PR if you could give me some pointers.

**Comment by romainthomas** [comment]
Hi @branchseer.
Yes I'm planning to add this target (along with other) pretty soon!

**Comment by romainthomas** [comment]
Done (along with `aarch64-apple-ios`). More update on the bindings themselves will follow.
