### ISSUE TITLE
Support for .relr.dyn

### ISSUE THREAD

**Issue by junghee** [lief-project/LIEF#1058]
**Describe the bug**
The latest version of LIEF doesn't seem to support `.relr.dyn` (an array of relocation entries that encode relative relocations that do not require explicit addends or other information), which seems to be a relatively new feature that enables to reduce file sizes.

**To Reproduce**
[librt.so.1.zip](https://github.com/lief-project/LIEF/files/15324157/librt.so.1.zip)

**Expected behavior**
The readelf on ubuntu22 shows:
```
Relocation section '.relr.dyn' at offset 0x890 contains 3 entries:
   3 offsets
0000000000003d78
0000000000003d80
0000000000004010
```
The addresses are the entries in `.init_array` and `fini_array`, and the first entry of the section `.data`, respectively.

The LIEF version 0.14.1 fails to provide relocation information for those entries.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04
 - Target format: ELF
 - LIEF commit version: 0.14.1-bae887e0

**Additional context**
https://maskray.me/blog/2021-10-31-relative-relocations-and-relr

**Comment by romainthomas** [comment]
@junghee `.relr.dyn` relocations are not in the `0.14.x` release but they are implemented in the `main` branch.

@TheDauntless LIEF is **not applying** any relocation in the binary so even if the relocation are supported, you will still observe the 0.
