### ISSUE TITLE
str(Binary) -> MemoryError: std::bad_alloc

### ISSUE THREAD

**Issue by MementoRC** [lief-project/LIEF#1060]
**Describe the bug**
Using `str(lief.ELF.parse("<path-to-binary>"))` results in `MemoryError: std::bad_alloc` error

**To Reproduce**
`sbcl --version && python -c 'import lief; str(lief.ELF.parse("sbcl"))'`

**Expected behavior**
Displays version followed by the string representation of sbcl `Binary`

**Environment (please complete the following information):**
 - System and Version : [Linux Debian0 5.18.0-0.deb11.4-amd64]
 - Target format (ELF)
 - LIEF commit version: 0.14.1

**Additional context**
The executable seems to be working well, it is a Common Lisp compiler and can re-build itself from source. Attached is the `gzip sbcl` binary.
[sbcl.gz](https://github.com/lief-project/LIEF/files/15393265/sbcl.gz)

**NOTICE**

If the issue does not contain enough information to be reproduced,
it will be flagged as [incomplete](https://github.com/lief-project/LIEF/issues?q=is%3Aissue+is%3Aclosed+label%3AIncomplete)
and closed.

**/NOTICE**

**Comment by romainthomas** [comment]
Already fixed in `main`

**Comment by MementoRC** [comment]
Great. Is there anything I can do to mitigate this error (compilation flags, etc...)? LIEF is used in conda-forge processes and this is preventing the release of a recipe. When is the next release scheduled? Thank you
