### ISSUE TITLE
Missing Exports in PE (dll)

### ISSUE THREAD

**Issue by gdesmar** [lief-project/LIEF#1061]
**Describe the bug**
Parsing the sample with LIEF, YARA-X and [pefile](https://github.com/erocarrera/pefile) gives a different result for LIEF.
YARA-X and pefile agrees that those samples have exports, but LIEF says there is none.

**To Reproduce**
Download [Sample1](https://bazaar.abuse.ch/sample/f30b9f6e913798ca52154c88725ee262a7bf92fe7caac1ae2e5147e457b9b08a) or [Sample2](https://bazaar.abuse.ch/sample/272cfaebf22e0f6a34c0a93b7c9c5b67c725947ba0f17e60ed67dbf6e1602043) to test. 
```python
>>> import lief
>>> lief.__version__
'0.15.0-54d0a72c'
>>> import pefile
>>> pefile.__version__
'2023.2.7'
>>> b = lief.parse("f30b9f6e913798ca52154c88725ee262a7bf92fe7caac1ae2e5147e457b9b08a")
>>> b.has_exports
False
>>> b = pefile.PE("f30b9f6e913798ca52154c88725ee262a7bf92fe7caac1ae2e5147e457b9b08a")
>>> b.DIRECTORY_ENTRY_EXPORT.struct.TimeDateStamp
0
>>> len(b.DIRECTORY_ENTRY_EXPORT.symbols)
1
>>> print(b.DIRECTORY_ENTRY_EXPORT.symbols[0].name)
None
>>> print(b.DIRECTORY_ENTRY_EXPORT.symbols[0].ordinal)
1
>>> print(b.DIRECTORY_ENTRY_EXPORT.symbols[0].forwarder)
None
>>> print(b.DIRECTORY_ENTRY_EXPORT.symbols[0].address)
89552
```

If you have VirusTotal download access, there is another [sample](https://www.virustotal.com/gui/file/ffc89c701c4ab21f012eb8c69f01ca38ad6b011b5d4c56ed3237e937c49253d0) that have more entries:
```python
>>> import lief
>>> import pefile
>>> b = lief.parse("ffc89c701c4ab21f012eb8c69f01ca38ad6b011b5d4c56ed3237e937c49253d0")
>>> b.has_exports
False
>>> b = pefile.PE("ffc89c701c4ab21f012eb8c69f01ca38ad6b011b5d4c56ed3237e937c49253d0")
>>> b.DIRECTORY_ENTRY_EXPORT.struct.TimeDateStamp
958731115
>>> len(b.DIRECTORY_ENTRY_EXPORT.symbols)
11
>>> print(b.DIRECTORY_ENTRY_EXPORT.symbols[0].name)
None
>>> print(b.DIRECTORY_ENTRY_EXPORT.symbols[0].ordinal)
1
>>> print(b.DIRECTORY_ENTRY_EXPORT.symbols[0].forwarder)
None
>>> print(b.DIRECTORY_ENTRY_EXPORT.symbols[0].address)
162392
>>> print(b.DIRECTORY_ENTRY_EXPORT.symbols[-1].name)
None
>>> print(b.DIRECTORY_ENTRY_EXPORT.symbols[-1].ordinal)
11
>>> print(b.DIRECTORY_ENTRY_EXPORT.symbols[-1].forwarder)
None
>>> print(b.DIRECTORY_ENTRY_EXPORT.symbols[-1].address)
162492
```

**Expected behaviour**
I'd like to first confirm that there really is exports in those samples. If there are, have their information even if there is no name associated with them.

**Environment:**
 - System and Version: Debian 11 Bullseye
 - Target format: PE
 - LIEF commit version: Tested with both 0.14.1 and 0.15.0-54d0a72c

**Additional context**
I will add a comment to this ticket if I find an example on MalwareBazaar with multiple exports that are missing, in case it makes a difference or makes it easier to fix.
I wanted to test with the latest available version in case it was already fixed, so I used `pip install --index-url https://lief.s3-website.fr-par.scw.cloud/latest lief==0.15.0.dev0` but that version look to be dating back to late April. Is the nightly build broken?

**Comment by romainthomas** [comment]
Thanks @gdesmar for raising this issue. I'll take a look!

**Comment by romainthomas** [comment]
The root cause of the missing export is: 

https://github.com/lief-project/LIEF/blob/c80b6274848cb6fd3ba35c0aecb0aa7c7625dcf4/src/PE/Parser.cpp#L847-L850

I think we can relax this condition given the fact that these samples are using an empty export
