### ISSUE TITLE
'Header' object has no attribute 'flags_list' and 'lief._lief.ELF' has no attribute 'PROCESSOR_FLAGS'

### ISSUE THREAD

**Issue by Timonheu** [lief-project/LIEF#1062]
**Describe the bug**
According to the [header documentation](https://lief.re/doc/latest/api/python/elf.html#header), a header object has the property `flags_list`, but this appears to not be true. (I get AttributeError: 'Header' object has no attribute 'flags_list')

 I can get the processor flags as an integer using the `processor_flag` property, but when I want to parse this with `lief.ELF.PROCESSOR_FLAGS.from_value()`, (found in the [documentation on this class](https://lief.re/doc/latest/api/python/elf.html#lief.ELF.PROCESSOR_FLAGS)) it appears that the class `PROCESSOR_FLAGS` does not exist either. (I get AttributeError: 'lief._lief.ELF' has no attribute 'PROCESSOR_FLAGS').

**To Reproduce**
```python
import lief

bin = lief.ELF.parse("ls")
header = bin.header

# Gives integer form of processor flags
proc_flag = header.processor_flag

# This gives an attribute errror:
proc_flags = header.flags_list

# This also gives an attribute error
flag = elf.ELF.PROCESSOR_FLAGS.from_value(proc_flags)
```

**Expected behavior**
For `flags_list` to give a list of `lief.ELF.PROCESSOR_FLAG` objects, and for `lief.ELF.PROCESSOR_FLAG` to exist, in accordance with the documentation.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 22.04.4 LTS
 - Target format: ELF
 - LIEF commit version: 0.14.1-bae887e0

**Additional context**
Is there another way to parse the processor flags that is not in the documentation/documented elsewhere?

I did find that attributes like `arm_flags_list` do exist in a Header object, but I only found this under the header of version 0.8.0 in [the changelog](https://lief.re/doc/latest/changelog.html#october-16-2017).

**Comment by romainthomas** [comment]
Hi @Timonheu 

The documentation you are pointing is actually for the **nightly** build. For the latest **release** you should use the stable dir: https://lief.re/doc/stable/

Note that on the left bar you have the exact commit/version for which the documentation is generated.

**Comment by Timonheu** [comment]
Ah I completely missed that, and did not manage to find the stable docs. Thank you very much!
