### ISSUE TITLE
Mach-O: lief.MachO.parse is very slow in version 0.14.1

### ISSUE THREAD

**Issue by nightlark** [lief-project/LIEF#1069]
**Describe the bug**

We are trying to use LIEF to get information on Mach-O files, and noticed that using LIEF for processing the binary files in the [macOS release of HELICS](https://github.com/GMLC-TDC/HELICS/releases) was taking 120x longer than similar code for Windows and Linux releases that use the `pefile/dnfile` and `pyelftools`.

Adding some prints, we determined that the line in our code that is just calling [lief.MachO.parse](https://github.com/LLNL/Surfactant/blob/228177c6e2114104f3db17145ebf18a4d11c7dd0/surfactant/infoextractors/mach_o_file.py#L40) was taking a very long time to return.

When we pinned the LIEF version to 0.13.2, we found that the runtime for processing all of the files dropped from [3 minutes to 1.6 seconds](https://github.com/LLNL/Surfactant/pull/184#issuecomment-2138697018), which is in line with what we'd expect (due to universal2 macOS binaries having two architectures resulting in roughly twice the amount of work in a comparable Windows/Linux binary).

Using Python 3.9 on macOS, here are the time results for several different files. I also tested with Python 3.12 and lief 0.12 and got similar results. At first I thought it was just correlated with file size, but then I'd expect Electron Framework to take much longer.

program                   | file size | 0.13.2 | 0.14.1   | slow down
--------------------|-------- |--------|--------|------------
/bin/zsh                    | 1.3MB   | 0.068s  | 0.615s   | 9.04x
helics_app                | 15MB   | 0.155s   | 18.253s | 117.76x
Electron Framework | 135MB | 0.263s  | 41.379s | 157.33x

Wrapping the call in cProfile gives the following results in 0.13.2:
```python
cProfile.run('lief.MachO.parse("helics_app")')
         4 function calls in 0.116 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.003    0.003    0.116    0.116 <string>:1(<module>)
        1    0.000    0.000    0.116    0.116 {built-in method builtins.exec}
        1    0.113    0.113    0.113    0.113 {built-in method lief._lief.MachO.parse}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

And in 0.14.1:
```python
cProfile.run('lief.MachO.parse("helics_app")')
         3 function calls in 18.130 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1   18.130   18.130   18.130   18.130 <string>:1(<module>)
        1    0.000    0.000   18.130   18.130 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

I'm not particularly familiar with how the profiling output is meant to be read, but based on [this stackoverflow post](https://stackoverflow.com/questions/5964126/pythons-profile-module-string1) it sounds like that might just be saying that it's spending a long time in a function call to one of the native lief functions.

**To Reproduce**

```python
import lief

# Using the `helics_app` binary from the bin folder in https://github.com/GMLC-TDC/HELICS/releases/download/v3.5.2/Helics-3.5.2-macOS-universal2.zip or `/bin/zsh`, or really any other binary should exhibit similar issues
# note: same performance as lief.parse on MachO files
binary = lief.MachO.parse("helics_app")
```

Note: You *must* use a Python version between 3.8 and 3.11 to reproduce the test numbers in the table, since the 0.13.x series of LIEF releases do not provide an sdist (the performance regression creates a bit of a conundrum for using lief as a required dependency -- we need to pin the version to 0.13.* due to the performance issue with 0.14.* versions, but that blocks Python 3.12 users since the 0.13 releases don't have a binary wheel for anything newer than Python 3.11; it looks like we'll need to add multiple conditional dependencies that pin lief to different versions for different Python versions unless we want to limit ourselves to just the supported platforms and Python versions that lief currently provides binary wheels for).

**Expected behavior**

The performance for 0.13 and 0.14 should be similar, not 1-2 orders of magnitude slower. I'm not sure if this regression is unique to the Python bindings.

**Environment (please complete the following information):**

* System and Version: macOS Sonoma and Windows 10 were tested with similar behavior; I tried running on RHEL 8 just now and it seems like it may not be affected?
* Target format:  Mach-O
* LIEF commit version: 0.14.1-bae887e0 (or whichever one the PyPI release was built from)

**Comment by romainthomas** [comment]
Hi @nightlark 

Thank you for all the details and your analysis of the performances. I confirm the regression and it's pretty weird that this regression only happens on macOS/Windows system and not Linux.

I'll investigate to figure out why we have this performance issue.

Thanks again!

**Comment by romainthomas** [comment]
After investigation, the root cause of this performance regression is this check: 

https://github.com/lief-project/LIEF/blob/fe10cd9fd7a75cde7ba03ccad3d6a7fb052ff839/src/MachO/BinaryParser.cpp#L287-L292
