### ISSUE TITLE
MACHO: "Segmentation fault 11" When Accessing Section Entropy

### ISSUE THREAD

**Issue by rammy22** [lief-project/LIEF#107]
I have a script that performs some checks on the section en along the lines of:
```python
for i,s in enumerate(macho.sections):
 sname = s.name
 # do smthg with sname
```
which causes a segmentation fault when i use `sname`

If I change the for loop to `for s in macho.sections` the fault does not appear anymore. 

Do you have any idea why is this happening? Is there another python object lifetime issue at play here, when using `enumerate`?

Thanks for looking into this.

**Later edit**: It seems the Seg Fault still happens regardless, once i've uncommented parts of my code. Tracing through the code it seems that the issue is definitely happening when accessing `sname` but I can't replicate it in a toy example... Suggestions?

**Later edit 2:** Allowing the python tracing to output to the console, instead of redirecting to a file, enabled me to see that the segmentation always happens when accessing `s.entropy`. A thing to notice is that I parse the MachoFat from a raw buffer, not passing a filename. 
``` python
with open('macho_file', 'rb') as f:
 fat = MachO.parse(list(bytearray(f.read())), '')
 for idx, m in enumerate(fat):
  for i,s in enumerate(m.sections):
   # do smthg with s.entropy
```

**Comment by romainthomas** [comment]
Which version of Python ?

**Comment by rammy22** [comment]
2.7

**Comment by romainthomas** [comment]
Could you please provide a sample that trigger the bug. (I tried on ssh, libc...)

**Comment by rammy22** [comment]
Sha2: ac3249e5b51fd8f74df8097a0c1da00cf18fc10b6e0988dcd455dcff760b2ef0
"Hopper Disassembler v3"

**Comment by romainthomas** [comment]
With Python 2.7 and latest release of LIEF (0.8.2):
```python
import lief

from lief import MachO
with open('ac3249e5b51fd8f74df8097a0c1da00cf18fc10b6e0988dcd455dcff760b2ef0', 'rb') as f:
    fat = MachO.parse(list(bytearray(f.read())), '')
    for idx, m in enumerate(fat):
        for i,s in enumerate(m.sections):
            print(s.entropy)
```
```
6.30095196903
6.33909525007
4.96738595669
4.22803267124
5.55463270293
3.28062669469
4.23344879463
4.21051876481
4.21527205916
3.14942565822
6.5014752214
4.07855039108
2.03063895829
-0.0
0.272905787521
3.34019931883
-0.0
2.29793159294
1.94251338275
3.19218231552
1.75
2.9683414282
3.14315110331
-0.0
3.52494180443
3.85861827594
2.80275809577
2.00782011937
3.0832002315
1.44918707501
1.51458638165
2.99986028653
-0.0
-0.0
```
