### ISSUE TITLE
write instruction doesn't take previously changed rpath

### ISSUE THREAD

**Issue by arttson** [lief-project/LIEF#1074]
**Describe the bug**
Previously changed MachO rpath is not taken by write instruction.

**To Reproduce**
As shown on attachment. 

**Environment (please complete the following information):**
 - macOS Sonoma 14.5
 - MachO
 - LIEF v0.14.1

![lief](https://github.com/lief-project/LIEF/assets/145224701/879d5507-f9ec-4bb4-b5ab-b3aaee0ec084)

**Comment by romainthomas** [comment]
Thanks @arttson for spotting this issue. I can reproduce it on my end.

**Comment by arttson** [comment]
No problem! Thanks for LIEF! Such an amazing library.

**Comment by romainthomas** [comment]
Thanks for your sponsoring @arttson :pray:  I started to work on it in the branch: [feat/macho-build-rpath](https://github.com/lief-project/LIEF/tree/feat/macho-build-rpath) and hopefully I should be able to finish it next week-end!

**Comment by arttson** [comment]
Take Your time!. I tipped because I like the project, not to get it to work faster 😄

Have a nice weekend!

**Comment by romainthomas** [comment]
Done with: 402e7a9

**Comment by LecrisUT** [comment]
I am hitting the warning "Not enough room left to rebuild" and I am not sure if we are supposed to resize it manually or it does it for us. Afaict from the implementation it is the latter.

But then, regarding the test introduced in 402e7a9b02ca425bd7d793eaa1c61b33de464f80, shouldn't the new paths be bigger than the current ones to check that the rebuilding works
https://github.com/lief-project/LIEF/blob/c4069b6b818e61e86fcd47b5083ae757bd50d556/tests/macho/test_builder.py#L620-L624

something like
```python
    rpaths[0].path = "@loader_path/some/very/long/path/that/will/trigger/not/enough/room/to/rebuild"
    rpaths[1].path = "/bar"
```

Let me know if I got this wrong and it is supposed to be used differently. For context, I am trying to do something along the lines
```python
            import lief.MachO

            fat_macho = lief.MachO.parse(artifact)
            for macho_it in range(fat_macho.size):
                macho = fat_macho.at(macho_it)
                macho.remove(lief.MachO.LoadCommand.TYPE.RPATH)
                for rpath in final_rpaths:
                    macho_rpath = lief.MachO.RPathCommand.create(rpath)
                    macho.add(macho_rpath)
            fat_macho.write(str(artifact))
```
