### ISSUE TITLE
Update size of existing functions in Mach O binaries

### ISSUE THREAD

**Issue by localacct** [lief-project/LIEF#1077]
I want to modify the existing functions in a Mach O binary by adding or removing instructions to it. However, I do not know how to update the size of the function after adding instructions as the functions can be located next to one another in terms of addresses and any increase in size will cause the instructions of the current function to cross over to the next function.

Any modification would probably require the changing of the start address of other functions, etc as well.

If this cannot be done, are there alternatives?

My environment
Mac OS Sonoma 14.5
Target file (Mach O)
LIEF commit version: 0.14.1-bae887e0

**Comment by romainthomas** [comment]
Hi @localacct 
As you identified, addressing this feature is not trivial and LIEF is out of scope for that.
You can check [bolt](https://github.com/llvm/llvm-project/tree/main/bolt)
