### ISSUE TITLE
python 3.12 Segmentation fault on iteraor

### ISSUE THREAD

**Issue by amaelFr** [lief-project/LIEF#1079]
**python 3.12 `Segmentation fault` on iterator**
At least two iterator on python created a segfault on python 3.12

**To Reproduce**
```
import lief
for symbol in lief.parse(ELF_PATH').symbols:
  print(symbol)
```

```
import lief
for section in lief.parse('ELF_PATH').sections:
  print(section)
```

**Expected behavior**
Print the list of elements

**Environment:**
 - System and Version : `Ubuntu 24.04` `Linux tcrl049 6.5.0-1024-oem #25-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 14:47:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
 - Target format ELF
 - LIEF commit version: `0.14.1-bae887e0`
 -  Python version: Python 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] on linux

**Additional context**
Reproducible from a cli interactive python or a python src file.
No issue if the Parsed object (from lief.parse) is affected to a variable and then used.
```
elf_symbols = lief.parse('ELF_PATH').symbols
for symbol in elf_symbols:
  print(symbol)
```

**Comment by romainthomas** [comment]
Yes you need to set the result of `lief.parse(...)` in a dedicated variable. This is a (complex) issue with Python lifetime:

```diff
- elf_symbols = lief.parse('ELF_PATH').symbols
- for symbol in elf_symbols:
+ elf = lief.parse('ELF_PATH')
+ for symbol in elf.symbols:
  print(symbol)
```
