### ISSUE TITLE
python package has name UNKNOWN

### ISSUE THREAD

**Issue by amuehlem** [lief-project/LIEF#108]
I tried to install the python module via pip or using setup.py, in both cases the name was 'unknown' insted of 'lief'.

pip install lief
Collecting lief
  Downloading lief-0.8.0.post6.zip
  Running setup.py (path:/tmp/pip-build-pM8KE0/lief/setup.py) egg_info for package lief produced metadata for project name unknown. Fix your #egg=lief fragments.
Installing collected packages: unknown
  Running setup.py install for unknown ... done
Successfully installed unknown-0.8.0

**Comment by romainthomas** [comment]
``pip install setuptools --upgrade`` should fix the issue

**Comment by amuehlem** [comment]
That helped, thanks a lot!
