### ISSUE TITLE
Mach-O Failing to convert offset to virtual address

### ISSUE THREAD

**Issue by ddash-ct** [lief-project/LIEF#1087]
**Describe the bug**
Observing a sample where lief is failing to convert an offset to a virtual address in macho

**To Reproduce**

Using the following code:
```python
import lief

with open('fbcb7580db7bc04d695c3fd0308bb344', 'rb') as f:
    data = list(bytearray(f.read()))

macho = lief.MachO.parse(data)
for idx in range(macho.size):
    macho_bin = macho.at(idx)
    print(f'{macho_bin.offset_to_virtual_address(0x42dae):08x}')
```

Result is 
`>>> 00042dae`

**Expected behavior**

Expected value is `100042DAE`

**Environment (please complete the following information):**
 - System and Version : Windows 10 Pro
 - Target format: Mach-O
 - LIEF commit version: 0.15.1-

**Additional context**

The relevant sample is attached and the password is "infected". Please note, this is malware and may be identified by A/V:

[fbcb7580db7bc04d695c3fd0308bb344.zip](https://github.com/user-attachments/files/16680842/fbcb7580db7bc04d695c3fd0308bb344.zip)

**NOTICE**

If the issue does not contain enough information to be reproduced,
it will be flagged as [incomplete](https://github.com/lief-project/LIEF/issues?q=is%3Aissue+is%3Aclosed+label%3AIncomplete)
and closed.

**/NOTICE**

**Comment by romainthomas** [comment]
Nice catch. Thanks for reporting :+1:
