### ISSUE TITLE
Dynamic Symbol Removal Seg Fault

### ISSUE THREAD

**Issue by erik-macintyre** [lief-project/LIEF#1089]
**Describe the bug**
When removing a dynamic symbol from an ELF file if it has multiple references in the dynamic relocation table; only one reference gets removed leaving the other reference with a malformed pointer. This will cause a seg fault during the write process when building the dynamic relocation table when accessing `symbol->name()`.

**To Reproduce**
Remove any symbol with multiple references in a relocation table. I was specifically encountering this while looking at `libip4tc.so.2.0.0` for AArch64 where removal of `iptc_read_counter` will trigger this behavior.
Attached the library: 
[libip4tc.zip](https://github.com/user-attachments/files/16729206/libip4tc.zip). The package archive can be downloaded from: https://archlinuxarm.org/packages/aarch64/iptables

**Expected behavior**
Removal of all `symbol` references from all relevant tables.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04
 - Target format ELF
 - LIEF commit version: 0.14.1

**Additional context**
I imagine this affects the other tables where the symbol is only removed once, but may appear more than once. But only encountered this issue with multiple references to a symbol in a dynamic relocation table in `libip4tc.so` so far.

**NOTICE**

If the issue does not contain enough information to be reproduced,
it will be flagged as [incomplete](https://github.com/lief-project/LIEF/issues?q=is%3Aissue+is%3Aclosed+label%3AIncomplete)
and closed.

**/NOTICE**

**Comment by romainthomas** [comment]
Hi @erik-macintyre 
Thanks for raising this issue, I can reproduce on my end.

I'll provide a fix quickly.
