### ISSUE TITLE
DWARF\Type.hpp compile error

### ISSUE THREAD

**Issue by lucianpin** [lief-project/LIEF#1093]
**Describe the bug**
After switching to the latest version of LIEF, I just compiled my project and get the following error:

```
  enum class KIND {
    UNKNOWN = 0,
    UNSPECIFIED,
    BASE,
    CONST, <--- DWARF\Type.hpp(112,5): error C2143: syntax error: missing '}' before 'const'
    CLASS,
    ARRAY,
    POINTER,
    STRUCT,
    UNION,
  };
```

I use Windows.h and somewhere there is `#define CONST const`, but I would like to keep everything as is.
Any ideas?

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen (if applicable)

**Environment (please complete the following information):**
 - System and Version : Windows 10
 - Target format: PE
 - LIEF commit version: 0.15.1

**Additional context**

**NOTICE**

If the issue does not contain enough information to be reproduced,
it will be flagged as [incomplete](https://github.com/lief-project/LIEF/issues?q=is%3Aissue+is%3Aclosed+label%3AIncomplete)
and closed.

**/NOTICE**

**Comment by romainthomas** [comment]
Windows [...] :facepalm:
