### ISSUE TITLE
Type hints aren't working properly

### ISSUE THREAD

**Issue by omer54463** [lief-project/LIEF#1095]
Currently, many of the type hint files (`.pyi`) import classes that they hint from the library.
For example, `lief\__init__.pyi` contains the lines:

```python3
import lief.Binary # type: ignore
import lief.Function # type: ignore
import lief.DebugInfo # type: ignore
```

However, the file provides hints for those two classes!

```python3
class Binary(Object):
    ...

class Function(Symbol)
    ...

class DebugInfo:
    ...
```

This confuses `mypy`, so I get no hints for those types.

This behavior makes sense - a `pyi` file "shadows" a python file for the duration of the type check, so you are importing... from the file itself...?

The correct solution would be to not import classes that are hinted within the `pyi` file.

**Comment by romainthomas** [comment]
Hi @omer54463 

Thank you for raising this issue with the associated PR. 

> This confuses mypy, so I get no hints for those types.

Do you have an example for that?

**Comment by omer54463** [comment]
Huh, it seems I confused `mypy` and `pylance`. `mypy` detects the type properly, but `pylance` was the linter who got pissed at me.

```
binary = lief.parse(...)
reveal_type(binary) # pylance says "Any | None", mypy would say "lief.Binary | None"
```

Either way, importing the type you are declaring makes little sense.

**Comment by romainthomas** [comment]
Humm in this case I guess it can be worth to raise this issue to `pylance`. The `*.pyi` are **automatically** generated by mypy's stubgen as as long as it works with mypy/jedi I won't prioritize this support in LIEF.
