### ISSUE TITLE
Corrupted dynamic-link library names (`DT_NEEDED`) and shared object name (`DT_SONAME`)

### ISSUE THREAD

**Issue by abcSup** [lief-project/LIEF#1097]
**Describe the bug**
After rebuilding a ELF binary without any modification, many strings in the `.dynstr` section, which are used by the dynamic library entries (`DT_NEEDED`) and shared object name (`DT_SONAME`), are corrupted.

**To Reproduce**
Use the testcase from here:
https://gitgud.io/Van-Firmware-Dumps/samsung/e1s/-/blob/e1sxxx-user-14-UP1A.231005.007-S921BXXS2AXEF-release-keys/system/system/lib64/libhwui.so

Run the following python script:
```
from lief import *
elf = ELF.parse("libhwui.so")
elf.write("libhwui_modified.so")
```

Listing all dynamic-link library with `readelf` shows corrupted string names. `DT_NEEDED` and `DT_SONAME` entries point to corrupted strings.
```
$ readelf -d libhwui_modified.so 

Dynamic section at offset 0xc29690 contains 72 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [APS2?]
 0x0000000000000001 (NEEDED)             Shared li?]ary: [
 0x0000000000000001 (NEEDED)             Sha?ed li?ra??? [
                             ?
                          ?] ?
 0x0000000000000001 (NEEDED)       ?]?   Shared library:([
 0x0000000000000001 (NEEDED)             Shared library: [libdng_sdk.so]
# ----- snipped -----
 0x000000000000000e (SONAME)             Library soname: [
                                                   ]
```

The first dynamic-link library entry should have the name `libimage_io.so`. The `.dynstr` section does not contain the string `libimage_io.so`. It also contain some invalid strings.
```
$ readelf -x .dynstr libhwui_modified.so

Hex dump of section '.dynstr':
  0x00008ec8 00414269 746d6170 436f6e66 69675f67 .ABitmapConfig_g
# ----- snipped -----
  0x00010d48 68777569 2e736f00 41505332 fe05009b hwui.so.APS2....
  0x00010d58 03018182 8080b002 c0c68006 0808d00b ................
  0x00010d68 28a00ce8 0738c002 08101808 9003c008 (....8..........
  0x00010d78 0808e003 c8090808 08080818 080808d0 ................
  0x00010d88 0018b808 d82aa008 080808d8 0c080898 .....*..........
  0x00010d98 01a00108 d000a001 08e00608 e8050808 ................
  0x00010da8 08080880 04080890 1508f800 08c00908 ................
  0x00010db8 9001a80d 08081010 10081008 c0008007 ................
# ----- snipped -----
```

**Expected behavior**
I expect LIEF to maintain all dynamic-link library names even after rebuilding the ELF binary.

```
$ readelf -d libhwui.so

Dynamic section at offset 0xc28690 contains 72 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libimage_io.so]
 0x0000000000000001 (NEEDED)             Shared library: [libultrahdr.so]
 0x0000000000000001 (NEEDED)             Shared library: [libpng.so]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdng_sdk.so]
# ----- snipped -----
 0x000000000000000e (SONAME)             Library soname: [libhwui.so]
```

**Environment (please complete the following information):**
 - System and Version : Ubuntu 16.04
 - Target format: ELF (Android Native)
 - LIEF commit version: `0.15.1-`

**Additional context**

**Comment by abcSup** [comment]
All the dynamic-link library names and shared object name remain intact when rebuilding with `config.force_relocate` enabled.

```python
#!/bin/env python

from lief import *

elf = ELF.parse("libhwui.so")

config = ELF.Builder.config_t()
config.force_relocate = True
elf.write("libhwui_modified.so", config)
```

If you suspect this is just a usage error, please feel free to close the issue.

**Comment by romainthomas** [comment]
No this is definitely an issue. Thanks for reporting. I'll see to address it this week end

**Comment by abcSup** [comment]
Thank you very much!
