### ISSUE TITLE
Problem with building the lief Rust bindings in sandboxed mode

### ISSUE THREAD

**Issue by bartavelle** [lief-project/LIEF#1098]
**Describe the bug**
Building with Nix is done in sandboxed mode. Helpers are present to download all dependencies before building. However, the `lief-build` dependency tries to download an archive during the build process, which fails because network is sandboxed.

**Expected behavior**
Could it be possible to have an environment variable containing the path to the .zip archive, and have the build process check for it when building the `dst_archive` variable?

**Comment by bartavelle** [comment]
I would like to write a PR, but I could not find the source of the rust bindings, I had to pull them from crates.io.

**Comment by romainthomas** [comment]
Hi!

- The source code is here: [api/rust](https://github.com/lief-project/LIEF/tree/main/api/rust)
- And the documentation (which details the usage of `LIEF_RUST_PRECOMPILED`) here: https://lief.re/doc/latest/api/rust/index.html
