### ISSUE TITLE
PE parse memory consumption bug

### ISSUE THREAD

**Issue by earada** [lief-project/LIEF#110]
Trying to analyze this sample makes LIEF consume too much memory and crash.

```
src $ python
>>> import lief
>>> pe = lief.parse("sample")
Killed
src $
```

[sample.zip](https://github.com/lief-project/LIEF/files/1418447/sample.zip)
Password: infected

**Comment by romainthomas** [comment]
Using ``python3.6 - x86_64`` it takes ~5Go and 0.71s to parse the binary. It's seems reasonable nop ?

**Comment by earada** [comment]
Well, I was running it under a 4GB vm. I've increased the mem and it works now. Do it really need ~5GB for a 12M sample?

**Comment by romainthomas** [comment]
Some LIEF's object can be quite complex (like resources etc). I plan to provide a flag to do a shallow parsing.
