### ISSUE TITLE
PE Signature check wrongly says CERT_EXPIRED

### ISSUE THREAD

**Issue by lucianpin** [lief-project/LIEF#1101]
**Describe the bug**
Inside the method `Signature::check` (from src\PE\signature\Signature.cpp), going to `CounterSignature Checks` code, the call to:

`VERIFICATION_FLAGS cs_flags = verify_ts_counter_signature(signer, *counter, checks);`

would return `INVALID_SIGNER (0x00000001)`.

As a consequence, `timeless_signature` stays false and the code proceeds to verify if the signer certificate is not expired. The certificate is expired and `VERIFICATION_FLAGS::CERT_EXPIRED` would be returned, but the problem is that the timestamp counter signature should have been ok and the file still considered valid and signed.

**To Reproduce**
I have attached the test file to reproduce exactly this problem.
[jar.zip](https://github.com/user-attachments/files/16959163/jar.zip)

**Expected behavior**
The test file should be considered signed with valid signature.

**Environment (please complete the following information):**
 - System and Version : Windows 10
 - Target format: PE
 - LIEF commit version: 0.15.1

**Additional context**

**NOTICE**

If the issue does not contain enough information to be reproduced,
it will be flagged as [incomplete](https://github.com/lief-project/LIEF/issues?q=is%3Aissue+is%3Aclosed+label%3AIncomplete)
and closed.

**/NOTICE**

**Comment by romainthomas** [comment]
Hi @lucianpin 
Thank you for raising this issue. I'll check that shortly
