### ISSUE TITLE
Support glibc 2.31 on aarch64 linux

### ISSUE THREAD

**Issue by novas0x2a** [lief-project/LIEF#1104]
I wasn't sure if this was an intentional change (it's not in the changelog), so I'm filing this just in case it was an accident :)

It looks like LIEF 0.14 [supported glibc 2.31](https://pypi.org/project/lief/0.14.1/#files) on aarch64 via manylinux_2014, but 0.15 bumped the minimum requirement to 2.33 (for aarch64). Was that intentional? It unfortunately excludes Ubuntu 20.04 and Debian 11 which are both old but not yet EOL.

It looks like (in 0.15) x86_64 used manylinux_2_28, but aarch64 used manylinux_2_33; there's a [compat chart](https://github.com/mayeut/pep600_compliance?tab=readme-ov-file#distro-compatibility) if you're curious what supports what.

**Comment by romainthomas** [comment]
Hi @novas0x2a 

Yes I updated the toolchain for Linux AArch64 and one of the consequences is the bump of the minimum version of the glibc (I was aware of that)

I understand it's a concern for you so I'll see to lower back the glibc version for the next release.

**Comment by romainthomas** [comment]
I updated the docker image and I confirm that the next wheels for Linux AArch64 will be `manylinux2014` compliant.

**Comment by romainthomas** [comment]
@novas0x2a I just re-uploaded `manylinux2014` wheels for LIEF `0.15.1`
