### ISSUE TITLE
Parsing Mach-O from a file object using lief.MachO.parse() is (still) broken

### ISSUE THREAD

**Issue by nneonneo** [lief-project/LIEF#1114]
**Describe the bug**
After fixing #1113, `lief.MachO.parse` is still subtly broken. With the Python bindings, using `lief.MachO.parse` to parse file objects (as opposed to filenames) results in dyld_info bindings not being properly parsed.

**To Reproduce**

1. Download and unpack [bugtest.so.zip](https://github.com/user-attachments/files/17270802/bugtest.so.zip)
2. Run the following script in the same directory:
```python
import lief
bin1 = lief.parse("bugtest.so")
bin2 = lief.MachO.parse(open("bugtest.so", "rb"))[0]
print(list(bin1.dyld_info.bindings))
print(list(bin2.dyld_info.bindings))
```

**Expected behavior**
It should print out two lists with the same length (3 bindings).

**Observed behavior**
The first list contains 3 bindings as expected. The second list is empty:

```
[<lief._lief.MachO.DyldBindingInfo object at 0x104a84d10>, <lief._lief.MachO.DyldBindingInfo object at 0x104a84d50>, <lief._lief.MachO.DyldBindingInfo object at 0x104a84d90>]
[]
```

**Environment:**
- macOS 14.6.1 (Intel), Python 3.10.11, lief 0.16.0-11f65a05

**Comment by romainthomas** [comment]
For the record, it was more an inconsistency between the C++ interface and the Python interface

**Comment by nneonneo** [comment]
Cool! Thanks for the quick fix. From my reading of the code, the same change looks like it needs to be applied to the `bytes` override?

**Comment by romainthomas** [comment]
Indeed you are right!
