### ISSUE TITLE
critical bug of memory exhaustion

### ISSUE THREAD

**Issue by richardPang517** [lief-project/LIEF#1115]
hello,
       I found a critical bug of rapid memory consumption and 100% cpu usage until totally memory exhaustion when using Lief to parse a PE sample(api:  lief.parse(...)).
       This sample was captured from network traffic, and due to network reason, the sample is incomplete.  The sample is assumed to be malicious.
       Originally lief 0.8.3-python was used to parse, and I found the newest python version still has the same problem.
       Please check whether it is a python version problem or exists in all versions.
[f_3_463732359790993934_0.zip](https://github.com/user-attachments/files/17348963/f_3_463732359790993934_0.zip)

**Comment by romainthomas** [comment]
Hi @richardPang517 
Thank you for raising this critical bug. I'll push the fix ASAP.

Thank you again
