### ISSUE TITLE
Base address is off by one page after adding a new symbols to an ELF file

### ISSUE THREAD

**Issue by endrazine** [lief-project/LIEF#1117]
**Describe the bug**
After reading an ELF, adding a new symbol and writing the resulting output, the base address in the output ELF is off by one page.

**To Reproduce**
Here is sample code to replicate the issue:

#include <LIEF/LIEF.hpp>
#include <array>
#include <iostream>

#include <math.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>

int main()
{
        struct sym_t *sym = 0, *tmp = 0;
        std::unique_ptr<LIEF::ELF::Binary>   elf;

        elf = LIEF::ELF::Parser::parse("./ls");

        elf->add_exported_function(0x4141, "toto");

        elf->write("./ls2");
}

The input file used is /bin/ls from coreutils 9.4-3ubuntu6 on Ubuntu LTS 24.04

**Expected behavior**
The base address within ls and ls2 should be the same.

However:

jonathan@blackbox:/tmp/lief/bug$ objdump -Mintel -d -j .text ls|head -n 20

ls:     file format elf64-x86-64

Disassembly of section .text:

0000000000004d70 <_obstack_begin@@Base-0x8ef0>:
    4d70:	e8 db f9 ff ff       	call   4750 <abort@plt>
    4d75:	e8 d6 f9 ff ff       	call   4750 <abort@plt>
    4d7a:	e8 d1 f9 ff ff       	call   4750 <abort@plt>
    4d7f:	e8 cc f9 ff ff       	call   4750 <abort@plt>
    4d84:	e8 c7 f9 ff ff       	call   4750 <abort@plt>
    4d89:	e8 c2 f9 ff ff       	call   4750 <abort@plt>
    4d8e:	e8 bd f9 ff ff       	call   4750 <abort@plt>
    4d93:	66 2e 0f 1f 84 00 00 	cs nop WORD PTR [rax+rax*1+0x0]
    4d9a:	00 00 00 
    4d9d:	0f 1f 00             	nop    DWORD PTR [rax]
    4da0:	f3 0f 1e fa          	endbr64
    4da4:	55                   	push   rbp
    4da5:	48 89 e5             	mov    rbp,rsp
jonathan@blackbox:/tmp/lief/bug$ 

While:

jonathan@blackbox:/tmp/lief/bug$ objdump -Mintel -d -j .text ls2|head -n 20

ls2:     file format elf64-x86-64

Disassembly of section .text:

0000000000005d70 <toto@@Base+0xc2f>:
    5d70:	e8 db f9 ff ff       	call   5750 <abort@plt>
    5d75:	e8 d6 f9 ff ff       	call   5750 <abort@plt>
    5d7a:	e8 d1 f9 ff ff       	call   5750 <abort@plt>
    5d7f:	e8 cc f9 ff ff       	call   5750 <abort@plt>
    5d84:	e8 c7 f9 ff ff       	call   5750 <abort@plt>
    5d89:	e8 c2 f9 ff ff       	call   5750 <abort@plt>
    5d8e:	e8 bd f9 ff ff       	call   5750 <abort@plt>
    5d93:	66 2e 0f 1f 84 00 00 	cs nop WORD PTR [rax+rax*1+0x0]
    5d9a:	00 00 00 
    5d9d:	0f 1f 00             	nop    DWORD PTR [rax]
    5da0:	f3 0f 1e fa          	endbr64
    5da4:	55                   	push   rbp
    5da5:	48 89 e5             	mov    rbp,rsp
jonathan@blackbox:/tmp/lief/bug$

**Environment (please complete the following information):**
 - System and Version : Ubuntu 24.04 LTS
 - Target format ELF
 - LIEF commit version: LIEF-0.15.1-Linux-x86_64

**Additional context**
Thanks for this useful project :)

**Comment by romainthomas** [comment]
Hi @endrazine 

This shift is on purpose since LIEF needs to add an additional segment to handle 
the `.dynstr` extension. The **generic** approach used LIEF to add segments requires  
to shift by a page size. Hence, the difference.  

If the new `ls` segfault with the **latest** version of LIEF, please reopen this issue.
