### ISSUE TITLE
ELF(so) change symbol binding, local to global, is't possible?

### ISSUE THREAD

**Issue by StephenZengCn** [lief-project/LIEF#112]
i try 
```
import lief
lib = lief.parse('crack.so')
lib.symbols[symbol_index_i_need].binding = lief.ELF.SYMBOL_BINDINGS(1)
lib.write('newcrack.so')
```
`nm newcrack.so`
seems like it changed from 't' to 'T', but when i gcc to link it, faild, undefine reference error.
can u give me some hint?

**Comment by romainthomas** [comment]
Could you do add information about ``lib.symbols[symbol_index_i_need]``
like:
```python
>>> print(lib.symbols[symbol_index_i_need])
```

**Comment by StephenZengCn** [comment]
before
```
>>> print(lib.symbols[5480])
CHECK::CHECK(char*)       FUNC      LOCAL     17b5ca    630
```
after
```
>>> print(lib.symbols[5480])
CHECK::CHECK(char*)       FUNC      GLOBAL    17b5ca    630
```

**Comment by StephenZengCn** [comment]
i saw a statement here https://github.com/BR903/ELFkickers/tree/master/rebind, says:
>>>Note that rebind does not permit you to make local symbols global, or
vice versa. The dynamic symbol table requires that all local symbols
be listed before global symbols, so making these sort of changes
requires that the symbol table be reordered.
and i checked the address is not reordered, is't relevant?

**Comment by StephenZengCn** [comment]
for more information
```
2879: 000000000017b5ca  1584 FUNC    GLOBAL DEFAULT   11 _ZN7XXX_XXXC2EPc
5121: 000000000017b5ca  1584 FUNC    GLOBAL DEFAULT   11 _ZN7XXX_XXXC1EPc
```
i found the function have two symbol name?
`gcc -S fake.cpp` in my file, it call the function like this `call    _ZN7DNN_VADC1EPc`
and the so self call the function like this `call    _ZN7DNN_VADC2EPc`

**Comment by StephenZengCn** [comment]
so, it means i need some way to call the base object constructor instead of default complete object constructor?

**Comment by StephenZengCn** [comment]
follow the rebind's reorder statement, i write a script to change the binding and swap the location of the index like this(so changed success but compile failed, still undefine reference error):
```
import lief
import fire

def symbol_assignment(src, dst):
    src.binding = dst.binding
    #src.demangled_name = dst.demangled_name
    src.exported = dst.exported
    src.imported = dst.imported
    src.name = dst.name
    src.shndx = dst.shndx
    src.size = dst.size
    src.type = dst.type
    src.value = dst.value

def swap_symbol_by_index(lib, src, dst):
    tmp = lief.ELF.Symbol()
    symbol_assignment(tmp, lib.symbols[src])
    symbol_assignment(lib.symbols[src], lib.symbols[dst])
    symbol_assignment(lib.symbols[dst], tmp)

def get_last_local_index(lib):
    lastindex = 0
    for index, symbol in enumerate(lib.symbols):
        if symbol.binding == lief.ELF.SYMBOL_BINDINGS.LOCAL:
            lastindex = index
    return lastindex

def get_indexs_from_keyword(lib, keyword):
    indexs = []
    for index, symbol in enumerate(lib.symbols):
        if symbol.type == lief.ELF.SYMBOL_TYPES.FUNC and symbol.name.find(keyword) != -1:
            indexs.append(index)
    return indexs

def main(src, dst, keyword, binding='global'):
    lib = lief.parse(src)

    indexs = get_indexs_from_keyword(lib, keyword)

    for index in indexs:
        if binding == 'global':
            lib.symbols[index].binding = lief.ELF.SYMBOL_BINDINGS.GLOBAL
        else: pass

    lastlocal = get_last_local_index(lib)
    for index in indexs:
        if index >= lastlocal: continue
        swap_symbol_by_index(lib, index, lastlocal)
        lastlocal -= 1

    lib.write(dst)

if __name__ == '__main__':
    fire.Fire(main)
```

**Comment by StephenZengCn** [comment]
for more information, i call the so file's original global function success.

**Comment by StephenZengCn** [comment]
i notice that the global function always have a symbol both in symbol table '.dynsym' and '.symtab'.
it's that means i need to add a symbol in the '.dynsym' table if i change a local symbol that only appear in '.symtab' to global?

**Comment by StephenZengCn** [comment]
after add the symbol to .dynsym use lib.add_dynamic_symbol(), compile success.

but execute got segment fault.

**Comment by romainthomas** [comment]
Hi @StephenZengCn
Thanks for this interesting problem.
Actually there is not API to bind (or create) Symbol with ``SymbolVersion`` so I'll add it
Estimated time: couple of weeks

**Comment by StephenZengCn** [comment]
happy to hear that.
and,
awesome project!

**Comment by romainthomas** [comment]
@StephenZengCn  I have the fix. I need to clean up some stuff and I'll push

**Comment by StephenZengCn** [comment]
awesome!
can not wait for that

**Comment by romainthomas** [comment]
@StephenZengCn could you check if what you want to do is working on the branch [elf/symbol_binding](https://github.com/lief-project/LIEF/tree/elf/symbol_binding)

You have an example here:

https://github.com/lief-project/LIEF/blob/c0e33ed122be5cdf14876fd9b8a1e74189912111/tests/elf/test_bin2lib.py#L117-L122

**Comment by StephenZengCn** [comment]
of course, tonight.

**Comment by StephenZengCn** [comment]
compile success, but execute failed.
`readelf -s libtest.so | grep basename`
```
  5663: 000000000003b410   100 FUNC    LOCAL  DEFAULT   11 _Z11basenamePc
```
`readelf -s libtest_new.so | grep basename`
```
   359: 000000000003d410   100 FUNC    GLOBAL DEFAULT   11 _Z11getbasenamePc
  5663: 000000000003d410   100 FUNC    GLOBAL DEFAULT   11 _Z11getbasenamePc
```
i notice that lots of function address is changed

**Comment by StephenZengCn** [comment]
test like this
`vi test.cpp`
```
#include <stdio.h>

int test_global(char *s){
    printf("test global: %s....\n", s);
    return 0;
}

int test_local(char *s){
    printf("test local: %s...\n", s);
    return 0;
}
```
`vi export.map`
```
{

global:
    _Z11test_globalPc;

local:
    *;

};
```
`gcc test.cpp -Wl,--version-script=export.map -fPIC -shared -o libtest.so`
`vi main.cpp`
```
#include <stdio.h>

extern int test_global(char *);
extern int test_local(char *);

int main(void){
    test_global("11111");
    //test_local("22222");
}
```
`gcc main.cpp -L./ -ltest`

**Comment by romainthomas** [comment]
Should be good with https://github.com/lief-project/LIEF/commit/46241596a7f9a3e6ea201278d981a529596b961c

You can try with [test.zip](https://github.com/lief-project/LIEF/files/1499018/test.zip)

```bash
$ make test
```

**Comment by StephenZengCn** [comment]
@romainthomas  failed, missing attribute SYMBOL_VISIBILITY
```
rm -rf *.o *.so *.bin
cc -Wl,--version-script=export.map -fPIC -shared -o libtest.so libtest.c
python export.py libtest.so libtest2.so
Traceback (most recent call last):
  File "export.py", line 10, in <module>
    test_local_sym.visibility = lief.ELF.SYMBOL_VISIBILITY.DEFAULT
AttributeError: 'module' object has no attribute 'SYMBOL_VISIBILITY'
Makefile:10: recipe for target 'libtest2.so' failed
make: *** [libtest2.so] Error 1
```
try 0 instead, failed, missing attribute visibility
```
rm -rf *.o *.so *.bin
cc -Wl,--version-script=export.map -fPIC -shared -o libtest.so libtest.c
python export.py libtest.so libtest2.so
Traceback (most recent call last):
  File "export.py", line 10, in <module>
    test_local_sym.visibility = 0
AttributeError: '_pylief.ELF.Symbol' object has no attribute 'visibility'
Makefile:10: recipe for target 'libtest2.so' failed
make: *** [libtest2.so] Error 1
```

**Comment by romainthomas** [comment]
I think you should clear your cache because both
https://github.com/lief-project/LIEF/blob/elf/symbol_binding/api/python/ELF/pyELFStructures.cpp#L1026
and 
https://github.com/lief-project/LIEF/blob/elf/symbol_binding/api/python/ELF/objects/pySymbol.cpp#L63
are present

**Comment by StephenZengCn** [comment]
emm..
i delete the build dictionary, and follow the compilation section of lief doc to rebuild.
weird, still the same error.
i double check the code, it's the version exactly like your paste.
any suggestion?

**Comment by romainthomas** [comment]
Check that the ``__init__.py`` of ``python -c "import lief;print(lief)"`` is the one in your *build* directory
