### ISSUE TITLE
Deoptimization of macOS dyld shared cache does not work.

### ISSUE THREAD

**Issue by kohnakagawa** [lief-project/LIEF#1127]
**Describe the bug**
Deoptimization of macOS dyld shared cache does not work.

**To Reproduce**

I wrote the following script to extract the `XprotectFramework` file in the macOS dyld shared cache (macOS version 15.2).

```python
import lief

dyld_cache = lief.dsc.load("./macos-15.2")
opt = lief.dsc.Dylib.extract_opt_t()
opt.create_dyld_chained_fixup_cmd = True
opt.fix_branches = True
opt.fix_memory = True
opt.fix_objc = True
opt.fix_relocations = True

dylib_name = "XprotectFramework"
dylib = dyld_cache.find_lib_from_name(dylib_name)
macho = dylib.get(opt)
macho.write(f"on-disk-{dylib_name}")
```

While running this script, I encountered numerous error messages like "Can't resolve symbol for address: ...".

```
% python3 test.py          
Hi kohnakagawa! Enjoy LIEF extended
Can't resolve symbol for address: 0x00000001f2128358
Can't resolve symbol for address: 0x00000001f20d17c8
Can't resolve symbol for address: 0x00000001f20d17d0
Can't resolve symbol for address: 0x00000001f20d17d8
Can't resolve symbol for address: 0x00000001f20e4568
Can't resolve symbol for address: 0x00000001f20f60e0
Can't resolve symbol for address: 0x00000001f20f6108
Can't resolve symbol for address: 0x00000001f2104468
Can't resolve symbol for address: 0x00000001f2104cd8
Can't resolve symbol for address: 0x00000001f20ee478
Can't resolve symbol for address: 0x00000001f20d1b38
Can't resolve symbol for address: 0x00000001f20d1b40
Can't resolve symbol for address: 0x00000001f20d1bd8
...
Can't resolve 0x00000001e3a9c100 into a symbol
Can't resolve 0x00000001e3a8f0c8 into a symbol
Can't resolve 0x00000001e3a8f1d8 into a symbol
Can't resolve 0x00000001e3a84388 into a symbol
Can't resolve 0x00000001e3a84388 into a symbol
...
Can't load rebases map
```

When opening the extracted dylib with Binary Ninja, the symbols do not display properly (see the attached image).

![IMG_0048](https://github.com/user-attachments/assets/e137b622-546a-4e01-a27f-da1eec388989)

According to your blog post (https://www.romainthomas.fr/post/24-09-apple-lockdown-dbi-lifting/), LIEF deoptimizes the dyld_shared_cache, and these symbols should be resolved properly.

**Expected behavior**
The symbols should be resolved properly.

**Environment (please complete the following information):**
 - macOS Sequoia 15.2
 - dyld shared cache
 - LIEF extended 0.16.0.2384

**Additional context**
I have already reported this issue via email. I posted here for tracking.

**Comment by romainthomas** [comment]
Fixed from the extended build id: `2449`
