### ISSUE TITLE
LIEF 0.16.0 cannot be linked with only MachO module

### ISSUE THREAD

**Issue by DzenIsRich** [lief-project/LIEF#1138]
Consider the following `cmake` configure command that enables only MachO module:
```bash
cmake -G "Ninja Multi-Config" -DBUILD_SHARED_LIBS=ON -DLIEF_MACHO:BOOL=ON -DLIEF_ELF:BOOL=OFF -DLIEF_PE:BOOL=OFF -DLIEF_DEX:BOOL=OFF -DLIEF_ART:BOOL=OFF -DLIEF_EXAMPLES:BOOL=OFF -DLIEF_USE_CCACHE:BOOL=OFF -DLIEF_EXTERNAL_SPDLOG:BOOL=OFF -B build
```

If you try to build LIEF configured this way
```bash
cmake --build build
```

you would get linker errors that `LIEF::ELF::Binary::has_interpreter() const` is not found.

This symbol is referenced in `LIEF::Header::from(LIEF::ELF::Binary const&)`: https://github.com/lief-project/LIEF/blob/e81492631fb6dad9d519e962ea9edf281849f3b7/src/Abstract/Header.cpp#L111-L112

**Comment by romainthomas** [comment]
Thank you for reporting this regression. It has been fixed and the commit has also been cherry-picked for the next patch version (c.f. [release/0.16.x](https://github.com/lief-project/LIEF/tree/release/0.16.x))
