### ISSUE TITLE
Add LIEF to vcpkg

### ISSUE THREAD

**Issue by Ch40zz** [lief-project/LIEF#1141]
Since vcpkg is becoming more widely known and used it seems like a good idea to add this library to vcpkg.
From doing some quick research, this has been attempted several times but there were a few issues around embedded/packaged dependencies and mainly mbedtls versioning with vcpkg.
What is the current state of the vcpkg implementation of LIEF?
Thanks!

**Comment by romainthomas** [comment]
Hi @Ch40zz,

I agree on this `vcpkg` support. Recently @luadebug created this PR https://github.com/microsoft/vcpkg/pull/42374 so I guess it's on track.

**Comment by Ch40zz** [comment]
Thats great! Some of the patches he made should dprobably go back into LIEF to make creating new LIEF versions on vcpkg easier, but looking good! :)
Hope this will be merged soon into vcpkg <3

**Comment by romainthomas** [comment]
Note that the *packaged dependencies* is the default behavior but you can also provide your own packages:
https://lief.re/doc/latest/compilation.html#third-party

**Comment by Ch40zz** [comment]
> Note that the _packaged dependencies_ is the default behavior but you can also provide your own packages: https://lief.re/doc/latest/compilation.html#third-party

That mostly works but I think he had to replace/patch a lot of includes in various cpp files. That should probably be fixed to make updates easier next time

**Comment by romainthomas** [comment]
> That mostly works but I think he had to replace/patch a lot of includes in various cpp files. That should probably be fixed to make updates easier next time

True but I don't understand the need of the patches removing the `<LIEF/third-party/xxx.hpp>`. I'll be happy to address misbehavior there.

**Comment by romainthomas** [comment]
Done by @luadebug: https://github.com/microsoft/vcpkg/pull/42374
