### ISSUE TITLE
LIEF object life time

### ISSUE THREAD

**Issue by romainthomas** [lief-project/LIEF#119]
Actually the LIEF parsers (e.g. ``LIEF::ELF::Parser::parse``) return pointer and the user is responsible for managing its life time (i.e call ``delete``).

It could be better to return a pointer wrapped by a ``std::unique_ptr<>`` as suggested by @aguinet

**Comment by neitsa** [comment]
Follow up and related question for python objects returned by `parse()`. How is their lifetime managed?

Would it be possible to have a dedicated and explicit  `close()` method **and** a [`with`](https://docs.python.org/3/reference/compound_stmts.html#with) context manager?

**Comment by romainthomas** [comment]
For Python API it is automatically wrapped with a ``std::unique_ptr``
See: https://github.com/lief-project/LIEF/blob/92a601190cc71dbc4457f8cdd04e1981b8e87248/api/python/PE/objects/pyParser.cpp#L28
and 
http://pybind11.readthedocs.io/en/stable/advanced/functions.html#return-value-policies

**Comment by neitsa** [comment]
Understood! Thanks Romain!
