### ISSUE TITLE
Issues with ELF binaries without sections

### ISSUE THREAD

**Issue by AlexAltea** [lief-project/LIEF#121]
I'm working with ELF files that have been generated from memory dumps. Therefore, no sections headers are available which makes LIEF throw some warnings when parsing them:

> The current binary doesn't have a section header

My plan from the beginning was to use LIEF to analyze dynamic entries and attempt to recreate certain sections (e.g. `SYMTAB`, `STRTAB`). However, I ran into multiple bugs:

1. Opening and saving the file without changes results in a crash
```python
lief.parse(path_input).write(path_output) # Crash
```

2. Opening, adding sections **by specifying an existing offset (and not by using the `content` key)** and saving results in various oddities:
    - The size of the file gets duplicated for no apparent reason (second half is zero-padded and ends with the section headers).
    - The section headers contain wrong information (wrong offsets, name, etc.).
    - Following warnings are thrown.

```
Unable to find the section
You inserted data in section '.dynsym' It may lead to overaly! (0 < 11)
```

---

This is a sample of the header of the binaries I'm working with:

```
$ readelf -h data.elf
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 09 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - FreeBSD
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0xffffffff82602f40
  Start of program headers:          64 (bytes into file)
  Start of section headers:          0 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         5
  Size of section headers:           0 (bytes)
  Number of section headers:         0
  Section header string table index: 0
```

This is the script I'm using to patch the binaries:

**Script: [patch-sections.zip](https://github.com/lief-project/LIEF/files/1504587/patch-sections.zip)**

**Comment by romainthomas** [comment]
Hi @AlexAltea 
Actually the ELF's builder is **not able** to handle ELF files without sections.

**Comment by AlexAltea** [comment]
Are there any plans to add support for ELF files without sections? Or rather, would you accept a pull request that enabled support for those or is this strictly a non-goal?

**Comment by romainthomas** [comment]
Yes what you want to do is very cool and very useful. I'll be glade to accept your PR ;) 
Actually I'm focused on the instrumentation of the MachO format (adding sections & cie)

**Comment by romainthomas** [comment]
Section-less ELF binaries are can now be modified by LIEF :)

**Comment by AlexAltea** [comment]
That's amazing, thank you!
