### ISSUE TITLE
Return type of `get_content_from_virtual_address` in Python

### ISSUE THREAD

**Issue by AlexAltea** [lief-project/LIEF#122]
The return type of `lief.ELF.Binary.get_content_from_virtual_address` seems to be a `list` of integers, not a `bytes`-like object, which is the most advisable type in Python 3 for this kind of data:

* Expected:
```
>>> type(lief.parse(path).get_content_from_virtual_address(addr, size))
<class 'bytes'>
```

* Current behavior as of 0.8.3:
```
>>> type(lief.parse(path).get_content_from_virtual_address(addr, size))
<class 'list'>
```

**Comment by romainthomas** [comment]
You are right but LIEF also target Python 2.7 and ``list`` are the common type. Moreover Pybind11 automatically convert ``std::vector<uint8_t>`` into a list. 
The user can do:

```python
buffer = bytes([...])
buffer = bytearray([...])
```
