### ISSUE TITLE
Verbose Logging During ELF Parsing

### ISSUE THREAD

**Issue by sjcappella** [lief-project/LIEF#125]
I'm using LIEF to parse ELF binaries and I'm getting some spurious/verbose logging information. Using the documentation for [building the SDK](https://lief.quarkslab.com/doc/compilation.html) in release mode and adding the option `-DLIEF_LOGGING=off`, I'm still seeing the messages:

- `You inserted data (18) in section '' which has SHT_NOBITS type !`
- `You inserted data (e0c) in section '' which has SHT_NOBITS type !`
- `You inserted data (18) in section '' which has SHT_NOBITS type !`

I find this odd since all I'm literally doing is using `LIEF::ELF::Parser::parse(path)`. I don't expect to see these types of logs unless I'm actively adding data to the ELF. Any suggestions on how to suppress these messages or turn off logging completely?

**Comment by romainthomas** [comment]
Which version / commit of the SDK do you use ?

**Comment by sjcappella** [comment]
I just did a fresh checkout and build of revision ae4c2a9. Now I'm actually seeing even more information being out. I'm following the steps in the 'Libraries only (SDK)' section of the documentation except I'm configuring the build with `cmake -DLIEF_PYTHON_API=off -DCMAKE_BUILD_TYPE=Release -DLIEF_LOGGING=off ..` and then running `sudo make install` at the end.

**Comment by sjcappella** [comment]
This fixed the issue, thanks!!
