### ISSUE TITLE
[doc] Wrong return type (as stated by documentation) for PE.Imports.Entry.Ordinal

### ISSUE THREAD

**Issue by neitsa** [lief-project/LIEF#126]
Documentation states that the [`ordinal`](https://lief.quarkslab.com/doc/api/python/pe.html#import-entry) field in PE Import entry is a boolean while it is an `uint16_t`.

[CPP Code](https://github.com/lief-project/LIEF/blob/315a00f65d2585ef7744864a95202671fd9f7622/include/LIEF/PE/ImportEntry.hpp#L51)

      //! @brief ordinal value
    uint16_t ordinal(void) const;

[Python Wrapper](https://github.com/lief-project/LIEF/blob/17569cae5b771bbcc6c1c0c9bfd3b66183dd58d9/api/python/PE/objects/pyImportEntry.cpp#L61)

        .def_property_readonly("ordinal",
        &ImportEntry::ordinal,
        "``True`` if ordinal is used") // (possible fix) "ordinal number"

**Comment by romainthomas** [comment]
Thanks!
