### ISSUE TITLE
some structures and enums are inaccessible.

### ISSUE THREAD

**Issue by Razzile** [lief-project/LIEF#13]
Some structures and enums that are used by the public api aren't public, such as LIEF::ELF::SECTION_FLAGS which can be used with LIEF::ELF::Section::has_flag. 

![image](https://cloud.githubusercontent.com/assets/5256381/25020915/224ee658-2088-11e7-8198-0879b240e187.png)

if I add the following include to my file the error goes away but this is less than ideal.

![image](https://cloud.githubusercontent.com/assets/5256381/25020888/0e31c1fe-2088-11e7-87ad-1accc2aebcbc.png)

this problem seems to affect all three file formats from what I can tell. It's worth noting that this may just be a problem with my project however.

**Comment by Razzile** [comment]
also including the .inc file directly seems to work (although the enums won't be in their respective namespaces)

**Comment by Razzile** [comment]
Okay I fixed it by adding this line to my CMakeLists.txt

![image](https://cloud.githubusercontent.com/assets/5256381/25021916/cb9456a0-208b-11e7-90be-567fea5ecdbb.png)

I'll leave this issue open and let you guys to decide what to do with it

**Comment by romainthomas** [comment]
How do you use LIEF in your project: 
 * from the pre-built SDK ?
 * from CMake ``external_project`` ?
 * Other ?

**Comment by Razzile** [comment]
I use LIEF with cmake by adding it as a subdirectory of my project.

**Comment by romainthomas** [comment]
So it's normal as some files like ``Structures.hpp`` and ``enums.hpp`` are generated at CMake **configuration** step. 
See: [CMakeLists.txt#L427](https://github.com/lief-project/LIEF/blob/master/CMakeLists.txt#L427) and [CMakeLists.txt#L258](https://github.com/lief-project/LIEF/blob/master/CMakeLists.txt#L258)
