### ISSUE TITLE
pip2 install fail on xcode 9

### ISSUE THREAD

**Issue by pbrunet** [lief-project/LIEF#130]
I tried to run triton with xcode9 on travis but it fails : https://travis-ci.org/JonathanSalwan/Triton/jobs/324683322

During installation, we can read : `error: can't copy 'ief.so': doesn't exist or not a regular file`
So I guess there are change in xcode9 so that lxxxx.so is the xxxx library.

**Comment by romainthomas** [comment]
``pip install setuptools --upgrade`` should fix the probem (c.f. REAME)
