### ISSUE TITLE
[API] LIEF version

### ISSUE THREAD

**Issue by cpu-00** [lief-project/LIEF#131]
Hi.

I wasn't able to find(in Python API) a function that returns the LIEF version. Is it available? Can you help, please?

**Comment by romainthomas** [comment]
Hi 
What about:
https://github.com/lief-project/LIEF/blob/09f4a4019cdf4d1677401d8902b24eb6aa678d08/api/python/__init__.py.in#L7

You can print it as follow:
```bash
python -c "import lief; print(lief.__version__)"
```
