### ISSUE TITLE
PE: Expose CodeView structure

### ISSUE THREAD

**Issue by ralphje** [lief-project/LIEF#138]
At this moment, the CodeView structure is not exposed by LIEF. This is only a single step further, which would allow to expose the pdb path, which is useful when debugging applications.

For more info see http://www.debuginfo.com/articles/debuginfomatch.html

**Comment by romainthomas** [comment]
Will be soon available in master.
Example of output: 

![debug](https://user-images.githubusercontent.com/7450402/36313930-831d7bea-1333-11e8-9159-5a38e4eea261.png)
