### ISSUE TITLE
PE: ResourceDialog must expose id/lang/sublang and items not available

### ISSUE THREAD

**Issue by ralphje** [lief-project/LIEF#139]
There are two issues with the ResourceDialog object:

* ResourceDialogItem is not exposed to Python
* The id, lang and sublang of the resource are not exposed

**Comment by romainthomas** [comment]
``ResourceDialogItem`` was just missing in the documentation. See commit above

**Comment by ralphje** [comment]
I was a little bit brief in my description regarding the ResourceDialogItem issue. When trying to access the items attribute of a ResourceDialog, I get this error om the current version in PyPI:

```>>> pe.resources_manager.dialogs[0].items
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Unable to convert function return value to a Python type! The signature was
	(arg0: _pylief.PE.ResourceDialog) -> LIEF::const_ref_iterator<std::__1::vector<LIEF::PE::ResourceDialogItem, std::__1::allocator<LIEF::PE::ResourceDialogItem> > const&, std::__1::vector<LIEF::PE::ResourceDialogItem, std::__1::allocator<LIEF::PE::ResourceDialogItem> > const&>

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.```

**Comment by romainthomas** [comment]
Indeed, I forgot to expose the iterator (Fixed with https://github.com/lief-project/LIEF/commit/1418272c2c8a7e3aae653d6e01d9614330e45c14)
