### ISSUE TITLE
PE Section entropy seems off

### ISSUE THREAD

**Issue by ralphje** [lief-project/LIEF#141]
The entropy for sections in PE executables seems to be calculated incorrectly.

LIEF displays the following for a Russian calc.exe from Windows XP:

```
.text     126b0     1000      12800     400       0         6.20531   CNT_CODE - MEM_EXECUTE - MEM_READ
.data     101c      14000     a00       12c00     0         3.58681   CNT_INITIALIZED_DATA - MEM_READ - MEM_WRITE
.rsrc     8a70      16000     8c00      13600     0         5.18754   CNT_INITIALIZED_DATA - MEM_READ
```
Whereas [VirusTotal](https://www.virustotal.com/#/file/ef854d21cbf297ee267f22049b773ffeb4c1ff1a3e55227cc2a260754699d644/details) lists the following:

```
.text	4096	75440	75776	6.19	28f821ddc492e7c89b132aeb7e8947e7
.data	81920	4124	2560	3.59	8e8381392a4f163121ab9e1cfbe54486
.rsrc	90112	35440	35840	5.23	f6f507b4f5cbf01cc2684b6c1d32db17
```

You can see that only .data is within the rounding error, but for .text, lief is slightly higher, and .rsrc is slightly lower.

--

For another sample, WannaCry in this case, LIEF displays this:

```
.text     69b0      1000      7000      1000      0         6.59876   CNT_CODE - MEM_EXECUTE - MEM_READ
.rdata    5f70      8000      6000      8000      0         6.69136   CNT_INITIALIZED_DATA - MEM_READ
.data     1958      e000      2000      e000      0         5.30123   CNT_INITIALIZED_DATA - MEM_READ - MEM_WRITE
.rsrc     349fa0    10000     34a000    10000     0         7.99987   CNT_INITIALIZED_DATA - MEM_READ
```
Whereas [VirusTotal](https://www.virustotal.com/#/file/ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa/details) shows this:
```
.text	4096	27056	28672	6.4	920e964050a1a5dd60dd00083fd541a2
.rdata	32768	24432	24576	6.66	2c42611802d585e6eed68595876d1a15
.data	57344	6488	8192	4.46	83506e37bd8b50cacabd480f8eb3849b
.rsrc	65536	3448736	3448832	8	f99ce7dc94308f0a149a19e022e4c316
```
Note that .text is slightly off, .rdata is also off, .data is completely different and .rsrc is probably correct.

**Comment by mvdnes** [comment]
It appears that LIEF calculates the entropy on the in-memory data, while other tools do in on the disk image.

A section on disk may contain a string like `XXPADDINGPADDING` repeated multiple times so that the section on disk will be aligned. This piece of data is taken into account by tools like VirusTotal, but not by LIEF. This is the case when `SizeOfRawData < VirtualSize`.
For example: in the .rsrc section of the first binary VirusTotal calculates the entropy of 0x8c00 bytes, but LIEF calculates it a dataset of 0x8a70 bytes in length.

In my opinion, LIEF is more correct as it disregards data that will never be available to a program. However, it may warrant a disclaimer.

**Comment by romainthomas** [comment]
Hi, entropy is computed in the abstract section of LIEF:

https://github.com/lief-project/LIEF/blob/79a5d0e93be82878efdb36282798a34950bce893/src/Abstract/Section.cpp#L184-L199

Computation is based on the raw data at ``[offset; offset + raw_size[`` where ``raw_size`` is the **physical** size and not the virtual one. 

What is important when looking at the entropy if it's ``7.999`` or ``8.000001`` but the magnitude of the value.

**Comment by ralphje** [comment]
@romainthomas 
I agree that it is not important whether it is 7.9999 or 8.0001, or even 5.9 vs 5.8, but differences that are close to 1 whole point (as in the WannaCry .data case) should be explained (or at least explainable) in one way or another. @mvdnes 's explanation seemed fair, but am I correct that you say that that's not the case?

There is some way that the entropy is calculated differently, leading to wild differences with VirusTotal and this package, which may be indicative of a bug in the entropy calculation. I believe this warrants a closer investigation.

**Comment by mvdnes** [comment]
`raw size` is not always the **physical** size. It can be the **virtual** if that size is smaller (this *does* happen in the field):

https://github.com/lief-project/LIEF/blob/79a5d0e93be82878efdb36282798a34950bce893/src/PE/Parser.cpp#L206-L210

**Comment by romainthomas** [comment]
> raw size is not always the physical size. It can be the virtual if that size is smaller (this does happen in the field):

Yes I forgot to mention the PE case. Thanks 

> but differences that are close to 1 whole point (as in the WannaCry .data case) should be explained

I totally agree and if you have another idea to compute the entropy, you can open an issue / PR associated with.
