### ISSUE TITLE
PE Authentihash calculation

### ISSUE THREAD

**Issue by ralphje** [lief-project/LIEF#142]
This is a feature request probably going to the long list, but it would be awesome if LIEF would have the ability to calculate the authentihash of a PE file, given a hashing algorithm. This could be used to verify the data currently already in LIEF (regarding ContentInfo), but also to match samples with the same content but different signature, as VirusTotal currently does (it shows the authentihash as sha256).

The way to calculate this hash is currently documented in here: http://download.microsoft.com/download/9/c/5/9c5b2167-8017-4bae-9fde-d599bac8184a/Authenticode_PE.docx

There is a rather old Python 2.7 module approximately doing the same thing: https://github.com/anthrotype/verify-sigs

**Comment by Rafiot** [comment]
(this issue can be closed => https://lief.quarkslab.com/doc/latest/api/python/pe.html#lief.PE.Binary.authentihash)
