### ISSUE TITLE
Not compiling in VS 2015 (with instructions to fix)

### ISSUE THREAD

**Issue by aurelianito** [lief-project/LIEF#144]
The master thread does not compile using Visual Studio 2015, as some `IMAGE_DEBUG*` constants are not being undefined. 

To do so add after `#undef IMAGE_DEBUG_TYPE_CLSID` in `include/LIEF/PE/undef.h` the following lines:

```
#undef IMAGE_DEBUG_TYPE_VC_FEATURE
#undef IMAGE_DEBUG_TYPE_POGO
#undef IMAGE_DEBUG_TYPE_ILTCG
#undef IMAGE_DEBUG_TYPE_MPX
#undef IMAGE_DEBUG_TYPE_REPRO
```

**Comment by romainthomas** [comment]
Thanks!
