### ISSUE TITLE
Error when linking against debug libraries (static)

### ISSUE THREAD

**Issue by aurelianito** [lief-project/LIEF#147]
I am developing in Visual Studio 2015. After finding  #144 I managed to compile LIEF. But I cannot link the debug version of the libraries. If I do so a lot of errors similar to this one appear:

```
5>LIEF.lib(Binary.cpp.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in lief_test.obj
5>LIEF.lib(Binary.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in lief_test.obj
```

`lief_test.obj` is the name of the obj I generated.

I compile LIEF in debug mode by running
```
mkdir deb32
cd deb32
cmake -DLIEF_LOGGING=off -DLIEF_PYTHON_API=off -DCMAKE_BUILD_TYPE=Debug -DLIEF_ENABLE_JSON=off -DLIEF_ELF=off -DLIEF_MACHO=off ..
cmake --build . --target LIB_LIEF_STATIC --config Debug
cd ..
```

I suspect that somewhere in the compilation the build type is set as release, but I cannot find it anywhere in the `CMakeLists.txt` file. 
I am only interested in parsing PE files, that's why I am compiling with `-DLIEF_ELF=off` and `-DLIEF_MACHO=off`

Am I doing anything wrong?

This error happens when I compile in both 32 bits and 64 bits.

When I compile in release mode, it seems to be working properly.

PS: The VS 2015 error is explained here. https://stackoverflow.com/questions/7668200/error-lnk2038-mismatch-detected-for-iterator-debug-level-value-0-doesnt

**Comment by romainthomas** [comment]
Does changing ``/MT`` to ``/MTd`` in visual studio before the 
``cmake --build . --target LIB_LIEF_STATIC --config Debug``
Work ?

**Comment by aurelianito** [comment]
If I manually change the setting in Visual Studio it then links properly :).

**Comment by aurelianito** [comment]
I changed the setting in the LIB_LIEF_STATIC project in Visual Studio.

**Comment by aurelianito** [comment]
Where you able to work on this? Is there anything I can help you with?

**Comment by romainthomas** [comment]
Could you check if this commit: https://github.com/lief-project/LIEF/commit/8e8e2f2cb653ae97cb46ff1c35e80168c60ac333 fix the problem ?

**Comment by aurelianito** [comment]
When I try to run cmake to generate either debug or release in the 8e8e2f2cb653ae97cb46ff1c35e80168c60ac333 commit like this:
```C:\devel\LIEF\rel32>cmake -DLIEF_LOGGING=off -DLIEF_PYTHON_API=off -DCMAKE_BUILD_TYPE=Release -DLIEF_ENABLE_JSON=off -DLIEF_ELF=off -DLIEF_MACHO=off .. ```

I get this error:
```
-- Build Types: Release
CMake Error at examples/cpp/CMakeLists.txt:59 (target_compile_options):
  Cannot specify compile options for target "_shared" which is not built by
  this project.


CMake Error at examples/cpp/CMakeLists.txt:59 (target_compile_options):
  Cannot specify compile options for target "_shared" which is not built by
  this project.


CMake Error at examples/cpp/CMakeLists.txt:59 (target_compile_options):
  Cannot specify compile options for target "_shared" which is not built by
  this project.


CMake Error at examples/cpp/CMakeLists.txt:59 (target_compile_options):
  Cannot specify compile options for target "_shared" which is not built by
  this project.


CMake Error at examples/cpp/CMakeLists.txt:59 (target_compile_options):
  Cannot specify compile options for target "_shared" which is not built by
  this project.
```

This does not happen if I use master (commit 251676a0a253a3d1a5db79999a117f2594a40e64)

**Comment by romainthomas** [comment]
Ok I fixed this error with https://github.com/lief-project/LIEF/commit/88f49209a197d621fd2f6c7ae195264e03d0d819

**Comment by aurelianito** [comment]
Now the debug branch generates debug and release .lib files :smile:. 

Thanks!
