### ISSUE TITLE
`PE` API inconsistency

### ISSUE THREAD

**Issue by tathanhdinh** [lief-project/LIEF#151]
In `PE::Section` class, [`sizeof_raw_data`](https://github.com/lief-project/LIEF/blob/master/src/PE/Section.cpp#L91) is implemented by calling [`Abstract::Section::size`](https://github.com/lief-project/LIEF/blob/master/src/Abstract/Section.cpp#L71), which returns `size_`. 

From a [constructor](https://github.com/lief-project/LIEF/blob/master/src/PE/Section.cpp#L69) of `PE::Section`, I suppose that the constraint `size_ == content_.size()` would be kept. But `PE::Section` has method [`content`](https://github.com/lief-project/LIEF/blob/master/src/PE/Section.cpp#L99) which returns a reference to the internal `content_`, using this method we can modify `content_` and that will break the constraint `size == content_.size()`.

The following use-case shows this inconsistency:
```
auto text_section = LIEF::PE::Section(".text");
text_section.content() = { 0x90, 0x90, 0x90 };
text_section.sizeof_raw_data(); // this returns 0 instead of 3
```
A possible fix would be not exporting any reference to `content_` ?

**Comment by romainthomas** [comment]
Hi @tathanhdinh 

You are right, ``text_section.content()`` should not break the invariant of the Section class. In fact I exposed the reference to avoid copy constructor under certain circumstance (even if copy elision can be used)   

As a fix, I will rename the ``content`` method in ``content_ref`` and move it into a private scope
