### ISSUE TITLE
Error compiling LIEF with VS2015 (fatal error C1001) 

### ISSUE THREAD

**Issue by aurelianito** [lief-project/LIEF#152]
Running `cmake --build . --target INSTALL --config Release` makes a weird error.

fatal error C1001: An internal error has occurred in the compiler

```
"C:\devel\CTAEngine\external\install\Release\Win32\build\LIEF\INSTALL.vcxproj" (default target) (1) ->
"C:\devel\CTAEngine\external\install\Release\Win32\build\LIEF\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\devel\CTAEngine\external\install\Release\Win32\build\LIEF\LIB_LIEF_SHARED.vcxproj" (default target) (4) ->
(ClCompile target) ->
  C:\devel\LIEF\include\LIEF/ELF/DynamicEntryArray.hpp(33): fatal error C1001: An internal error has occurred in the compiler. [C:\devel\CTAEngine\external\install\Release\Win32\build\LIEF\LIB_LIEF_SHARED.vcxproj]
```

This happens compiling master. I am using Visual Studio 2015.

**Comment by romainthomas** [comment]
Hi @aurelianito, We also had this problem with CI and it seems to be a bug in Visual Studio 2015. We had to move to VS2017

**Comment by aurelianito** [comment]
@romainthomas I want raise a pull request to workaround the issue, as it triggers when generating the dynamic library but the static library is fine. Is this ok with you? Would you accept it?

**Comment by aurelianito** [comment]
I want to be able to run install for the static library

**Comment by romainthomas** [comment]
Yes, It would very nice!

**Comment by aurelianito** [comment]
@romainthomas, If everything goes fine I will be raising a PR this week. Thanks!

**Comment by romainthomas** [comment]
Great! Thank you.

**Comment by aurelianito** [comment]
@romainthomas here is the promised pull request :smile:

**Comment by aurelianito** [comment]
Issue worked around. Is good enough for me. Closing bug.
