### ISSUE TITLE
Update section of a data directory

### ISSUE THREAD

**Issue by tathanhdinh** [lief-project/LIEF#157]
I still cannot figure out how to set a section for a newly created data directory. There is a [`section`](https://github.com/lief-project/LIEF/blob/master/src/PE/DataDirectory.cpp#L98) method which returns a reference to the internal `section_`, so I guess that this method can be used to set section for a data directory, something likes that:

```
auto text_section = Section(".text");
auto export_dir = DataDirectory(DATA_DIRECTORY::EXPORT_TABLE);
export_dir.section() = text_section;
```
But this does not work since [`section`](https://github.com/lief-project/LIEF/blob/master/src/PE/DataDirectory.cpp#L98) is a `const cast` of a [constant reference returning method](https://github.com/lief-project/LIEF/blob/master/src/PE/DataDirectory.cpp#L89), which throws an exception if the internal `section_` is `nullptr`, this is always the case for a newly created data directory.

**Comment by romainthomas** [comment]
Hi @tathanhdinh,
Indeed actually one can't change the section of a Data Directory. I'll provide the API by the end of the day

**Comment by romainthomas** [comment]
Could you explain for which purpose you would like to change or set the section bound to a DataDirectory. Actually it could break internal state of the ``PE::Binary`` object.
