### ISSUE TITLE
strtab out of bounds error; STRSZ=1751, name=1751

### ISSUE THREAD

**Issue by Rprop** [lief-project/LIEF#159]
```C++
auto binary = LIEF::ELF::Parser::parse("/system/bin/app_process");
binary->add_library("libMyFramework.so");
binary->write("/data/data/com.MyTest/app_process_x");
```
cp /system/lib/libc.so /system/lib/libMyFramework.so
cd /data/data/com.MyTest/
chmod 777 app_process_x
./app_process_x: strtab out of bounds error; STRSZ=1751, name=1751

[sample](https://github.com/lief-project/LIEF/files/1955445/Temp.zip)

**Comment by Rprop** [comment]
hi, @romainthomas, here is another sample which will crash during `__dl___linker_init_post_relocation`, and if it's something you're aware of, wondered if you can fix it?
[sample_crash.zip](https://github.com/lief-project/LIEF/files/1961260/sample_crash.zip)

**Comment by romainthomas** [comment]
It's on a 4.4 device ?

**Comment by Rprop** [comment]
No, it's 4.1.1, and after investigation I found that there may be certain restrictions of statically linking against a shared library or something wrong with the system linker since the modified so can be loaded successfully by `dlopen`.
Thanks again, pls ignore this issue.
