### ISSUE TITLE
Can I update anything in LIEF?

### ISSUE THREAD

**Issue by jackqk** [lief-project/LIEF#169]
int main(int argc, char *argv[])
{
        LIEF::PE::Binary* binary = LIEF::PE::Parser::parse("C:\\Users\\FrogGod\\Desktop\\FGTest\\notepad.exe");
        auto head = binary->dos_header();
        head.magic(0x1111);
        binary->write("C:\\Users\\FrogGod\\Desktop\\FGTest\\notepad1.exe");
        delete binary;
        return 0;
}

but magic number don't change in notepad1.exe.

**Comment by romainthomas** [comment]
In you C++ code the ``auto head = binary->dos_header();`` returns a **copy** of the ``LIEF::PE::DosHeader`` object. You should use: ``auto& head = binary->dos_header();``

**Comment by jackqk** [comment]
I See.Thank you bro
