### ISSUE TITLE
Handle Dwarf format

### ISSUE THREAD

**Issue by romainthomas** [lief-project/LIEF#17]

**Comment by pombredanne** [comment]
This would be an awesome addition!

**Comment by romainthomas** [comment]
As suggested by @aguinet this feature could be handled through an LLVM interface.

**Comment by pombredanne** [comment]
@romainthomas ok, so you do not want it in lief after all?

**Comment by romainthomas** [comment]
Actually I think it would be better to have a *bridge* between LIEF and the LLVM Dwarf API.
Basically, LIEF could be used to access the dwarf-related sections while LLVM Dwarf would manage the parsing.

On the other hand, I'm not close to the idea to have a LIEF plugin-like for Dwarf. I'm currently prototyping objc metadata as an external LIEF module and it seems to be a pretty good design (IMO).

**Comment by romainthomas** [comment]
There we go: https://lief.re/doc/latest/extended/dwarf/index.html
