### ISSUE TITLE
Code Crash at lief.parse() method

### ISSUE THREAD

**Issue by Krishnasawe** [lief-project/LIEF#172]
The Code Crashing at "lief_binary = lief.parse(pefile)" with Error.

Unable to find the section associated with EXPORT_TABLE
Offset: 0x287694cf is bigger than the binary size
Offset: 0xb80000ff is bigger than the binary size

Below field are Invalid. Even after using Exception handling the Code Crashes.
Exp_data_dir_rva = 1
Exp_data_dir_size = 0

Suggest me What wrong I am doing.
I also tried "lief.PE.parse(list(bytez))"

**Comment by romainthomas** [comment]
Could you attach the binary ?

**Comment by Krishnasawe** [comment]
[06334f414248b304cd69200bb908529e.zip](https://github.com/lief-project/LIEF/files/2022373/06334f414248b304cd69200bb908529e.zip)

**Comment by Krishnasawe** [comment]
Let me know if you require anything else from my Side.

**Comment by romainthomas** [comment]
Humm based on commit 2de4bab, LIEF is able to load the binary:

```python
>>> import lief
>>> lief.__version__
0.8.3-2de4bab
>>> pe = lief.parse("06334f414248b304cd69200bb908529e")
>>> print(pe)
...
```

**Comment by Krishnasawe** [comment]
Hi,
I am trying in Python. Still getting Crash. below is the Code i wrote. Can you try this with Python

import lief

pe = lief.parse("E:\\Xcluded\\ML\\ember-master\\PE_Ember_extra_prop_added\\Problamatic_Samples\\06334f414248b304cd69200bb908529e")

print(pe)

**Comment by romainthomas** [comment]
Yes I did see above and it works. You may have a path problem...

**Comment by romainthomas** [comment]
Could you past the error ?

**Comment by Krishnasawe** [comment]
Unable to find the section associated with EXPORT_TABLE
Offset: 0x287694cf is bigger than the binary size
Offset: 0xb80000ff is bigger than the binary size

**Comment by romainthomas** [comment]
Yes, because the export table is corrupted....

**Comment by Krishnasawe** [comment]
I executed it on thousands of File. Its working fine for all the File.
The problem occur only with this File.

**Comment by romainthomas** [comment]
It could be use as an anti-debug.

**Comment by Krishnasawe** [comment]
Yes the Export table is Corrupted...
  But I want my program should not Crash. the execution must continue

**Comment by Krishnasawe** [comment]
I tried exception handling but still the problem occurs. Any Idea bro

**Comment by romainthomas** [comment]
```python
Python 3.6.5 (default, Apr 14 2018, 13:17:30) 
[GCC 7.3.1 20180406] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
>>> pe = lief.parse("./06334f414248b304cd69200bb908529e")
>>> print(pe.entrypoint)
4200604
>>> print(pe.sections[0])
.text     0         1000      2         1000      0         1         CNT_CODE - MEM_EXECUTE - MEM_READ
```

Check you script

**Comment by Krishnasawe** [comment]
I tried it bro. but still same error occurs. Can it be due to the version of LIEF. i am using the latest version.

>>> import lief
>>> pe = lief.parse("06334f414248b304cd69200bb908529e")
Unable to find the section associated with EXPORT_TABLE
Offset: 0x287694cf is bigger than the binary size
Offset: 0xb80000ff is bigger than the binary size

**Comment by Krishnasawe** [comment]
>>> import lief
>>> print(lief.__version__)
0.8.3-18d5b75
>>>

**Comment by romainthomas** [comment]
Ok please try with:

```
pip install https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.8.3.dev.zip
```

**Comment by Krishnasawe** [comment]
Requirement already satisfied (use --upgrade to upgrade): lief==0.8.3 from https://github.com/lief-project/pac
kages/raw/lief-master-latest/pylief-0.8.3.dev.zip in c:\python\python36-32\lib\site-packages

**Comment by romainthomas** [comment]
``pip uninstall lief`` first ...

**Comment by Krishnasawe** [comment]
I Uninstalled LIEF and then installed it again.
>>> import lief
>>> lief.__version__
'0.8.3-4fcfba0'

Still the problem is not resolved. Is there any System configuration which need to check.

**Comment by romainthomas** [comment]
Ok I confirm the issue with 32 bits version of LIEF.

**Comment by romainthomas** [comment]
But you use Python 23-bits right ?

**Comment by Krishnasawe** [comment]
i am using Python 3.6

**Comment by Krishnasawe** [comment]
Its 32 bit

**Comment by Krishnasawe** [comment]
How do i install package (dc909a1).

**Comment by Krishnasawe** [comment]
Thank u Bro. I got the Package and now its working properly.
Thanks very much

**Comment by Krishnasawe** [comment]
:+1:
