### ISSUE TITLE
Error calculating imports

### ISSUE THREAD

**Issue by aurelianito** [lief-project/LIEF#174]
The attached file (**WARNING: it may be malware, I am not sure**)
[12acfd47b205f6488bd225bd583c40cf78f7f094b153ec4150715e507a119fc4.gz](https://github.com/lief-project/LIEF/files/2023653/12acfd47b205f6488bd225bd583c40cf78f7f094b153ec4150715e507a119fc4.gz) does not have any import. The latest release (0.8.3) lists the imports properly.

When I parse the file (gunziped) with the top of master it detects a weird thing:

```
>>> b = lief.parse("12acfd47b205f6488bd225bd583c40cf78f7f094b153ec4150715e507a119fc4")
>>> b.has_imports
True
>>> list(b.imports)
[<_pylief.PE.Import object at 0x0000000003A5A030>]
>>> l = list(b.imports)
>>> l[0]
<_pylief.PE.Import object at 0x0000000003A5A030>
>>> e = l[0]
>>> e.name
u'qlite3_value_double'
```

Similar behavior happens when I run equivalent code in C++. I am using `Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32`.

**Comment by aurelianito** [comment]
PS: I double checked. It does not seem to have any import.

```
> dumpbin /imports 12acfd47b205f6488bd225bd583c40cf78f7f094b153ec4150715e507a119fc4
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file e:\amp_integration_data_machine\binaries\12acfd47b205f6488bd225bd583c40cf78f7f094b153ec4150715e507a119fc4

File Type: DLL

  Section contains the following imports:

  Summary

        3000 .data
        1000 .gfids
       10000 .rdata
        4000 .reloc
        1000 .rsrc
       89000 .text
```

**Comment by romainthomas** [comment]
Yes it's weird, CFF explorer also print this import 

![cffex](https://user-images.githubusercontent.com/7450402/40344428-109e8cc4-5d95-11e8-8b06-de67e9d00e80.png)

I'll see what kind of *rules* we can have on imports to check that they are valid

**Comment by aurelianito** [comment]
Thanks!

**Comment by aurelianito** [comment]
Is there any news on this?

**Comment by romainthomas** [comment]
Do you have any information about what is a valid DLL name regarding to Windows loader ?

**Comment by aurelianito** [comment]
@romainthomas, I looked for it. It seems that any valid file name is a valid dll name.

https://stackoverflow.com/questions/7244918/loadlibrary-of-a-file-with-other-the-dll-extension

**Comment by aurelianito** [comment]
@romainthomas, confirmed. Someone reversed PE file loading on Windows and static imports can point to about anything. http://j00ru.vexillium.org/?p=881 I think commit e2466bb should be reverted.

**Comment by romainthomas** [comment]
Already done. So I can close the issue ?

**Comment by aurelianito** [comment]
Do you understand why is there a difference between the reported imports in the current master versus the latest release of LIEF for this file? Which one is working properly? I would not close this issue unless we can be sure that the current behavior is correct and the old LIEF has a bug.

**Comment by romainthomas** [comment]
Ok got it. Indeed it was not about MIN_DLL_NAME_SIZE. In fact in LIEF 0.8.3 we stop imports parsing at the first error (in your output the first import has no name so parsing abort at the first entry). In master we continue parsing and skip the import that has an error.

**Comment by aurelianito** [comment]
If the issue is understood then closing seems the right action
