### ISSUE TITLE
Wrong Optional Header is Generated for certain files.

### ISSUE THREAD

**Issue by Krishnasawe** [lief-project/LIEF#175]
Hi Team,
   For certain files(Mostly Corrupt files) the LIEF is printing wrong values of Optional Header. It should either print Right values or Indicate if the Optional Header is not proper.
I have attached the PE File along with the Output Generated by CFF Explorer and LIEF

![cff](https://user-images.githubusercontent.com/30498165/40407610-9daca860-5e82-11e8-945b-b3c48797ed89.png)
![lief_code](https://user-images.githubusercontent.com/30498165/40407611-9dd82828-5e82-11e8-8692-84dac12f9bd1.png)

**Comment by romainthomas** [comment]
Could you attach the given file ?

**Comment by Krishnasawe** [comment]
[de53e487c4b43d3fd0f3eeb24ab4940d.zip](https://github.com/lief-project/LIEF/files/2030219/de53e487c4b43d3fd0f3eeb24ab4940d.zip)

**Comment by romainthomas** [comment]
If you enable the log you will that the optional header is corrupted. This file is not even executable since it is too small. 

The above output is the result of the OptionalHeader's default constructor and in your script you should do a prepossessing step to filter corrupted PE files (that are not runnable)

See also #133

**Comment by Krishnasawe** [comment]
I Agree with you that the  File is too small and Corrupted. But i am running the Code on large sample set and i want to avoid this type files. is there any Mechanism in LIEF to seperate out Corrupted Files.

**Comment by romainthomas** [comment]
You can have your own function:

```python
def is_valid(path):
    if not lief.is_pe(path):
        return False

    pe = None
    try:
        pe = lief.parse(path)
    except Exception:
        return False

    if pe is None or len(pe.sections):
        return False

    return True
```

**Comment by Krishnasawe** [comment]
Ok. Thank you
