### ISSUE TITLE
Flag for MIPS arch

### ISSUE THREAD

**Issue by ManSoSec** [lief-project/LIEF#177]
There is a bug on some binaries with MIPS arch when trying to get its type (Binary.header.machine_type)

Example hash: a85fdf6a8bc9fe4cfbb69f6e7b3a9ac355e301556e06e17bf73a5eab862be2f5

Thanks!

**Comment by romainthomas** [comment]
Related to #173  and fixed with e794ac1502ee7636755bd441923368f88525a7d0
You can try by installing the "dev" version
