### ISSUE TITLE
Unable to modify interpreter of ELF executable

### ISSUE THREAD

**Issue by Bidski** [lief-project/LIEF#182]
I am trying to change the path of the interpreter of an ELF executable. My code is is as follows
```
binary = lief.parse('/path/to/executable')
interp = binary.get_section('.interp')
interp.content = '/path/to/new/interpreter'.encode('utf-8')
binary.write('/path/to/executable')
```

Unfortunately, I receive one of 2 results. Either I get the following error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError: std::bad_alloc
```

Or, I get no error, but running `patchelf --print-interpreter /path/to/executable` shows the original interpreter of `/path/to/executable` and not `/path/to/new/interpreter`.

This is happening using both v0.8.3 and v0.9.0 from pip.

What is happening here?

**Comment by romainthomas** [comment]
Hi @Bidski 

You can try this way:

```python
binary = lief.parse('/path/to/executable')
binary.interpreter = "/path/to/new/interpreter"
binary.write('/path/to/executable_modified')
```

**Comment by Bidski** [comment]
@romainthomas my sincerest apologies for not getting back on this. 

That did indeed fix my problem. Thank you for your help.
