### ISSUE TITLE
Unable to add symbols to relocation

### ISSUE THREAD

**Issue by roie-c2a** [lief-project/LIEF#184]
I am trying to copy a PLTGOT relocation from one ELF to another ELF.
However, once calling binary.add_pltgot_relocation(), the symbol is removed from the relocation.
If I try later to set the symbol property, I get an error that this attribute cannot be set.
I tried to set the info property of the relocation, and it was changed indeed, but when I write that elf to a file, the symbol information is lost.

**Comment by romainthomas** [comment]
As an example:

https://github.com/lief-project/LIEF/blob/a9f3cb8f9b4a1f2cdaa95eee4568ff0b162f77cd/tests/elf/modify_relocations.py#L33-L42
