### ISSUE TITLE
Invalid p_filesz in PT_DYNAMIC program header after adding library in ELF

### ISSUE THREAD

**Issue by jeanbmar** [lief-project/LIEF#194]
First, great job with LIEF.
I'm using LIEF 0.9.0 to inject Frida into an Android native library.
Generated lib works great on Android <= 7, but crashes on Android 8+.

This is due to a new Android 8 check: invalid-elf-header_section-headers-enforced-for-api-level-26 (https://android.googlesource.com/platform/bionic/+/master/linker/linker_phdr.cpp).

It seems the PT_DYNAMIC p_filesz is set by LIEF to 0x1000 no matter the real size of the .dynamic section.

I understand patching the .dynamic section isn't trivial. 
Is there any way we could write the right size?

**Comment by romainthomas** [comment]
I think it has been fixed in https://github.com/lief-project/LIEF/issues/186 (c.f. https://github.com/lief-project/LIEF/commit/3098193227f6c2c00e1a689128c2881e38f7dc9a)

**Comment by romainthomas** [comment]
You can try with:

```python
pip install https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.9.0.dev.zip
```

**Comment by jeanbmar** [comment]
Great thanks, sorry for duplicate!
