### ISSUE TITLE
PyLIEF aborts on SIGINT

### ISSUE THREAD

**Issue by Mrmaxmeier** [lief-project/LIEF#199]
```
(venv) ⋊> pip list
Package    Version
---------- -------
lief       0.9.0
...
(venv) ⋊> python3
Python 3.6.6 (default, Jun 27 2018, 13:11:40) 
[GCC 8.1.1 20180531] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
>>> # hit ctrl-c
... fish: “python3” terminated by signal SIGABRT (Abort)
```

Python aborts in [`el::base::debug::defaultCrashHandler`](https://github.com/muflihun/easyloggingpp/blob/66a3a8741c42a512bd9237dff458bb6b055215e7/src/easylogging%2B%2B.cc#L2878) of `_pylief.cpython-36m-x86_64-linux-gnu.so`.
It looks like the default crash handler provided by easylogging++ handles all signals including SIGINT.

See https://github.com/muflihun/easyloggingpp/issues/186 for a similar issue.

**Comment by romainthomas** [comment]
Hi! 
Yes I fixed with this commit https://github.com/lief-project/LIEF/commit/ce4af44b265809b32fb506e8486dbd2a794e2412
