### ISSUE TITLE
elf hook issue

### ISSUE THREAD

**Issue by pcheng74** [lief-project/LIEF#203]
Hi,

Based on doc:https://lief.quarkslab.com/doc/latest/tutorials/04_elf_hooking.html
I wrote the following C ++ code to do my own function hook.

int main(int argc, char **argv) {

	std::cout << "ELF patch  _init function" << std::endl;

	std::unique_ptr<Binary> binary{ Parser::parse(argv[1]) };
	std::unique_ptr<Binary> stub{ Parser::parse(argv[2]) };

	Symbol my_init_sym = (Symbol &)stub->get_symbol("my_init");
	Segment init_seg = (Segment )stub->segment_from_virtual_address(my_init_sym.value());
	Segment segment_added  = binary->add(init_seg);

	uint64_t my_init_addr = segment_added.virtual_address() + my_init_sym.value();
	Symbol init_sym = (Symbol &)binary->get_symbol("my_init");

	init_sym.value(my_init_addr);

	binary->write(argv[3]);
	return 0;
}

And above code can run successfully, however when I checked the new generated so file the hooked my_init function address is not changed.

Any suggestions?

**Comment by romainthomas** [comment]
Your code involves copy constructors. You have to use reference (i.e ``Symbol`` -> ``Symbol&`` etc)

**Comment by romainthomas** [comment]
Please read the doc: https://github.com/lief-project/LIEF/blob/master/include/LIEF/ELF/Binary.hpp#L343
Most value returned from LIEF should be considered as reference

**Comment by romainthomas** [comment]
Yes it is related to references because you use object copy so it breaks internal state.

**Comment by pcheng74** [comment]
@romainthomas,

If so, can you give me a C++ sample to demonstrate how to update the value of symbol?

Thanks,
