### ISSUE TITLE
Visual Studio Configuration: ImpLib has same name as static library and is overwritten if you build the whole solution

### ISSUE THREAD

**Issue by mitp0sh** [lief-project/LIEF#209]
Hi, 

Today I realized that the impl lib as well as the static lib do have the same name. If you actually build the whole solution this will result in the static lib be overwritten by the impl lib, which is not nice.

Could be easily fixed by giving the static link a suffix like "_static".

Would be cool if you fix that one day.

Cheers,
mitp0sh

PS: LIEF is great!!! Keep on the good work ;-D

**Comment by romainthomas** [comment]
Yes I'm aware of this issue and @aguinet provided a PR for that https://github.com/lief-project/LIEF/pull/201 
I still need to take time to update CI & tests

**Comment by romainthomas** [comment]
Fixed with #201
