### ISSUE TITLE
Some string encoding errors in Exports

### ISSUE THREAD

**Issue by blaquee** [lief-project/LIEF#21]
Writing a simple script using python to list the exports and I get this error when dumping kernl32.dll exports:
`UnicodeDecodeError: 'utf8' codec can't decode byte 0xba in position 0: invalid start byte`

this occurs when using either the list from ```binary.exported_functions``` or the ```binary.get_export()/export.entries``` combination.

I tried adding a string.encode('utf-8') but that doesnt work. Not sure how these strings are being encoded for python.

**Comment by blaquee** [comment]
right now i can only confirm this occurs on kernel32.dll on a windows 10 x64 machine. 32bit kernel32.dll

**Comment by romainthomas** [comment]
Does it related to #10 ?
