### ISSUE TITLE
Error importing LIEF in pypy2.7 env

### ISSUE THREAD

**Issue by AndyXan** [lief-project/LIEF#211]
Hello,

I'm encountering an Issue unique to a pypy environment. 

```
unable to load extension module '/home/.virtualenvs/pypy-angr/site-packages/_pylief.pypy-41.so': /home/virtualenvs/pypy-angr/site-packages/_pylief.pypy-41.so: undefined symbol: PyExc_ValueError
```

The file _pylief.pypy-41.so is present at the correct location and for a usual cpython environment everything works. Also worth mentioning, for importing and executing I'm using standard Ipython, not pypy in this case - so this seems to be a pure environmental problem and not directly linked to the interpreter itself. 

Anyone stumbled upon this? 

Best Regards, 
Andreas

**Comment by romainthomas** [comment]
I think LIEF prebuilt packages are not compatible with Pypy. Maybe you should try with the official version of Python
