### ISSUE TITLE
Missing egg file for Python 3.7

### ISSUE THREAD

**Issue by Ayrx** [lief-project/LIEF#214]
As mentioned in title, installing LIEF with pip fails if you are using Python 3.7. Could we get eggs uploaded for that version?

**Comment by romainthomas** [comment]
Yes, CI only provide egg packages for Python 2.7, 3.5 and 3.6. Starting from 2019 we will drop py2.7 packages and provide 3.7.

For now you can still compile LIEF for python 3.7 as follow:

```console
$ mkdir build && cd build
$ cmake -DPYTHON_VERSION=3.7 .. 
$ make -j3 pyLIEF
$ export PYTHONPATH=$(pwd)/api/python 
```

**Comment by colincowie** [comment]
Any update on the missing egg file?

**Comment by romainthomas** [comment]
c.f: https://github.com/lief-project/LIEF/issues/282#issuecomment-473993736

**Comment by nil0x42** [comment]
i have the same problem

**Comment by 3vangel1st** [comment]
What I did was download the dev version from https://lief.quarkslab.com/packages/lief/

in my case for OSX, executed the following command:

pip install lief-0.9.0.dev0-cp35-cp35m-macosx_10_12_x86_64.whl 

and worked like a charm
