### ISSUE TITLE
compiling an example on ubuntu using eclipse. issue is un resolved. 

### ISSUE THREAD

**Issue by gsr819** [lief-project/LIEF#217]
I am compiling the below demo on eclipse ubuntu
------------------------------------------------
//============================================================================
// Name        : LIEF.cpp
// Author      : Sunder
// Version     :
// Copyright   : Your copyright notice
// Description : Hello World in C++, Ansi-style
//============================================================================

#include <LIEF/LIEF.hpp>

int main(int argc, const char** argv) {

  LIEF::PE::Binary *pe = LIEF::PE::Parser::parse("C:\\Windows\\explorer.exe").get();

  std::cout << *pe   << std::endl;

  delete pe;
}
The below is unresolved issue... 
-----------------------------------------
20:02:46 **** Incremental Build of configuration Debug for project LIEF ****
make all 
Building target: LIEF
Invoking: GCC C++ Linker
g++ -L/home/sunder/LIEF-0.9.0-Linux/lib -o "LIEF"  ./src/LIEF.o   -lLIEF
./src/LIEF.o: In function `main':
/home/sunder/lief/LIEF/Debug/../src/LIEF.cpp:14: undefined reference to `LIEF::PE::Parser::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make: *** [LIEF] Error 1
makefile:45: recipe for target 'LIEF' failed

20:02:47 Build Finished (took 437ms)
------------------------------------------------------------

**Comment by gsr819** [comment]
any updates

**Comment by romainthomas** [comment]
It looks like you misconfigured the eclipse project. LIEF is tested on Ubuntu 14.04.

**Comment by gsr819** [comment]
my ubuntu is 18.04, hope it should get thru' with this ubuntu release.

**Comment by gsr819** [comment]
what may be misconfigured in eclipse set up for this LIEF code?

**Comment by gsr819** [comment]
can u tell me the check points in eclipse setup for this code to compile successfully?
