### ISSUE TITLE
Improve CMakeLists.txt for better reading/editing in Visual Studio IDE

### ISSUE THREAD

**Issue by ek0** [lief-project/LIEF#22]
Hi,

I've encountered a small issue trying to edit the source code in visual studio.
Currently the generated solution doesn't group the source files under filters.
Also the header files are put under the "External Dependencies" section.
Here is an example of the currently generated tree:
![image](https://cloud.githubusercontent.com/assets/7302683/25346749/8226355c-28e6-11e7-81a6-19d7ad772d67.png)
But I think it would be better, for example to have something like this:
![image](https://cloud.githubusercontent.com/assets/7302683/25346809/b4e0c8ea-28e6-11e7-9b49-1de2d30115bf.png)

Thanks

**Comment by romainthomas** [comment]
close with #24
