### ISSUE TITLE
[ELF][Python] PT_DYNAMIC is not updated after DT_RPATH is removed.

### ISSUE THREAD

**Issue by Linvail** [lief-project/LIEF#220]
Python code:

    libBin = lief.parse(target_lib.abspath())
    if libBin.has(lief.ELF.DYNAMIC_TAGS.RPATH):
        libBin.remove(lief.ELF.DYNAMIC_TAGS.RPATH)
        libBin.write(target_lib.abspath())

The size in .dynamic in section headers is updated (decreased) correctly, but the PT_DYNAMIC in program header seems not.

I got this error in runtime:

    java.lang.UnsatisfiedLinkError: dlopen failed: "/vendor/app/MyQtApp/lib/arm64/libQt5Quick.so" .dynamic section has invalid size: 0x270, expected to match PT_DYNAMIC filesz: 0x280

**Comment by romainthomas** [comment]
Could you provide the version of LIEF used: `python -c "import lief;print(lief.__version__)"`

**Comment by Linvail** [comment]
$ python -c "import lief;print(lief.__version__)"
C:\Python27_32Bit\lib\site-packages\lief\__init__.py:4: FutureWarning: pybind11-bound class '_pylief.ELF.Section' is using an old-style placement-new '__init__' which has been deprecated. See the upgrade guide in pybind11's docs. This message is only visible when compiled in debug mode.
  import _pylief
**0.9.0-de064eb**

Thank you.

**Comment by romainthomas** [comment]
Sorry I can't reproduce the bug: 

```python
import lief
print(lief.__version__)
app = lief.parse("libQt5Quick.so")
if lief.ELF.DYNAMIC_TAGS.RPATH in app:
    print("yes")
    app -= lief.ELF.DYNAMIC_TAGS.RPATH
    app.write("libQt5Quick_modified.so")

libQt5Quick_modified = lief.parse("./libQt5Quick_modified.so")

pt_dynamic      = libQt5Quick_modified[lief.ELF.SEGMENT_TYPES.DYNAMIC]
dynamic_section = libQt5Quick_modified.get_section(".dynamic")

print(pt_dynamic.file_offset == dynamic_section.offset)
print(pt_dynamic.physical_size == dynamic_section.size)
```
Output:
```0.9.0-c4524ea
yes
True
True
```

I attached the `libQt5Quick.so` I used. Could you attach yours ?

**Comment by Linvail** [comment]
My bad. My build system is using virtualenv, so the version number I posted is wrong because the virtualenv didn't update.
I was actually using 0.9.0-a448c5e.
I will test different versions soon.

**Comment by Linvail** [comment]
I cannot reproduce this issue on the commits later than de064eb.
