### ISSUE TITLE
Memory leaks when using abi::__cxa_demangle

### ISSUE THREAD

**Issue by igasparis** [lief-project/LIEF#221]
Inside LIEF::ELF::Symbols::demangled_name and LIEF::MachO::demangled_name. 
The caller is responsible for deallocating the memory that is returned by abi::__cxa_demangle.

A simple solution could be something like this:
```
  char* demangle_name = abi::__cxa_demangle(name.c_str(), 0, 0, &status);
  
  if (status == 0) {
    std::string realname(demangle_name);
    free(demangle_name);
    return realname;
  }
```

**Comment by romainthomas** [comment]
Thanks @igasparis
