### ISSUE TITLE
Overriding pybind11 is not possible without patching the CMake scripts

### ISSUE THREAD

**Issue by sztomi** [lief-project/LIEF#223]
I'm creating a conan package for LIEF. To do this, I need to disable the builtin dependency management and use conan packages instead. LIEFDependencies.cmake allows skipping itself if `__add_lief_dependencies` is defined. But pybind11 is not added in that file, instead it is added in api/python/CMakeLists.txt unconditionally.

**Comment by romainthomas** [comment]
> I need to disable the builtin dependency management and use conan packages instead
I welcome a PR to tweak the dependencies
