### ISSUE TITLE
Git is required even when __add_lief_git is set

### ISSUE THREAD

**Issue by sztomi** [lief-project/LIEF#224]
Related to https://github.com/lief-project/LIEF/issues/223

I need to set the version/tag from the conan package.

LIEFGit.cmake can be skipped if `__add_lief_git` is defined, but git is required in the main CMakeLists.txt unconditionally. Instead it should be required only in LIEFGit.cmake.

**Comment by romainthomas** [comment]
It should be ok thanks to these lines: 
https://github.com/lief-project/LIEF/blob/084fc4544f1eca6cb9b1b12b9942df9ff480609b/CMakeLists.txt#L16-L26
