### ISSUE TITLE
How to compute resource data entropy in a fast way?

### ISSUE THREAD

**Issue by Blade94** [lief-project/LIEF#227]
Hello! I need to compute the entropy of all resource data of PE but there's no native function to do so. It is present only for the entropy section. Can you point me out where is defined the algorithm for the computation in the source code? I need to apply that exact algorithm on all resources of the PE.

Thanks in advance for the answer.

**Comment by romainthomas** [comment]
Hello.
The implementation is located in the abstract of LIEF: 
https://github.com/lief-project/LIEF/blob/8620b08f95b02356773dcadd99e8f99fefb57766/src/Abstract/Section.cpp#L184-L199

To compute the entropy of resources, you should implement it in this class: 
https://github.com/lief-project/LIEF/blob/8620b08f95b02356773dcadd99e8f99fefb57766/include/LIEF/PE/ResourceData.hpp#L32
