### ISSUE TITLE
Several Binary methods missing but used in pe_reader script

### ISSUE THREAD

**Issue by mgoffin** [lief-project/LIEF#230]
I was using the `pe_reader.py` example file and came across this error:

```python
------------------------------------------------------------
Exception in print_ctor: '_pylief.PE.Binary' object has no attribute 'ctor_functions'
  File "pe_reader.py", line 30, in __call__
    return self.func(*args, **kwargs)
  File "pe_reader.py", line 442, in print_ctor
    print("Functions: ({:d})".format(len(binary.ctor_functions)))
------------------------------------------------------------
```

I took a look at a `Binary` object in Python and noticed there are several other methods used in that script that are also missing:

```python
>>> b.functions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_pylief.Binary' object has no attribute 'functions'
>>> b.exception_functions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_pylief.Binary' object has no attribute 'exception_functions'
>>>
```

Were these methods removed, or is there a different way they should be accessed now?

**Comment by romainthomas** [comment]
It's because you don't have an updated version of LIEF (only available with 'master' version)

**Comment by mgoffin** [comment]
I am using the latest commit per the `README`:

```
pip install https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.9.0.dev.zip
```

By the looks of it that should have the latest commit as of 8 minutes ago, but it still seems to be failing. Is there some other way I need to be acquiring the latest commit to install it?
