### ISSUE TITLE
eggs for FreeBSD or any other way to create a binary wheel?

### ISSUE THREAD

**Issue by sztomi** [lief-project/LIEF#236]
I'm trying to run `pip wheel lief` on Windows, Linux, macOS, FreeBSD. The first three succeeds, but the last one fails, because setup.py tries to fetch a non-existent .egg package from github. Is there a way for me to create a binary wheel?

**Comment by romainthomas** [comment]
Hi, 
Yes you can compile LIEF for FreeBSD. You can find the documentation here: https://lief-project.github.io/doc/latest/compilation.html
