### ISSUE TITLE
License link on website appears to be missing

### ISSUE THREAD

**Issue by psifertex** [lief-project/LIEF#238]
See subject. Not a huge deal, I assume it should either be pointing to https://github.com/lief-project/LIEF/blob/master/LICENSE or https://www.apache.org/licenses/LICENSE-2.0

**Comment by psifertex** [comment]
Thanks! I should have clarified that I was referring to https://lief.quarkslab.com/ which still has a broken link. Appreciate the addition here as well though, never hurts.

**Comment by romainthomas** [comment]
Done as well!
