### ISSUE TITLE
Symbols disappear after writing ELF

### ISSUE THREAD

**Issue by sztomi** [lief-project/LIEF#239]
I'm most likely holding this wrong, so excuse my ignorance. I'm trying to replace `patchelf` with a python script that uses LIEF. However, I noticed that in a specific environment a huge percentage of the symbols go missing from the file after any modification. This is one way to trigger it:

```
vagrant@vagrant:~/openssl-1.0.2p$ nm -DC libcrypto.so | wc -l
4124
vagrant@vagrant:~/openssl-1.0.2p$ ipython
Python 3.6.4 (default, Nov 26 2018, 16:32:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import lief

In [2]: from lief.ELF import DynamicEntryRunPath

In [3]: elf = lief.parse("libcrypto.so")

In [4]: rpath = DynamicEntryRunPath("$ORIGIN/../lib:$ORIGIN/lib")

In [5]: elf.add(rpath)
Out[5]: <_pylief.ELF.DynamicEntryRunPath at 0x7ff7641685e0>

In [6]: elf.write("libcrypto.so")

In [7]: quit()
vagrant@vagrant:~/openssl-1.0.2p$ nm -DC libcrypto.so | wc -l
103
```

The environment is a stock Vagrant box created via `vagrant init bento/ubuntu-16.04`. I'm not able to reproduce this in Linux Mint 19 (which is Ubuntu 18.10-based if I'm not mistaken). I originally observed this in our CI build which runs a 16.04-based Docker image.

Headers: 

```
vagrant@vagrant:~/openssl-1.0.2p$ readelf -h libcrypto.so
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x65300
  Start of program headers:          64 (bytes into file)
  Start of section headers:          2535424 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         7
  Size of section headers:           64 (bytes)
  Number of section headers:         29
  Section header string table index: 28
```

In fact, I just realized, running the following one-liner on 16.04 reproduces the problem:

```
$ python -c 'import lief; lief.parse("libcrypto.so").write("libcrypto.so")'
```

But not on my Linux Mint system. I've attached the file in question. 

[libcrypto.so.zip](https://github.com/lief-project/LIEF/files/2617094/libcrypto.so.zip)

**Comment by romainthomas** [comment]
Hello @sztomi 
Actually ``nm``, ``readelf`` and more globaly ``binfmt`` rely on **section** to parse **symbols**. It's not reliable and I checked with lief that we keep the same number of symbols before and after:

```python
import lief
crypto_1 = lief.parse("libcrypto.so")
print(len(crypto_1.symbols)) # output 138
crypto_1.write(libcrypto-lief.so")

crypto_lief = lief.parse("libcrypto-lief.so")
print(len(crypto_lief.symbols)) # output 138
```
Could you check you have a similar output ?

By the way the file you attached is a simlink :)

**Comment by sztomi** [comment]
Oh sorry about the symlink, I thought it will do the right thing :sweat_smile: 

> Actually nm, readelf and more globaly binfmt rely on section to parse symbols. It's not reliable

Oh, good to know. However, the reason I looked with nm in the first place was because I was getting linker errors if I postprocessed my libs with lief.

```
 -lssl -lcrypto -lz && :
CMakeFiles/test.dir/test.c.o: In function `main':
../../test.c:(.text+0x2d): undefined reference to `MD5'
../../test.c:(.text+0x18e): undefined reference to `SSLeay_version'
<my full path>/libssl.so: undefined reference to `EVP_PKEY_copy_parameters'
<my full path>/libssl.so: undefined reference to `sk_shift'
...
```

`MD5` and `SSLeay_version` should come from libssl, `EVP_PKEY_copy_parameters` and one million others from libcrypto. `nm` does see those:

```
$ nm -DC libcrypto.so.1.0.0 | grep EVP_PKEY_copy_parameters
000000000011e6a0 T EVP_PKEY_copy_parameters
$ python -c 'import lief; lief.parse("libcrypto.so.1.0.0").write("libcrypto.so.1.0.0")'
$ nm -DC libcrypto.so.1.0.0 | grep EVP_PKEY_copy_parameters
$ echo $?
1
```

I retried on my Linux Mint installation again, and it seems this behavior does reproduce there as well, but I'm not getting a linker error. I don't yet know why, I'm assuming it tries to link to something else.

For the test (I added a missing quote but otherwise copied your script exactly):

```
$ python test.py
6610
6610
$ nm -DC libcrypto-lief.so | wc -l
103
$ nm -DC libcrypto.so | wc -l
4124
```



[libcrypto.zip](https://github.com/lief-project/LIEF/files/2619039/libcrypto.zip)

**Comment by sztomi** [comment]
I tried this library: https://github.com/arthaud/python3-pwntools/

It seems to do what I want, although with a much less pleasant API (and I've no idea yet how to add a new entry if it doesn't already exist):

```
In [18]: e = ELF("files/libcrypto.so")

In [19]: dt_soname = e.dynamic_by_tag("DT_SONAME")

In [20]: dt_strtab = e.dynamic_by_tag("DT_STRTAB")

In [21]: e.write(dt_strtab.entry.d_ptr + dt_soname.entry.d_ptr, "henlo.so\0".encode())

In [22]: e.dynamic_by_tag("DT_SONAME").soname
Out[22]: 'henlo.so'

In [24]: e.save("mylibcrypto.so")

In [25]: quit

~/work/pecself took 11m 37s 
[I] ➜ patchelf --print-soname mylibcrypto.so
henlo.so

~/work/pecself 
[I] ➜ nm -DC mylibcrypto.so | wc -l
4124

~/work/pecself 
[I] ➜ nm -DC files/libcrypto.so | wc -l
4124

~/work/pecself 
[I] ➜ diff <(xxd files/libcrypto.so) <(xxd mylibcrypto.so)
13097,13098c13097,13098
< 00033280: 5f5f 6273 735f 7374 6172 7400 6c69 6263  __bss_start.libc
< 00033290: 7279 7074 6f2e 736f 2e31 2e30 2e30 0047  rypto.so.1.0.0.G
---
> 00033280: 5f5f 6273 735f 7374 6172 7400 6865 6e6c  __bss_start.henl
> 00033290: 6f2e 736f 002e 736f 2e31 2e30 2e30 0047  o.so..so.1.0.0.G
```

Is this within the scope of LIEF?

**Comment by romainthomas** [comment]
I investigated the problem and it seems that the linker doesn't handle the hash table built by LIEF. I think pwntools can't handle the case where the entry doesn't exists but I didn't try.
Also could you share the version of the linker that trigger the problem ? (``ld --version``)

**Comment by romainthomas** [comment]
Ok there is definitely a bug in LIEF to get number of symbols based on the hash. As a temporarily fix, you can specify the argument
[lief.ELF.DYNSYM_COUNT_METHODS.SECTION](https://lief-project.github.io/doc/latest/api/python/elf.html#lief.ELF.DYNSYM_COUNT_METHODS.SECTION) in the ``parse`` function

```python
libcrypto = lief.ELF.parse('./libcrypto.so.1.0.0', lief.ELF.DYNSYM_COUNT_METHODS.SECTION)
print(len(app.dynamic_symbols)) # 4125
```
Let me know if it fix you problem.

**Comment by sztomi** [comment]
This doesn't seem to work:

```
$ python -c 'import lief; lief.parse("libcrypto.so.1.0.0", lief.ELF.DYNSYM_COUNT_METHODS.SECTION).write("libcrypto2.so")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: parse(): incompatible function arguments. The following argument types are supported:
    1. (filepath: str) -> _pylief.Binary
    2. (raw: List[int], name: str='') -> _pylief.Binary
    3. (io: object, name: str='') -> _pylief.Binary
```

**Comment by romainthomas** [comment]
You need to use **lief.ELF.parse** not **lief.parse**

**Comment by sztomi** [comment]
oh sorry, I totally missed that. That seems to work, at least the number of symbols remain the same after writing.
