### ISSUE TITLE
Macho add section raise error

### ISSUE THREAD

**Issue by xnxin** [lief-project/LIEF#240]
This code run with lief version `0.9.0-a448c5e`, when i run this script, It raise an error:
`AttributeError: '_pylief.MachO.Binary' object has no attribute 'get_segment'`
```python
import lief
import tempfile

original = lief.parse('/Users/developer/Desktop/change_file_section')
_, output = tempfile.mkstemp(prefix="lief_ssh_")

# Add 3 section into __TEXT
__text = original.get_segment("__TEXT")
for i in range(3):
    section = lief.MachO.Section("__text_{:d}".format(i))
    section.content = [0xC3] * 0x100
    original.add_section(__text, section)

original.write(output)
```

**Comment by romainthomas** [comment]
Hello, 
I think you have an error in your LIEF install or in your setup:

![lief](https://user-images.githubusercontent.com/7450402/49136929-632e1180-f2eb-11e8-991c-25ed0c2ab4d8.png)
