### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by gauravb3007** [lief-project/LIEF#244]
Hello Author,

While extracting Imports & Exports features from EXE files, it is taking time to extract information as it is text based. **Almost 10-15 secs or more** for files that have huge imports/exports.

Any improvement in this area can be helpful.

**Comment by romainthomas** [comment]
Hello,
At the beginning of the project, LIEF was not designed with performance in mind but we try to fix it.
Should be possible to share the sample ?

**Comment by romainthomas** [comment]
What's the name of the DLL ? Is it a part of Windows ?

**Comment by gauravb3007** [comment]
No It is not part of windows but a Maya 3D 2018 dll

**Comment by gauravb3007** [comment]
Does the Python extraction work better or C++?? @romainthomas

**Comment by romainthomas** [comment]
Python are just binding on C++ code so that you will probably have the same performance.

**Comment by gauravb3007** [comment]
Can we apply multithreading on imported and exported functions to decrease the time required to import it?

The more the data in imports and exports, the higher the time it is taking to extract text.

Any workaround on this? @romainthomas

**Comment by romainthomas** [comment]
I don't think it would be a good idea add multi-threading complexity in LIEF. If you really need multi-threading, you can always fork the project and add this feature
