### ISSUE TITLE
to_string function of machine type doesn't include "ARM64"

### ISSUE THREAD

**Issue by Folk19** [lief-project/LIEF#249]
Hi,
Thank you for this project.
I found out that to_string function of machine type doesn't include "ARM64."

to_string:
https://github.com/lief-project/LIEF/blob/dc8742376167974c7e24a4ef0b84e1d05754f455/src/PE/EnumToString.cpp#L56-L64

enum:
https://github.com/lief-project/LIEF/blob/dc8742376167974c7e24a4ef0b84e1d05754f455/include/LIEF/PE/enums.inc#L7-L15

also python api:
https://github.com/lief-project/LIEF/blob/3b892188a177f6d47c5c70606de92f482bbeb7c2/api/python/PE/pyEnums.cpp#L33-L40

Thank you.

Best,
Shawn

**Comment by romainthomas** [comment]
Fixed with  c1758ba
