### ISSUE TITLE
Unsupported binary

### ISSUE THREAD

**Issue by pbrunet** [lief-project/LIEF#25]
With the triton project, we used to have our own Elf parser.
As LIEF looks to be a good replacement for any file parsing, I tried to use lief instead of our own Parser but I had an issue with : 
https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/ctf-writeups/hackover-ctf-2015-r150/rvs

Lief report this binary as corrupted (symboles not found) while we were able to parse and get symboles with out own parser. I have no idea of this issue as I don't know the Elf format but may be you can help us on it?

**Comment by romainthomas** [comment]
I located the problem, the fix should be committed in a couple of days.
You can follow the branch: https://github.com/lief-project/LIEF/tree/issue/25

**Comment by romainthomas** [comment]
BTW: In Triton you use a ``ẁhile(true)`` loops and you break on some arbitrary condition (which couldn't be exhaustive) 
https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/format/elf/elf.cpp#L227

Actually there is solutions to know exactly the number of dynamic symbols:
* based on symbol version
* based on hash table

I will implemented this kind of counting in LIEF

**Comment by romainthomas** [comment]
@pbrunet not finished yet but this commit: b44abe658ffc75c8b99f032393b612ede2110510 enables to read the [rvs](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/ctf-writeups/hackover-ctf-2015-r150/rvs) binary.
