### ISSUE TITLE
Adding section cause a Segmentation fault

### ISSUE THREAD

**Issue by forker11234** [lief-project/LIEF#252]
I try that piece of code:
```python
# Describe the new section to add to the file
section = lief.ELF.Section()
section.name = 'newsection'
section.type = lief.ELF.SECTION_TYPES.PROGBITS
section.alignment = 4
section.flags = lief.ELF.SECTION_FLAGS.EXECINSTR
section.content = 'a' * 100

ofile = lief.parse(ELF)
ofile.add(section)
ofile.write(patched_file)
```

This makes the elf crash in _dl_relocate_object

**Comment by romainthomas** [comment]
For which architecture ?

**Comment by romainthomas** [comment]
Just checked right know with this code:

```c
#include <stdio.h>

int main(int argc, char** argv) {
  printf("Hello World\n");
  return 0;
}
```
```console
$ gcc -m32 hello.c -o hello
```
```python
import lief

section = lief.ELF.Section()
section.name = 'newsection'
section.type = lief.ELF.SECTION_TYPES.PROGBITS
section.alignment = 4
section.flags = lief.ELF.SECTION_FLAGS.EXECINSTR
section.content = [0x41] * 100

app = lief.parse("/tmp/hello")
app.add(section)
app.write("/tmp/hello2")
```

And `/tmp/hello2` works fine

**Comment by forker11234** [comment]
I tried the same thing you did (on a 32 bit machine), I received the following error:
Inconsistency detected by ld.so: rtld.c: 1191: dl_main: Assertion `GL(dl_rtld_map).l_libname' failed!

**Comment by romainthomas** [comment]
No I think the error comes from an old version of the linux loader that contains a bug. Could you send the version of the loader ? (``ld --version`` should be fine)

**Comment by forker11234** [comment]
GNU ld (GNU Binutils for Ubuntu) 2.26.1
Im using Ubuntu 16.04.5 LTS kernel version 4.15.0-43-generic

**Comment by romainthomas** [comment]
Could you try on Ubuntu 18.10 which have a recent loader ?

**Comment by forker11234** [comment]
Yes it is working.
Thanks.
