### ISSUE TITLE
segmentation fault when parsing incomplete PE resource section

### ISSUE THREAD

**Issue by williballenthin** [lief-project/LIEF#253]
When using LIEF via Python, the process segfaults when fetching resource data from a PE file with a truncated resource section:

![image](https://user-images.githubusercontent.com/156560/50648941-c25df200-0f39-11e9-8091-c20a56e0483f.png)

The test file is attached here: ![k32-truncated](https://user-images.githubusercontent.com/156560/50650940-17e8cd80-0f3f-11e9-81b5-2bf8a22b34b5.gif)

I've encountered this issue against real world (corrupt) files; however, I'm not sure that I can share them. Therefore, I reproduced the issue by taking kernel32.dll and truncating it from the middle of the StringFileInfo structure:

![image](https://user-images.githubusercontent.com/156560/50651069-79a93780-0f3f-11e9-9746-44933ad1bcef.png)

I haven't had a chance to build the bindings with symbols so I can more easily debug the exception. 

My suspicion is that the bug is around here:

https://github.com/lief-project/LIEF/blob/882bf35197bc6cff5b66d45e629037eedb68aab7/src/PE/ResourcesManager.cpp#L399

There are indexed accesses into the children nodes without validating that they exist (I think). The out of bounds access results in an assertion error within the iterator implementation:

![image](https://user-images.githubusercontent.com/156560/50651400-72365e00-0f40-11e9-9aa5-81c797c73a93.png)

If this is, in fact, the bug, then there are a number of other places to update in the same file. I can maybe attempt a fix in the order of a week or two, or welcome assistance from you or others.

**Comment by romainthomas** [comment]
Indeed I didn't cover this case. I'll check what is wrong in LIEF with the sample you provided.

**Comment by romainthomas** [comment]
Feel free to re-open the issue if the fix doesn't work with your private sample

**Comment by williballenthin** [comment]
this fixes the issue against our private samples, too. thank you!
