### ISSUE TITLE
delete section in python binding

### ISSUE THREAD

**Issue by havu0** [lief-project/LIEF#255]
Hello, I'm making simple PE packer using LIEF Project.
I know that C++ binding has `delete_section` function, but python binding does not have `delete_section` function.
is there another way to delete PE's section in python binding?

**Comment by romainthomas** [comment]
Yes it has: https://lief-project.github.io/doc/latest/api/python/pe.html#lief.PE.Binary.remove_section

**Comment by havu0** [comment]
Oops, Sorry...

**Comment by romainthomas** [comment]
Upgrade your LIEF version with 
``pip install https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.9.0.dev.zip``

**Comment by havu0** [comment]
it works! thank you very much :>
