### ISSUE TITLE
PE exports with no RVA

### ISSUE THREAD

**Issue by mwilliams31** [lief-project/LIEF#259]
I've encountered several PEs (some packed with VMProtect) that contain an export that has no corresponding function address. These samples also contain an `AddressOfNames` entry that points to a large blob of binary data that precedes the first ASCII export name. Example output for MD5 `b5e7832464bff54896b1d42a76760dbc` is shown below. The sample is available on VT but let me know if I need to send it directly.

![export_issue](https://user-images.githubusercontent.com/13837569/51125898-c1f21080-17ef-11e9-8c0d-d3bf0f9df47c.png)

The PE-bear output below further illustrates the export directory anomaly:

![pe-bear](https://user-images.githubusercontent.com/13837569/51125901-c6b6c480-17ef-11e9-8604-10d5a04017b0.png)

One approach would be to ignore export entries that contain a `NULL` function address.  This approach is used in the [`pefile` module](https://github.com/erocarrera/pefile/blob/master/pefile.py#L3631). 

MD5 `ae9529727144d83fe2a5a75dcf2bcb3d` is a similar sample.

**Comment by romainthomas** [comment]
Yes could you attach the file (or share by email) ?
