### ISSUE TITLE
CentOS support

### ISSUE THREAD

**Issue by InTheorium** [lief-project/LIEF#26]
Does this library support CentOS? I've gotten the prebuilt packages to work without issue on OSX and Ubuntu but am having trouble getting them to work on CentOS 6 and 7. I get this error when trying to import from python:

`ImportError: /lib64/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found (required by ./lief.so)`

I also had issues building from source on centos as it ships with gcc 4.8 and there are build dependencies for LIEF that rely on gcc 4.9. After compiling and building gcc 4.9.2 I was able to build LIEF successfully from source but I still get the issue noted above. Running ldd on lief.so I get the same error.

Any insights? 

Thanks!

~Brian

**Comment by romainthomas** [comment]
Hi Brian,

Well actually I didn't tested on CentOS. Thanks for the feedback.

Does the``libstdc++`` version provided in CentOS support C++11 ?
From the GCC [page](https://gcc.gnu.org/gcc-4.8/cxx0x_status.html) it seems that all C++11 features are implemented in the version **4.8.1**. So you can check it's ok with this version. 

It is a good idea to provide pre-built packages for CentOS but it won't be priority for now. (You can open a pull request). I will focus the next version on feature a API design.

**Comment by mutedmouse** [comment]
Just an additional caveat to InTheorium and romainthomas posted.

Centos glib support stops right at 3.4.19 by default. And while this framework s a game changer, you will find a dramatic loss of userbase without centos and rhel support.  

All it takes is a rebuild to 3.4.19 compatible glib.  FYI python 2.7, 3.5 and 3.6 are unusable on Centos as well.

Final note...not planning for compatibility is a fatal flaw in any framework, and you have removed functionality from a full third of the Unix market in doing so.

3 month old ticket...please engage this issue.

**Comment by mutedmouse** [comment]
To enable CentOS 7.x compatibility with 0.7.0 Release:
<resolution to issue #26 in short term

<install ius centos 7 community repo
yum install -y https://centos7.iuscommunity.org/ius-release.rpm

<install git, cmake3, python35u, python35u-pip, python35u-devel, devtoolset-4
yum install -y git cmake3 python35u python35u-pip python35u-devel devtoolset-4

<clone lief github <https://github.com/lief-project/LIEF.git>
git clone --recursive https://github.com/lief-project/LIEF.git

<cd into LIEF
cd LIEF

<enable devtoolset-4
scl enable devtoolset-4 bash

<symlink devtoolset-4 into /usr/bin/lib
mv /usr/lib/gcc /usr/lib/gcc-bkup && cd /usr/lib && ln -s /opt/rh/devtoolset-4/root/usr/lib/gcc

<cmake3 && make and make install LIEF binaries
cmake3 . && make -j && make install

<wget the pip installation
wget https://github.com/lief-project/LIEF/releases/download/0.7.0/linux_lief-0.7.0_py3.5.tar.gz

<install pip python files <not really necessary but nice to have the pip package in place>
pip3.5 install linux_lief-0.7.0_py3.5.tar.gz

<rebuild python3.5 install
cd LIEF/api/python/ && python3.5 setup.py build && python3.5 setup.py install

**Comment by romainthomas** [comment]
@mutedmouse  I setup a Dockerfile for Centos thanks to your work.

**Comment by romainthomas** [comment]
Resolved with https://github.com/lief-project/Dockerlief/blob/master/dockerlief/dockerfiles/centos.docker

**Comment by ppanero** [comment]
@romainthomas Trying to build if for python 2.7 I get the following:
```
[root@misp-dev build]# scl enable devtoolset-4 'bash -c "cmake3     \
>     -DLIEF_PYTHON_API=on                         \
>     -DLIEF_DOC=off                               \
>     -DCMAKE_INSTALL_PREFIX=${LIEF_INSTALL}       \
>     -DCMAKE_BUILD_TYPE=Release                   \
> .."'
-- Could NOT find cppcheck (missing:  CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG) 
-- LIEF 0.8.3
-- ccache: ON
-- Enable JSON support
-- Could NOT find cppcheck (missing:  CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG) 
-- Configuration Types: 
-- Build Types: Release
CMake Warning (dev) at api/python/CMakeLists.txt:10 (find_package):
  Ignoring EXACT since no version is requested.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Python version: 
-- Python lib:     python2.7
-- Python include: /usr/include/python2.7
-- Python interpreter: /usr/bin/python
CMake Error at api/python/CMakeLists.txt:98 (set_target_properties):
  set_target_properties called with incorrect number of arguments.


-- OS: Linux-3.10.0-693.2.2.el7.x86_64
-- Configuring incomplete, errors occurred!
See also "/var/www/MISP/app/files/scripts/lief/LIEF/CMakeFiles/CMakeOutput.log".
See also "/var/www/MISP/app/files/scripts/lief/LIEF/CMakeFiles/CMakeError.log".
```

Being the error file
```
Performing C++ SOURCE FILE Test HAS_WARN_EVERY failed with the following output:
Change Dir: /var/www/MISP/app/files/scripts/lief/LIEF/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_dc5c1/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_dc5c1.dir/build.make CMakeFiles/cmTC_dc5c1.dir/build
gmake[1]: Entering directory `/var/www/MISP/app/files/scripts/lief/LIEF/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_dc5c1.dir/src.cxx.o
/opt/rh/devtoolset-4/root/usr/bin/c++     -DHAS_WARN_EVERY   -Weverything -o CMakeFiles/cmTC_dc5c1.dir/src.cxx.o -c /var/www/MISP/app/files/scripts/lief/LIEF/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option '-Weverything'
gmake[1]: *** [CMakeFiles/cmTC_dc5c1.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory `/var/www/MISP/app/files/scripts/lief/LIEF/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_dc5c1/fast] Error 2

Source file was:
int main() { return 0; }

```
any pointers? docker file did not work either

**Comment by romainthomas** [comment]
Could you try to add the ``-DPYTHON_VERSION=2.7`` to the ``cmake`` command ?

**Comment by ppanero** [comment]
@romainthomas thanks. That plus some other twicks and it worked. I will comment here with some packages/instructions in a bit. Thanks a lot!

**Comment by romainthomas** [comment]
Thanks I'll include in the documentation

**Comment by ppanero** [comment]
Conclusion need for:
-python-devel
Run:
scl enable devtoolset-4 'bash -c "cmake3     \
    -DLIEF_PYTHON_API=on                         \
    -DLIEF_DOC=off                               \
    -DCMAKE_INSTALL_PREFIX=${LIEF_INSTALL}       \
    -DCMAKE_BUILD_TYPE=Release                   \
    -DPYTHON_VERSION=2.7						 \
.."'
