### ISSUE TITLE
PE imports: Invalid ordinals and IAT/ILT

### ISSUE THREAD

**Issue by mwilliams31** [lief-project/LIEF#260]
I've encountered several PEs that produce a significant amount of invalid imports. One example is MD5 `f22a27f746eec4919ee0ca14547b17d8`. It's available on VT but please let me know if you need me to provide it directly. LIEF produces the following:

![imports_issue](https://user-images.githubusercontent.com/13837569/51135023-12289d00-1807-11e9-9001-a8f50db528d5.png)

The ILT contains valid data; however, the IAT's first entry (first four actually) is `0xFFFFFFFF`. Based on the [specification](https://docs.microsoft.com/en-us/windows/desktop/debug/pe-format#the-idata-section), if the ordinal flag is set, "bits 30-15 or 62-15 must be 0". One solution is adding a sanity check for ordinal imports. The `pefile` module implements this check [here](https://github.com/erocarrera/pefile/blob/master/pefile.py#L4216). Another possible solution is giving precedence to the ILT over the IAT even though, in theory, they should match until binding. 

ILT precedence would eliminate issues I'm seeing in other samples that produce invalid imports, such as `c03b5985f2504939da9874246a439e25`. This sample's IAT is not terminated before it gets to the ILT. In this case, LIEF produces the following output:

![imports_issue_c03b](https://user-images.githubusercontent.com/13837569/51135166-6a5f9f00-1807-11e9-904e-c1fe7250a284.png)

For reference, the `pefile` module [gives precedence to the ILT](https://github.com/erocarrera/pefile/blob/master/pefile.py#L4026).

**Comment by romainthomas** [comment]
Same as #259, Could you attach the file ?

**Comment by romainthomas** [comment]
@mwilliams31 Let me know if you agree with this fix: https://github.com/lief-project/LIEF/commit/fecd5bc465f681d6cae6b89470c04b0b10916794

```python
import lief
sample = "./f22a27f746eec4919ee0ca14547b17d8"

app = lief.parse(sample)
for dll in app.imports:
    for entry in dll.entries:
        if entry.is_ordinal:
            print(dll.name + "!" + str(entry.ordinal))
        else:
            print(dll.name + "!" + entry.name)
```

Output: 

```console
kernel32.dll!LoadLibraryA
kernel32.dll!GetProcAddress
kernel32.dll!GetModuleHandleA
kernel32.dll!VirtualAlloc
```

-----

> Another possible solution is giving precedence to the ILT over the IAT even though, in theory, they should match until binding.

It's the case:

https://github.com/lief-project/LIEF/blob/2778882bc28882f4375a39d82bbf904cd2b71f5c/src/PE/Parser.tcc#L332

**Comment by mwilliams31** [comment]
@romainthomas Looks good to me! Thanks for the quick response!
