### ISSUE TITLE
Valid import/export names

### ISSUE THREAD

**Issue by mwilliams31** [lief-project/LIEF#261]
Related to issues #259 and #260, add a check for valid import and export functions names. For reference, the `pefile` module performs this check [here](https://github.com/erocarrera/pefile/blob/master/pefile.py#L1463).

**Comment by mwilliams31** [comment]
A check for valid import names was added (https://github.com/lief-project/LIEF/commit/fecd5bc465f681d6cae6b89470c04b0b10916794) to close #260. Could you apply the same logic to export names to close out this issue? I have (packed) samples that are producing large garbage export names and can provide them offline if necessary.

**Comment by romainthomas** [comment]
It should be ok now.
