### ISSUE TITLE
The SHT_NOBITS section was not processed correctly.

### ISSUE THREAD

**Issue by daviyang35** [lief-project/LIEF#263]
File location: LIEF/src/ELF/Section.cpp 
Function: std::vector<uint8_t> Section::content(void) const
Problem:
When the processed file contains the .bss section (SHT_NOBITS).
It is wrong to get the content contained in the section object by the section() method.

```c
  auto elf = LIEF::ELF::Parser::parse("xxx.so");
  for (const auto &section : elf.get()->sections()) {
      uint64_t va = section.virtual_address();
      
      auto content = section.content();
      void* ptr = content.data();
      uint64_t size = content.size();
      // use there
      memcpy(DST,ptr,size) ;
  }
```

The correct way I think is reasonable is that the returned content is a buffer that is all 0.

Currently elf section::content does not process the SHT_NOBITS section, copying the data directly from the file offset. Caused an error.

**Comment by romainthomas** [comment]
Should be fixed
