### ISSUE TITLE
API inconsistincies

### ISSUE THREAD

**Issue by KOLANICH** [lief-project/LIEF#264]
I need to deal with PE and ELF and MachO uniformly. Unfortunately the API is not uniform enough. This makes me keeping format-specific code in my lib which I prefer to avoid.

More presicely, my use case is patching a data table in a binary, and these binaries are built to all the platforms from the same source code, so the structures and approaches for patching are the same.

* To convert a virtual address into offset in a file functions with [different names are used](https://gitlab.com/KOLANICH/FrozenTable.py/blob/91332a86/FrozenTable/binPatchTools.py#L182).
    * For  `PE` format `va_to_offset` is used,
    * for ELF `virtual_address_to_offset` is used.
    It is proposed to choose the single name and use it.
* In order to resolve an offset back into a virtual address and make some other manipulations I need a function determining the relocatable chunk of binary containing the specific offset
    * for `PE`  `section_from_offset` function is used,  and it returns the object which `offset` property is needed
    * for `ELF` `segment_from_offset` is used, and it returns the object which `file_offset` property is needed.
    It is proposed to select single names and use them everywhere.
* items of `PE.abstract.exported_functions` have RVA in their `value` property, other formats have raw virtual addresses in this property.
It is proposed to store raw virtual address there for PE format too.

* To get image base
    * for a `PE` file I have to use `concrete.optional_header.imagebase`
    * But for `ELF` I have to use `imagebase`.
    It is proposed to make `imagebase` an alias to `concrete.optional_header.imagebase` for `PE`
* Sometimes one needs to manipulate an RVA for some  even in the formats not using this term. Though it is possible to compute an rva using image base. So it is proposed for each function operating on a raw address add a one operating on RVA  for each format.
* `concrete.get_symbol` does not work for retrieving the symbol of the hardcoded table (I have not tested on anything else) in PE, so I have to use `abstract.exported_functions` and crawl them myself.

**Comment by KOLANICH** [comment]
@romainthomas has it been fixed?

**Comment by romainthomas** [comment]
Won't fix. Especially this kind of issue without context and without details will be closed

**Comment by KOLANICH** [comment]
@romainthomas has it been fixed?
