### ISSUE TITLE
Drop python 2

### ISSUE THREAD

**Issue by KOLANICH** [lief-project/LIEF#269]
It is 2019 and in 2020 python 2 is going to be dropped by some major projects. Other major projects have already dropped python 2.

Sometimes it feels like someone will still use python 2 untill the the Second Coming. But it is definitely not the reason not to drop its support. Python 3 is available even for ancient platforms like Windows XP OS and Pentium III CPU. All the needed code is migrated with 2to3 (IDK if native extensions can be easily recompiled) with minimal manual fixes, I personally have done that (for projects by other authors) lot of times. 

So IMHO there is no real reason use python 2 in 2019 (even in 2013 there was no, I have been using python 3 exclusively since then and felt no trouble).

**Comment by romainthomas** [comment]
LIEF is available for Python 2.7, 3.5, 3.6 and 3.7.

**Comment by romainthomas** [comment]
and the code base doesn't depend on Python version
