### ISSUE TITLE
resources example

### ISSUE THREAD

**Issue by chico-depressive** [lief-project/LIEF#28]
hi, thank you for this lib, there is support for adding and changing resources? can you consider adding some example?

**Comment by romainthomas** [comment]
Hi,
With the current version of LIEF (``0.6.1``) you can more less modify PE resources (only in C++):
* Add a *node*: https://github.com/lief-project/LIEF/blob/master/src/PE/ResourceNode.cpp#L100
* Reconstruction process: https://github.com/lief-project/LIEF/blob/master/src/PE/Builder.cpp#L229
* Resource manager: https://github.com/lief-project/LIEF/blob/master/src/PE/ResourcesManager.cpp

In the version ``0.7.0`` there will be a better API in the *ResourcesManager* to 
* Change icons
* Read/Change manifest
* Add resources (and not simply a node)
...

And it will also be available with the Python API.

**Comment by romainthomas** [comment]
I close this issue as it is planned to be done in the next version
