### ISSUE TITLE
Cannot install lief 0.8.3

### ISSUE THREAD

**Issue by silversurfer147** [lief-project/LIEF#282]
Hi, I would like to install lief in version 0.8.3, but I always get error 
` Url: https://github.com/lief-project/packages/raw/lief-master-latest/lief-0.8.3-py3.7-windows_x64.egg
  HTTP Error 404: Not Found`

Could someone help me, how to solve this problem? The whole error message is here https://pastebin.com/iJcfLHKH
Thank you in advance.

**Comment by williballenthin** [comment]
there is no package for LIEF version 0.8.3 for python 3.7. looks like py3.6 is the max python version for LIEF 0.8.3:  https://github.com/lief-project/LIEF/releases/tag/0.8.3

**Comment by romainthomas** [comment]
Yes LIEF 0.10 will come with Python 3.7. The release is planned for June
