### ISSUE TITLE
PE pdb support?

### ISSUE THREAD

**Issue by VPaulV** [lief-project/LIEF#283]
Hi Guys,

Could you provide an example on how to load a pdb file for a PE binary in order to have access to symbols?
I found that you have CodeViewPDB and it is even possible to set the filename there, but symbols are not parsed anyway. (I guess binary should be reparsed after?) Is it even possible?

Thank you!

**Comment by romainthomas** [comment]
Hi @VPaulV 
LIEF doesn't support the PDB format and it's not in the sort-term feature but feel free to add it if you want.

**Comment by romainthomas** [comment]
LIEF won't support the PDB format. You can nevertheless use LLVM which contains the support for this format
