### ISSUE TITLE
imphash IndexErrors

### ISSUE THREAD

**Issue by mwilliams31** [lief-project/LIEF#284]
I'm receiving `get_imphash()` errors similar to the following for some packed samples:

`IndexError: basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 8)`

I'll send samples for testing.

**Comment by romainthomas** [comment]
Thanks @mwilliams31 I will address this issue next couple of days

**Comment by romainthomas** [comment]
These samples have some imports without the ``.dll`` extension. Do you know if the Windows loader skip them ?
