### ISSUE TITLE
FutureWarning: pybind11-bound class '_pylief.ELF.Section' is using an old-style placement-new '__init__' which has been deprecated.

### ISSUE THREAD

**Issue by williballenthin** [lief-project/LIEF#285]
using a nightly build, I encounter the following warning when importing LIEF in python 3.7:

```
C:\Users\user\env\lib\importlib\_bootstrap.py:219: FutureWarning: pybind11-bound class '_pylief.ELF.Section' is using an old-style placement-new '__init__' which has been deprecated. See the upgrade guide in pybind11's docs. This message is only visible when compiled in debug mode.
  return f(*args, **kwds)
```

**Comment by williballenthin** [comment]
the relevant documentation seems to be here: https://github.com/pybind/pybind11/blob/master/docs/upgrade.rst#new-api-for-defining-custom-constructors-and-pickling-functions

**Comment by williballenthin** [comment]
and i think the warning is applying to this line: https://github.com/lief-project/LIEF/blob/406115c8d097da0b61f00b2bb7b2442322ffc5d1/api/python/ELF/objects/pySection.cpp#L50

**Comment by romainthomas** [comment]
Thanks
