### ISSUE TITLE
modify section content

### ISSUE THREAD

**Issue by wmsuper** [lief-project/LIEF#290]
I need to modify .code section of PE file for develop packer tool.
the length of  code maybe increase so that I have to write code to fix the offset of other sections.
can you add a function like update_content() to process it? or better suggestions？

**Comment by romainthomas** [comment]
```python
import lief
pe = lief.parse(...)
pe.get_section(".code").content = <your content>
pe.write("...")
```

**Comment by wmsuper** [comment]
It don't work，I can't find the code that fix offset of section,I think I should write code to fix it.
Thank you for your answer.
