### ISSUE TITLE
[ELF][Python] PT_DYNAMIC is not updated after add_library

### ISSUE THREAD

**Issue by Velby** [lief-project/LIEF#293]
LIEF version: 0.9.0-a448c5e

python code:

```
print(lief.__version__)

f = 'libmain.so'
libnative = lief.parse(f)
libnative.add_library("libgadget.so") # Injection!
libnative.write(f)

libnative = lief.parse(f)

pt_dynamic      = libnative[lief.ELF.SEGMENT_TYPES.DYNAMIC]
dynamic_section = libnative.get_section(".dynamic")

print(pt_dynamic.physical_size == dynamic_section.size)
```

This returns False and is the cause for my apk not running properly. Runtime throws this error:

`.../lib/arm64/libmain.so" .dynamic section has invalid size: 0x240, expected to match PT_DYNAMIC filesz: 0x1000`

[libsofiles.zip](https://github.com/lief-project/LIEF/files/3143649/libsofiles.zip)

related issue: https://github.com/lief-project/LIEF/issues/220 was solved by updating to latest version, but that didn't seem to work in my case

**Comment by romainthomas** [comment]
Work on nightly build:

```bash
$ pip install [--user] --index-url  https://lief-project.github.io/packages lief
```
