### ISSUE TITLE
Force install the dev version of lief is tricky

### ISSUE THREAD

**Issue by Rafiot** [lief-project/LIEF#294]
**Describe the bug**

I want to install the current nightly version of lief (because I have python 3.7). But the version of the release in the nightly repository is `0.9.0.dev0`, which is assumed as older than 0.9 by pip, so I have to force the version manually.

**To Reproduce**

(in `requirements.txt`, on a machine using python 3.7 by default)
```
-i https://pypi.org/simple                                  
--extra-index-url https://lief-project.github.io/packages/  

lief ; python_version >= '3.5'
<other dependencies>
```

**Expected behavior**

Install the most recent version of lief from one of the two indexes (should be the nightly release).

**Current behavior**

Install the version from pypi, because `lief==0.9.0.dev0` < `lief==0.9`.

**Possible solutions**

1. Rename the nightly `lief==0.10.0.dev0`
2. Put the following content in `requirements.txt`

```
-i https://pypi.org/simple                                  
--extra-index-url https://lief-project.github.io/packages/  

lief==0.9.0.dev0 ; python_version >= '3.5'
<other dependencies>
```

I think the first solution makes more sense, but the 2nd one is a working hotfix until the release of lief 0.10.

**Comment by romainthomas** [comment]
I think the proper way would be to rename nightly package as ``lief.0.10.0.dev0``. It should be done by the end of the week

**Comment by Rafiot** [comment]
Excellent, thank you very much.

**Comment by romainthomas** [comment]
Done: https://lief-project.github.io/packages/lief/
