### ISSUE TITLE
Broken link on the main page under "Code Injection" section

### ISSUE THREAD

**Issue by thejunkjon** [lief-project/LIEF#296]
**Describe the bug**
This is a minor issue but just thought I'd report it.  I noticed there is a broken link on your main page when I click on "More" in the "Code Injection" section.  It tries to link to https://lief.quarkslab.com/doc/tutorials/04_elf_hooking.html

**To Reproduce**
Navigate to main page (https://lief.quarkslab.com/) and then in the "Code Injection" section, click on "More".

**Expected behavior**
Link should be valid (or removed) and the page should load.

**Environment (please complete the following information):**
Browser

**Additional context**

**Comment by romainthomas** [comment]
Thanks, it has been fixed
