### ISSUE TITLE
Android so add dynamic entry and crash on 9.0?

### ISSUE THREAD

**Issue by Youlor** [lief-project/LIEF#297]
**Describe the bug**
Android so, add dynamic entry , crash

**To Reproduce**
1. add dynamic entry
2. replace the so in apk, install and run
3. crash beacuse size in DYNAMIC and size in sections not equal!

**Expected behavior**
run success, don't crash

**Environment (please complete the following information):**
 - System and Version : [e.g. Ubuntu 16.04]
Android 9.0
 - Target format (PE, ELF, Mach-O)
ELF
 - LIEF commit version: ``python -c "import lief;print(lief.__version__)"`` or the one from 
``LIEF/config.h``
0.9.0-a448c5e

**Additional context**
I try to fix this bug, but how to compile in Visual Studio 2017 on Windows10?

**Comment by romainthomas** [comment]
Duplicate: https://github.com/lief-project/LIEF/issues/194
