### ISSUE TITLE
PE imphash does not match YARA, VirusTotal, pefile

### ISSUE THREAD

**Issue by jshlbrd** [lief-project/LIEF#299]
**Describe the bug**
The imphash calculated by lief.PE.get_imphash() does match the imphash calculated by other tools. Here's an example:

```
executable SHA256: ad3722ab9dc9ad41a0e50122423737c241f98cc7374b4ddac999ed6eda4cfe9c
YARA imphash: 06694565e94cd10f48e1e4b90bc04bc2
VirusTotal imphash: 06694565e94cd10f48e1e4b90bc04bc2
pefile imphash: 06694565e94cd10f48e1e4b90bc04bc2
lief imphash: 0ffe645e98030f6b53caa49d22180504
```

**To Reproduce**
Compare the output by lief.PE.get_imphash() to other tools mentioned above.

**Expected behavior**
The imphash output of lief.PE.get_imphash() matches other tools commonly used in the industry.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 18.04
 - Target format: PE
 - LIEF commit version: 0.9.0-a448c5e

**Comment by jshlbrd** [comment]
The following code produces the same imphash as the other tools:
```
import hashlib

import lief

exe = lief.PE.parse('ad3722ab9dc9ad41a0e50122423737c241f98cc7374b4ddac999ed6eda4cfe9c')

imp_list = []
for imp in exe.imports:
    imp = lief.PE.resolve_ordinals(imp)  # Resolve ordinals to function names when they appear
    imp_name = imp.name.lower()  # Convert DLL names to lowercase
    imp_name = imp_name.rsplit('.')[0]  # Remove file extensions from imported module names
    for entry in imp.entries:
        if entry.is_ordinal:
            ordinal = entry.ordinal.lower()  # Convert function names to lowercase
            imp_list.append(f'{imp_name}.{ordinal}')
        else:
            name = entry.name.lower()  # Convert function names to lowercase
            imp_list.append(f'{imp_name}.{name}')

print(hashlib.md5(','.join(imp_list).encode()).hexdigest())
```

**Comment by jshlbrd** [comment]
Looking further into this, it appears that the discrepancy comes from LIEF having a more up-to-date ordinal table mapping than pefile: https://github.com/lief-project/LIEF/tree/master/src/PE/utils/ordinals_lookup_tables

Here is pefile's table for reference: https://github.com/erocarrera/pefile/tree/master/ordlookup

I'm not sure how you resolve this without getting someone from Mandiant involved to provide guidance.

**Comment by romainthomas** [comment]
Hello,  
Sorry for the delay, but yes LIEF tries to resolve some imports by ordinal while computing the ``imphash``.
I don't know how to properly address this issue if we use an up-to-date ordinal table.

**Comment by jshlbrd** [comment]
@romainthomas No problem. Based on some private conversations I've had, I believe the best way to move forward with this is to treat LIEF's imphash calculation as its own implementation of the imphash spec. VirusTotal, YARA, and pefile may be using their own variations of the imphash spec and any changes among them will break backward compatibility. I'd suggest that if users really want the other specs, then they can code them in themselves (YARA's ordinals can be found [here](https://github.com/VirusTotal/yara/blob/ac0d090d47246782c789914069479d5a3c9b3388/libyara/modules/pe_utils.c#L353-L1929), pefile's ordinals can be found [here](https://github.com/erocarrera/pefile/tree/master/ordlookup), no clue what VirusTotal uses but I think it may be some version of pefile).

I'd also suggest we leave this issue open in case any folks from Mandiant would like to add their thoughts.

**Comment by williballenthin** [comment]
@jshlbrd that seems reasonable. though, i'd recommend that we document clearly that LIEF imphash != pefile imphash != XXX imphash.

chatting with people internally, it sounds like there are no plans to further tweak the algorithm. i think the feeling is that the algorithm works well as-is, and though updates could be made to the ordinal mapping, the algorithm is still deterministic. practically speaking, if this mapping is updated, then everyone that relies on the implementation must re-index their dataset.

regarding what we use and to quote a colleague:

> I think everybody takes the definition used by VT / pefile.py as the official version, just by consensus and because VT is used by so many people.

**Comment by romainthomas** [comment]
Ok, sounds good for me.

**Comment by evandrix** [comment]
https://github.com/lief-project/LIEF/issues/299#issue-450607705

> **Describe the bug**
> The imphash calculated by lief.PE.get_imphash() does match the imphash calculated by other tools. Here's an example:
> 
> ```
> executable SHA256: ad3722ab9dc9ad41a0e50122423737c241f98cc7374b4ddac999ed6eda4cfe9c
> YARA imphash: 06694565e94cd10f48e1e4b90bc04bc2
> VirusTotal imphash: 06694565e94cd10f48e1e4b90bc04bc2
> pefile imphash: 06694565e94cd10f48e1e4b90bc04bc2
> lief imphash: 0ffe645e98030f6b53caa49d22180504
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save
> **To Reproduce**
> Compare the output by lief.PE.get_imphash() to other tools mentioned above.
> 
> **Expected behavior**
> The imphash output of lief.PE.get_imphash() matches other tools commonly used in the industry.
> 
> **Environment (please complete the following information):**
> 
> * System and Version : Ubuntu 18.04
> * Target format: PE
> * LIEF commit version: 0.9.0-a448c5e

sample attached
[00413413a221123517b4e1e5d173a5310b9a48fc.bin.zip](https://github.com/lief-project/LIEF/files/4694158/00413413a221123517b4e1e5d173a5310b9a48fc.bin.zip)
