### ISSUE TITLE
CMake failed on configuring with the error from `ChooseMSVCCRT.cmake`

### ISSUE THREAD

**Issue by vic4key** [lief-project/LIEF#303]
**Describe the bug**
CMake failed on configuring with the error from `ChooseMSVCCRT.cmake:100`.

**To Reproduce**
1. Using CMake GUI to load project
2. Go to `Option` -> `Warning Messages` to turn off all `Suppress Warnings`.
3. Press `Configure` and specify the generator (my case is `VS 2012 Win64` or `VS 2017 Win64`).
4. An error is occurred;
> CMake Error at cmake/ChooseMSVCCRT.cmake:100 (string):
>   string no output variable specified
> Call Stack (most recent call first):
>   CMakeLists.txt:8 (include)

**Expected behavior**
No error on CMake configuring.

**Environment (please complete the following information):**
 - System and Version : `Windows 7` or `Windows 10` (also occurred on another Windows X I think).
 - Target format (PE, ELF, Mach-O)
 - LIEF commit version: Checkout source code at latest commit on Jun 8, 2019 .

**Additional context**
![Capture](https://user-images.githubusercontent.com/5672864/59574524-bded5600-90e1-11e9-9c6c-def67ce91738.JPG)

**Comment by vic4key** [comment]
@romainthomas Not related to above but could you please tell me a version that working well in VS 2012? Thanks.

**Comment by romainthomas** [comment]
Hello @vic4key 
I didn't checked with the CMake GUI but I think it requires to tweak this line:
https://github.com/lief-project/LIEF/blob/9dd9ded098815bd97ed490106b0fd878017e2770/cmake/ChooseMSVCCRT.cmake#L56 

> Not related to above but could you please tell me a version that working well in VS 2012?

No, VS 2012 has bugs so that it can't compile LIEF

**Comment by vic4key** [comment]
It's occurred at line 100 `string(TOUPPER ${CMAKE_BUILD_TYPE} build)`. Last night I have commented this line and changed the line 56 `set(LIEF_CRT "")` to

> set(LIEF_CRT "DEBUG")
> set(build "DEBUG")

After doing that, I configured succeed in the CMake but build in VS failed.

> No, VS 2012 has bugs so that it can't compile LIEF

It's really so sad. Our project is working on VS 2012.

**Comment by fbures** [comment]
Hi guys,

I can confirm there are similar problems while using VS2019. The experimental fix above makes it buildable(with warnings) but the linker fails. VS2015 cannot be used because of some problems in  C++14 support. Which Visual studio is suitable and can I request support for VS2017/2019 ?

František

**Comment by romainthomas** [comment]
Hello @fbures did you check the documentation: https://lief.quarkslab.com/doc/latest/compilation.html#libraries-only-sdk

**Comment by fbures** [comment]
Hi Romain,
Yes, I checked it. I can confirm it is buildable in VS2017 using LIEF_USE_CRT_RELEASE=MT(d). This is enough for me now.
Thanks!
