### ISSUE TITLE
Seg fault on ppc64le

### ISSUE THREAD

**Issue by tjakob** [lief-project/LIEF#304]
**Describe the bug**
Files written using Lief throw a seg fault on ppc64le.

**To Reproduce**
```
echo "int main(){return 0;}" > test.c
gcc test.c -o test
./test # this works
python -c 'import lief; test=lief.parse("test"); test.write("broken")'
chmod +x broken
./broken # seg faults
```
**Expected behavior**
`./broken` should function the same as `./test` and not give a segmentation fault.

**Environment (please complete the following information):**
 - System and Version : Red Hat Enterprise Linux Server release 7.6 (Maipo)
 - Target format (PE, ELF, Mach-O): ELF
 - LIEF commit version: ``python -c "import lief;print(lief.__version__)"`` or the one from ``LIEF/config.h``: `python -c "import lief;print(lief.__version__)"` gives 0.9.0-

**Additional context**
LIEF was installed from conda-forge (the recipe is using the 0.9.0 release)

**Comment by romainthomas** [comment]
Ack

**Comment by leofang** [comment]
Hi @romainthomas Does LIEF support ppc64le now? We are trying to fix the corrupted cuDNN and cuTENSOR packages on conda-forge, and I noticed that LIEF fixes cuDNN but not cuTENSOR (also segfault upon dlopen'ing). Just wanna check the current support status, thanks!

**Comment by romainthomas** [comment]
Hi @leofang. Actually ppc64le is not supported by LIEF.
