### ISSUE TITLE
Lifetime of binary symbols in Python?

### ISSUE THREAD

**Issue by awilke** [lief-project/LIEF#305]
**Describe the bug**
I was experiencing an intermittent segfault at `LIEF::ELF::Symbol::value() const` in a Python script. I believe that it was caused by a mismatch in object lifetimes between the LIEF library and my script, but I'm not familiar enough with LIEF or its Python bindings to say for sure.

**To Reproduce**
This is roughly what the script was doing to cause the segfault. (Note that this code alone does not segfault.)
```
def find_binary_symbol(elfs):
    for elf in elfs:
        binary = lief.parse(elf)
        if binary.has_symbol(SYMBOL_NAME):
            return binary.get_symbol(SYMBOL_NAME)

    raise ParseError()

elfs = [...]
symbol = find_binary_symbol(elfs)
print(symbol.value)  # <== segfault here
```

I tweaked the script so that the `Symbol` and `Binary` only ever exist within the same scope. Then I could no longer reproduce a segfault:
```
def find_binary_address(elfs):
    for elf in elfs:
        binary = lief.parse(elf)
        if binary.has_symbol(SYMBOL_NAME):
            return binary.get_symbol(SYMBOL_NAME).value

    raise ParseError()

elfs = [...]
addr = find_binary_address(elfs)
print(addr)
```

I noticed that the Python binding for `LIEF::Binary::get_symbol()` uses [`return_value_policy::reference`](https://github.com/lief-project/LIEF/blob/master/api/python/Abstract/objects/pyBinary.cpp#L126). Is it plausible that the symbol reference returned by `find_binary_symbol()` was pointing to already-freed memory? Should `get_symbol()` use `return_value_policy::reference_internal` instead?

**Expected behavior**
See above description.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 14.04
 - Target format: ELF
 - LIEF commit version: `0.9.0-a448c5e`

**Additional context**
N/A

**Comment by romainthomas** [comment]
Hello @awilke 

Nice catch and you are perfectly right!

ELF symbol life-time is tied to the ``Binary`` object. In your first script the ``binary`` object is deleted at the end of the function. Thus, ``print(symbol.value)`` is called on a free object.

**Comment by romainthomas** [comment]
Thanks!
