### ISSUE TITLE
FatBinary has no attribute 'write'

### ISSUE THREAD

**Issue by ddecadall** [lief-project/LIEF#309]
Thank you for your great tool. 
I meet a problem, please tell me my fault.
I leverage pip to install lief 
and my code is as follow 
`import lief
fat_binary = lief.MachO.parse("tmp_py")
fat_binary.write("hello")
`
it tells me 
Traceback (most recent call last):
  File "test_lief.py", line 3, in <module>
    fat_binary.write("hello")
AttributeError: '_pylief.MachO.FatBinary' object has no attribute 'write'

did it lose some step? 
thanks

**Comment by romainthomas** [comment]
> did it lose some step?

Check with the nightly build ([lief.MachO.FatBinary ](https://lief.quarkslab.com/doc/latest/api/python/macho.html#lief.MachO.FatBinary))
