### ISSUE TITLE
can not extract Binary correctly from FatBinary

### ISSUE THREAD

**Issue by ddecadall** [lief-project/LIEF#310]
I leverage Cpp sdk to extract a Binary from FatBinary of MachO.
this is my code : 
`std::unique_ptr<LIEF::MachO::FatBinary> binary = LIEF::MachO::Parser::parse(argv[1]);
  
  std::cout<< binary->size()<<std::endl;
  LIEF::MachO::Binary& n_binary =   binary->at(0);
  n_binary.write("new_py");`

And I extract the same architecture Binary File from the same FatBinary of MachO by lipo.
I compared two files. there is one byte differ between two files.  
Then I searched the origin FatBinary is the same as the file extracted by lipo  in that byte.
But the file extracted by LIEF is different,  it seems that LIEF modifed that byte which makes it wrong.

I wonder it might be a bug.   can you please check it.   the origin FatBinary is the python in /usr/bin/  at Macbook Arch64.

**Comment by romainthomas** [comment]
What is the byte you are talking ?

**Comment by ddecadall** [comment]
one binary byte in  the mach-O file.
