### ISSUE TITLE
MSVC2019 Failed with /std:c++latest

### ISSUE THREAD

**Issue by addhaloka** [lief-project/LIEF#312]
1>D:\LIEF-0.9.0-win64\include\LIEF\Builder.hpp(21,29): error C2253:  'Parser': pure specifier or abstract override specifier only allowed on virtual function
1>D:\\LIEF-0.9.0-win64\include\LIEF\Builder.hpp(21,29): error C2633:  'Parser': 'inline' is the only legal storage class for constructors

**Comment by addhaloka** [comment]
By the way, how to disable unnecessary section alignment?
```
std::unique_ptr<Binary> &&elf = ELF::Parser::parse("lib.so");
elf->write("lib_out.so");
```
```
readelf -h lib.so
ELF Header:
  Start of section headers:          74892 (bytes into file)
```
```
readelf -h lib_out.so
ELF Header:
  Start of section headers:          81920 (bytes into file)
```

**Comment by romainthomas** [comment]
Thanks, the file ``Builder.hpp`` was a mistake and does not aim to be here. (Resolved with 8f27705 )

**Comment by romainthomas** [comment]
> By the way, how to disable unnecessary section alignment?

Did you modify the library before the write ?

**Comment by addhaloka** [comment]
> > By the way, how to disable unnecessary section alignment?
> 
> Did you modify the library before the write ?

No, do nothing, just parse and write.
