### ISSUE TITLE
vs build error:error C4146:  unary minus operator applied to unsigned type, result still unsigned

### ISSUE THREAD

**Issue by stonedreamforest** [lief-project/LIEF#314]
![image](https://user-images.githubusercontent.com/16742566/60754364-8273e680-a012-11e9-8fea-584e1937b15b.png)

**Comment by stonedreamforest** [comment]
we can fixed do this:
![image](https://user-images.githubusercontent.com/16742566/60754381-b3ecb200-a012-11e9-8907-86016e31fc87.png)

but still have some warning:
![image](https://user-images.githubusercontent.com/16742566/60754385-ca930900-a012-11e9-93ec-fa9c83703f45.png)

**Comment by romainthomas** [comment]
For which version of MSVC did you get this error ?

**Comment by addhaloka** [comment]
> For which version of MSVC did you get this error ?

VS2019 16.1.5
It seems that you would better use (size_t)-1 rather than -1u

**Comment by stonedreamforest** [comment]
vs2017 15.9.13 
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27031.1 for x86/x64.

**Comment by romainthomas** [comment]
Feel free to re-open the issue if you still have this problem
