### ISSUE TITLE
Reconstruct the ELF binary will drop PROTECTED symbols

### ISSUE THREAD

**Issue by ghost** [lief-project/LIEF#315]
**Describe the bug**
Reconstruct the Android ELF binary will drop PROTECTED symbols.

**To Reproduce**
Just parse and write ELF object with PROTECTED symbols.

**Expected behavior**
You can use 'readelf -W -s' to check that.

**Comment by romainthomas** [comment]
Hello @addhaloka,
Sorry the late answer. 
Could you try to parse the ELF file with the option [ELF.DYNSYM_COUNT_METHODS.SECTION](https://lief.quarkslab.com/doc/latest/api/python/elf.html#lief.ELF.DYNSYM_COUNT_METHODS.SECTION)  and tell me if the ``PROTECTED`` symbols are still missing ?

**Comment by addhaloka** [comment]
> Hello @addhaloka,
> Sorry the late answer.
> Could you try to parse the ELF file with the option [ELF.DYNSYM_COUNT_METHODS.SECTION](https://lief.quarkslab.com/doc/latest/api/python/elf.html#lief.ELF.DYNSYM_COUNT_METHODS.SECTION) and tell me if the `PROTECTED` symbols are still missing ?

No, the `PROTECTED` symbols are kept if ELF::DYNSYM_COUNT_METHODS::COUNT_SECTION is specified.
