### ISSUE TITLE
pylief. Add Section - size of section is aligned in 4096 bytes when "loaded=True"

### ISSUE THREAD

**Issue by prusanov** [lief-project/LIEF#316]
While adding a new section to ELF there is a different behavior:
- when `loaded=True` the section size is alligned on 4096 bytes (seems to be a BUG)
- when `loaded=False` the section size in set to real size of content (seems to the right behavior)

**To Reproduce**
Code in Python:
```
binary  = lief.parse(ORIGINAL_FILE)
data = bytearray(b"\xFF" * 16)

section = Section(".testme", lief.ELF.SECTION_TYPES.PROGBITS)
section += lief.ELF.SECTION_FLAGS.EXECINSTR
section.content = data  
print("section size is %d" % section.size)

binary.add(section, loaded=True)    # set loaded=False to see differences
s = binary.get_section(".testme")
print(s.name, s.size)
```

**Expected behavior**
Expect that the size of added section will be the same as content's length.

**Environment:**
 - System and Version : Windows, Linux
 - Target format: ELF
 - LIEF commit version: 0.9.0-a448c5e

**Comment by romainthomas** [comment]
Hello @prusanov 
The alignment on 4096 bytes is not a bug. The mechanism implemented in LIEF to make a hole in an ELF binary requires such alignment.

**Comment by prusanov** [comment]
Okay, I see.
But I have some more questions.
* Why when setting `loaded=False` the size of section is equal to size of its content?
* Is there a way to strip these extra bytes from the loaded section?

Despite everything, thank you for the library!

**Comment by romainthomas** [comment]
> Why when setting loaded=False the size of section is equal to size of its content?

You mean why it does not require to have 4096 extra bytes ?

> Is there a way to strip these extra bytes from the loaded section?

No, as the extra bytes are not appended at the **end ** of the ELF file

**Comment by prusanov** [comment]
> You mean why it does not require to have 4096 extra bytes ?
Yes. As I understand, this is because of segment allocation?

My use-case is to add loadable section. At the time I have to do such manipulation:
- add section with content;
- get this new section back from binary;
- set the content again.

```
binary  = lief.parse(filename)

data = bytearray(b"\xFF" * 16)

section = lief.ELF.Section(".testme", lief.ELF.SECTION_TYPES.PROGBITS)
section += lief.ELF.SECTION_FLAGS.EXECINSTR 
section += lief.ELF.SECTION_FLAGS.ALLOC
section.content = data  

binary.add(section, loaded=True)

# extra manipulations here
s = binary.get_section(".testme")
s.content = data
s.alignment = 256

binary.write('test.patched')
```
