### ISSUE TITLE
Sending used stream to lief from python raises an error

### ISSUE THREAD

**Issue by davidt99** [lief-project/LIEF#318]
**Describe the bug**
Lief can't parse a stream that a data was read from.

**To Reproduce**
```python
import lief
with open(file_path, 'rb') as f:
    f.read(2)
    f.seek(0)
    pe = lief.PE.parse(f)
```

**Expected behavior**
lief will be able to parse the file, but `bad_format` exception is raised.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 18.04.
 - Target format: PE.
 - LIEF commit version: 0.9.0.

**Additional context**
For some reason, the seek call doesn't affect the stream from lief standpoint of view.

**Comment by romainthomas** [comment]
Hello @davidt99 
>  Lief can't parse a stream that a data was read from.

Yes, it can't take a Python stream in input but you can try to handle this case here: https://github.com/lief-project/LIEF/blob/3a11b2479800ff65612c8314092005ff45ff5552/api/python/Abstract/objects/pyParser.cpp#L39-L74

**Comment by davidt99** [comment]
lief can use python stream, just not one that was used. Looking at the code, I don't see a reason why fresh stream works and used one not. weird.
