### ISSUE TITLE
invalid comparator assertion in windows 10 

### ISSUE THREAD

**Issue by VirtualSeeker** [lief-project/LIEF#324]
**Describe the bug**
In function optimize of ELF/Builder.tcc, the comparator in line 151 is not strict weak ordering. In my case, I run the elf_builder.exe and the program will throw an assertion about invalid comparator in windows 10.

**To Reproduce**
Just build the project in visual studio 2017 and run the example program build_elf.exe.

**Expected behavior**
An assertion error will occur when this program tries to rebuild an elf  which has two sections with the same length of section name.
![LIEF_bug](https://user-images.githubusercontent.com/24785394/62779157-f8bdaa00-bae4-11e9-9374-eb9e7706822d.png)

**Environment (please complete the following information):**
- Windows 10
- Target format: PE
 - LIEF commit version: "0.10.0-"
**Additional context**

**Comment by romainthomas** [comment]
Hello,
Does it append when you build in Release mode ?
