### ISSUE TITLE
Non-compliant manylinux1 wheels

### ISSUE THREAD

**Issue by lkollar** [lief-project/LIEF#325]
**Describe the bug**
I noticed that there are now `manylinux1` wheels published which is amazing. I am experimenting with switching to LIEF from `patchelf` in `auditwheel` and in order to support the `manylinux1` Docker image we need compliant wheels for all dependencies. Unfortunately `auditwheel show` displays the following results when checking against `lief-0.10.0.dev0-cp37-cp37m-manylinux1_x86_64.whl`:

```
lief-0.10.0.dev0-cp37-cp37m-manylinux1_x86_64.whl is consistent with
the following platform tag: "linux_x86_64".

The wheel references external versioned symbols in these system-
provided shared libraries: libm.so.6 with versions {'GLIBC_2.2.5'},
libgcc_s.so.1 with versions {'GCC_3.0', 'GCC_3.4'}, libstdc++.so.6
with versions {'CXXABI_1.3.5', 'CXXABI_1.3.9', 'GLIBCXX_3.4.9',
'GLIBCXX_3.4.18', 'CXXABI_1.3', 'GLIBCXX_3.4.21', 'CXXABI_1.3.8',
'CXXABI_1.3.3', 'GLIBCXX_3.4', 'GLIBCXX_3.4.14', 'GLIBCXX_3.4.11',
'GLIBCXX_3.4.20'}, libc.so.6 with versions {'GLIBC_2.7',
'GLIBC_2.2.5', 'GLIBC_2.3.4', 'GLIBC_2.4', 'GLIBC_2.14'}
```

Of these two seem to be non-compliant with manylinux1: GLIBC 2.14 (up to 2.5 is allowed)  and GLIBCXX 3.4.20 (up to 3.4.8 is allowed). Attempting to import the module on the `manylinux1` Docker image results in the following error:

`ImportError: /opt/python/cp37-cp37m/lib/python3.7/site-packages/lief.cpython-37m-x86_64-linux-gnu.so: ELF file OS ABI invalid`

**To Reproduce**

1. `docker run -it --rm quay.io/pypa/manylinux1_x86_64`
1. `curl -O https://files.pythonhosted.org/packages/84/92/18295cf0de2c24fa89e18f8cd714574996889efcd64525f1d1e4a8715ccd/lief-0.10.0.dev0-cp37-cp37m-manylinux1_x86_64.whl`
1. `auditwheel show lief-0.10.0.dev0-cp37-cp37m-manylinux1_x86_64.whl`
1. `/opt/python/cp37-cp37m/bin/python -c "import lief"`

**Expected behavior**
- `audtwheel` confirming `manylinux1` compliance
- Python successfully importing `lief` in the `manylinux1` image

**Environment (please complete the following information):**
 - System and Version : CentOS 5 (manylinux1)
 - Target format: 
 - LIEF commit version: 

**Additional context**
I had actually attempted to build `manylinux1` wheels for LIEF before I realised that these are now being produced. I managed to get compliant wheels with the following process:

1. Use `quay.io/pypa/manylinux1_x86_64` Docker image for the build
1. Install CMake: `/opt/python/cp37-cp37m/bin/pip install cmake==3.13.2`
1. Set the PATH for `cmake` executable:  export PATH=$PATH:/opt/python/cp37-cp37m/bin/
1. Install a newer GCC from [centos-devtools](https://github.com/squeaky-pl/centos-devtools/releases) (I used 6.3 as I ran into issues with the 8.2 build): `curl -L https://github.com/squeaky-pl/centos-devtools/releases/download/6.3/gcc-6.3.0-binutils-2.27-x86_64.tar.bz2 | tar -C / -xj`
1. Build LIEF wheel statically linking libstdc++:
  ```
  export CC=/opt/devtools-6.3/bin/gcc
  export CXX=/opt/devtools-6.3/bin/g++
  export CXXFLAGS=-static-libstdc++
  /opt/python/cp37-cp37m/bin/python setup.py bdist_wheel
  ```
1. Vendor libraries into the wheel: `auditwheel repair dist/lief-0.10.0.dev0-cp37-cp37m-linux_x86_64.whl`

If there is an automated build process for creating these wheels, I'm happy to help out to make it create `manylinux` compliant packages.

**Comment by romainthomas** [comment]
Hello @lkollar 

I didn't try to build LIEF on CentOS 5 and CI nightly build are generated using Ubuntu from Travis CI: 
https://github.com/lief-project/LIEF/blob/df2d56c532b8194b2523fddba5cd6cafc8be2687/.travis.yml#L215 

If somehow you manage to setup the CI to generate compliant ``manylinux1`` I would be happy to integrate it

**Comment by lkollar** [comment]
I gave this a try using [`cibuildwheel`](https://github.com/joerick/cibuildwheel) and managed to build compliant wheels for the supported interpreters with the following command:

```
CIBW_BEFORE_BUILD_LINUX="pip install cmake==3.13.2 && \
curl -L https://github.com/squeaky-pl/centos-devtools/releases/download/6.3/gcc-6.3.0-binutils-2.27-x86_64.tar.bz2 | tar -C / -xjk" \
CIBW_ENVIRONMENT_LINUX="CC=/opt/devtools-6.3/bin/gcc CXX=/opt/devtools-6.3/bin/g++ \
CXXFLAGS=-static-libstdc++" \
CIBW_BUILD="cp35-* cp36-* cp37-*" \
cibuildwheel --platform linux
```
Now I need to figure out how to properly integrate this into the Travis build and probably replace the macOS and Windows builds as well since `cibuildwheel` can do those too.

**Comment by romainthomas** [comment]
Thanks for the update. Let me know if you need feedback or test for Travis

**Comment by lkollar** [comment]
Turns out `cibuildwheel` does not allow passing options to the build step (`setup.py` in this case) so I ended up creating a new `Dockerfile` based on the `manylinux1` image and setting it up with GCC 6.3. The PR still needs work as a bunch of tests are failing.

**Comment by LecrisUT** [comment]
Maybe things are changed, but `cibuildwheel` allows passing the [`--config-settings`](https://cibuildwheel.pypa.io/en/stable/options/#config-settings). Could a cibuildwheel approach be revisited?

**Comment by LecrisUT** [comment]
It offloads the maintenance of python version tracking, it has better coverage of python environments, it automates tasks like wheel repair and so on.
