### ISSUE TITLE
takes a long time to reconstruct ELF binary

### ISSUE THREAD

**Issue by WalkingAlone-David** [lief-project/LIEF#326]
**Describe the bug**
The size of ELF library is about ``26M``,   I just use python to load the library, then write the library.
But i find it will take almost 15min to finish this process. Can you offer some advice to accelerate this process?

**To Reproduce**
```
binary = lief.ELF.parse(inlibname)

binary.write(outlibname)
```

**Expected behavior**

**Environment (please complete the following information):**
 - System and Version : Windows 7
 - Target format (PE, ELF, Mach-O): ELF
 - LIEF commit version:  0.9.0-a448c5e

**Comment by romainthomas** [comment]
Hello @WalkingAlone-David 
Can you tell me how many relocations, you binary contain ?

**Comment by WalkingAlone-David** [comment]
Yes,  the binary contains more than 40,000 relocations.

**Comment by romainthomas** [comment]
I think this is the root cause of the bad performances. Unfortunately, I don't have a "quick" solution to deal with that.
