### ISSUE TITLE
LIEF::ELF::DataHandler::Handler has shallow copyable Node pointers

### ISSUE THREAD

**Issue by urif-c2a** [lief-project/LIEF#328]
**Describe the bug**
- The LIEF::ELF::DataHandler::Handler is copyable (both copy ctor and op= are default).
- In other hand the nodes_ vector holds Node pointers allocated by new.
- Since the copy ctor/op= are default, they don't allocate copies, and both Handler objects will point to the same Nodes.
- Once one of the Handler copies be destroyed, the second one will point to deleted Nodes, and trying to destroy the second Handler will throw.

**To Reproduce**
For now I can't find actual usage of Handler copying, so maybe it's not critical now.

**Expected behavior**
The Handler class should be either non-copyable, or should provide specialize copy methods, which may either deep copy or refcount-share the nodes.
Also consider using make_unique/make_shared to wrap the allocations.

**Environment (please complete the following information):**
  - Target format ELF
 - LIEF commit version: df2d56c532b8194b2523fddba5cd6cafc8be2687

**Comment by romainthomas** [comment]
Hello @urif-c2a 

You are perfectly right, the object should implement C++ constructor properly. I plan to make the ELF binary object copyable that would require to have Handler copy.

Currently, the ELF's Binary object is marked as non-copyable: 
https://github.com/lief-project/LIEF/blob/088951ddb72e6a1f8d875731756d757eaf81d7cd/include/LIEF/ELF/Binary.hpp#L68-L69
thus, this constructor should not be called. 

Let me know if I miss something in the way the DataHandler copy constructor can be called

**Comment by urif-c2a** [comment]
The non-copyable Binary makes the problem non-critical, but it's still there, if the **Handler** is shallow-copyable.
If you're planning to make the handler copyable, then customized copy methods are essential. You'll need to decide if the copies will share same Nodes (use make_shared), or get their own copies (use make_unique and copy the pointee).
Anyway for meantime disabling copying for **Handler** may be enough.

**Comment by romainthomas** [comment]
Fixed
