### ISSUE TITLE
ELF add_library fails

### ISSUE THREAD

**Issue by pgarba** [lief-project/LIEF#333]
**Describe the bug**
I'm trying to inject a shared object into a ELF binary. The injection works but when I start the output binary I get the following error:

[23979.727023] 1905 (op1_.): Uhuuh, elf segment at 0000000000202000 requested but the memory is mapped already

**To Reproduce**
  std::unique_ptr<LIEF::ELF::Binary> binary(
      LIEF::ELF::Parser::parse(Path.str()));
  binary->add_library("libsaturn.so")
  binary->write(OutPath);

**Expected behavior**
The output binary shouldn't crash.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 19.04
 - Target format (PE, ELF, Mach-O): ELF
 - LIEF commit version: 4d4f96d2689e907196e13c633c58f7fce2fae8ed

**Additional context**
[op1.zip](https://github.com/lief-project/LIEF/files/3544916/op1.zip)
[op1_.zip](https://github.com/lief-project/LIEF/files/3544910/op1_.zip)

**Comment by romainthomas** [comment]
Thanks, I spotted this issue in the ELF builder. It's not trivial to fix but I'll try in the next couple of weeks.

**Comment by romainthomas** [comment]
It turned to be easier than I thought. You can check https://github.com/lief-project/LIEF/commit/58ca827f36c8bfbf500b25001e7bfcd69320d217 that fix your case

**Comment by pgarba** [comment]
Thanks, it works !

**Comment by pgarba** [comment]
Sorry, now its crashing in the libc during startup:

[34492.146282] op1_[9527]: segfault at 0 ip 00007f1bdbbbf3c6 sp 00007ffe9a080230 error 4 in libc-2.29.so[7f1bdbb9b000+173000]
[34492.146293] Code: 41 54 45 31 e4 55 53 48 83 ec 28 48 89 74 24 08 85 c9 0f 85 ec 02 00 00 83 fa 01 0f 84 8b 01 00 00 83 fa 24 0f 87 82 01 00 00 <49> 0f be 45 00 49 8b 48 68 4c 89 eb 48 89 c6 f6 44 41 01 20 74 16

**Comment by romainthomas** [comment]
With the same binary ?

**Comment by pgarba** [comment]
Yes, same binary

**Comment by pgarba** [comment]
Sorry my fault. You code is working fine!

One more question. If I add a symbol like this:

  LIEF::ELF::Symbol Sym(FunctionName);
  Sym.set_imported(true);
  Sym.type(LIEF::ELF::ELF_SYMBOL_TYPES::STT_FUNC);
  auto &S = binary->add_dynamic_symbol(Sym, LIEF::ELF::SymbolVersion::local());

Is there a way get the address of the symbol ?

**Comment by romainthomas** [comment]
Nop, when you add this symbol, LIEF does not create a plt entry

**Comment by pgarba** [comment]
ok, I create a new segment and then create a new relocation that should write the resolved address into it.

`
  LIEF::ELF::Segment Seg;
  std::vector<uint8_t> d(0x1000, 0);
  Seg.content(d);
  Seg.virtual_address(0x23000000);
  Seg.virtual_size(0x1000);
  Seg.alignment(8);
  Seg.flags(LIEF::ELF::ELF_SEGMENT_FLAGS::PF_R |
            LIEF::ELF::ELF_SEGMENT_FLAGS::PF_W);
  Seg.type(LIEF::ELF::SEGMENT_TYPES::PT_LOAD);
  binary->add(Seg);

LIEF::ELF::Relocation *R = new LIEF::ELF::Relocation(
        Sec_VA, LIEF::ELF::RELOC_x86_64::R_X86_64_JUMP_SLOT, 0, true);
    R->purpose(LIEF::ELF::RELOCATION_PURPOSES::RELOC_PURPOSE_PLTGOT);
    R->symbol(&Sym);
    binary->add_pltgot_relocation(*R);
`


I can see that the loader is writing into this address but it writes a 0 instead the symbol address.
Any idea what I do wrong ?

**Comment by romainthomas** [comment]
Humm ``LD_BIND_NOW=1`` ?

**Comment by greek-stasia** [comment]
@pgarba did you ever find a solution? I believe I'm trying to do the same thing with the python api

**Comment by pgarba** [comment]
@greek-stasia Yes, I finally solved it. Basically the code was ok but the symbol was missing some options.

```
std::unique_ptr<LIEF::ELF::Binary> binary(
      LIEF::ELF::Parser::parse(Path.str()));

  // add libsaturn.so
  binary->add_library("libsaturn.so");

  // create new segment to hold the symbol addr
  LIEF::ELF::Segment Seg;
  Seg.flags(LIEF::ELF::ELF_SEGMENT_FLAGS::PF_R |
            LIEF::ELF::ELF_SEGMENT_FLAGS::PF_W);
  Seg.type(LIEF::ELF::SEGMENT_TYPES::PT_LOAD);
  Seg.virtual_size(0x8);
  Seg.alignment(8);
  std::vector<uint8_t> d(8, 0);
  Seg.content(d);
  Seg = binary->add(Seg);

  // Create PLTGOT relocation
  LIEF::ELF::Relocation *R = new LIEF::ELF::Relocation(
      Seg.virtual_address(), LIEF::ELF::RELOC_x86_64::R_X86_64_JUMP_SLOT, 0,
      true);
  R->purpose(LIEF::ELF::RELOCATION_PURPOSES::RELOC_PURPOSE_PLTGOT);

  auto sympf =
      reinterpret_cast<LIEF::ELF::Symbol &>(binary->get_symbol("printf"));

  // Create Symbol
  LIEF::ELF::Symbol Sym("execute");
  Sym.set_imported(true);
  Sym.type(LIEF::ELF::ELF_SYMBOL_TYPES::STT_FUNC);
  Sym.binding(LIEF::ELF::SYMBOL_BINDINGS::STB_GLOBAL);
  R->symbol(&Sym);
  binary->add_pltgot_relocation(*R);

  binary->write(OutPath);
`
