### ISSUE TITLE
ELF add_segment(EXEC) moves sections header too far

### ISSUE THREAD

**Issue by urif-c2a** [lief-project/LIEF#335]
**Describe the bug**
src/ELF/Binary.tcc:351:
`header.section_headers_offset(header.section_headers_offset() + new_phdr_offset + phdr_size * header.numberof_segments());`

Usually sections header placed at the end of file, so section_headers_offset is almost the file size. The new_phdr_offset is placed at the end of file too. That is, the sum in parentheses is about twice the file size.

**To Reproduce**
Add segment to an ELF EXEC binary. See the file size twice as original.

**Expected behavior**
Maybe the sections header should be just after the new-added segment?

**Environment (please complete the following information):**
master

**Additional context**
Similar at Binary.tcc: lines 413, 417

**Comment by romainthomas** [comment]
>  Maybe the sections header should be just after the new-added segment?

If you manage to have a working version with this way, I will be happy to merge your PR
