### ISSUE TITLE
Saving without modify ELF file increments size

### ISSUE THREAD

**Issue by djmacross** [lief-project/LIEF#338]
**Describe the bug**
Saving without modify ELF file increments size

**To Reproduce**
std::unique_ptr<Binary> binary{ Parser::parse(my_str) };
binary->write(my_str);

New ELF file is bigger and add extrasegments to the original.

**Expected behavior**

**Environment (please complete the following information):**
Windows 10
``LIEF/config.h``

**Additional context**

**Comment by romainthomas** [comment]
Humm I agree it is not normal for the new segment. Could you send the binary ?

**Comment by greek-stasia** [comment]
Going off of that - I've run into a similar issue. I add a single load segment but what I end up getting is 5 additional segments. No wonder it's so big. I'm basically using the ELF Hooking example.

**Comment by romainthomas** [comment]
Indeed, LIEF add new segments for some kind of modification. For instance, if you change a symbol name, the ``.dynstr`` is likely to  be larger and thus, it need to be relocated.

Nevertheless, a ``parse() -> write()`` should not lead to new segments. 
This is why, I asked to @djmacross if he can provide a minimal sample to reproduce this behavior

**Comment by greek-stasia** [comment]
Ahh thank you for that explanation. Out of curiosity, I tested for @djmacross  problem on a simple hello world program and it does seem to add another segment of 4096 bytes.
[lief-test.zip](https://github.com/lief-project/LIEF/files/3580209/lief-test.zip)
Env: Ubuntu
Api: Python
I hope this helps.  :)

**Comment by romainthomas** [comment]
Thanks @greek-stasia. At first sight, it seems to come from the GNU Hash table reconstruction.

**Comment by romainthomas** [comment]
It should be fixed now
