### ISSUE TITLE
deploy script fails to create "deploy" directory

### ISSUE THREAD

**Issue by lkollar** [lief-project/LIEF#343]
**Describe the bug**
The `deploy.sh` script in Travis fails at the `mkdir deploy` step:

```
+cd /home/travis/build/lief-project/LIEF/build
+mkdir deploy
mkdir: cannot create directory ‘deploy’: Permission denied
```
[Travis build log](https://travis-ci.org/lief-project/LIEF/jobs/585495985)

**To Reproduce**
Probably by triggering a new build on master. I can't reproduce it in a PR as the script would just exit on my branch.

**Expected behavior**
`deploy.sh` to run to completion.

**Environment (please complete the following information):**
 - System and Version : [e.g. Ubuntu 16.04] Travis CI

[Failed `deploy.sh`](https://travis-ci.org/lief-project/LIEF/jobs/585495985) vs [Success](https://travis-ci.org/lief-project/LIEF/jobs/582743184).

**Additional context**
It is possible that this is happening due to https://github.com/lief-project/LIEF/pull/337 but I can't see anything which might cause the permission denied error.

**Comment by romainthomas** [comment]
I think it's because ``/home/travis/build/lief-project/LIEF/build`` is created from the Docker file, thus 
Travis user can't create ``/home/travis/build/lief-project/LIEF/build/deploy``

**Comment by romainthomas** [comment]
Also, I noticed that the build time is longer than before (5min vs 25min now) Any idea to improve compilation time ?

**Comment by lkollar** [comment]
> I think it's because `/home/travis/build/lief-project/LIEF/build` is created from the Docker file, thus
> Travis user can't create `/home/travis/build/lief-project/LIEF/build/deploy`

Yes, that must be it. I will see if I can work around this or if not, just copy the source into the container and then copy the built artifacts out at the end. I already had an version which did this but it seemed too complicated for no good reason so I dropped it.

> Also, I noticed that the build time is longer than before (5min vs 25min now) Any idea to improve compilation time ?

Yes, I was wondering about it too. I took another look this morning and noticed that `ccache` is not installed in the Docker image. I will add it and see if it improves the compile times.

**Comment by romainthomas** [comment]
It seems there is still an error: https://travis-ci.org/lief-project/LIEF/jobs/586369965#L6773

**Comment by lkollar** [comment]
Looks like I have to copy the whole `build` dir out of the container instead of just `dist`. Will try to submit a fix later today.

**Comment by lkollar** [comment]
Another issue 🤦‍♂ 
`./.github/deploy.sh: line 130: /opt/python/cp35-cp35m/bin/python3.5: No such file or directory`

The `deploy.sh` script uses the `PYTHON_BINARY` environment variable which points to the interpreter in the Docker image.

**Comment by lkollar** [comment]
While working on the fix for this I found an unrelated bug: https://github.com/lief-project/LIEF/issues/348. Seems like this has been there for a while.
