### ISSUE TITLE
setup.py is not being generated in api/python

### ISSUE THREAD

**Issue by lkollar** [lief-project/LIEF#348]
Generating `setup.py` for the Python API is commented out: https://github.com/lief-project/LIEF/blob/ab9ddf740e8f9392864e5b5130fe462f7e62d641/api/python/CMakeLists.txt#L189

This causes a silent failure in Travis: https://travis-ci.org/lief-project/LIEF/jobs/582743184#L11132.

**Comment by romainthomas** [comment]
Oh yes, my bad. This script is no longer used.
