### ISSUE TITLE
Upload latest wheels to PyPI

### ISSUE THREAD

**Issue by lkollar** [lief-project/LIEF#355]
Many thanks for helping out getting #337 landed. I tested the new `manylinux1` wheels at https://lief.quarkslab.com/packages/lief/ and they work well now on the `manylinux1` Docker image. However, PyPI still contains the old wheels built in July. Do you plan to upload the new wheels there?

**Comment by mingwandroid** [comment]
Would there be any interest in helping to maintain LIEF on conda-forge too? When is 0.10 expected to be ready? Looking forward to it!

**Comment by romainthomas** [comment]
> However, PyPI still contains the old wheels built in July. Do you plan to upload the new wheels there?

Yes I'll do by the end of the month.

@mingwandroid yes sure!

**Comment by lkollar** [comment]
Any update on this?

**Comment by romainthomas** [comment]
Done :)

**Comment by lkollar** [comment]
Awesome, many thanks!
