### ISSUE TITLE
Section.offset and Section.file_offset seems not correct

### ISSUE THREAD

**Issue by liborui** [lief-project/LIEF#361]
**To Reproduce**
LIEF with python binding
```python
for item in parsed_binary.sections:
     print(item.name, hex(item.offset), hex(item.file_offset))
```
which generates:
 0x0 0x0
.text 0xb4 0xb4
.rodata 0xa364 0xa364
.data 0xa604 0xa604
.....

**Expected behavior**
I thought the Section.offset and Section.file_offset is different, corresponding to the "Addr" and "Off" in the ```readelf -h``` output. But it seems to be the same, same as "Off".

```readelf -h``` output:
[Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
[ 1] .text             PROGBITS        00004a00 0000b4 00a2b0 00  AX  0   0  2
[ 2] .rodata           PROGBITS        0000ecb0 00a364 00029f 00   A  0   0  4
.....

**Environment (please complete the following information):**
 - System and Version : Ubuntu 18.04
 - Target format: ELF(for MSP430 embedded platform)
 - LIEF commit version: 0.10.1-bfe5414

**Comment by romainthomas** [comment]
Hello @liborui 

- [section.offset](https://github.com/lief-project/LIEF/blob/master/api/python/Abstract/objects/pySection.cpp#L48) is the shared attribute for ELF, PE and Mach-O.
- [section.file_offset](https://github.com/lief-project/LIEF/blob/master/api/python/ELF/objects/pySection.cpp#L80) is ELF specific and an alias for the previous one
- [section.virtual_address](https://github.com/lief-project/LIEF/blob/master/api/python/Abstract/objects/pySection.cpp#L53): as the name said, it's the virtual address.

I think the API is well [documented](https://lief.quarkslab.com/doc/latest/api/python/elf.html#section) and the names quite explicit. I won't do any change expect if you have strong arguments.
