### ISSUE TITLE
Fail to extend c program's .text section with lief

### ISSUE THREAD

**Issue by tjdhc3889** [lief-project/LIEF#362]
**Describe the bug**

c program extend .text section and get segmentation fault when running.

**To Reproduce**

import lief
c=lief.parse("test")
t=c.getsection(".text")
c.extend(t,1000)
c.write("test0")

**Expected behavior**
test0 shall be exactly behavior as test

**Environment (please complete the following information):**
 - System and Version : [e.g. Ubuntu 16.04]
 - Target format (PE, ELF, Mach-O)
 - LIEF commit version: ``python -c "import lief;print(lief.__version__)"`` or the one from ``LIEF/config.h``

test program is very simple hello world c program
python3 -c "import lief;print(lief.__version__)"
0.10.1-bfe5414

**Additional context**

**Comment by sudhackar** [comment]
Currently this will fail for PIE binaries which use `rip` relative addressing e.g. to call functions in GOT. This would require to patch all such `call`, `lea` etc which use resources/variables from pages after the `.text` mapping.

**Comment by romainthomas** [comment]
Yep, extending the ``.text`` section will corrupt the binary unless you patch the assembly code. I close the issue as it is not the purpose of LIEF to patch assembly code.
