### ISSUE TITLE
LIEF 0.10.1 doesn't compile w/o cppcheck

### ISSUE THREAD

**Issue by newgre** [lief-project/LIEF#363]
**Describe the bug**
Trying to compile examples/cmake/external_project on Windows using VS 2019, in the configure phase, I get the error:

Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
2>-- Configuration Types: Debug;Release;MinSizeRel;RelWithDebInfo
2>-- Build Types:
2>-- Configuring incomplete, errors occurred!

0.9.0 did work, but 0.10.1 does not.

**To Reproduce**
1) clone LIEF 0.10.1
2) In examples/cmake/external_prokect/CMakeLists.txt change LIEF_VERSION from 0.9.0 to 0.10.1.
3) Use cmake to configure LIEF.
4) Above error appears.

**Comment by romainthomas** [comment]
This issue does not come from cppcheck, you forgot to set ``CMAKE_BUILD_TYPE`` to ``Release``

**Comment by newgre** [comment]
Sorry, my comment was slightly imprecise: the error happens during the **build** phase after LIEF has been cloned.
The build type is set implicitly for a Visual Studio project depending on whether I build as Debug, Release, right? So even if I select Release the error still appears. In any case, the build of the example doesn't work for Visual Studio out of the box.
Is there an easy way to fix this?

**Comment by newgre** [comment]
@romainthomas I'm unable to re-open the issue, so pinging you directly.

**Comment by romainthomas** [comment]
@newgre the issue is not related to LIEF but about your VS configuration. 
![Screenshot_2019-12-13 Compilation — LIEF 0 11 0-a26ae60 documentation](https://user-images.githubusercontent.com/7450402/70773571-18f1c400-1d78-11ea-9183-81d0647c97b2.png)

**Comment by newgre** [comment]
Thank you Romain, I somehow missed [this part of the documentation](https://lief.quarkslab.com/doc/stable/compilation.html). I was under the impression that the example would work out of the box. Thanks!
