### ISSUE TITLE
Unable to Install with Python2.7

### ISSUE THREAD

**Issue by rocahe** [lief-project/LIEF#366]
**Describe the bug**
Unable to Install with Python2.7. 
I tried on both MacOS 10.15 and Ubuntu18.04.

"setup.py" is not compatible with Python 2.7:

Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6f/5987spd9487_qh83qb2xbh2w0000gn/T/pip-install-_cSVKL/lief/setup.py", line 306
        def format_version(version: str, fmt: str = fmt_dev, is_dev: bool = False):
                                  ^
    SyntaxError: invalid syntax
---------------------------------------------------------------------------------
**To Reproduce**
pip install lief (python2.7.)
OR
python setup.py install (python2.7)

**Comment by romainthomas** [comment]
Yep, we dropped the Python 2.7 support

**Comment by rocahe** [comment]
I'm currently working on a project using Triton, which only supports python 2.7. Is it possible to use lief and Triton together with python?

**Comment by romainthomas** [comment]
I disagree, Triton also supports Python 3

**Comment by rocahe** [comment]
OK, thanks for clarifying.
