### ISSUE TITLE
Debug build w/ MSVC not working

### ISSUE THREAD

**Issue by newgre** [lief-project/LIEF#367]
**Describe the bug**
Compiling example program under _examples/cmake/external_project_ w/ MSVC using the debug configuration fails.

**To Reproduce**
Check out LIEF 0.10.1, change line 35 in CMakeLists.txt to use the debug CRT:
`list(APPEND ${LIEF_CMAKE_ARGS} -DLIEF_USE_CRT_DEBUG=MTd)`
configure, open the VS project and build.

**Expected behavior**
The compilation should be successful.

**Environment (please complete the following information):**
Windows 10, latest MSVC 2019, CMake 3.16

**Additional context**
~~Above process works w/ 0.9.0~~

**Comment by romainthomas** [comment]
Does it work in Release mode with the command line ?

```console
$ cmake -DCMAKE_BUILD_TYPE=Release ..
$ cmake --build . --target HelloLIEF --config Release
```

**Comment by newgre** [comment]
This command line produces tons of "unresolved external symbol" linker errors, e.g.,:
`
LIEF.lib(ResourceDialogItem.obj) : error LNK2001: unresolved external symbol "void * __cdecl operator new(unsigned __int64)" (??2@YAPEAX_K@Z) 
LIEF.lib(ResourceDialog.obj) : error LNK2001: unresolved external symbol "void * __cdecl operator new(unsigned __int64)" (??2@YAPEAX_K@Z) 
LIEF.lib(EnumToString.cpp.obj) : error LNK2001: unresolved external symbol "void * __cdecl operator new(unsigned __int64)" (??2@YAPEAX_K@Z) 
msvcprt.lib(locale0_implib.obj) : error LNK2001: unresolved external symbol "void * __cdecl operator new(unsigned __int64)" (??2@YAPEAX_K@Z) 
`
However, it at least seems to compile.

**Comment by newgre** [comment]
Note the when changing line 35 in CMakeLists.txt to `list(APPEND ${LIEF_CMAKE_ARGS} -DLIEF_USE_CRT_DEBUG=MTd)` and using this command line:

`$ cmake -DCMAKE_BUILD_TYPE=Debug ..
$ cmake --build . --target HelloLIEF --config Debug`

then everything compiles and links successfully.

**Comment by newgre** [comment]
And here's the CMake output when trying to build the Debug configuration w/ Visual Studio:

`1>Performing configure step for 'LIEF'
1>CMake Error at cmake/ChooseMSVCCRT.cmake:100 (string):
1>-- LIEF_CRT: /
1>  string no output variable specified
1>Call Stack (most recent call first):
1>  CMakeLists.txt:8 (include)
1>
1>
1>-- Using Debug VC++ CRT: MDd
1>-- Using Release VC++ CRT: MD
1>-- Using MinSizeRel VC++ CRT: MD
1>-- Using RelWithDebInfo VC++ CRT: MD
1>-- Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
1>-- Tagged: 1
1>-- Tag: 0.10.1
1>-- Current branch: HEAD
1>-- LIEF 0.10.1
1>-- ccache: ON
1>-- Enable JSON support
1>-- Enable Frozen (C++14 support)
1>-- Number of parallel compiler jobs set to /MP
1>-- Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
1>-- Configuration Types: Debug;Release;MinSizeRel;RelWithDebInfo
1>-- Build Types:
1>-- Configuring incomplete, errors occurred!`

**Comment by newgre** [comment]
What's the priority of fixing this issue?
Just wanted to emphasize that an out-of-the-box build of `examples/cmake/external_project` with VisualStudio doesn't work  (VS 2019, CMake 3.16.4) in *any* configuration for 0.10.1. That is, the windows build for latest LIEF is non-functional when using MSVC.

**Comment by romainthomas** [comment]
Hello @newgre 
I currently don't have time to dig into this issue and I would say it is not in the top priority but
feel free to open a PR if you have a fix.

**Comment by medievalghoul** [comment]
I've been encountering the same issue with LIEF, 
![image](https://user-images.githubusercontent.com/61852278/91112791-ddaed100-e638-11ea-9c2d-4775567b18f9.png)

**Comment by romainthomas** [comment]
To be re-opened if the issues still exist in the master.
