### ISSUE TITLE
pybind11 linking error on 0.10.1

### ISSUE THREAD

**Issue by luigino** [lief-project/LIEF#370]
**Describe the bug**
While building on openSUSE Tumbleweed, the final pybind11 linking phase fails with numerous undefined references.

**To Reproduce**
```
> wget https://github.com/lief-project/LIEF/archive/0.10.1.tar.gz
...
> /usr/bin/cmake /home/abuild/rpmbuild/BUILD/LIEF-0.10.1/. '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PA
TH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTAL
L_LIBDIR:PATH=/usr/lib64 -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_C_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fun
wind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -DNDEBUG' '-DCMAKE_CXX_FLAGS=-O2 -Wall
 -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type
 -flto=auto -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwi
nd-tables -fstack-clash-protection -Werror=return-type -flto=auto -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--
no-undefined -Wl,-z,now' '-DCMAKE_MODULE_LINKER_FLAGS=-flto=auto -Wl,--as-needed' '-DCMAKE_SHARED_LINKER_FLAGS=-flto=auto -Wl,--as-need
ed -Wl,--no-undefined -Wl,-z,now' -DLIB_SUFFIX=64 -DCMAKE_SKIP_RPATH:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=
ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/shar
e/cmake/Modules
...
> /usr/bin/make -O VERBOSE=1 -j8
```

**Expected behavior**
A successful build.

**Environment (please complete the following information):**
 - System and Version : [openSUSE Tumbleweed]

**Additional context**

See full [build log](https://github.com/lief-project/LIEF/files/3992288/LIEF_tw64.txt).

**Comment by romainthomas** [comment]
This error comes from the undefined variable ``-DPYTHON_EXECUTABLE=<path to python>``

**Comment by luigino** [comment]
[No apparent change](https://github.com/lief-project/LIEF/files/3996276/LIEF_tw64_2.txt.gz).

**Comment by romainthomas** [comment]
Somehow you don't link against ``libpythonX.Y.so``. This is the error

**Comment by luigino** [comment]
[Done](https://github.com/lief-project/LIEF/files/3996672/pylink.patch.txt).

Now I see [this](https://github.com/lief-project/LIEF/files/3996679/LIEF_tw64_3.txt).

Speaking of which, do you think I could use the system pybind11?

**Comment by luigino** [comment]
It comes out all I needed was this commit https://github.com/lief-project/LIEF/commit/f9e88a6665e80675c67310089d43045ebd3b64ef .
