### ISSUE TITLE
Using lief to patch the elf RUNPATH for AppImage

### ISSUE THREAD

**Issue by azubieta** [lief-project/LIEF#377]
I'm experimenting with lief to use it at https://github.com/AppImageCrafters/appimage-builder/ to patch the elf file embed. So far the process works well, the only issue is that it takes forever when large libraries (> 10 Mb) are being modified. 

So I wonder if there is more efficient (quicker) way of only changing the RUNPATH for an elf:

Here is my code:
```
        binary = ELF.parse(file)

        link_dirs = self._resolve_elf_link_dirs(binary)

        logging.info("Setting RUNPATH: %s" % file)

        binary.remove(ELF.DYNAMIC_TAGS.RPATH)
        binary.remove(ELF.DYNAMIC_TAGS.RUNPATH)

        run_path = ELF.DynamicEntryRunPath()
        for dir_path in link_dirs:
            rel_path = os.path.relpath(dir_path, os.path.dirname(file))
            run_path_entry = '$ORIGIN/%s' % rel_path

            logging.info("\t%s" % run_path_entry)
            run_path.append(run_path_entry)

        binary.add(run_path)
        binary.write(file)
```

**Comment by romainthomas** [comment]
I suspect, it comes from a large number of relocation in your binary. I'm aware that LIEF lacks of optimization on this part.

**Comment by azubieta** [comment]
> I suspect, it comes from a large number of relocation in your binary

Pravably, we are talking about libs like: libjvm and libLLVM. Is there any known workaround ?

**Comment by romainthomas** [comment]
I would say that there is no workaround as the *build* process is quite complex and involves several components

**Comment by JanuszL** [comment]
This PR may address this issue https://github.com/lief-project/LIEF/pull/413.

**Comment by romainthomas** [comment]
Should have been addressed. See: https://lief-project.github.io/blog/2022-01-23-new-elf-builder/

Feel free to reopen the issue if the performances are still an issue
