### ISSUE TITLE
class Symbol::section() method throw unknown exception always.

### ISSUE THREAD

**Issue by dc-koromo** [lief-project/LIEF#388]
The `section` method in the `Symbol` class caused an error and could not get section information.

**Environment (please complete the following information):**
 - System and Version : Windows10
 - Target format ELF
 - LIEF commit version: https://lief-project.github.io/packages/sdk/LIEF-0.11.0-win64.zip
 - Sample: [a.zip](https://github.com/lief-project/LIEF/files/4420131/a.zip)

``` cpp
std::unique_ptr<LIEF::ELF::Binary> elf = LIEF::ELF::Parser::parse("a.out");
auto syms = elf->symbols();
for (auto& sym : syms)
{
  cout << sym.name() << "\r\n";
  try
  {
    auto sec = sym.section();
    cout << sec.name() << "\r\n";
  }
  catch(exception e) {
    auto wh = e.what();
    cout << wh << "\r\n";
  }
}
```

**Comment by romainthomas** [comment]
Yes, a symbol is not always tied to a section.
