### ISSUE TITLE
Frida Gadget error when patching APK

### ISSUE THREAD

**Issue by localacct** [lief-project/LIEF#390]
**Describe the bug**
I used lief-injection.py to patch an APK to load libgadget.so. When the application is launched, it does not pause and continue to run and I can see the log entry
````
V frida-lief: I'm in the process!
````

However, when I tried to connect to it from my Mac laptop, I get this error
````
Failed to enumerate processes: unable to connect to remote frida-server: Unexpected lack of content trying to read a line
````

Is the application supposed to pause on startup and how can I troubleshoot the error from frida-gadget?

**To Reproduce**
Use lief-injection to patch an APK and then try connecting to the running application from the host machine.

**Expected behavior**
I should be able to use Frida to instrument the application.

**Environment (please complete the following information):**
 - System and Version : Mac OS 10.14.6
 - Target format: APK (ARM)
 - LIEF commit version: 0.10.1-bfe5414

I have tried both the libgadget.so that comes with tutorial 09 and also tried the latest 12.8.20 release

**Additional context**

**Comment by romainthomas** [comment]
Frida misconfiguration.
