### ISSUE TITLE
Regarding #390

### ISSUE THREAD

**Issue by localacct** [lief-project/LIEF#391]
Hi Romain

With regards to #390, you mentioned that it is a Frida misconfiguration. May I know what configuration do I need to change and where? I have tried
````
adb forward tcp:27042 tcp:27042
````

````
adb forward tcp:0 tcp:27042
````

but it still cannot connect to the remote frida-server.

I did a netstat on the rooted device and I cannot see the default port 27042 being listed.

Secondly, is the application process supposed to pause on startup or continue to run? In my case, the application just continued to run and did not pause.

**Comment by romainthomas** [comment]
Please stop open issue related to Frida here!
