### ISSUE TITLE
Incorrect parsing MSB-ELF on Windows

### ISSUE THREAD

**Issue by prusanov** [lief-project/LIEF#398]
Parsing an MSB-ELF file under Windows gives an incorrect result : all IDs and lengths are encoded in the little-endian format instead of big-endian. While the same file under Linux is parsed correctly.

For example, under Windows - `e_machine`-bytes `00 08` are parsed as 0x800, but it should be 0x08 (EM_MIPS). And under Linux they are parsed correctly - 0x08.

ELF-file: https://github.com/JonathanSalwan/binary-samples/blob/master/elf-Linux-Mips4-bash

**Environment (please complete the following information):**
 - System and Version : Windows 7 x64; Manjaro Linux 19.0.2
 - Target format - ELF
 - Tested on different versions:
    - Python 2.7.13, LIEF 0.9.0-a448c5e
    - Python 3.7.7, LIEF 0.10.1-bfe5414

**Comment by romainthomas** [comment]
Should be fixed since then. Feel free to re-open the issue
