### ISSUE TITLE
PE parse consuming memory

### ISSUE THREAD

**Issue by davidt99** [lief-project/LIEF#399]
I have a file that parsing it consumes a lot of memory, to a point of OOM.
The file itself is not a valid or runnable PE but I can't know that before parsing it.
You mentioned in #110 that you plan to add a shallow flag, do you have an ETA or a branch I can pick the work from?

**Expected behavior**
[The file](https://file.io/BlJCI6nZ)

**Environment:**
 - System and Version : Ubuntu 18.04
 - Target format: PE
 - LIEF commit version: 10.1

**Comment by williballenthin** [comment]
![image](https://user-images.githubusercontent.com/156560/79909511-562b2a00-83da-11ea-81c3-7ba2a7c4f16e.png)
 
would you mind sharing the file elsewhere? (maybe on VT?)

**Comment by davidt99** [comment]
@williballenthin 
https://www.virustotal.com/gui/file/5653564a122b7afa838a3707c7fdbbf8b14ec1934d6198f25cb2340d3dedf8a4/detection

**Comment by romainthomas** [comment]
@davidt99 actually I didn't start to deal with this issue so feel free to base your work on the master branch and if you have any question on the design / API you can ping me on Gitter

**Comment by romainthomas** [comment]
I refactored some parts of the PE parser. Feel free to reopen this issue if there is still a problem with the memory consumption.
