### ISSUE TITLE
ImportError: OS_ABI: element "GNU" already exists! Error on ARM machine

### ISSUE THREAD

**Issue by sborpo** [lief-project/LIEF#403]
**Describe the bug**
Lief module doesn't deployed properly on an ARM based system.
When trying to import the module - throws an import error:
```
Python 3.7.7 (default, Mar 10 2020, 17:25:08)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: OS_ABI: element "GNU" already exists!
```

**To Reproduce**
1. Clone the repository - tag version 0.10.1
2. Execute `sudo python3 ./setup.py install`
3. Try to import lief

**Expected behavior**
The module should be imported successfully.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 16.04
 - LIEF tag: 0.10.1
 - Platform: uname_result(system='Linux', release='4.15.0-1057-aws', version='#59~16.04.1-Ubuntu SMP Fri Dec 6 09:25:33 UTC 2019', machine='aarch64', processor='aarch64')

**Additional context**
When tried to install it using pip3 install lief - it failed, so tried to clone the repository and
run the installation directly.

**Comment by romainthomas** [comment]
Could you provide the output of ``python -c "import lief;print(lief.__version__)"`` ?

**Comment by sborpo** [comment]
It's python3 deployment, the issue is that the library cannot be imported
```
$ python3 -c "import lief;print(lief.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: OS_ABI: element "GNU" already exists!
```

The egg dir:
```
$:/usr/local/lib/python3.7/dist-packages/lief-0.10.1-py3.7-linux-aarch64.egg$ ll
total 10808
drwxr-sr-x   4 root staff     4096 Apr 29 05:16 ./
drwxrwsrwx 400 root staff    20480 Apr 29 05:16 ../
drwxr-sr-x   3 root staff     4096 Apr 29 05:16 EGG-INFO/
-rwxr-xr-x   1 root staff 11026792 Apr 29 05:16 lief.cpython-37m-aarch64-linux-gnu.so*
-rw-r--r--   1 root staff      310 Apr 29 05:16 lief.py
drwxr-sr-x   2 root staff     4096 Apr 29 05:16 __pycache__/
```

**Comment by romainthomas** [comment]
Ok and if you do ``strings ./lief.cpython-37m-aarch64-linux-gnu.so|grep "0.10.1-"`` ?

**Comment by sborpo** [comment]
```
0.10.1-bfe5414
0.10.1
1.0.10118.3.0.49
1.0.10118.3.0.50
1.0.10118.3.0.55
1.3.6.1.4.1.311.10.10.1
```

**Comment by romainthomas** [comment]
Could you try with the master branch ?

**Comment by sborpo** [comment]
Had the same issue on the master branch, that's why i tried to go to previous release to check if they are more stable in that sense.
 Is there anything that should prevent this from being complied on ARM? some C extension or some unusual configuration?

**Comment by romainthomas** [comment]
The problem has been solved. I think you have conflict in your Python setup especially, try to **completely** uninstall LIEF and then reinstall LIEF from the master branch.

**Comment by sborpo** [comment]
There was some kind of fix in master?
I have removed Lief completely and deployed from master - lief 0.11.0-dev 
But still returns me the same error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: OS_ABI: element "GNU" already exists!
```
Is there any special dependency that might cause it?

**Comment by romainthomas** [comment]
Do you have the same issue if you build LIEF on Linux ?

**Comment by ejortega** [comment]
I'm having the same issue. Built latest from master on Ubuntu 16.04 and get the same error on "import lief"

**Comment by ejortega** [comment]
@sborpo try commenting out the following lines in LIEF/api/python/ELF/pyEnums.cpp

`// .value("GNU", OS_ABI::ELFOSABI_GNU)
// .value("C6000_ELFABI", OS_ABI::ELFOSABI_C6000_ELFABI)
// .value("ECOG1", ARCH::EM_ECOG1)
`

**Comment by ejortega** [comment]
@sborpo try commenting the follow lines from LIEF/api/python/ELF/pyEnums.cpp

`.value("GNU", OS_ABI::ELFOSABI_GNU)`
`.value("C6000_ELFABI", OS_ABI::ELFOSABI_C6000_ELFABI)`
`.value("ECOG1", ARCH::EM_ECOG1)`

**Comment by romainthomas** [comment]
How could I reproduce this issue ? 
I tried on a Rbpi but I can't trigger the error:

```bash
ubuntu@ubuntu:~/dev/LIEF$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
ubuntu@ubuntu:~/dev/LIEF$ python3 -c "import lief;print(lief.__version__)"
0.11.0-022ec6e
ubuntu@ubuntu:~/dev/LIEF$
```
