### ISSUE TITLE
Python v3.8 on Windows 10 x64?

### ISSUE THREAD

**Issue by evandrix** [lief-project/LIEF#404]
Noticed from the frontpage https://lief.quarkslab.com, that Python v3.8 is missing on Windows x64, but available on Linux and macOS. Any estimate on availability?

**Comment by romainthomas** [comment]
Yes Python 3.8 fails on Windows with the following error:
``Fatal Python error : _PyInterpreterState_Get(): no current thread state``
I'll check if the update of pybind11 fixes this issue

**Comment by romainthomas** [comment]
Still the same issue: https://ci.appveyor.com/project/Romain/lief/builds/32785573/job/1bkv8ac1luvbxvcu#L3850

```console
CUSTOMBUILD : Fatal Python error : _PyInterpreterState_Get(): no current thread state [C:\projects\lief\build\temp.win32-3.8\Release\tests\check-lief.vcxproj]
  Python runtime state: initialized
```
