### ISSUE TITLE
Unable to use within an Xcode project

### ISSUE THREAD

**Issue by greggjaskiewicz** [lief-project/LIEF#41]
In order to use in an Xcode project - developer expects library to be packaged up into a framework bundle. 
Especially something like the LIEF library, which comes with many header files and is written in c++. 
I have found it very difficult to do it by just dropping the header files and .a file into my project, had to give up - due to the include search paths issue. 

Couple things. 
There are many header files existing in this project with the same name.
#include <> vs #include "" when you use it inside your own project. 
Logging++ was missing

When I generated Xcode project using cmake, it included stripts trying to self-update using git. Not something you expect to happen in a building environment .

**Comment by romainthomas** [comment]
I added the documentation about XCode integration.

I don't provide a *framework bundle* because include hierarchy is not well supported in CMake: https://gitlab.kitware.com/cmake/cmake/issues/16739 

Don't hesitate to reopen the issue if you have questions.
