### ISSUE TITLE
Missing a section in a segment

### ISSUE THREAD

**Issue by vincentdupaquis** [lief-project/LIEF#412]
I am working with Cortex-M3 code and I have a case of a .elf file containing a section (.isr_vector) which never seems to appear in the sections list of the segment.
I have tested against the information given back by arm-none-eabi-readelf and readelf, and I could not find any solution to get the section back.
Doing some experiments, I figured-out that the first section if often omitted, which is quite weird to me.

To reproduce it, generate a standard "arm" code, having a .isr_vector section in front. A typical binary for a stm32 should do it. The elf file I use have nothing really specific.

The .isr_vector section is omitted from the corresponding segment, which it appears in readelf.

I've imported lief using pip3, and currently I am using 0.10.1-bfe5414 (from lief.__version__ after importing it). I am running ubuntu 18.04 LTS, and using python 3.6.

I can generate an elf file reproducing the issue, but I would have to work a bit on generating it, stripped from any confidential information.

For instance listing all segments (using readelf) from an bugging elffile gives me :
```
Elf file type is EXEC (Executable file)
Entry point 0x3c95
There are 2 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x010000 0x00000000 0x00000000 0x078bc 0x078bc RWE 0x10000
  LOAD           0x022000 0x20002000 0x20002000 0x00000 0x05130 RW  0x10000

 Section to Segment mapping:
  Segment Sections...
   00     .isr_vector .text .rodata .ARM.extab .ARM .init_array .fini_array .dataf 
   01     .data .bss ._user_heap_stack 
```

and listing the sections from each segment using lief gives :
```
.text .rodata .ARM.extab .ARM .preinit_array .init_array .fini_array .dataf
.data .bss ._user_heap_stack
```
In fact, all debug-information sections have been removed (which is good in my case), but also the .isr_vector section (which is unexpected and regretable, as it contains vital information (the vector's table)).

Would anyone have an idea on how to work-around this issue ?

Regards,
Vincent.

**Comment by vincentdupaquis** [comment]
Indeed, making some experiments, it appears that this section is not stripped if it starts at an address different from zero. Zero seems to be the starting value that is used as a criteria to determine it contains debug information, which is wrong on some arm targets !
I have a start of a solution there.
I would still recommend the bug to be investigated, as the behavior is wrong in this case.

**Comment by romainthomas** [comment]
Thanks @vincentdupaquis for reporting this issue. Would you mind to attach a binary so that I can reproduce the issue ?

**Comment by vincentdupaquis** [comment]
Romain,

Here are a problematic elf file, along with the python script to show the issue.

There are indeed 1 issue I've spotted :

    - the .isr_vectors section which disappears from the segment 0

the output of readelf is the following for this file :

```
readelf --segments mergestrpall.elf

Type de fichier ELF est EXEC (fichier exécutable)
Point d'entrée 0x3c95
Il y a 2 en-têtes de programme, débutant à l'adresse de décalage 52

En-têtes de programme :
  Type           Décalage Adr. vir.  Adr.phys.  T.Fich. T.Mém.  Fan Alignement
  LOAD           0x010000 0x00000000 0x00000000 0x078bc 0x078bc RWE 0x10000
  LOAD           0x020000 0x20000000 0x20000000 0x00000 0x07d30 RW  0x10000

 Correspondance section/segment :
  Sections de segment...
   00     .isr_vector .text .rodata .ARM.extab .ARM .init_array .fini_array .dataf
   01     .data .bss ._user_heap_stack
```
[mergestrpall.zip](https://github.com/lief-project/LIEF/files/4628410/mergestrpall.zip)


best regards,

Vincent.

**Comment by vincentdupaquis** [comment]
The output of the script is the following : 
```
Total sections
*  *
* .isr_vector *
* .text *
* .rodata *
* .ARM.extab *
* .ARM *
* .preinit_array *
* .init_array *
* .fini_array *
* .data *
* .dataf *
* .bss *
* ._user_heap_stack *
* .ARM.attributes *
* .comment *
* .to-protect *
* .shstrtab *
Total sections per segment
* .text *
* .rodata *
* .ARM.extab *
* .ARM *
* .preinit_array *
* .init_array *
* .fini_array *
* .dataf *
* .data *
* .bss *
* ._user_heap_stack *

```
In fact section .isr_vector disappears from the list of sections per segment, probably because of its base address (0). When I have it set at a different address ( > 0, it reappears).
Vincent.

**Comment by romainthomas** [comment]
Thanks, I'll check that this week.

**Comment by romainthomas** [comment]
This issue comes the fact that LIEF only considers section's virtual address to check if a section belongs to a segment:

https://github.com/lief-project/LIEF/blob/3cee05646c0537f6558b0d86989de036316ee37f/src/ELF/Parser.tcc#L904-L909

In the case of ``.isr_vector`` it has a section virtual address set to 0. I'll provide a fix that considers section offset when the virtual address is 0.
