### ISSUE TITLE
[Question] How to use LIEF to read the digest algorithm of multiple signatures in PE files?

### ISSUE THREAD

**Issue by Jeremy203** [lief-project/LIEF#414]
Great project! Thank you! But I have a question.
For some PE files containing 2 or more signatures, is there any way to read their digest algorithm?

Like this one.
![image](https://user-images.githubusercontent.com/65395833/82040038-7d72cf80-96d8-11ea-93e6-19c24cc6e60d.png)

**Comment by recvfrom** [comment]
I don't think LIEF currently parses any nested signatures or counter signatures, but it will extract the main Authenticode signature and the embedded certificates used for that, which makes it possible to do basic Authenticode signature verification.

**Comment by Jeremy203** [comment]
@recvfrom Thank you!
