### ISSUE TITLE
Python installation

### ISSUE THREAD

**Issue by pbrunet** [lief-project/LIEF#42]
Hi,

I forget to say it before but downloading the tgz file for python 2.7 (at least) and using `python setup.py install` do not work. I have to move `lief.so` by hand in the correct directory.

**Comment by romainthomas** [comment]
Oh yes I forgot this issue. Temporarily you can do a ``pip install PACKAGE.tar.gz``

**Comment by romainthomas** [comment]
@pbrunet Could you confirm that ``pip install linux_lief-0.7.0_py2.7.tar.gz`` works ?

**Comment by helen-simecek** [comment]
@romainthomas  I'm not OP, but I was having trouble installing and this worked perfectly, thanks!

**Comment by romainthomas** [comment]
BTW: It's mentioned in the doc: https://lief.quarkslab.com/doc/installation.html#python :)

**Comment by romainthomas** [comment]
@pbrunet  you can now install lief with ``python setup.py install``
cf. commit https://github.com/lief-project/LIEF/commit/968e93f95ccd2954ffc5d8b3ec47d453ebbaa305
