### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by evandrix** [lief-project/LIEF#425]
...while attempting to parse [9924a2120d12752655fd64ac85db6e0d27cb6907.bin.zip](https://github.com/lief-project/LIEF/files/4690921/9924a2120d12752655fd64ac85db6e0d27cb6907.bin.zip)

_sample report (to prove that it *should* parse)_

- https://manalyzer.org/report/671215ee4e00a8d71ffbfb97c8a50309
- http://pedump.me/671215ee4e00a8d71ffbfb97c8a50309

additionally, `pefile` parses it without error

**Comment by kohnakagawa** [comment]
This issue is caused by accessing the empty group icon entry.

<img width="774" alt="empty_group_icon" src="https://user-images.githubusercontent.com/5129526/83088221-1557bc80-a0ce-11ea-9bd2-b58bfbf4582d.PNG">

I confirmed that this issue can be resolved by #419.

**Comment by evandrix** [comment]
verified it works beautifully! thank you so much for your quick response & help ^_^
