### ISSUE TITLE
HEADER_CHARACTERISTICS::IMAGE_FILE_32BIT_MACHINE

### ISSUE THREAD

**Issue by evandrix** [lief-project/LIEF#427]
https://github.com/lief-project/LIEF/blob/a69f4b0867ef29b1eec9497661c4f1f41ff47bc8/src/PE/EnumToString.cpp#L94
`HEADER_CHARACTERISTICS::IMAGE_FILE_EXECUTABLE_IMAGE => EXECUTABLE_IMAGE`

https://github.com/lief-project/LIEF/blob/a69f4b0867ef29b1eec9497661c4f1f41ff47bc8/src/PE/EnumToString.cpp#L100
why is `HEADER_CHARACTERISTICS::IMAGE_FILE_32BIT_MACHINE => CHARA_32BIT_MACHINE`, not `32BIT_MACHINE`?

**Comment by romainthomas** [comment]
You can't start an enum with a number
