### ISSUE TITLE
Do not install json.hpp directly in `/usr/include`

### ISSUE THREAD

**Issue by yuyichao** [lief-project/LIEF#428]
**Describe the bug**
If json support is enabled, LIEF always install a json.hpp header without any prefix. This isn't very nice and can easily conflict with other headers on the system.

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

**Additional context**
A few more detailed points and what I think should be done.
1. Allow externally supplied json.hpp. If I read the code correctly, this isn't possible.
2. Use `#include <nlohmann/json.hpp>` since it is what the upstream recommends and would be necessary to support external json.hpp.
3. Since it is just a header, to minimize conflicts with other libraries due to one definition rule, it'll be nicer to namespace the bundled json.hpp include. The macro definition will still conflict when directly included and cross linking can still happen, but at least linking should not have any problems.

**Comment by romainthomas** [comment]
@yuyichao ``json.hpp`` is now packaged in its own directory ``include/LIEF/third-party/json.json``. Does it enough to fix this issue ?

**Comment by yuyichao** [comment]
Based on the change I believe this should be fixed.
