### ISSUE TITLE
Add a segment on a non pie binary make ld.so fail

### ISSUE THREAD

**Issue by 08A** [lief-project/LIEF#431]
**Describe the bug**
If you add a segment on a non pie elf file, ld.so crash
```
Inconsistency detected by ld.so: rtld.c: 1492: dl_main: Assertion `GL(dl_rtld_map).l_libname' failed!
```

**To Reproduce**
![2020-06-23-194305_427x281_scrot](https://user-images.githubusercontent.com/32521367/85436715-c5afc800-b589-11ea-813e-0d9eee006e7e.png)
1. Use this code in a script to add a segment and write the modified binary to the disk.
2. Exec

**Expected behavior**
No assertion error

**Environment (please complete the following information):**
 - System and Version : Archlinux
 - Target format ELF
 - LIEF commit version: 0.10.1-bfe5414

**Additional context**
![2020-06-23-194512_837x37_scrot](https://user-images.githubusercontent.com/32521367/85436935-19baac80-b58a-11ea-884d-de2a0592d289.png)
The modified binary: 
[test_64.zip](https://github.com/lief-project/LIEF/files/4821010/test_64.zip)

**Comment by romainthomas** [comment]
Should have been fixed with the new ELF builder.
