### ISSUE TITLE
Option to disable stripping

### ISSUE THREAD

**Issue by yuyichao** [lief-project/LIEF#436]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be a way to disable stripping of the python library.

**Describe the solution you'd like**
Stripping for release build by default is fine, but an option to disable it would be nice (iiuc cmake strip behavior is controlled by install vs install/strip)

**Describe alternatives you've considered**
Currently patching `cmake/strip.cmake` away in my build script.

**Additional context**

**Comment by romainthomas** [comment]
Done
