### ISSUE TITLE
Python lib compiled with build time RPATH

### ISSUE THREAD

**Issue by yuyichao** [lief-project/LIEF#437]
**Describe the bug**
Since the python lib was not installed via cmake `install`, it lacks the post processing done by cmake to switch between build target and install target. The main issue I can see is that by default the library installed has a RPATH pointing to the build directory.

Ideally the solution is to use cmake to do the install, thhough manually changing the RPATH according to cmake setting is also fine...

Currently for packaging I'm setting `CMAKE_SKIP_BUILD_RPATH` but that's usually bad for running local tests in the build directory.

**To Reproduce**
Install on linux, the python library will have RPATH points to build directory.

**Expected behavior**
No RPATH in the installed version by default.

**Environment (please complete the following information):**
 - System and Version : ArchLinux
 - Target format (PE, ELF, Mach-O)
 - LIEF commit version: 0.10.1-bfe5414 (0.10.1 tag)

**Additional context**

**Comment by yuyichao** [comment]
Why was this closed? I've just tested compilation and it seems that the build directory rpath is still in there.

**Comment by romainthomas** [comment]
Hello @yuyichao 

LIEF Python packages are ``rpath`` free. I don't get the point of this issue since your  rpath output depends on your configuration

**Comment by yuyichao** [comment]
> I don't get the point of this issue since your rpath output depends on your configuration

the configuration is the default one. If one run the default python setup.py and install the resulting file then the binary installed have rpath in it.

**Comment by yuyichao** [comment]
Actually come to think of it, the none default setting is building shared library. AFAICT when building shared library the python library is build with the build rpath that isn’t stripped during installation.

**Comment by romainthomas** [comment]
Well I still don't get your point but feel free to make a PR with your improvement

**Comment by yuyichao** [comment]
> building shared library

Confirmed and I've updated the issue title accordingly.

> since your rpath output depends on your configuration

Yes and no. It's true that if I added a linker flag of some sort specifying a rpath then I would expect the rpath to be in the final binary. I assume that's what you mean by "depends on configuration". However, if I didn't specify any of such options, the installed result must not have references in the rpath, to the build directory. However, the latter is what is happening.

> Well I still don't get your point

The point is that if you run

```
cmake . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=1
python setup.py build --build-temp=build
make -C build DESTDIR="${PWD}/pkg" install
python setup.py install --optimize=1 --root="${PWD}/pkg" --skip-build
```

and look at the python module installed under `pkg`, you'll see that it has rpath set that points to the build directory. This should no happen. (it'll also be better if setup.py can install other things and allow setting of the shared flags directly but that's less of an issue).

> feel free to make a PR with your improvement

As I explained in the original report, this is caused by not using cmake to do the installation. As such, this isn't a simple change and requires a somewhat major rework of the build system (at minimum, have python pass in the path to cmake and have cmake do the installation) and that's why I don't want to just go ahead and change things in a major way without first having you understand what this is an issue.

**Comment by romainthomas** [comment]
Ok so I have two questions:

1. Why linking the Python bindings dynamically with a shared version of LIEF?
2. Why not just using ``./setup.py install`` ?

**Comment by romainthomas** [comment]
Python bindings do not aim at being installed with CMake (but with Python setuptools) and as you can see in the nightly builds, they are rpath free ...

**Comment by yuyichao** [comment]
> Why linking the Python bindings dynamically with a shared version of LIEF?

Both are installed so why not make one use the other? To start, it saves memory and disk space (even though it's not a lot here, if everyone follows the same approach it'll be a bigger issue). Also, in general, building shared code into a shared library removes most of the issues when the library is loaded via different dependencies. (e.g. loading another c++ library using lief into the python process). Symbol conflicts could cause issues even if the two don't talk to each other.

> Why not just using `./setup.py install` ?

I am using `setup.py install`? And having to do that was exactly the issue as I mentioned in the original post.

If you mean why I'm running the build and install as two separate steps then it's simply because this is copied from the package build script. I'm 99% sure that removing the build step will have the same issue assuming that I can find the flags to set the build directory but since these exact commands are what I've tested I'm pasting things that I know works. Knowing that the difference between this and the absolute minimum version not really relevant

**Comment by yuyichao** [comment]
> Python bindings do not aim at being installed with CMake (but with Python setuptools)

This can still be done with cmake behind a flag (install python for example) and also for your current usage you don't seem to use the cmake install independently anyway when the python modules are being build anyway so just install them in cmake shouldn't make any difference.

> and as you can see in the nightly builds, they are rpath free ...

And they are statically linked, which is an issue, as explained above. They are mostly fine, and maybe even desired, for pip packages and maybe on windows, but not for making distribution packages, when proper and managed shared library installation is the norm.

**Comment by romainthomas** [comment]
Ok so if someone else look at this issue and has the same problem I'll consider to investigate a bit more what you describe.

**Comment by yuyichao** [comment]
> Ok so if someone else look at this issue and has the same problem I'll consider to investigate a bit more what you describe.

That's a very weird take.

1. This issue is closed, which makes it quite a bit harder to find.
2. You'll only get this kind of report from distribution package maintainers, which is of course much fewer than normal users, and only ones that looks carefully enough (the AUR packages have this problem but the maintainer didn't notice) and are ones that reports back upstream. (many distributions won't bother).
3. AFAICT, no other distribution currently offers the python binding package.

It'll be good to at least
1. Reopen this issue to acknowledge this is an issue / confirm the observation or
2. If it's unclear why building and linking as shared library is desired (or any other aspect of it, like creating distribution package) please let me know what about it isn't clear.

**Comment by yuyichao** [comment]
> and are ones that reports back upstream

Case in point, debian seems to have had a patch for https://github.com/lief-project/LIEF/issues/428 since 2018 (if you trust the date in their patch) but never ever reported it afaict.

**Comment by romainthomas** [comment]
The fact is that:

1. I'm the only maintainer who has to deal with CI/features/bug fixes/documentation/release/...
   I keep issues opened (even for a long time) as long as it seems relevant / not a *user case*
2. The python packages can be smoothly installed with a ``pip install lief``
3. The way your are building LIEF/Python packages is understandable but it sounds like *unique* (even if I understand your point now) 
4. When I asked if you can do a PR to address this issue the response was not really positive.
5. You will likely face to other versioning problems by dynamically linking the python bindings with the shared library.

Yes definitely the build system can be improved in a lot of ways. Feel free to contribute.

**Comment by yuyichao** [comment]
> The python packages can be smoothly installed with a pip install lief

No, that bypasses the package manager on the system. And even though I have a new enough version of the system libraries so this shouldn't be much of an issue, downloading binary that isn't built using the same version of system library as the one on the system. Also, as I said, you can't use it with a c++ library that uses lief.

> but it sounds like unique

It's the standard way all of the packages in a distribution are built. I have not invented any rules here and I've also given the reasoning behind the rules.

> When I asked if you can do a PR to address this issue the response was not really positive.

My response was conditioned on you understand why this is necessary and willing to accept a solution that involves somewhat major change of the build system. If you think that's fine then yes I could give it a try. You clearly have your way of distributing the pre-built binary (which is perfectly fine and I understand it's necessity given the platforms that doesn't have a working package manager) so I don't want to write something that makes sense for all the distribution packages but breaks how you want to build/distribute your packages on any of the many platforms you do so. That's why I only want to commit more time if I know that my solution can be accepted and the approach I may take is acceptable. So far I've not got a positive response on either.

> You will likely face to other versioning problems by dynamically linking the python bindings with the shared library.

What other problems are you talking about? I don't believe there is any when you use distribution packages.

* I assume you used the soname correctly which helps with linking to incompatible versions.
* On top of that, it's the package manager's job, in the case that the python and c++ libraries are in different packages, to make sure the versions are compatible. For Arch Linux, split package like this isn't the norm so the two libraries are in the same package and their version will strictly track each other.
* Or in another word, there should not be any more version problems than a c++ library/application that uses libLIEF. The python module should just be a special c++ library that uses libLIEF.
