### ISSUE TITLE
Consider migrating CI to azure pipelines

### ISSUE THREAD

**Issue by benjamb** [lief-project/LIEF#454]
**Is your feature request related to a problem? Please describe.**

AppVeyor doesn't enable concurrency by default, and charges $50 per concurrent build for the privilege.
Current LIEF builds take ~4 hours, since jobs are forced to run sequentially.

**Describe the solution you'd like**

As far as https://github.com/marketplace/azure-pipelines describes, it allows 10 free parallel jobs for open source projects. This would considerably reduce pipeline times.

**Comment by romainthomas** [comment]
Thanks for the advice. I will try this CI for windows. Do you know if you have cache support like in Travis ?

**Comment by benjamb** [comment]
As far as I'm aware, yes.

**Comment by romainthomas** [comment]
@benjamb if you want to check, I started to boostrap the configuration on the ``ci/azure`` branch

**Comment by romainthomas** [comment]
We improved CI so that it now takes ~15/20min for each build on Windows
