### ISSUE TITLE
BUG elf_binary_save_header saving header's entrypoint 

### ISSUE THREAD

**Issue by pabx06** [lief-project/LIEF#457]
on linux ubuntu 18

test.c
```
#include <LIEF/LIEF.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, const char** argv) {
	if(argc!=2){
		return 0;
	}

  Elf_Binary_t* elf_binary  =  elf_parse(argv[1]);
  elf_binary->header.entrypoint = 0x47ffc140UL ;
  int saved = elf_binary_save_header(elf_binary);
  printf("Saved =%d\n",saved);
}
```
then
```
$clang++ test.c -o test -lLIEF && ./test tmp.elf
 saved =1

$readelf -a tmp.elf|grep Entry
  Entry point address:               0x0
```

i was expecting 0x47ffc140 
file didnt get updated nor mod time:

![image](https://user-images.githubusercontent.com/4013370/91348271-d1b34280-e7e3-11ea-8a90-4ca1b5b9d875.png)

**Comment by pabx06** [comment]
also: section's flag of elf file are of type uint32_t 
![image](https://user-images.githubusercontent.com/4013370/91348607-53a36b80-e7e4-11ea-83c7-128d305a6cdb.png)

while i was expecting an **enum** type to be able to use this api:
```
LIEF_API const char* ELF_SECTION_TYPES_to_string(enum LIEF_ELF_ELF_SECTION_TYPES e);
```

**Comment by romainthomas** [comment]
Yes the C API is very limited and not really updated. PRs for this fix are welcomed

**Comment by pabx06** [comment]
is the cpp API more complete ?

**Comment by romainthomas** [comment]
Yes
