### ISSUE TITLE
Failure to parse files wchars on windows

### ISSUE THREAD

**Issue by MennaEssa** [lief-project/LIEF#460]
**Describe the bug**
LIEF is not supporting wstrings which are essential for dealing with paths on windows, when I try to parse a file with Arabic characters it will fail as NTFS uses UTF-16 encoding so if i don't use wchars the path will be decoded incorrectly and thus LIEF throws bad_file exception.
I went a head and overloaded the components that parse PE files with wstrings arguments and it works fine now , but It needs to be generalized across the project to support all types

**To Reproduce**
just something as simple as this with a path that contains Arabic letters , if i don't use wmain and wstring the path provided in the args would not be decoded correctly.
```
int wmain( int argc , wchar_t* argv[]) {
	wstring str = argv[1];
	auto p_ = LIEF::PE::Parser::parse(str);
	LIEF::PE::Signature signature = p_->signature();
	return 1;
}
```

**Expected behavior**
handle different chars encoding 
**Environment (please complete the following information):**
 - windows 10
- PE
- LIEF commit version: master branch

**Additional context**
I may be missing something obvious here but I couldn't find any other workarounds other than overloading the functions; so your advice would be much appreciated to handle this issue properly.

**Comment by romainthomas** [comment]
I close this issue unless there is a PR
