### ISSUE TITLE
remove all relocations not successful

### ISSUE THREAD

**Issue by lpxnvk** [lief-project/LIEF#464]
**Describe the bug**
remove all relocations (inclucde add relocation) not successful

**To Reproduce**
- remove
```CPP
    std::unique_ptr<LIEF::PE::Binary> pe_binary =
        LIEF::PE::Parser::parse("test.dll");
    pe_binary->remove_all_relocations();
   auto builder = LIEF::PE::Builder(pe_binary.get());
    builder.build();

    builder.write("Ttest.lief.dll");
```

- add
```CPP
    std::unique_ptr<LIEF::PE::Binary> pe_binary =
        LIEF::PE::Parser::parse("test.dll");
    for (auto& relocation : relocations) {
        vecBackup.push_back(relocation);
    }
    for (auto& relocation : vecBackup) {
        pe_binary->add_relocation(relocation);
    }
   auto builder = LIEF::PE::Builder(pe_binary.get());
    builder.build();

    builder.write("Ttest.lief.dll");
```

use [die](http://ntinfo.biz/index.html) to check reloctions
![image](https://user-images.githubusercontent.com/61929809/92709198-4b713180-f389-11ea-9e86-008d9e24d315.png)

**Expected behavior**
use add and remove will be successful

**Environment (please complete the following information):**
 - widnows10
 - pe
 - the latest release c++ version

**Comment by stonedreamforest** [comment]
Ok i have solved this problem, we should use `build_relocations`,And` build` must be used behind it. like this:
```CPP 
	builder.build_relocations();
	builder.build();
```
Hope this can help those in need

**Comment by lpxnvk** [comment]
Ok i have solved this problem, we should use build_relocations,And build must be used behind it. like this:
```CPP
	builder.build_relocations();
	builder.build();
```
Hope this can help those in need
