### ISSUE TITLE
Rebuilding ELF breaks .rel.dyn and causes crash at runtime

### ISSUE THREAD

**Issue by google-mirror** [lief-project/LIEF#465]
**Describe the bug**
You can see what goes wrong wrong with IDA tools.
Original:
![libart](https://user-images.githubusercontent.com/70927995/93432905-bc1fcd00-f8f8-11ea-87bd-342cadedb475.png)

Rebuilt:
![libart_p](https://user-images.githubusercontent.com/70927995/93432969-ce017000-f8f8-11ea-85de-2dd3ece6505d.png)

**Code**
```
static void rebuild_elf_test_case() {
	// e.g. _ZNK3art8verifier10LongHiType4DumpEv -> _ZNK3art8verifier10LongLoType4
	std::unique_ptr<Binary> &&elf = ELF::Parser::parse("libart.so");
	for (Symbol &symbol : elf->symbols()) {
		const std::string &name = symbol.name();
		if (name.find("_ZNK3art8verifier10LongHiType4DumpEv") != std::string::npos) {
			symbol.name("_ZNK3art8verifier10LongLoType4");
		}
	}
	elf->write("libart_p.so");
}
```

**Environment (please complete the following information):**
LIEF-0.11.0-win64

**Additional context**
[case.zip](https://github.com/lief-project/LIEF/files/5237019/case.zip)

**Comment by romainthomas** [comment]
Android ``libart.so`` uses packed relocations (see #111) which are not currently supported by LIEF. Feel free to take a look
at the branch [android-packed-relocations](https://github.com/lief-project/LIEF/tree/android-packed-relocations).

If you absolutely need this feature you can send me a DM.
