### ISSUE TITLE
[Question]How to insert the LoadCommand at somewhere ?

### ISSUE THREAD

**Issue by rockbean** [lief-project/LIEF#468]
**Describe the bug**
I'm trying the "add(self: lief.MachO.Binary, load_command: LIEF::MachO::LoadCommand, index: int)" to insert LoadCommand at some specific index, but I got the "symbol not found" failure which should be found in the original LoadCommands.

**To Reproduce**
My target DBTest:
```
    char *db = "/Users/x/libs/test.db";
    sqlite3 *pDB = NULL;
    sqlite3_initialize();
    int rc = sqlite3_open_v2(db, &pDB, SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, NULL );
    if (rc != SQLITE_OK) {
        sqlite3_close(pDB);
        NSLog(@"%s %d >>> fail to open db", __func__, __LINE__);
        exit(-1);
    } else {
        NSLog(@"%s %d >>> create db", __func__, __LINE__);
    }
    sqlite3_close(pDB);
    sqlite3_shutdown();
```

My inject /Users/x/libs/libtest.dylib:
```
__attribute__((constructor)) void pre_load(void)
{
    NSLog(@"Hello\n");
}
```

My LIEF test:
```
    std::unique_ptr<LIEF::MachO::FatBinary> binaries{LIEF::MachO::Parser::parse("/Users/x/test/DBTest")};
    LIEF::MachO::Binary& binary = binaries->back();
    binary.remove_signature();
    binary.add(LIEF::MachO::DylibCommand::load_dylib("/Users/x/libs/libtest.dylib", 16);
    binary.write("/Users/x/test/DBTest");
```

After the LIEF test, the libtest.dylib has been injected before the libsqlite3.dylib as I wished:
```
$ otool -L MyFoo
DBTest:
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1560.12.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1560.12.0)
	/Users/x/libs/libtest.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libsqlite3.dylib (compatibility version 9.0.0, current version 274.20.0)
```

But I got these errors:
```
$ /Users/x/test/DBTest
Hello
dyld: lazy symbol binding failed: Symbol not found: _sqlite3_initialize
  Referenced from: /Users/x/test/DBTest
  Expected in: /Users/x/libs/libtest.dylib

dyld: Symbol not found: _sqlite3_initialize
  Referenced from: /Users/x/test/DBTest
  Expected in: /Users/x/libs/libtest.dylib

Abort trap: 6
```
It seems the offset of these symbols haven't been updated which is still use the old one leading to the wrong place.

**Expected behavior**
I thought the "add(LoadCommand, Index)" could do everything but it seems not. Could you tell me how to make the things right ?

**Environment (please complete the following information):**
 - System and Version : MacOS 10.14.5
 - Target format : Mach-O
 - LIEF commit version:  0.10.1 release

**Additional context**
None

**Comment by romainthomas** [comment]
Adding a LoadCommand at a **specific index** can be complicated to achieved since you may break PIE offsets in the ``.text``
segment.
As far I know, it does not exist a **generic** technique without using a disassembler and patching the relative offsets in the assembly code.

Feel free to send me a DM on [gitter](https://gitter.im/lief-project) if my explanations are not clear.

**Comment by rockbean** [comment]
Thanks for your answer. I understand it needs some special work for the offset problem depends on the specific file.
