### ISSUE TITLE
Possibility of allowing linking  with shared runtime (MD/MDd VisualStudio)

### ISSUE THREAD

**Issue by rafael-santiago** [lief-project/LIEF#478]
Hi there!

I need to use lib LIEF on a project that requires shared linking (CRT). I noticed the impossibility of doing this kind of linking when I got the following linking error from ``VisualStudio 2019``:

```
LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in file.obj
```
What about besides the static ``lief.lib`` artifact in ``SDK`` also include a static one with shared runtime, a stuff like ``liefmd.lib`` (at least on Windows)? 

Is there some technical issue or license issue for not including a shared version of LIEF in ``SDK`` packages?

Thanks in advance!

**Comment by romainthomas** [comment]
Hello @rafael-santiago 
There is not *technical or license issues* it just that the CI are not configured for that. Feel free to submit a PR if you have the solution.

**Comment by romainthomas** [comment]
Fixed with https://github.com/lief-project/LIEF/pull/483
