### ISSUE TITLE
Inconsistent number of functions when Parsering MachO binaries?

### ISSUE THREAD

**Issue by puffyCid** [lief-project/LIEF#479]
Hello,

I am encountering a small issue when attempting to parse MachO binaries twice.
When I parse the binary the first time it returns the correct number of functions.
```
>>> import lief
>>> bin1 = lief.MachO.parse("/bin/ls")
>>> len(bin1[0].exported_functions)
1
>>> len(bin1[0].functions)
21
>>> len(bin1[0].symbols)
85
```

But when i try parsing it a second time it returns one less function
```
>>> bin2 = lief.MachO.parse("/bin/ls")
>>> len(bin2[0].exported_functions)
0
>>> len(bin2[0].functions)
20
>>> len(bin2[0].symbols)
85
```

I've tried searching the docs and examples for possible solutions but i did not find any.
Am i doing something wrong?
I tested with Python3 and lief version 0.10.1-bfe5414

I am also encountering the same issue with C++ and the lief nightly version
let me know if any more information is needed, thanks.

**Comment by romainthomas** [comment]
Thanks for catching this problem :)
