### ISSUE TITLE
Add a new section in a ELF Files

### ISSUE THREAD

**Issue by sungmirr** [lief-project/LIEF#48]
Many thanks for your useful project. I have a question.

I am testing 'add_new_section' example(c++) included in LIEF0.7.0, and it works well for ELF AMD 64bit Binary. But not for ELF AMD 32bit Binary or ELF ARM 32/64bit Binary.

When I add a section to the executable file(ELF ARM 32bit) with 'add_new_section' and then run it, the following error message occurs.
> CANNOT LINK EXECUTABLE: empty/missing DT_HASH in "./addsection_call_arm_a" (built with —hash-style=gnu?)

**I want to add a new section to the 'ELF ARM 32bit Binary' and i hope it operates normally.**
I think LIEF::ELF::BINARY::add_section() seems to have a problem, please check it.

Thank you.

**Comment by romainthomas** [comment]
Hi @sungmirr. The executable is a *pie* one ?

**Comment by sungmirr** [comment]
Thank you for your reply.
No, It just compiled without PIE option.

Additionally, 'addsection_call_arm' is simple program that just prints to the console.
(./elf_add_section  addsection_call_arm  addsection_call_arm_a)

**Comment by romainthomas** [comment]
OK thanks for the precisions, I will look at it. An alternative to add code in an executable is to use the [add_segment](https://lief.quarkslab.com/doc/api/python/elf.html#lief.ELF.Binary.add_segment) method which is more reliable than adding a section. You have an example here: [tests/elf/add_segment.py](https://github.com/lief-project/LIEF/blob/master/tests/elf/add_segment.py#L35-L40)

**Comment by sungmirr** [comment]
I'll try it the way you tell me. Thank you.

**Comment by romainthomas** [comment]
I tested this script on an ELF32 ARM binary and it works well (the ``foo` executable still run):

```python
import lief
target = lief.parse("simple_1")
section           = lief.ELF.Section()
section.name      = "test"
section.type      = lief.ELF.SECTION_TYPES.PROGBITS
section.content   = [1] * 512
section.alignment = 8
section           = target.add_section(section, True)
target.write("foo")
```

Could you detail how you add the section ?

**Comment by sungmirr** [comment]
Sorry for the confirmation was delayed.

LIEF0.7.0 is tested by c++.  
elf_add_section.cpp
```c++
std::unique_ptr<Binary> binary{Parser::parse(argv[1])};
Section new_section;
std::vector<uint8_t> d(4096, 0);
new_section.name("test");
new_section.content(d);

binary->add_section(new_section, true);
binary->write(argv[2]);
```

addsection_call_arm is simple program compiled by ndk-build, and addsection_call_arm_a is section added file.
![arm64_2](https://user-images.githubusercontent.com/1487794/28254649-7eff0486-6ae9-11e7-98ff-1d8795374118.png)


and execute it at Android device.
![arm64](https://user-images.githubusercontent.com/1487794/28254832-805957f8-6aeb-11e7-98ca-e87796b3c26b.png)


and another test case, LIEF0.6.X   
```python
import lief
target = lief.parse("simple_1")
section           = lief.ELF.Section()
section.name      = "test"
section.type      = lief.ELF.SECTION_TYPES.PROGBITS
section.content   = [1] * 512
#section.size       = 64  
#section.entry_size = 0
section.alignment = 8
section           = target.add_section(section, True)
target.write("foo")
```
simple_1 is a linux x86 binary.
![x86](https://user-images.githubusercontent.com/1487794/28254837-88d0d064-6aeb-11e7-84bd-7aca60a27b67.png)

Tested on Ubuntu 16.04.1 Desktop(64bit), g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

The way you said before adding a segment is done well.  
Please let me know if you have the another information you need.

**Comment by romainthomas** [comment]
Thanks for the details, I will investigate the problem.

**Comment by garasmc** [comment]
@romainthomas 
hello, I tested this script on an ELF32 ARM binary. 
> import lief
target = lief.parse("simple_1")
section           = lief.ELF.Section()
section.name      = "test"
section.type      = lief.ELF.SECTION_TYPES.PROGBITS
section.content   = [1] * 512
section.alignment = 8
section           = target.add_section(section, True)
target.write("foo")

But returned an error. 
> You insert data in the section .shstrtab whose the size it bigger (272 > 268). It may lead to overaly

Then i am modifying the script
> section.name      = ""

The script works well, but 'foo' can not be executed.

> shell@hammerhead:/data/local/tmp $ ./foo
Killed

Can you help me to see what is the problem? Thanks

The test file is as follows
[simple.zip](https://github.com/lief-project/LIEF/files/1164979/simple.zip)

**Comment by romainthomas** [comment]
Which version of Android ?

**Comment by garasmc** [comment]
Android 4.4.4
Ndk r10e

**Comment by garasmc** [comment]
hi,I did some more tests

I tested again by C++.
[https://github.com/lief-project/LIEF/blob/master/examples/cpp/elf_add_section.cpp](url)

The test object is as follows
[https://github.com/lief-project/LIEF/blob/master/tests/elf/hello_lief.bin](url)

> ./HelloLIEF ../hello_lief.bin ../hello_lief_add_section.bin
ELF Section rename
You insert data in the section .shstrtab whose the size it bigger (109 > 105). It may lead to overaly

The result is the same can not run
> ./hello_lief_add_section.bin
segmentation fault  ./hello_lief_add_section.bin

help me, plz
Thanks

**Comment by romainthomas** [comment]
Actually ``add_section`` only works on **EXEC** binaries (i.e not library and not pie executables).
``hello_lief.bin`` is a PIE binary so it's *normal* that the final binary crash

If you want to insert code in a shared library you can look at: [``insert_content``](https://lief.quarkslab.com/doc/api/python/elf.html#lief.ELF.Binary.insert_content)

**Comment by garasmc** [comment]
Thank you for your reply.Then I will continue to study.
Thank you very much for sharing the great project!

**Comment by romainthomas** [comment]
For the issue:

> shell@hammerhead:/data/local/tmp $ ./foo
> Killed

It may due to the warning in https://lief.quarkslab.com/doc/api/python/elf.html#lief.ELF.Segment.virtual_address

**Comment by romainthomas** [comment]
What you mean by *standard* ?

**Comment by dzonerzy** [comment]
I mean a normal C file (C99) , how can I compile it like hello_lief.bin , I mean a static shared object without relocations.
