### ISSUE TITLE
Cannot build lief on Ubuntu 16.04

### ISSUE THREAD

**Issue by dmjh** [lief-project/LIEF#481]
**Describe the bug**
When built lief package on Ubuntu 16.04 leads to a error

**To Reproduce**
python3.6 -m venv venv
source venv/bin/activate
git clone https://github.com/lief-project/LIEF.git
cd LIEF
python setup.py install

Build error:
![image](https://user-images.githubusercontent.com/43782775/97786889-eb14a880-1bf1-11eb-8b13-493cb11c83fb.png)

**Expected behavior**
lief should have been installed

**Environment (please complete the following information):**
 - System and Version : Ubuntu 16.04 x86_64
 - Target format: ELF
 - Python version: python 3.6.3
 - cmake version: 3.5.1
 - LIEF commit version: 0.11.0 (When I cloned it, it was displayed as version 0.11.0.)

**Additional context**
It builds successfully on Ubuntu 18.04 and 20.04, but in 16.04 it fails. And I tried -DPYTHON_VERSION=3.6 referring to another issue but it doesn't work for me.

Thanks!

**Comment by romainthomas** [comment]
Ack the PR #475 makes more sense now.

**Comment by romainthomas** [comment]
I keep this issue open but I'll soon raise the C++ standard.
