### ISSUE TITLE
Issue with patch_address

### ISSUE THREAD

**Issue by apphackuno** [lief-project/LIEF#489]
I am trying to inject hello world into /bin/date and then hijack one of the .init_array pointers.

This is the code for my hello-world -

#include "arch/x86_64/syscall.c"
#define stdout 1

int myHello(int argc, char *argv[]) {
asm("push %rax");
asm("push %rcx");
asm("push %rdx");
asm("push %rsi");
asm("push %rdi");
const char msg[] = "Hello World!\n";
_write(stdout, msg, sizeof(msg));
asm("pop %rax");
asm("pop %rcx");
asm("pop %rdx");
asm("pop %rsi");
asm("pop %rdi");
asm("push $0x4023b0");
return 0;
}

The last statement pushed the address of one of the .init_array pointer.

Below is the code for my code injection:
import lief

myDate = lief.parse("/bin/date")
hello = lief.parse("hello_date")

hello_symbol = hello.get_symbol("myHello")
new_segment = myDate.add(hello.segment_from_virtual_address(hello_symbol.value))
new_entry = new_segment.virtual_address + hello_symbol.value
print new_entry
import struct
arr = struct.pack('<L', new_entry)
arr = struct.unpack('<BBH', arr)
arr = list(arr)
while len(arr) < 8:
arr.append(0)

const_section = myDate.get_section(".init_array")
print const_section.virtual_address, const_section.content
myDate.patch_address(const_section.virtual_address, [i for i in arr])
print const_section.virtual_address, const_section.content
myDate.write("myDate")

myDate2 = lief.parse("myDate")
const_section2 = myDate2.get_section(".init_array")
print const_section2.content

Output:

======== RESTART: /home/binary/Desktop/ABA/Lec7/SBI/Lab/hookConst.py ========
8458969
6356496 [176L, 35L, 64L, 0L, 0L, 0L, 0L, 0L]
6356496 [217L, 18L, 129L, 0L, 0L, 0L, 0L, 0L]
[176L, 35L, 64L, 0L, 0L, 0L, 0L, 0L]

Content is added to replace the original pointer with the address of the entry point. But after writing the binary, this change did not persist.

The problem seems to be from the patch_address function.

**Comment by romainthomas** [comment]
Please open an issue following the template
