### ISSUE TITLE
incorrect content size in new section

### ISSUE THREAD

**Issue by avkhadeev** [lief-project/LIEF#492]
When I tried to add new section using  [example](https://github.com/lief-project/LIEF/blob/master/examples/cpp/elf_add_section.cpp), I noticed that size of a new section is always set to 0.  The bug is probably here: 
https://github.com/lief-project/LIEF/blob/8872b85fc78a4bd6422c430c4b76567a1c34989d/src/ELF/Section.cpp#L330-L331

I think swapping the lines 330 and 331 is enough to fix

**Comment by romainthomas** [comment]
Nice catch!
