### ISSUE TITLE
Segmentation fault (0.10.1)

### ISSUE THREAD

**Issue by ajosh0504** [lief-project/LIEF#495]
**Describe the bug**
Segmentation fault in 0.10.1 while getting resources from PE binary

**Expected behavior**
Expected output was a json of the resources manager 

**Environment (please complete the following information):**
 - System and Version : Ubuntu 18.04
 - Target format: PE

**Additional context**
I am running a service which extracts components from PE binaries like resources, imports, sections etc. using LIEF. I was running version 0.10.1. One particular binary caused my service to crash with a segmentation fault while obtaining the resources using `resources = json.loads(lief.to_json(lief_binary.resources_manager))`. I then changed to LIEF version 0.9.0 which gives me an empty resources dictionary, no segmentation fault. What's also weird is that the `has_resources` check for version 0.10.1 returns `True` whereas 0.9.0 returns `False`.

**Comment by romainthomas** [comment]
Could you provide the underlying binary ?

**Comment by ajosh0504** [comment]
MALWARE INCOMING! Here:
[13a89a8e4d60e018ac0bd6d39a03d3c059ed6cf123c1a275d63aef3ff3b892bb.txt](https://github.com/lief-project/LIEF/files/5585373/13a89a8e4d60e018ac0bd6d39a03d3c059ed6cf123c1a275d63aef3ff3b892bb.txt)

**Comment by romainthomas** [comment]
Thanks!

**Comment by romainthomas** [comment]
Already fixed on the upsrteam version
