### ISSUE TITLE
Malformed resources json (0.9.0)

### ISSUE THREAD

**Issue by ajosh0504** [lief-project/LIEF#496]
**Describe the bug**
`json.loads(lief.to_json(binary.resources_manager))` results in malformed resources.

**To Reproduce**
Run `json.loads(lief.to_json(binary.resources_manager))` on the binary provided using lief==0.9.0.

**Expected behavior**
The resources for the binary should look as follows (acc. to lief==0.10.1- note the langcode_items):
`{
icons: [
{
bit_count: 32,
color_count: 0,
height: 48,
id: 1,
lang: "NEUTRAL",
pixels: 93471027,
planes: 1,
reserved: 0,
sublang: "DEFAULT",
width: 48
}
],
version: {
fixed_file_info: {
file_date_LS: 0,
file_date_MS: 0,
file_flags: 0,
file_flags_mask: 63,
file_os: "WINDOWS32",
file_subtype: "UNKNOWN",
file_type: "APP",
file_version_LS: 1,
file_version_MS: 65536,
product_version_LS: 1,
product_version_MS: 65536,
signature: 4277077181,
struct_version: 65536
},
key: "VS_VERSION_INFO",
string_file_info: {
key: "StringFileInfo",
langcode_items: [
{
items: {
CompanyName: "",
FileDescription: "DriveExplorer MFC Application",
FileVersion: "1, 0, 0, 1",
InternalName: "DriveExplorer",
LegalCopyright: "Copyright (C) 2002",
LegalTrademarks: "",
OriginalFilename: "DriveExplorer.EXE",
ProductName: "DriveExplorer Application",
ProductVersion: "1, 0, 0, 1"
},
key: "040904B0",
type: 1
}
],
type: 1
},
type: 0,
var_file_info: {
key: "VarFileInfo",
translations: [
78644233
],
type: 1
}
}
}`

**Environment (please complete the following information):**
 - System and Version : Ubuntu 18.04, macOS 10.15
 - Target format: PE

**Additional context**
I am trying to use lief.to_json(binary.resources_manager) to get resources for PE binaries but I'm seeing some malformed json in the output (look at langcode items):
`{'icons': [{'bit_count': 32, 'color_count': 0, 'height': 48, 'id': 1, 'lang': 'NEUTRAL', 'pixels': 93471027, 'planes': 1, 'reserved': 0, 'sublang': 'DEFAULT', 'width': 48}], 'version': {'fixed_file_info': {'file_date_LS': 0, 'file_date_MS': 0, 'file_flags': 0, 'file_flags_mask': 63, 'file_os': 'WINDOWS32', 'file_subtype': 'UNKNOWN', 'file_type': 'APP', 'file_version_LS': 1, 'file_version_MS': 65536, 'product_version_LS': 1, 'product_version_MS': 65536, 'signature': 4277077181, 'struct_version': 65536}, 'key': 'VS_VERSION_INFO', 'string_file_info': {'key': 'StringFileInfo', 'langcode_items': [{'items': {'0, 0, 1': '<\x0e\x01InternalName', 'CompanyName': 'd\x1e\x01FileDescription', 'galTrademarks': 'L\x12\x01OriginalFilename', 'veExplorer': 'J\x13\x01LegalCopyright', 'veExplorer Application': ':\x0b\x01ProductVersion', 'veExplorer MFC Application': '6\x0b\x01FileVersion', 'veExplorer.EXE': 'T\x1a\x01ProductName', 'yright (C) 2002': '('}, 'key': '040904B0', 'type': 1}], 'type': 1}, 'type': 0}}`
I noticed that 0.10.1 doesn't have this issue. I'm using 0.9.0 to avoid segmentation fault errors is 0.10.1 (documented those in a separate issue).

**Comment by ajosh0504** [comment]
Binary to test (MALICIOUS):
[b7d18176c45eb4c93cf45452e290eadf9b246d092a94e1d3b2a578f55039fd8c.txt](https://github.com/lief-project/LIEF/files/5585415/b7d18176c45eb4c93cf45452e290eadf9b246d092a94e1d3b2a578f55039fd8c.txt)

**Comment by romainthomas** [comment]
Already fixed on the upsrteam version
