### ISSUE TITLE
code_signature question

### ISSUE THREAD

**Issue by Sunr1seSun** [lief-project/LIEF#502]
**Describe the bug**
When I use lief.MachO.Binary.code_signature, find something different from my expectations.

**To Reproduce**
There are two ways to get code_signature.data_offset from a macho, in my example, one is `fat_bin.at(0).code_signature.data_offset` and the other is `fat_bin.at(0).get(lief.MachO.LOAD_COMMAND_TYPES.CODE_SIGNATURE).data_offset`.They should be the same, but lief  gave me two different results.

**Expected behavior**
In my opinion, `fat_bin.at(0).code_signature.data_offset` give me an unexpected result.

**Environment (please complete the following information):**
 - OS X
 - Macho
 - LIEF commit version: `0.10.1-bfe5414`

**Comment by romainthomas** [comment]
Do you have multiple signature commands ?

**Comment by sunrise1996** [comment]
In one binary, there is only one signature command. the problem is that the code_signature. data_offset give me the information of command LC_DYLIB_CODE_SIGN_DRS. Shouldn't it be LC_CODE_SIGNATURE?
```
Load command 31
      cmd LC_DYLIB_CODE_SIGN_DRS
  cmdsize 16
  dataoff 2261168
 datasize 152

In [4]: fat_bin.at(1).code_signature.data_offset
Out[4]: 2261168

In [6]: fat_bin.at(1).code_signature.command
Out[6]: LOAD_COMMAND_TYPES.DYLIB_CODE_SIGN_DRS
```
