### ISSUE TITLE
Send logs to stderr

### ISSUE THREAD

**Issue by jcrussell** [lief-project/LIEF#503]
**Is your feature request related to a problem? Please describe.**

Logging for LIEF goes to stdout which can mix with the output from other tools (e.g. https://github.com/fireeye/capa/issues/368).

This appears to be the spot (thanks @williballenthin):

https://github.com/lief-project/LIEF/blob/1364f22c78475caaa2d6b7cbe01f74e87cf44c34/src/logging.cpp#L37

**Describe the solution you'd like**

Provide an option to log to stderr or log there by default.

**Describe alternatives you've considered**

Disabling logging works but maybe there is useful output that is being discarded?

**Additional context**

This is using the Python library.

**Comment by romainthomas** [comment]
@jcrussell @williballenthin what about logging WARN / ERR and CRITICAL to stderr and all the other to stdout ? 

As @jcrussell  mentioned, you can disable logging or change its level (https://github.com/fireeye/capa/issues/368#issuecomment-733804833)

**Comment by williballenthin** [comment]
a single data point, my philosophy when building cli tool is to write the intended output/report/results to stdout, while informational data such as progress, warnings, and other meta-results to stderr. this way, the tool can emit structured information, like json, to stdout to be processed by subsequent tools/steps, while the data in stderr gives context, etc. If libraries write to stdout, then they may break the structure of the report.

i agree that disabling the logging will fix our issue and capa, and this is what we'll do in the short term. longer term, just wanted to provide the above explanation for your consideration.

**Comment by romainthomas** [comment]
Thanks @williballenthin for the explanations, it perfectly makes sense.
