### ISSUE TITLE
lief PE.parse gives pylief.bad_file exception?

### ISSUE THREAD

**Issue by LusKrew** [lief-project/LIEF#504]
When i use  LIEF to parse a PE file, giving the PE.parse its representing bytes as input, the problem is, if i dont give name argument as a empty string, it gives me pylief bad_file exception ?!

    binary = lief.PE.parse(self.bytez) : this doesnt work

    binary = lief.PE.parse(self.bytez , name="") : this works

so the second one works, but why? what is the name argument anyways?!

lief version is 0.9.0 (cant upgrade, using a project that requires this)
system is ubuntu 20.0.4

**Comment by LusKrew** [comment]
If the LIEF is the latest version, either way i get "lief.bad_file" exception, adding name="" doesnt help anymore.

the file is correct as well, i basically read a exe file using : 

```
    with open(file ,'rb') as infile:
        bytez = infile.read() 
```

**Comment by romainthomas** [comment]
Either:
```python
with open(file ,'rb') as infile:
    lief.PE.parse(infile)

# or 

with open(file ,'rb') as infile:
    lief.PE.parse(list(infile.read()))
```
