### ISSUE TITLE
pip install failed on macos Big Sur

### ISSUE THREAD

**Issue by sleicasper** [lief-project/LIEF#505]
**Describe the bug**
    CMake Error at CMakeLists.txt:541 (add_subdirectory):
      add_subdirectory given source
      "/private/var/folders/ms/gzg0nrws61b33cd2bhjzbsp40000gn/T/pip-install-0y1p9l13/lief/package"
      which is not an existing directory.

**To Reproduce**
pip3 install lief

**Expected behavior**

**Environment (please complete the following information):**
 - System and Version : MacOS Big Sur
 - Python version: 3.9

**Comment by romainthomas** [comment]
Fixed on the nightly
