### ISSUE TITLE
CMakeLists.txt:541 add_subdirectory error

### ISSUE THREAD

**Issue by bwhitn** [lief-project/LIEF#508]
I am running into the exact same issue as #373 on Mac OS Big Sur running python 3.9 and installing the default LIEF 10.1.

CMake Error at CMakeLists.txt:541 (add_subdirectory):
      add_subdirectory given source
      "/private/var/folders/7_/rjpt_gqx3h51gp_fc_vz3h640000gn/T/pip-install-tjb9twbz/lief_04999daea269432a801c06474d9e424d/package"
      which is not an existing directory.

**Comment by romainthomas** [comment]
See: #505
