### ISSUE TITLE
Link to nightly package index URL is broken 

### ISSUE THREAD

**Issue by pgoodman** [lief-project/LIEF#514]
**Describe the bug**
The readme describes the package URL for nightly builds as `https://lief-project.github.io/packages`, which returns a 404. I think it should instead be `https://lief.quarkslab.com/packages/lief/`.

**To Reproduce**
Try to go the the URL.

**Expected behavior**
The URL works.

**Environment (please complete the following information):**
 - System and Version : macOS Big Sur
 - Target format: ELF

**Additional context**
On a related topic, It would be really appreciated if an example of how to integrate nightly builds with LIEF into a setup.py file were provided. For example, presumably the nightly packages are the `0.11.0` versions on the above link. However, if I try to specify a dependency on `0.11.0`, or `0.11.0.dev`, then I get errors. I would like to use the nigthly build as it apparently fixes #505 / #508.

In my setup.py, I'm specifying the following with no luck :-(

```python
    install_requires=[
        "wheel",
        "lief=0.11.0",
        # ...
    ],
    dependency_links=[
        "https://lief.quarkslab.com/packages/lief/"
    ],
```

**Comment by romainthomas** [comment]
Hi @pgoodman 
The URL of the wheel packages is https://lief.quarkslab.com/packages/lief/ but you need to use https://lief.quarkslab.com/packages with pip.

You must also specify ``lief==0.11.0.dev0`` (and not just ``dev``) . I updated the README accordingly 

Let me know if it fixes the issue

**Comment by pgoodman** [comment]
Thanks! I will add the `pip` install requirement to my own README :-)
