### ISSUE TITLE
The "name" attribute of "lief.ELF.SymbolVersionAux" can't be assigned to in the Python binding

### ISSUE THREAD

**Issue by marin-m** [lief-project/LIEF#515]
Hello,

#### Describe the bug

It seems that the version of a ELF symbol cannot be changed with the intent of rewriting it, because of an incorrect binding of the  [`SymbolVersionAux`](https://lief.quarkslab.com/doc/latest/doxygen/classLIEF_1_1ELF_1_1SymbolVersionAux.html) class to Python (while the `void name (const std::string &name)` C++ method seems to intend to provide this).

#### To Reproduce

The following test code was used:

```python
#!/usr/bin/python3
#-*- encoding: Utf-8 -*-
from lief import parse

elf = parse('monmorceaudebibliothequeavecbionicquejaimeraisbienporter.so')

for symbol in elf.symbols:
    
    if symbol.has_version and symbol.symbol_version.has_auxiliary_version and symbol.symbol_version.symbol_version_auxiliary.name == 'LIBC':
        
        symbol.symbol_version.symbol_version_auxiliary.name = 'GLIBC_2.2.5'

elf.write('patched_library.so')
```

This produces:

```shell-session
$ ./rewrite_elf.py 
Traceback (most recent call last):
  File "./rewrite_elf.py", line 11, in <module>
    i.symbol_version.symbol_version_auxiliary.name = 'GLIBC_2.2.5'
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (arg0: lief.ELF.SymbolVersionAux) -> str

Invoked with: <lief.ELF.SymbolVersionAuxRequirement object at 0x7feb840ff670>, 'GLIBC_2.2.5'
```

#### Expected behavior

An ELF file with the corrected symbol versions should be written to `patched_library.so`.

#### Environment

 - System and Version : Ubuntu 20.04
 - Target format: ELF
 - LIEF commit version: `0.11.0-4274537`

Regards,

**Comment by romainthomas** [comment]
Thanks, it was a typo.
