### ISSUE TITLE
Question: is it possible to create MachO file from scratch ?

### ISSUE THREAD

**Issue by leeehui** [lief-project/LIEF#516]
I found ELF and PE can create from scratch as follow:
bin_elf = ELF.Binary("elf_from-scrach", ELF.ELF_CLASS.CLASS64)
binary32 = PE.Binary("pe_from_scratch", PE.PE_TYPE.PE32)

but, 
macho = MachO.Binary("macho-from-scrach") raised "TypeError: lief.MachO.FatBinary: No constructor defined!"

**Comment by romainthomas** [comment]
It's not possible and it's not scheduled anytime soon
