### ISSUE TITLE
Setting the "name" attribute for a DynamicEntryLibrary created from scratch in the Python library causes segfault

### ISSUE THREAD

**Issue by marin-m** [lief-project/LIEF#518]
Hello,

#### Describe the bug

It seems that setting the `name` attribute for an ELF `DynamicEntryLibrary` created from scratch in the Python library causes a segmentation fault.

Conversely, changing the `name` attribute for an existing `.dynamic` library entry does not cause segfault, and takes effect correctly.

#### To Reproduce

The following test code was used:

```python
#!/usr/bin/python3
#-*- encoding: Utf-8 -*-
from lief.ELF import DynamicEntryLibrary

hook = DynamicEntryLibrary.__new__(DynamicEntryLibrary)
hook.tag = DYNAMIC_TAGS.NEEDED
hook.name = 'libhook.so'
```

This produces:

```shell-session
$ ./rewrite_elf.py 
Segmentation fault (core dumped)
```

#### Expected behavior

The user should be able to build a new library import to add to the `.dynamic` section of the ELF file.

#### Environment

 - System and Version : Ubuntu 20.04
 - Target format: ELF
 - LIEF commit version: `0.11.0-541cd5b`

Regards,

**Comment by romainthomas** [comment]
[lief.ELF.Binary.add_library](https://lief.quarkslab.com/doc/latest/api/python/elf.html#lief.ELF.Binary.add_library)
