### ISSUE TITLE
Make lief.DictStringVersion a MutableMapping

### ISSUE THREAD

**Issue by Rafiot** [lief-project/LIEF#52]
I'm not sure I'm doing it right, but accessing the file information of a PE is a bit difficult:

```python
pe = lief.parse("./2805/f325970fd24bb088f1befdae5788152329e26bf3")
string_info = lief.to_json(pe.resources_manager.version.string_file_info.langcode_items[0])
# and then, json.loads, and so on 
```

It would be very nice to be able to access all the data as a [`collections.abc.MutableMapping`](https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableMapping) so we could read and write the attributes directly in a pythonic way.

I may be doing it wrong ;)

**Comment by romainthomas** [comment]
Could you be more precise about the API you would like ?

**Comment by Rafiot** [comment]
I'd like to be able to do things like that:
```python
for key, value in pe.resources_manager.version.string_file_info.langcode_items[0].items():
    print(key, value)
```

**Comment by romainthomas** [comment]
Well actually the underlying C++ container is a ``std::map``: [include/LIEF/PE/resources/LangCodeItem.hpp#L96](https://github.com/lief-project/LIEF/blob/master/include/LIEF/PE/resources/LangCodeItem.hpp#L96) and the *translation* to Python (thanks to [pybind11](https://github.com/pybind/pybind11/)) is performed with a ``dict`` [like](https://github.com/pybind/pybind11/blob/master/include/pybind11/stl_bind.h#L462). The conversion to [`collections.abc.MutableMapping`](https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableMapping) is not trivial 

But you can iterate over the [`items`](https://lief.quarkslab.com/doc/api/python/pe.html#lief.PE.LangCodeItem.items) property as follow:

```python
for k, v in pe.resources_manager.version.string_file_info.langcode_items[0].items.items():
    print(k, v)
```

**Comment by Rafiot** [comment]
Hmmm, yeah, I get the problem. 
The list of tuples if fine for me to get the data out, but if you want to edit it at some point, it will be tricky.

**Comment by Rafiot** [comment]
FYI, I create my dict this way:
`dict(pe.resources_manager.version.string_file_info.langcode_items[0].items)`
