### ISSUE TITLE
Unable to change exported function name

### ISSUE THREAD

**Issue by dzonerzy** [lief-project/LIEF#527]
**Describe the bug**
Unable to changed exported function name

**To Reproduce**
```python
import lief
bin = lief.parse("bin.dll")
bin.exported_functions[0].name = "newname"
bin.save("bin2.dll")
````

**Expected behavior**
Exported function name should be changed

**Environment:**
 - System and Version : Windows 10
 - Target format: PE
 - LIEF commit version: latest

**Comment by romainthomas** [comment]
As discussed on Twitter, LIEF is not able to handle modification of PE's exports

**Comment by google-mirror** [comment]
> LIEF is not able to handle modification of PE's exports

Is LIEF able to remove PE's exports?
