### ISSUE TITLE
Cannot get signature information of a certain PE file

### ISSUE THREAD

**Issue by kohnakagawa** [lief-project/LIEF#536]
**Describe the bug**
Cannot get signatures of a certain PE file.

**To Reproduce**
Download [this file](https://www.virustotal.com/gui/file/001d1e0b4051f1d942ee8226ceeb686db7d70ab2d3d354630f912b2ae092f6db/details) via VirusTotal, then run the following script.

```python
# test.py
import lief

obj = lief.PE.parse("001d1e0b4051f1d942ee8226ceeb686db7d70ab2d3d354630f912b2ae092f6db")

print(obj.has_signatures) # False

for sig in obj.signatures:
    print(sig) # not printed its details
```

lief version 0.12.0-b1e1a44 cannot get the signature of this PE file.

However, VirusTotal's "DETAILS" tab indicates that this file has a signature.

![image](https://user-images.githubusercontent.com/5129526/105824573-e0578d00-6001-11eb-8954-114802025f3f.png)

**Expected behavior**

Can get the signature of the above file.

**Environment (please complete the following information):**

 - Ubuntu 20.04 on WSL2 on Windows 10
 - PE
 - 0.12.0-b1e1a44

**Additional context**

Older version of lief (at least lief version 0.10.1) can get this signature information.
I'm currently fixing this issue,

**Comment by kohnakagawa** [comment]
The signature of this file seems to be corrupted. So, there is no way to parse it.
I think that it is appropriate to show warning messages to the user when parsing a corrupted signature.

![image](https://user-images.githubusercontent.com/5129526/105937933-e0a36700-6099-11eb-903d-2bbdf5530571.png)

**Comment by romainthomas** [comment]
Ack
