### ISSUE TITLE
linux wheel for cp36

### ISSUE THREAD

**Issue by imidoriya** [lief-project/LIEF#539]
I had to roll back to 0.10.1 as I couldn't get 0.11 installed.  The wheel build just wouldn't complete.  Any chance you could add a cp36 to the releases?

**Comment by imidoriya** [comment]
Got it! Just took a really long time to build the wheel. I thought it dead, but guess I was just being too impatient and killed it before it could complete.

Would still be nice to include them if it's feasible.  I wasn't in a good place to update to Py3.7.

**Comment by romainthomas** [comment]
Ack I'll provide a wheel pour python 3.6
