### ISSUE TITLE
Compute imphash

### ISSUE THREAD

**Issue by Rafiot** [lief-project/LIEF#54]
I'm not sure it is something you want to do in lief directly, but it would be nice to compute the imhash for the PEs.

There is a sample code here: https://github.com/erocarrera/pefile/blob/8d60469de3b70109ac603c68c48fb3e7b84261e8/pefile.py#L3747

**Comment by romainthomas** [comment]
Given whatever **PE**, **ELF** or **Mach-O** you can compute an imhash (by using [imported_functions](https://lief.quarkslab.com/doc/api/python/abstract.html#lief.Binary.imported_functions)) as follow:
```python
import lief
from hashlib import md5
elf_pe_macho = lief.parse("/bin/ls")
imphash = md5(",".join(elf_pe_macho.imported_functions).encode()).hexdigest()
print(imphash)
```

**Comment by Rafiot** [comment]
Yeah, the lack import by ordinal will break quite a lot of hashes so I cannot really rely on it out-of-the-box. 

I can just have a wrapper to do it on my end, it's not a big deal.

**Comment by romainthomas** [comment]
What I could do is to implement this hash in the *utils* part of the format. Something like this:

```python
import lief
from lief.PE import imphash
pe = lief.parse("...")
print(imphash(pe))
```

**Comment by Rafiot** [comment]
I'm totally with you on that :)

In the utils part, I could also contribute a MISP object export for example

**Comment by Rafiot** [comment]
\o/
