### ISSUE TITLE
LIEFMT.dll not found when compiling LIEF CMake example

### ISSUE THREAD

**Issue by puffyCid** [lief-project/LIEF#540]
Hello,

Im encountering issues when when trying to integrate version 0.11.0 of LIEF into a CMake project.
I followed the find_package CMake example in the documentation but when I try to run the executable I get the error
`
The code execution cannot proceed because LIEFMT.dll was not found. Reinstalling the program may fix this problem.
`
If I place the LIEFMT.dll in the release in the same directory as my compiled executable it works perfectly.
Is there a way to include the LIEF library completely statically without needing the DLL?

When I was using the nightly 0.11.0 version it was working perfectly, I did not need the DLL, I only needed LIEFMT.lib (and headers)

I also tried compiling the example CMake files included the 0.11.0 release and I get the same error as above.

System: Windows 10
Target format: PE
LIEF version: 0.11.0

**Additional context**
I noticed that LIEFMT.lib is much smaller in the 0.11.0 release than in the previous release/0.11.0 nightlies (or when compiling LIEF source, ie: ~30MB (compiling from source) vs ~2MB (release))

I can share/post my CMake file if that would help.  
Thanks

**Comment by romainthomas** [comment]
Hello @puffyCid,
Yes it would be useful to share the cmake files so that I can try to reproduce the issue

**Comment by puffyCid** [comment]
So im trying to integrate LIEF into an existing C++ project (osquery)
So the CMake file maybe a little difficult to reproduce without downloading the osquery source code
```
project(LiefExt VERSION 1.0
  DESCRIPTION "LIEF Extension for Osquery"
  LANGUAGES CXX)

set(LIEF_DIR CACHE PATH ${CMAKE_INSTALL_PREFIX})
list(APPEND CMAKE_MODULE_PATH ${LIEF_DIR}/share/LIEF/cmake)
include(FindLIEF)
find_package(LIEF REQUIRED COMPONENTS STATIC)

function(osqueryLiefPeExtension)
  addOsqueryExtension(lief_pe src/main.cpp src/pelibraries.cpp src/pefunctions.cpp src/pesections.cpp src/pesig.cpp)
  if (MSVC)
    # Used for the 'and', 'or' ... keywords - See: http://www.cplusplus.com/reference/ciso646/
    target_compile_options(lief_pe PUBLIC /FIiso646.h)
	set_property(TARGET lief_pe PROPERTY LINK_FLAGS /NODEFAULTLIB:MSVCRT)
  endif()
  target_include_directories(lief_pe PUBLIC ${LIEF_INCLUDE_DIRS})

set_property(TARGET lief_pe
             PROPERTY CXX_STANDARD           11
             PROPERTY CXX_STANDARD_REQUIRED  ON)

target_link_libraries(lief_pe PUBLIC ${LIEF_LIBRARIES})
target_link_libraries(lief_pe PRIVATE osquery_sdk_pluginsdk osquery_extensions_implthrift)
endfunction()

osqueryLiefPeExtension()
```
The command im using to compile it
```
& 'C:\Program Files\CMake\bin\cmake.exe'  -G "Visual Studio 16 2019" -DLIEF_DIR=C:\Users\bob\Projects\osquery\external\extension_lief\ -DLIEF_LIBRARY=C:\Users\bob\Projects\osquery\external\extension_lief\lib\LIEFMT.lib -A x64 ..
```
The CMake file was working ok when I was using the 0.11.0 nightly versions
I am able to compile the macOS version of the LIEF library statically when using the same kind of Cmake file above

I also get the same error
```
 The code execution cannot proceed because LIEFMT.dll was not found. Reinstalling the program may fix this problem.
```
When trying to compile the example find_package CMake file in the 0.11.0 release

**Comment by romainthomas** [comment]
There is definitely an issue with the static library (all files are name ``LIEFMT.dll``)

**Comment by romainthomas** [comment]
I'll push the package's fix today

**Comment by romainthomas** [comment]
Done! I updated the release packages.
