### ISSUE TITLE
Undefined behaviour in `LIEF::PE::resolve_ordinals()`

### ISSUE THREAD

**Issue by j-jorge** [lief-project/LIEF#542]
I was wandering around in the repository and stumbled upon this code:

https://github.com/lief-project/LIEF/blob/51d258f95b3a39b441acb157d35e06dee8748855/src/PE/utils.cpp#L292-L294

`it_library_lookup` is either an iterator on `imphashstd::ordinals_library_tables` or `ordinals_library_tables`. As far as I know, it cannot be compared with an iterator on the other container as it would represent an invalid range, which is undefined behavior as per [§12 of [iterator.requirements.general]](https://eel.is/c++draft/iterator.requirements.general#12).

**Comment by romainthomas** [comment]
Indeed my bad. Thanks for pointing this issue.
