### ISSUE TITLE
Cannot find or install version 0.9.0 anymore

### ISSUE THREAD

**Issue by wangxiaoying** [lief-project/LIEF#544]
**Is your feature request related to a problem? Please describe.**
Previously I can install lief 0.9.0 by:
`pip install https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.9.0.dev.zip`

However, now it seems like there are some changes in the `packages` repo and this version is not available anymore. Is there another way that I can install it?

**Comment by romainthomas** [comment]
on pypi
