### ISSUE TITLE
authentihash segfault

### ISSUE THREAD

**Issue by imidoriya** [lief-project/LIEF#548]
**Describe the bug**
Running any of the authentihash **on this PE file** (_removed - let me know if you need it again_) causes a segmentation fault.

**To Reproduce**
```py
import lief
binary=lief.PE.parse('/home/segfault.exe')
print(binary.authentihash_sha256.hex())
```

> Segmentation fault (core dumped)

**Expected behavior**

> hash

**Environment (please complete the following information):**
 - System and Version : [e.g. Ubuntu 18.04]
 - Target format (PE, ELF, Mach-O)
 - LIEF commit version: `0.11.0-f58605f`
 - Python 3.6.7

**Comment by romainthomas** [comment]
Ack, I confirm the issue. I'll fix that this week and provide a patched version
