### ISSUE TITLE
Build failure on windows upgrading from 0.10.1 to 0.11.1

### ISSUE THREAD

**Issue by farzonl** [lief-project/LIEF#550]
**Describe the bug**
I'm seeing a linker failure using the 0.11.1 published release build I've documented here:
https://github.com/farzonl/Disassembler/issues/17

seems to be 2 main issues:

1. unresolved external symbol __dyn_tls_on_demand_init 
2.  unresolved external symbol __tls_guard 

**To Reproduce**
build linking the  LIEFMT.lib 0.11.1 library

**Expected behavior**

For the build to succeed.

**Environment (please complete the following information):**
 - System and Version :  WIndows 10 MSVC 2019 compiler

**Additional context**
I'm able to build from source just fine. In fact thats what I have to do to use debug builds. So what I think is going on here is you all are now using an older compiler than myself, but since the version of the build is only 4 months old  I didn't think that was a likely theory. Ideally I don't want to build from source to use LIEF, as it kills my CI build times, especially on windows.

**Comment by romainthomas** [comment]
We are also using MSVC 2019 on the CI: https://github.com/lief-project/LIEF/blob/56f503ade01dbd970d94276f8dd4bdcad004737b/.appveyor.yml#L2
Feel free to take a look if you notice something wrong.

**Comment by farzonl** [comment]
Closing this ticket. The appveyor build appears to be picking the latest version of VS. My local build failures corresponded with the msvc release schedule documented here: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.8

I've since upgraded my version of vs and am able to link against the latest version of lief.
