### ISSUE TITLE
PE section names contain null bytes, cannot be retrieved by name without \x00

### ISSUE THREAD

**Issue by isaac-ped** [lief-project/LIEF#551]
Parsing a 64-bit binary with lief 0.11.1 causes extra null bytes appended to the end of section names:
```python
>>> import lief
>>> b = lief.parse('test.exe')
>>> [section.name for section in b.sections]
['.text\x00\x00\x00', '.data\x00\x00\x00', '.rdata\x00\x00', '.pdata\x00\x00', '.xdata\x00\x00', '.bss\x00\x00\x00\x00', '.idata\x00\x00', '.CRT\x00\x00\x00\x00', '.tls\x00\x00\x00\x00', '/4\x00\x00\x00\x00\x00\x00', '/19\x00\x00\x00\x00\x00', '/31\x00\x00\x00\x00\x00', '/45\x00\x00\x00\x00\x00', '/57\x00\x00\x00\x00\x00', '/70\x00\x00\x00\x00\x00', '/81\x00\x00\x00\x00\x00', '/92\x00\x00\x00\x00\x00']
>>> b.get_section(".text")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
lief.not_found: No such section with this name
>>> b.get_section(".text\x00\x00\x00")
<lief.PE.Section object at 0x7f880d37a4b0>
```

The issue occurs for both 64-bit and 32-bit binaries compiled with `x86_64-w64-mingw32-gcc` and `i686-w64-mingw32-gcc`. Binaries compiled in other ways have been tested as well and show similar results.

Lief version is `0.11.1-a6d9ea9`. Happy to provide more information on request

*EDIT:* have verified that this issue does not occur on `0.11.0-f58605f`, and seems to be a direct consequence of this change:
https://github.com/lief-project/LIEF/commit/8d874a023b7d1c523aa1df0d3476e1fa6651500c

**Comment by romainthomas** [comment]
I made a patch release for this issue

**Comment by isaac-ped** [comment]
Thank you!
