### ISSUE TITLE
Question: Can LIEF detect if shared object (.so) is compiled with position independent code -fpic flag?

### ISSUE THREAD

**Issue by ajinabraham** [lief-project/LIEF#555]
Question

I see that LIEF has an API for `is_pie()` for ELF binaries
https://lief.quarkslab.com/doc/latest/api/python/elf.html?highlight=pie#binary

Is there an API or flag in LIEF that tells me if an ELF shared object is compiled with position independent code (-fpic) or not?

**Comment by romainthomas** [comment]
An ELF shared object is **always** position independent

**Comment by ajinabraham** [comment]
What is the significance of `-fPIC` flag in that case? Am I missing something here?

> On most architectures, when you compile source code to object code, you need to specify whether the object code should be position independent or not. There are occasional architectures which don't make the distinction, usually because all object code is position independent by virtue of the Application Binary Interface (ABI), or less often because the load address of the object is fixed at compile time, which implies that shared libraries are not supported by such a platform. If an object is compiled as position independent code (PIC), then the operating system can load the object at any address in preparation for execution. This involves a time overhead, in replacing direct address references with relative addresses at compile time, and a space overhead, in maintaining information to help the runtime loader fill in the unresolved addresses at runtime. Consequently, PIC objects are usually slightly larger and slower at runtime than the equivalent non-PIC object. The advantage of sharing library code on disk and in memory outweigh these problems as soon as the PIC object code in shared libraries is reused.

Ref: https://wiki.gentoo.org/wiki/Hardened/Introduction_to_Position_Independent_Code

**Comment by romainthomas** [comment]
PIC stands for **Position Independent Code** which means that  the object is relocatable (can be either executable or shared library) while PIE stands for **Position Independent Executable** which is only used for **executable**

* ``-fPIC`` should be used for executable **and libraries**
* ``-fPIE`` should be used for executable only

``-fPIE`` => ``-fPIC``

**Comment by romainthomas** [comment]
Could you have a shared library without ``-fPIC`` ?
