### ISSUE TITLE
Shared Library Binary Analysis are wrong 

### ISSUE THREAD

**Issue by anda5** [lief-project/LIEF#557]
Based on this issue: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1676#issuecomment-792367940 it looks like there are some binary analysis that is wrong ->_Regarding binary analysis, MobSF uses LIEF project for Binary Analysis._

**Comment by romainthomas** [comment]
What is wrong exactly ?

**Comment by romainthomas** [comment]
Feel free to re-open with a **clear** description of your problem.

**Comment by anda5** [comment]
I have this analysis from MOBSF 
[app_scan (2).pdf](https://github.com/lief-project/LIEF/files/6203486/app_scan.2.pdf)
with warning about FORTIFY_SOURCE=2 - this flag is added automatically by Android NDK when building:
(comment from xamarin: https://github.com/xamarin/xamarin-android/issues/5592#issuecomment-778315966 )

**Comment by romainthomas** [comment]
LIEF doesn't not assert and does not expose an API whether the library/binary has been
compiled with FORTIFY_SOURCE. This assertion is handled by MobSF

**Comment by anda5** [comment]
Ok, thank you

**Comment by abdi191188** [comment]
> I have this analysis from MOBSF [app_scan (2).pdf](https://github.com/lief-project/LIEF/files/6203486/app_scan.2.pdf) with warning about FORTIFY_SOURCE=2 - this flag is added automatically by Android NDK when building: (comment from xamarin: [xamarin/xamarin-android#5592 (comment)](https://github.com/xamarin/xamarin-android/issues/5592#issuecomment-778315966) )

Hello, I have the same problem when they performed the pentest on my mobile application

**Comment by abdi191188** [comment]
> Ok, thank you

@anda5   were you able to resolve this issue?
