### ISSUE TITLE
The rebuilt binary is different from the original one without changes

### ISSUE THREAD

**Issue by TTY-00** [lief-project/LIEF#558]
**Describe the bug**
The rebuilt binary is different from the original binary without changes.
```
bin = lief.parse(in_path)
bin.write(out_path)
```
I tested both ELF files and MachO files, both of the outputs are different from the original ones. And for the Big Sur files, this will make the binary un-executable.

**To Reproduce**

Firstly, run the python script
```
bin = lief.parse("/bin/bash")
bin.write("./bash_edited")
```
and then compare the rebuilt binary the original ones
```
> cmp -l /bin/bash ./bash_edited
```

**Expected behavior**
The rebuilt binary should be the same as the original one?

**Environment (please complete the following information):**
 - System and Version : BigSur 11.2.2, Apple m1
 - Target format:  Mach-O, ELF
 - LIEF commit version: 0.12.0-9cf2ec8

**Additional context**
The rebuilt MachO file is un-executable, the elf was not tested.

**Comment by romainthomas** [comment]
>  The rebuilt binary should be the same as the original one?

Semantically it aims at being the same but LIEF does not aim at rebuilding the binary with the exact same bytes even though there 
were no transformation made by the user.

**Comment by TTY-00** [comment]
Totally understand it.
But can you give me some hints about why there are some differences and where do the changes come from?
Because the changes made by LIEF seem destroyed the MachO file structure and make it illegal. So maybe I can do some work on LIEF myself with some hints.
Thanks a lot.

**Comment by romainthomas** [comment]
You can try to diff the output of [macho_reader.py](https://github.com/lief-project/LIEF/blob/master/examples/python/macho_reader.py) (and open another issue if you managed to detect where it failed)  or you can send me the original binary so that I can have a look.

**Comment by TTY-00** [comment]
Thanks. I'll try.
And I also send you an email on your GitHub page with three binaries and the rebuilt ones.
