### ISSUE TITLE
Erroneous  Warning printing out. PGO: UNKNOWN is not implemented yet!

### ISSUE THREAD

**Issue by farzonl** [lief-project/LIEF#560]
Seeing `PGO: UNKNOWN is not implemented yet!` printed out when parsing the following assembly
```asm
global main
extern GetStdHandle
extern WriteFile

section .text
main:
    mov     rcx, 0fffffff5h
    call    GetStdHandle

    mov     rcx, rax
    mov     rdx, NtlpBuffer
    mov     r8, [NtnNBytesToWrite]
    mov     r9, NtlpNBytesWritten
    sub     rsp, 40
    mov     dword [rsp + 32], 00h
    call    WriteFile
    add     rsp, 40
ExitProgram:
    xor     eax, eax
    ret

section .data
NtlpBuffer:        db    'Hello, World!', 00h
NtnNBytesToWrite:  dq    0eh

section .bss
NtlpNBytesWritten: resd  01h
```
compiled like so:
```batch
nasm.exe  -f win64 main.asm
link.exe /entry:main main.obj /subsystem:console /nodefaultlib /LARGEADDRESSAWARE:NO 
"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64\kernel32.lib"
```
https://github.com/lief-project/LIEF/blob/e875a8ffa279ddced72ea2f8add8e569791cf115/src/PE/Parser.cpp#L719

I'm not compiling with any PGO flags listed here:
https://docs.microsoft.com/en-us/cpp/build/profile-guided-optimizations?view=msvc-160

Not sure why I would be hitting this section.

**Comment by daimaxiaxie** [comment]
I also encountered the same problem. But my exe is compiled like this “pyinstaller -F test.py”. It also appeared PGO: UNKNOWN is not implemented yet!

**Comment by Unam3dd** [comment]
I have the same problem with msvc compiler !

**Comment by kohnakagawa** [comment]
I don't think this is not an erroneous warning because an executable compiled by nasm assembler actually contains the POGO (note that the type of IMAGE_DEBUG_TYPE_POGO is 0xd).

<img width="611" alt="スクリーンショット 2021-07-02 17 20 18" src="https://user-images.githubusercontent.com/5129526/124244507-fa217100-db59-11eb-96f9-d141bf8089f9.png">

**Comment by blaquee** [comment]
Just wanted to add I am getting alot of these also while traversing my Windows System32 folder.

**Comment by farzonl** [comment]
> I don't think this is an erroneous warning because an executable compiled by nasm assembler actually contains the POGO (note that the type of IMAGE_DEBUG_TYPE_POGO is 0xd).

So I don't know how NASM would be doing that since they don't have an `IMAGE_DEBUG_TYPE_POGO`  defined
https://github.com/netwide-assembler/nasm/blob/5368e4579403daaf6c12165eb857893f8acfc7f8/output/pecoff.h#L429-L440

so that leads me to belive that the linker might be adding the 0xd you are seeing? I'm not sure what the on by default flags are for link.exe.

That said I'm still not sure how this is related to the PE/Parser.cpp#L719
The enum for POGO isn't checking against the debug entry types its checking against: https://github.com/lief-project/LIEF/blob/158f291b1f1beec2e420e6624ec7833add0fb1e4/include/LIEF/PE/enums.inc#L297-L301

POGO_LCTG  (0x4C544347) & POGO_PGI  (0x50474900)  are quite large so i'd expect them to stand out in ida.

**Comment by romainthomas** [comment]
The verbosity has been reduced
