### ISSUE TITLE
Lief changes the String size of MachO file and makes it illegal

### ISSUE THREAD

**Issue by TTY-00** [lief-project/LIEF#561]
**Describe the bug**
diff the original bin and rebuild bin of the result of _macho_reader.py_:

ORIGINAL BIN:
== Symbol Command ==
Symbol offset     0xc1e0                        
Number of symbols 23                            
String offset     0xc3e8                        
String size       **0x140**    

AFTER REBUILD:
== Symbol Command ==
Symbol offset     0xc1e0                        
Number of symbols 23                            
String offset     0xc3e8                        
String size       **0x4a48**      

**To Reproduce**
```
    bin = lief.MachO.parse(in_path)
    bin.write(out_path)
```

**Expected behavior**
String size keeps the same as the original one.

**Environment (please complete the following information):**
 - System and Version : macos big sur
 - Target format: MachO
 - LIEF commit version:  0.12.0-9cf2ec8

**Comment by romainthomas** [comment]
Ack

**Comment by TTY-00** [comment]
p.s. And bind size (in DYLD_INFO) also changed.

**Comment by romainthomas** [comment]
It looks there is also an issue in the relocations

**Comment by romainthomas** [comment]
After investigation there were some errors in the Mach-O builder but I think that the root cause of your problem is the code signing.
