### ISSUE TITLE
Multiple bugs with logged message (error)

### ISSUE THREAD

**Issue by vietvo89** [lief-project/LIEF#567]
**Describe the bug**
Got multiple logged error but not know their meaning and how to handle them.

- Relocation corrupted: BlockSize is out of bound the binary's virtual size
- {} is not implemented yet!
- PGO: UNKNOWN is not implemented yet!
- Can't patch
- Unable to find the section associated with BOUND_IMPORT
- TLS's template corrupted
- Unable to find the section associated with CERTIFICATE_TABLE
- Try to read 0x4 bytes from 0x823838 (82383c) which is bigger than the binary's size
- Unable to find the section associated with BASE_RELOCATION_TABLE
- Unable to find the section associated with relocations
- The signature seems corrupted!
- Relocation corrupted: BlockSize is out of bound the binary's virtual size
- The leaf is corrupted
- Relocation corrupted: BlockSize is too small

How to know what do they mean and how to tackle them?

**Expected behavior**
clean and no log error

**Environment (please complete the following information):**
 - System and Version : [Ubuntu 18.04]
 - Target format (PE)
 - LIEF commit version: ``0.11.1``

**Comment by romainthomas** [comment]
You can look at the source code.
