### ISSUE TITLE
building on FreeBSD - wrong file listed in pkg-plist

### ISSUE THREAD

**Issue by dlangille** [lief-project/LIEF#575]
When building `lief-0.11.4` on `FreeBSD`, a file listed in the `pkg-plist` has the wrong name.

During a sanity check phase of building a FreeBSD package, the code compares the list of files to be installed against what is actually installed. There is a mismatch.

This file will be installed: `lief.cpython-38.so`

This is the file which was claimed to be installed: `f-0.11.4/lief.cpython-38.so`

It is expected that there is no mismatch. I don't know which file is corrt.

To reproduce, the Makefile and relevant output are at https://gist.github.com/dlangille/1f3829e5724bf30dc030eadb4c00e30c

 - FreeBSD 12.2
 - lief-0.11.4

**Comment by romainthomas** [comment]
Ack. I never tested LIEF in a FreeBSD environment but I'll check that.

**Comment by dlangille** [comment]
FYI, this conversation is from IRC which I mentioned the issue. The commentator looked at the code. Hope this helps.

*  re lief/ its likely, if youre using autoplist, that the upstream is overriding the default setuptools install_Data and other targets, and not correctly updating the RECORD list (which contains files that get installed, that autoplist uses)
* so yep
* https://github.com/lief-project/LIEF/blob/master/setup.py#L78
* they are
* https://github.com/lief-project/LIEF/blob/master/setup.py#L104
* and here
```
log.info("Copying {} into {}".format(pylief_path, pylief_dst))
copy_file(
               pylief_path, pylief_dst,
        pylief_path = os.path.join(cmake_library_output_directory, "{}.{}".format(PACKAGE_NAME, libsuffix))
```

**Comment by dlangille** [comment]
This is a gist containing the files for the FreeBSD port I am trying to create:

https://gist.github.com/dlangille/78902092fd8839bc4514492f949bad16

**Comment by dlangille** [comment]
See also https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=257041

**Comment by romainthomas** [comment]
To be reopen if there are still the issue with the latest version
