### ISSUE TITLE
pe_from_scratch.py example has a wrong SizeOfOptionnalHeader

### ISSUE THREAD

**Issue by themaks** [lief-project/LIEF#576]
**Describe the bug**
The PE generated by the [pe_from_scratch.py](https://github.com/lief-project/LIEF/blob/master/examples/python/pe_from_scratch.py) example has a small bug in the headers, that destroys the section table. As a result, the binary is not executable.

The "SizeOfOptionnalHeader" field in the IMAGE_FILE_HEADER is 0xF0. However, this is incorrect, since the section header starts at &OptionnalHeader + 0xD8. Patching the PE using CFF Explorer, changing the value from 0xF0 to 0xD8, repairs the binary, and make it normally executable.

I don't know if the problem only concerns the pe_from_scratch example, or if it affects the whole PE.Builder module.

**To Reproduce**
Execute the [pe_from_scratch.py](https://github.com/lief-project/LIEF/blob/master/examples/python/pe_from_scratch.py) and execute the pe_from_scratch.exe binary.

**Expected behavior**
The EXE executes correctly and displays a pop up message.

**Environment (please complete the following information):**
 - Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux
 - python 3.9
 - Target format PE
 - LIEF commit version: 0.11.4-dd13711

Cheers

**Comment by romainthomas** [comment]
Thanks for the report!
