### ISSUE TITLE
Memory issues with few binaries (included)

### ISSUE THREAD

**Issue by Rafiot** [lief-project/LIEF#58]
Both following samples are using 8G+ of ram (and OOM killer steps in ;) ):
https://github.com/viper-framework/pefile-tests/blob/master/tests/corkami/pocs/65535sects.exe
https://github.com/viper-framework/pefile-tests/blob/master/tests/corkami/pocs/manyimportsW7.exe

The binaries are definitely crafted, but you probably want to handle such cases too.

**Comment by romainthomas** [comment]
Thanks, I'm aware of this problem and it's related to the ``C++ --> Python`` interface (copy vs ref). 
It will take some times to solve it.

**Comment by romainthomas** [comment]
@Rafiot I fixed ``manyimportsW7.exe`` with commit https://github.com/lief-project/LIEF/commit/b09efa1d42f019ed90b34195fde3a7c3545237e5

**Comment by Rafiot** [comment]
Thanks!
