### ISSUE TITLE
Enable binary parsing of std::string_view

### ISSUE THREAD

**Issue by pgoodman** [lief-project/LIEF#581]
**Is your feature request related to a problem? Please describe.**
The problem I would like to have solved is that binary parsers do not require a vector of file contents, but can instead operate on a range/view of file contents. The issue as I see it is that the vector approach forces the user of a binary parser to know ahead of time how big the file is, or else conservatively assume it's very big. The scenario in which this problem occurs is when we're running LIEF on an ELF that is embedded within some other file.

**Describe the solution you'd like**
Make it so that a binary parser, e.g. `Parser::Parser` inside of the `ELF` namespace, can operate on a `std::string_view`. This should behave similarly to a `const std::vector<uint8_t> &`, but have the benefit that users can operate on a chunks within a file that they have opened.

**Comment by romainthomas** [comment]
For the follow up from gitter:

> Providing ``std::string_view`` is not planned in the short term since it raises the C++ standard to 
> C++17. I would ok to use C++17 internally but not in the public headers.
> Nevertheless, I thought about this use case and I started to create interfaces to:
>   - Parse from memory: https://github.com/lief-project/LIEF/blob/master/src/BinaryStream/MemoryStream.cpp#L38
>   - Parse from std::ifstream (without copying the whole content in a std::vector)
> 
> These two interfaces are not ready yet but they aims at resolving the following issues:
>   - Parsing iOS/macOS dyld shared cache
>   - Parsing PE in-memory and iOS app in memory (and fix the relocations stuff)
> I don't have a clear idea when they will ready but I expect to have something usable in the following months.

**Comment by romainthomas** [comment]
The parsers now support the abstract [BinaryStream](https://lief-project.github.io/doc/latest/doxygen/classLIEF_1_1BinaryStream.html) interface which can be used with a [SpanStream](https://lief-project.github.io/doc/latest/doxygen/classLIEF_1_1SpanStream.html).
