### ISSUE TITLE
.dynsym not sorted by symbol visibility when using sysv hash style

### ISSUE THREAD

**Issue by jheydebrand** [lief-project/LIEF#582]
**Describe the bug**
I am editing the symbol visibility of an ELF shared library and change the visiblity of several symbols from GLOBAL to LOCAL.
After writing the edited shared library back to disk I run readelf on it, which reports " Warning: local symbol 6 found at index >= .dynsym's sh_info value of 1".

**To Reproduce**
```bash
$ cat test.c
extern int foo() {return 1;}
extern int bar() {return 2;}
int main() { return 0; }

$ gcc -shared test.c -o test.so -Wl,--hash-style=sysv
$ python3 -c "import lief;print(lief.__version__);bin=lief.parse('test.so');bin.get_symbol('bar').binding=lief.ELF.SYMBOL_BINDINGS.LOCAL;bin.write('test-edit.so');"
0.12.0-9ef590f
$ readelf -sW test-edit.so

Symbol table '.dynsym' contains 8 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __cxa_finalize
     2: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_registerTMCloneTable
     3: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_deregisterTMCloneTable
     4: 0000000000001117    15 FUNC    GLOBAL DEFAULT   10 main
     5: 00000000000010f9    15 FUNC    GLOBAL DEFAULT   10 foo
     6: 0000000000001108    15 FUNC    LOCAL  DEFAULT   10 bar
readelf: Warning: local symbol 6 found at index >= .dynsym's sh_info value of 1
     7: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __gmon_start__
```

**Expected behavior**
Shared libraries with sysv style hash sections are sorted as is already done for .gnu.hash style files.
readelf does not show a warning.

**Environment (please complete the following information):**
WSL2 Ubuntu 20.04 x64 (Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
GNU ld (GNU Binutils for Ubuntu) 2.34
LIEF=0.12.0-9ef590f

**Additional context**
I saw #507 and #509 and am uncertain why sysv should not be sorted.
A local test which removed the `if` condition at https://github.com/lief-project/LIEF/blob/9ef590fb990422e6852337325f854271e3408086/src/ELF/Builder.tcc#L1103 and unconditionally sorted the symbol table seemed to get me the desired result (sorted table) for the binary which I am using it on and caused no issues at runtime.

**Comment by romainthomas** [comment]
The ``SYSV`` hash does not enforce any kind of sorting compared to the GNU Hash. Nonetheless, LIEF should also update 
the ``dynsym.sh_information`` attribute. It turns out that, thanks to @Clcanny, this attribute is correctly updated in the  ``sort_dynamic_symbols()`` function. 
I think that we can call this function in both cases.
