### ISSUE TITLE
LIEF does not allow access to the (PE) string table

### ISSUE THREAD

**Issue by jgcodes2020** [lief-project/LIEF#583]
**Describe the bug**
So I made a small PE dumper to test LIEF's capabilities.
[LINK TO PE DUMPER](https://gist.github.com/jgcodes2020/3f5a2614b352b110b17cc947e068e869)

In a debug DLL compiled with MinGW, LIEF seems to look for the correct number of sections, but doesn't look in the right spot.

**To Reproduce**

1. Use the LIEF build for Windows x64.
2. Configure your project (I adapted the VS instructions for the Meson build system).
3. Use this code [here](https://gist.github.com/jgcodes2020/3f5a2614b352b110b17cc947e068e869)
4. Attempt to parse a DLL with debug symbols compiled by MinGW

**Expected behavior**
This is what I get from my LIEF-based PE dumper:
```
Section info:
   .text:   1000
   .data:   13c000
  .rdata:   388000
  .pdata:   cdb000
  .xdata:   ce9000
    .bss:   cf7000
  .edata:   11a3000
  .idata:   11eb000
    .CRT:   11ec000
    .tls:   11ed000
  .reloc:   11ee000
      /4:   11fe000
     /19:   1202000
     /31:   1831000
     /45:   185b000
     /57:   18e4000
     /70:   1913000
     /81:   191a000
     /92:   191e000
```
These are the sections from `dumpbin`.
```
  Summary

        1000 .CRT
      4AC000 .bss
      24C000 .data
       2A000 .debug_abbrev
        4000 .debug_aranges
       2F000 .debug_frame
      62F000 .debug_info
       89000 .debug_line
        4000 .debug_loc
        1000 .debug_ranges
        7000 .debug_str
       48000 .edata
        1000 .idata
        E000 .pdata
      953000 .rdata
       10000 .reloc
      13B000 .text
        1000 .tls
        E000 .xdata
```
Note that the debug sections names are shown in their` /<pointer into string table>` form
**Environment (please complete the following information):**
 - System and Version : [e.g. Ubuntu 16.04] Windows 10, `ver` gives `[Version 10.0.19041.985]`
 - Target format (PE, ELF, Mach-O) PE
 - LIEF commit version: Version 0.11.5

**Additional context**
If there is a way to locate the string table, that would be very useful.

**Comment by jgcodes2020** [comment]
Closing, the headers with / followed by a number have their names in the string table, and the actual names are there

**Comment by romainthomas** [comment]
Humm the string table is tied to a section right ?

**Comment by polarina** [comment]
@romainthomas not in PE executable, no. There doesn't appear to be a way to access a PE's executable string table with LIEF.
