### ISSUE TITLE
Add hash for rich header

### ISSUE THREAD

**Issue by nyx0** [lief-project/LIEF#587]
**Is your feature request related to a problem? Please describe.**
Calculating the `rich_header` hash could be painful.
It would be nice to have a way to display the rich_header decrypted.

**Describe the solution you'd like**
Here is an example with pefile module:

```python
import pefile, hashlib
clear_rich = pefile.PE("file.exe").parse_rich_header().get('clear_data')
hash_rich_header = hashlib.sha1()
hash_rich_header.update(clear_rich)
print(hash_rich_header.hexdigest())
```

Potential example in LIEF:
```python
import lief, hashlib
clear_rich = lief.parse("file.exe").rich_header.clear_rich
hash_rich_header = hashlib.sha1()
hash_rich_header.update(clear_rich)
print(hash_rich_header.hexdigest())
```

**Describe alternatives you've considered**
An alternative way would be to provide a method.

```python
import lief, hashlib
lief.parse("file.exe").rich_header.get_hash()
```

thanks

**Comment by romainthomas** [comment]
Ack. I will think about that.

**Comment by gdesmar** [comment]
I would prefer the original example with the access to clear_rich as I would be interested to generate not only sha1, but other types of hash as well (VT uses md5 for the rich header hash). The proposed alternative solution could take an _algorithm_ parameter to also fill this preference.

**Comment by gdesmar** [comment]
In the meantime, I think that something like the following can help generate the rich header hash
```python
import sys, hashlib, lief

b = lief.parse(sys.argv[1])
clear_rich = ""
for entry in b.rich_header.entries:
    rich_header_hex = f"{entry.build_id.to_bytes(2, byteorder='little').hex()}{entry.id.to_bytes(2, byteorder='little').hex()}"
    clear_rich = f"{rich_header_hex}{entry.count.to_bytes(4, byteorder='little').hex()}{clear_rich}"
clear_rich = bytes.fromhex(f"44616e53{'0'*24}{clear_rich}") # DanS + 3x key

m = hashlib.md5()
m.update(clear_rich)
print(m.hexdigest())
```

I haven't tried it at large, so it may be flawed.
