### ISSUE TITLE
lief.parse stuck on scanning Mach-o

### ISSUE THREAD

**Issue by kevinmun** [lief-project/LIEF#593]
**Describe the bug**
Running lief.parse('Mach-O-file-path') does not return and remains stuck

**To Reproduce**
Trying to run the below code snippet:
```
python3
>> import lief
>> l = lief.parse('<PATH to MachO Binary>')
>> print(l.is_pie)
```
Lief remains stuck at lief.parse, never returning

**Expected behavior**
lief.parse returns and am able to inspect output

**Environment (please complete the following information):**
 - System and Version : MacOS Big Sur 11.1 / macOS 10.15.6 (Catalina)
 - Target format (PE, ELF, Mach-O): Mach-O
 - LIEF commit version: 0.11.5-551ede5

**Additional context**
linked issue from mobsf : https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1749

**Comment by kevinmun** [comment]
Let me know if binary needs to shared - I can do so via PM

**Comment by romainthomas** [comment]
Yes could send me the link on twitter ([@rh0main](https://twitter.com/rh0main)) ?

**Comment by kevinmun** [comment]
Actually, Is there any other way I can provide diagnosis other than sending the binary file 😅

**Comment by romainthomas** [comment]
Could you try with the nightly build (master branch) ?

**Comment by kevinmun** [comment]
Ah - it works for nightly build!

**Comment by romainthomas** [comment]
Maybe this: https://github.com/lief-project/LIEF/pull/579

**Comment by kevinmun** [comment]
Thanks for the help!

**Comment by cure53-abraham** [comment]
any chance LIEF can push the update to PyPi? This issue still happens on MobSF because the fix is not in PyPi yet.
Thanks!

**Comment by romainthomas** [comment]
The release candidate will be published mid-march and the final release by the end of march.
