### ISSUE TITLE
error parse ELF stripped

### ISSUE THREAD

**Issue by sh4m2hwz** [lief-project/LIEF#595]
binary: https://pastebin.com/HeRaWfUc
fragment py:
>>> from lief import *
>>> bin = parse("code")
The current binary doesn't have a section header
The current binary doesn't have a section header
>>>

**Comment by sh4m2hwz** [comment]
lol ,it is very good loader,but in real life ,it is crush :D

**Comment by sh4m2hwz** [comment]
elf format is not orientated for section headers,Linux kernel loader orientation for program headers

**Comment by romainthomas** [comment]
Yes and LIEF supports section-less binaries.
