### ISSUE TITLE
Compilation issues with Visual Studio 2017

### ISSUE THREAD

**Issue by JaceCearK1** [lief-project/LIEF#6]
This is my main.cpp (no errors; so I **assume** it's not the source):

```
#include <iostream>
#include <LIEF/LIEF.hpp>

int main(int argc, const char** argv) {
	LIEF::PE::Binary* openedExe = LIEF::PE::Parser::parse("C:\\Windows\\explorer.exe");
	std::cout << *openedExe << std::endl;
	delete openedExe;
}
```

These are the error codes; MSDN didn't really provide potencial fixes.
**Note:** I translated the error messages manually, so they might not be a 1:1 translation.
They appear 7 times each, all in "iterators.hpp"

./include/LIEF/iterators.hpp(125): **error C2065: "not": undeclared identifier**
./include/LIEF/iterators.hpp(228): **note: See reference to class Template instantiation "LIEF::ref_iterator<T>", that is compiled.**
./include/LIEF/iterators.hpp(125): **error C2059: Syntax error: "std::is_pointer<_Uty>::value"**
./include/LIEF/iterators.hpp(125): **error C2975: "_Test": Invalid Templete argument for "std::enable_if", constant compile time expression expected.**
./include/xtr1common(56): **note: See declaration of "_Test"**

**Comment by romainthomas** [comment]
You should add the ``iso646.h`` file or add the ``/FIiso646.h`` flag.

See also: https://github.com/lief-project/LIEF/blob/master/examples/cpp/CMakeLists.txt#L51

**Comment by JaceCearK1** [comment]
(For clarification: I used the release version 0.6.0.)
main.cpp itself gets compiled into an .obj file just fine, but it won't compile into a PE:

_These occured once:_
libcpmt.lib(xwctomb.obj) : **error LNK2005: _Getcvt is already defined in msvcprtd.lib(MSVCP140D.dll)**
LIEF-Test.exe : **fatal error LNK1169: At least one symbol defined multiple times**

_These occured many times in many object files included in LIEF.lib:_
LIEF.lib(Binary.cpp.obj) : **error LNK2038: Conflict determined for "_ITERATOR_DEBUG_LEVEL": The value "0" is not equal to "2" in main.obj.**
LIEF.lib(Binary.cpp.obj) : **error LNK2038: Conflict determined for "RuntimeLibrary": The value "MT_StaticRelease" is not equal to "MDd_DynamicDebug" in main.obj.**

**Comment by romainthomas** [comment]
You should try to compile your ``main.cpp`` in release mode and not debug mode. 
You can look at these flags:
https://github.com/lief-project/LIEF/blob/master/examples/cpp/CMakeLists.txt#L50

BTW: ``pe_reader.cpp`` compiles (and run) successfully on Windows: https://ci.appveyor.com/project/Romain/lief/build/0.4.3/job/ro4udt7qd5ixsg0h#L1811

**Comment by romainthomas** [comment]
@JaceCearK1 I documented the configuration to use the Windows SDK: https://github.com/lief-project/LIEF/commit/67d759ee201fe88ca524b7ca85bfa48bf0eba37a

**Comment by JaceCearK1** [comment]
Ah, switching the /MD-flag to /MT was the last step to fixing it!
Thank you very much! :)
Something OffTopic that now occured to me is that s5.png is not being loaded in [installation.rst](https://github.com/lief-project/LIEF/blob/67d759ee201fe88ca524b7ca85bfa48bf0eba37a/doc/sphinx/installation.rst)
I can't seem to find a typo though; maybe Git's at fault here! Try renaming it back to _static/windows_sdk/s6.png and look whether it fixes the issue.

**Comment by romainthomas** [comment]
Now the documentation is available here: https://lief.quarkslab.com/doc/installation.html#windows-sdk
