### ISSUE TITLE
Read out of bound

### ISSUE THREAD

**Issue by Rafiot** [lief-project/LIEF#60]
I'm not sure about the proper way to handle it, but the two following samples raise a `lief.read_out_of_bound exception` when calling `pe.resources_manager.version.string_file_info.langcode_items`:

https://github.com/viper-framework/pefile-tests/blob/master/tests/corkami/pocs/version_cust.exe
https://github.com/viper-framework/pefile-tests/blob/master/tests/corkami/pocs/version_mini.exe

**Comment by romainthomas** [comment]
For this kind of API, the user should be responsible for handle such exception (In this case *corruption*). 

See 347d607

**Comment by Rafiot** [comment]
Makes sense.
