### ISSUE TITLE
Segmentation fault from Python bindings when iterating relocations on temporary binary

### ISSUE THREAD

**Issue by williballenthin** [lief-project/LIEF#600]
**Describe the bug**
When iterating over the relocations of a parsed binary from a Python script, LIEF may segmentation fault. This seems to happen when the binary is "temporary"; that is, something like `lief.parse(buf).relocations`.

**To Reproduce**

```py
import sys
import lief

path = sys.argv[1]
with open(path, "rb") as f:
    buf = f.read()

for relocation in lief.parse(buf).relocations:
    print(relocation)
```

**Expected behavior**
I never desire unsafe behavior (such as a segmentation fault or memory access violation) when using a Python library (unless, of course, I'm doing something explicitly unsafe, like using ctypes to make native calls. LIEF does not fit this category to me). 

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04
 - Target format ELF
 - LIEF commit version: 0.11.5-37bc2c9

**Additional context**
I recognize that there may be some difficulty in maintaining the lifetime of the parse results. I'd would *much* rather that the iterator throw an exception rather than segfault.

I really like using LIEF; however, encountering segfaults from within Python gives me pause, since I often process malicious samples. Yes, I should (and do) sandbox :-)

**Comment by romainthomas** [comment]
Hi @williballenthin 

Actually this is not a segfault from LIEF internal engines but an issue with Python variable life span.
Here is the diff that fixes the issue:

```diff
< for relocation in lief.parse(buf).relocations:
---
> bin = lief.parse(buf)
>
> for relocation in bin.relocations:
```
