### ISSUE TITLE
Option to not use vendored/embedded depdnencies

### ISSUE THREAD

**Issue by autoantwort** [lief-project/LIEF#605]
**Is your feature request related to a problem? Please describe.**
I would like to add this package to vcpkg, but vcpkg forbids vendored/embedded dependencies. 

**Describe the solution you'd like**
An option do disable the use of vendored/embedded dependencies.

**Comment by romainthomas** [comment]
Do you have a reference to the documentation to explain what they mean by *packaged dependencies* ?

**Comment by autoantwort** [comment]
Sorry, that was the wrong term. I am referring to [this](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-vendored-dependencies).

**Comment by romainthomas** [comment]
Done
