### ISSUE TITLE
Macho string table size is wrong

### ISSUE THREAD

**Issue by cocos543** [lief-project/LIEF#607]
**Describe the bug**
Macho file.

**To Reproduce**
```
void ExtractMacho(const char *path, const char *arch, char destPath[1024]) {
    try {
        std::unique_ptr<LIEF::MachO::FatBinary> macho = LIEF::MachO::Parser::parse(path);

        for (LIEF::MachO::Binary& binary : *macho) {
            LIEF::MachO::Header& header = binary.header();
            std::cout << header << std::endl;
            
            if (header.cpu_type() == LIEF::MachO::CPU_TYPES::CPU_TYPE_X86_64 && strcmp(arch, "x86_64") == 0) {
                sprintf(destPath, "%s.x86_64", path);
                binary.write(destPath);
                return;
            }
        }
    } catch (const LIEF::exception& err) {
        std::cerr << err.what() << std::endl;
    }
}
```

**Expected behavior**

**Environment (please complete the following information):**
 - System and Version : MacOS 10.15.7
 - Target format: Mach-O

![image](https://user-images.githubusercontent.com/7421499/133736950-41cf6120-9470-4354-842f-6a03eea37192.png)

**Comment by romainthomas** [comment]
Why it's wrong ?

**Comment by rockbean** [comment]
Reproduced in my test:
MacOS 11.6 in x86_64
Test App: Google Chrome 95.0.4638.54
LIEF 0.10.0 ~ 0.11.5 all have this issue

It seems there's not enough space to add the new LC_LOAD_DYLIB in the original Chrome Mach-O file. 

Even if I only remove the signature of the Mach-O, the size of the string table is still wrong, which is too large.

**Comment by romainthomas** [comment]
Should be fixed now, feel free to re-open if that's not the case.
