### ISSUE TITLE
Load an ELF and write, segment fault(core dumped)

### ISSUE THREAD

**Issue by wuuuudle** [lief-project/LIEF#611]
**Describe the bug**
load an ELF and write, segment fault(core dumped)

**To Reproduce**
```cpp
#include <LIEF/LIEF.hpp>

int main() {
    auto elf = LIEF::ELF::Parser::parse("ELF1");
    elf->write("ELF1.1");
}
```
and the source of ELF1 is
```cpp
#include <iostream>
#include <atomic>

using namespace std;

int main() {
    cout << "Hello World:" << NAME << endl;
    for (int i = 0;; i++) {
        cout << i << endl;
        sleep(1);
    }
    return 0;
}
```

**Expected behavior**
The ELF file "ELF1.1" run normal.

**Environment (please complete the following information):**
 - System and Version : Linux manjaro 5.10.68-1-MANJARO [Manjaro 21.1.4 Pahvo]
 - Target format: ELF
 - LIEF commit version: 0.12.0

**Additional context**
I used edb to trace "ELF1.1". The problem comes from the segment NOTE. 
source file "Builder.tcc"
```cpp
  if (segment_note.physical_size() < raw_notes.size() and segment_note.physical_size() > 0) {
    LIEF_INFO("Segment Note needs to be relocated");
    Segment note = segment_note;
    note.virtual_address(0);
    note.file_offset(0);
    note.physical_address(0);
    note.physical_size(0);
    note.virtual_size(0);
    note.content(raw_notes.raw());
    this->binary_->replace(note, segment_note);
    return this->build<ELF_T>();
  }
```
The segment NOTE had been relocated to 0x10000(file offset), and LOAD segments not include new position. Therefore, illegal memory access occurs when the interpreter(ld-2.33.so) load the segments.
ELF1 and ELF1.1 is [here](https://github.com/lief-project/LIEF/files/7246629/elf.zip).

**Comment by romainthomas** [comment]
Duplication of #482
