### ISSUE TITLE
MachO dyld_info size adjustment

### ISSUE THREAD

**Issue by Sunr1seSun** [lief-project/LIEF#612]
**Is your feature request related to a problem? Please describe.**
```
Load command 5
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 0
    rebase_size 0
       bind_off 2818048
      bind_size 2872
  weak_bind_off 0
 weak_bind_size 0
  lazy_bind_off 0
 lazy_bind_size 0
     export_off 2820896
    export_size 17928
```
Things happen in dyld. If I make a difference to a binary and let the bind_size change, lief will fix bind_size (export_size is also the case) to the new size without considering about others offset in `Builder::build`.
I have to fix the offset after build manully.

**Describe the solution you'd like**
I have considered 2 possibilities about the condition:
1. Lief help me fix the offset automaticly.
2. Lief can provide api to let me fix dyld before build.

**Describe alternatives you've considered**
I have to fix the binary in hexedit now, there may be any better ideas.

**Comment by Sunr1seSun** [comment]
Perhaps the issue I have opened is not the main aspect, I found some program can't run any more after lief.MachO.Binary.write().

https://opensource.apple.com/source/ld64/ld64-609/src/ld/LinkEdit.hpp.auto.html
```c
// First push the total number of binds so that we can allocate space for this in dyld.
if ( log ) fprintf(stderr, &quot;BIND_SUBOPCODE_THREADED_SET_BIND_ORDINAL_TABLE_SIZE_ULEB(%lld)\n&quot;, numBinds + 1);
```
```
case BIND_SUBOPCODE_THREADED::BIND_SUBOPCODE_THREADED_SET_BIND_ORDINAL_TABLE_SIZE_ULEB:
   {
   output << tab << std::string("[") + to_string(subopcode) + "]\n";
   count = bind_stream.read_uleb128();
   ordinal_table_size = count + 1; // the +1 comes from: 'ld64 wrote the wrong value here and we need to offset by 1 for now.'
   use_threaded_rebase_bind = true;
   ordinal_table.reserve(ordinal_table_size);
   output << tab << tab << fmt::format("Ordinal table size := {:d}\n", count);
   break;
   }
```
ls64 has been update, maybe this is the cause.

**Comment by romainthomas** [comment]
Which platform ? Mac M1?

**Comment by Sunr1seSun** [comment]
> Which platform ? Mac M1?

yes

**Comment by romainthomas** [comment]
So the issue is more about code signing.
