### ISSUE TITLE
Build with an external spdlog install fails on windows

### ISSUE THREAD

**Issue by neuralmer** [lief-project/LIEF#616]
**Describe the bug**
Building LIEF with an external installation of `spdlog` fails on Windows with a compile error. Many compile errors of the form: `LIEF\include\LIEF/PE/Structures.hpp(540): error C2589: 'constant': illegal token on right side of '::'` are emitted.

**To Reproduce**
```
    cd spdlog
    git checkout v1.8.5
    cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX:PATH='C:\src\mike\lib' .
    cmake --build . --config Release
    cmake --install . --config Release
    cd ..\LIEF
    git checkout 717e4e9
    cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE="Release" -DLIEF_EXTERNAL_SPDLOG="on" -Dspdlog_DIR="C:\src\mike\lib\lib\cmake\spdlog" .
    cmake --build .
```

**Expected behavior**
The build should complete with out error.

**Actual behavior**
The compile initially fails trying to compile `src/PE/utils.cpp`.

**Environment (please complete the following information):**
 - System and Version : Windows 10, Visual Studio 2017, MSVC 19.16.27027.1
 - Target format : irrelevant, we don't get that far
 - LIEF commit version: 717e4e9, LIEF 0.77.0

**Additional context**
With a successful compilation (using the included `spdlog`), looking at the precompiled output I can see:
```
static const HEADER_CHARACTERISTICS header_characteristics_array[] = {
  HEADER_CHARACTERISTICS::IMAGE_FILE_INVALID,
  HEADER_CHARACTERISTICS::IMAGE_FILE_RELOCS_STRIPPED,
  HEADER_CHARACTERISTICS::IMAGE_FILE_EXECUTABLE_IMAGE,
  HEADER_CHARACTERISTICS::IMAGE_FILE_LINE_NUMS_STRIPPED,
...
```

With an external spdlog, that same section is:
```
static const HEADER_CHARACTERISTICS header_characteristics_array[] = {
  HEADER_CHARACTERISTICS::IMAGE_FILE_INVALID,
  HEADER_CHARACTERISTICS::0x0001,
  HEADER_CHARACTERISTICS::0x0002,
  HEADER_CHARACTERISTICS::0x0004,
...
```

I tried compiling against my `spdlog` and found that worked so long as the `-DLIEF_EXTERNAL_SPDLOG="on"` was not in effect. Adding this define appears to cause the issue. It isn't clear if `undef.h` isn't being applied at the right place or what is going on.

I added:
```
#define LIEF_PE_FORCE_UNDEF
#include "LIEF/PE/undef.h"
```
After `#include "LIEF/PE/utils.hpp"` in `src/PE/utils.cpp`, and this fixed compilation for _that file_, but another file also had the issue. I suspect that this is not the right way to fix this issue.

I did notice that a successful compile of `utils.cpp` will emit the `LIEF will disable #define enums. Please use LIEF_PE_XXXX or LIEF::PE::XXXX instead!` message, but the failed compile of `utils.cpp` will not.

I have tested this same configuration on macOS without issue.

**Comment by ekilmer** [comment]
@romainthomas I am encountering something similar to this issue during my experiments in packaging LIEF for vcpkg https://github.com/microsoft/vcpkg/pull/22957.

I've tried the workaround mentioned here by @neuralmer and it seems to work, but I also think there is probably a better fix?

The following patch included in the vcpkg PR (applied to current `master`@https://github.com/lief-project/LIEF/commit/05e3c6eb7cd0ca67c97208e34ac7b815ad0f318e) seems to fix the compilation errors on Windows, but I have no idea the impact

```diff
diff --git a/include/LIEF/PE/enums.hpp b/include/LIEF/PE/enums.hpp
index 0175eb38..dec357de 100644
--- a/include/LIEF/PE/enums.hpp
+++ b/include/LIEF/PE/enums.hpp
@@ -17,6 +17,7 @@
 #include <inttypes.h>
 #include <cstddef>
 #include "LIEF/enums.hpp"
+#define LIEF_PE_FORCE_UNDEF
 #include "LIEF/PE/undef.h"
 
 namespace LIEF {
diff --git a/src/PE/Binary.cpp b/src/PE/Binary.cpp
index 76f5deb6..0cd58cbe 100644
--- a/src/PE/Binary.cpp
+++ b/src/PE/Binary.cpp
@@ -34,6 +34,8 @@
 #include "LIEF/PE/Binary.hpp"
 #include "LIEF/PE/Builder.hpp"
 #include "LIEF/PE/utils.hpp"
+#define LIEF_PE_FORCE_UNDEF
+#include "LIEF/PE/undef.h"
 #include "LIEF/PE/EnumToString.hpp"
 #include "LIEF/PE/ResourceDirectory.hpp"
 #include "LIEF/PE/ResourceData.hpp"
diff --git a/src/PE/Builder.cpp b/src/PE/Builder.cpp
index f6aa79de..b18fde8a 100644
--- a/src/PE/Builder.cpp
+++ b/src/PE/Builder.cpp
@@ -27,6 +27,8 @@
 #include "LIEF/PE/Builder.hpp"
 #include "LIEF/PE/ResourceData.hpp"
 #include "LIEF/PE/utils.hpp"
+#define LIEF_PE_FORCE_UNDEF
+#include "LIEF/PE/undef.h"
 #include "LIEF/PE/ImportEntry.hpp"
 #include "LIEF/PE/Import.hpp"
 #include "LIEF/PE/Section.hpp"
diff --git a/src/PE/utils.cpp b/src/PE/utils.cpp
index 3545fec3..5158ed8f 100644
--- a/src/PE/utils.cpp
+++ b/src/PE/utils.cpp
@@ -29,6 +29,8 @@
 #include "LIEF/exception.hpp"
 
 #include "LIEF/PE/utils.hpp"
+#define LIEF_PE_FORCE_UNDEF
+#include "LIEF/PE/undef.h"
 #include "LIEF/PE/Binary.hpp"
 #include "LIEF/PE/Import.hpp"
 #include "LIEF/PE/ImportEntry.hpp"
```

**Comment by romainthomas** [comment]
Ack I'll create a branch with this patch to see if it has side-effect.

**Comment by romainthomas** [comment]
Done. (Waiting for the CI)

**Comment by romainthomas** [comment]
I merged the branch (https://github.com/lief-project/LIEF/commit/e61cba8dccbf2b1b6f790e5441f76a9cb3b58893)

**Comment by romainthomas** [comment]
@neuralmer could you try and tell us if you still face this issue with the recent changes in the master branch?
