### ISSUE TITLE
Question: how to use LIEF to resign?

### ISSUE THREAD

**Issue by dreamland94518** [lief-project/LIEF#618]
I use lief to inject my own library to the mach-o file by the followings:

    std:unique_ptr<LIEF::MachO::FatBinary> binaries::Parser::parse(".......");
    MachO::Binary& binary = binaries->back();
    binary.remove_signature();
    binary.add_library("......");
    binary.write();

Now, I wan't to re-sign the binary when modification finished, but I don't know how to do it , does LIEF provide the ability to resign the signature?

**Comment by romainthomas** [comment]
No LIEF does not provide such functionality. You need to use ``codesign``
