### ISSUE TITLE
[ELF-API] Inconsistent member names

### ISSUE THREAD

**Issue by ner0x652** [lief-project/LIEF#62]
The program header size is named `program_header_size` [1](https://github.com/lief-project/LIEF/blob/master/api/python/ELF/objects/pyHeader.cpp#L110) when the section header size is `sizeof_section_header` [2](https://github.com/lief-project/LIEF/blob/master/api/python/ELF/objects/pyHeader.cpp#L120). I suggest to make them alike.

**Comment by romainthomas** [comment]
It make sense. Thanks
