### ISSUE TITLE
The content of DyldInfo is incorrect after build the binary

### ISSUE THREAD

**Issue by rockbean** [lief-project/LIEF#624]
**Describe the bug**
Just write the Chrome to another file, the content of DyldInfo is wrong that I couldn't run Chrome with the new file.
```
dyld: malformed mach-o image: dyld lazy bind info overlaps weak bind info
[1]    21724 abort      ./Google\ Chrome
```
I just find this issue in the latest Google Chrome, the old one seems good to run.

**To Reproduce**
```
import lief
app = lief.parse("/xxxxx/Google Chrome.app/Contents/MacOS/Google Chrome")
app.write("/xxxxx/Google Chrome.app/Contents/MacOS/Google Chrome.new")
```

**Expected behavior**
Chrome should be as same as the original one.

**Environment (please complete the following information):**
 - System and Version : MacOS 11.6
 - Target format: Mach-O
 - LIEF commit version:  0.11.5
 - Google Chrome version: 95.0.4638.54

**Additional context**
Diff:
![image](https://user-images.githubusercontent.com/1439230/138277078-7575f464-0d46-4c5e-aadd-123858cf465e.png)

**Comment by romainthomas** [comment]
Should have been fixed with the new Mach-O builder.
