### ISSUE TITLE
How to create a segment with virtual_size different than physical_size?

### ISSUE THREAD

**Issue by bambu** [lief-project/LIEF#625]
I'm trying to create a segment in an ELF that has no content and a large virtual size. I have tried the following and verified the result with readelf:

1. Create a segment with no content, set virtual size, write elf
2. Create a segment with no content, set alignment to size that i want, write elf
3. Create a segment with a byte for content, set alignment / virtual size, write elf 
4. Tried `elf.extend` to extend my created size

For case 1 and 2 we end up with physical / virtual size of 0.
For case 3 we end up with physical / virtual size of 0x1000 despite alignment being set to larger than 0x1000
For case 4 it shifted the physical / virtual address by the amount of the size and then had the same size for physical / virtual size. 

Is there a way to create a segment with differing virtual and physical size or really any size greater than the content being provided to it? 

If i manually edit the elf after adding the segment to have a differing `p_memsz` then readelf is happy. However, I would prefer not to load and manually parse the ELF to make that change.

**Comment by bambu** [comment]
I ended up figuring this out not too long after creating this ticket. You have to first add the segment and then use the segment that is returned by `elf.add` to set the virtual size.

The following should work:
```python
# create segmetn
segment = lief.ELF.Segment()
segment.type = lief.ELF.SEGMENT_TYPES.LOAD
segment.flags = lief.ELF.SEGMENT_FLAGS.R
segment.virtual_address = 0x1230000

# add to elf then change size on new instance of segment
new_seg_inst = elf.add(segment)
new_seg_inst.virtual_size = 0x1000000

# write elf to disk
elf.write('/some/path/test.elf')
```

It would be nice to not have to get the new instance of the segment and just be able to specify it before adding it.

**Comment by mcejp** [comment]
I have run into the same problem -- this really feels like a bug, since the set `virtual_address` value is ignored silently.
