### ISSUE TITLE
init_array with relocated syms

### ISSUE THREAD

**Issue by FatsharkGo** [lief-project/LIEF#626]
**Is your feature request related to a problem? Please describe.**
In some shared object, entries of init vector maybe rels, `binary[lief.ELF.DYNAMIC_TAGS.INIT_ARRAY].array` would return the vector with un-relocated array which have to be relocated for the  next iteration process.

**Describe the solution you'd like**
Add an attribute `array_r` to return the relocated init_array will be helpfull.

**Describe alternatives you've considered**
Na~

**Additional context**
Na~

**Comment by romainthomas** [comment]
Hi @FatsharkGo 
I completely understand your need but I would say it should come from a post-processing of the parsing. Similarly,
we do not provide relocation information between plt relocations and plt stubs.
