### ISSUE TITLE
Publish Python 3.10 whl

### ISSUE THREAD

**Issue by williballenthin** [lief-project/LIEF#627]
Would you please publish to PyPI a LIEF whl for Python 3.10? 

Personally, I would be fine with this to be from the 0.11.5 tag if you don't want to create a new release.

**Comment by romainthomas** [comment]
I'll try to setup the CI for Python 3.10 this week-end

**Comment by coperni** [comment]
Bumping this request. Our CICD has been slammed by build.

**Comment by romainthomas** [comment]
I uploaded the Python 3.10 wheels for LIEF 0.11.5

**Comment by coperni** [comment]
Lifesaver! Thank you
