### ISSUE TITLE
[Python-API] Flags member name inconsistency

### ISSUE THREAD

**Issue by ner0x652** [lief-project/LIEF#63]
`Section` has a `flags` member : [section](https://github.com/lief-project/LIEF/blob/master/api/python/ELF/objects/pySection.cpp#L56), while `Segment` has `flag` member : [segment](https://github.com/lief-project/LIEF/blob/master/api/python/ELF/objects/pySegment.cpp#L47), but the description says "flags".

**Comment by romainthomas** [comment]
Nice catch!
