### ISSUE TITLE
Dynamic symbol over-counting using GNU_HASH sections

### ISSUE THREAD

**Issue by adamjseitz** [lief-project/LIEF#632]
**Describe the bug**

When using the `LIEF::ELF::DYNSYM_COUNT_METHODS::COUNT_HASH` (or `COUNT_AUTO`, which is default) methods for counting dynamic symbols of an ELF with a `GNU_HASH` section, it may over-count the symbols. This means when using the dynamic symbol iterator, symbols can be read from beyond the end of the `.dynsym` section.

The bug results from not handling bucket elements with index 0; the blog below notes that 0 is a reserved value:

> A bucket element will contain the index 0 if there is no symbol in the hash table for the given value of N. As index 0 of the dynsym is a reserved value, this index cannot occur for a valid symbol, and is therefore non-ambiguous.

https://blogs.oracle.com/solaris/post/gnu-hash-elf-sections

Additionally, looking at the history of this project, the `COUNT_HASH` and `COUNT_RELOCATIONS` options were added to support binaries with no section information. This bug occurs even if section information is present. In my opinion, the `.dynsym` section size should be used to calculate the definitive dynamic symbol count in `AUTO` mode if section information is present, since it is less complex and should be faster and less error-prone.

**To Reproduce**

```cpp
#include <LIEF/LIEF.hpp>

int main(void)
{
    std::string Path = "./sample.elf";

    std::unique_ptr<LIEF::ELF::Binary> ElfSection{LIEF::ELF::Parser::parse(Path, LIEF::ELF::DYNSYM_COUNT_METHODS::COUNT_SECTION)};
    LIEF::ELF::it_symbols SectionSymbolIt = ElfSection->dynamic_symbols();
    std::cout << "Section Count: " << std::distance(std::begin(SectionSymbolIt), std::end(SectionSymbolIt)) << std::endl;

    std::unique_ptr<LIEF::ELF::Binary> ElfHash{LIEF::ELF::Parser::parse(Path, LIEF::ELF::DYNSYM_COUNT_METHODS::COUNT_HASH)};
    LIEF::ELF::it_symbols HashSymbolIt = ElfHash->dynamic_symbols();
    std::cout << "Hash Count: " << std::distance(std::begin(HashSymbolIt), std::end(HashSymbolIt)) << std::endl;
}
```

This requires having a binary with some empty buckets in `GNU_HASH`, and with values such that the loop that checks for the end of hash chains walks beyond the end of the section. I have one that I can share if needed, but it's > 100 MB so too large to attach here.

**Expected behavior**
`COUNT_HASH` and `COUNT_SECTION` should return the same number of symbols; `COUNT_HASH` should not return more symbols than could possibly fit in the `.dynsym` section.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04
 - Target format: ELF
 - LIEF version: 0.11.5

**Additional context**
I will create a PR with fixes shortly.

**Comment by romainthomas** [comment]
Hi @adamjseitz 
I also observed this kind of issue while processing ``libcrypto.so``. I pushed your MR in a branch ([fix/gnu_hash_counting](https://github.com/lief-project/LIEF/tree/fix/gnu_hash_counting)) to run the complete CI pipeline.
