### ISSUE TITLE
A corrupted ELF section causes out of bound read and segmentation fault

### ISSUE THREAD

**Issue by jkilopu** [lief-project/LIEF#635]
**Describe the bug**
Getting the content of a corrupted ELF section causes out of bound read and segmentation fault in LIEF.

**To Reproduce**
The following example causes segmentation fault.
```
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
>>> lief.__version__
'0.11.5-37bc2c9'
>>> binary = lief.parse("./lief_crash")
  Section #0 is too large!
  Section #2 is too large!
  Section #3 is too large!
  Can't parse section #04
Unable to fetch the string section
  Section #0 is too large!
  Section #2 is too large!
  Section #3 is too large!
  Can't parse section #04
Unable to fetch the string section
>>> print(binary)
Segmentation fault
```

**Expected behavior**
Check the offset and size of sections. If they are corrputed, throw an error.

**Environment:**
 - System and Version : Ubuntu 20.04
 - Target format: ELF
 - Target binary:  [lief_crash.zip](https://github.com/lief-project/LIEF/files/7698991/lief_crash.zip)
 - LIEF commit version: 0.11.5-37bc2c9

**Additional context**
It seems that from initializing the section object to printing the content of section, no check is performed against the offset and size of sections.
In `std::vector<uint8_t> Section::content(void) const`, the following code may cause out of bound read：
https://github.com/lief-project/LIEF/blob/162f15d8846d14b8193099dfeed2a5eb944753da/src/ELF/Section.cpp#L263-L265

**Comment by romainthomas** [comment]
Fixed in the nightly build
