### ISSUE TITLE
Extract information whether the optional_header.magic is corrupted or not

### ISSUE THREAD

**Issue by gdesmar** [lief-project/LIEF#644]
I've encounter some samples, like cabe2e9ff9de316e771db57c8a60cbe42bdd027d01559e259887c5f3faa45c7c, which can not be read by LIEF because of a bad/corrupted optional_header.magic. There is a lot of information related to sections and other parts of the PE that could still be retrieved. It would be nice if LIEF could parse it still.

The sample can be found using 
> wget -O- sorel-20m.s3.amazonaws.com/09-DEC-2020/binaries/cabe2e9ff9de316e771db57c8a60cbe42bdd027d01559e259887c5f3faa45c7c | zlib-flate -uncompress > cabe2e9ff9de316e771db57c8a60cbe42bdd027d01559e259887c5f3faa45c7c

Thank you.

**Comment by romainthomas** [comment]
Does this sample is able to run?

**Comment by gdesmar** [comment]
Yes. I just loaded that file in a VM and it created a new folder right next to the exe.
The sorel dataset have neutralized samples, and in the case of that one, after running the wget into the zlib-flate, you can use the following code to re-arm it completely.

```python
with open("cabe2e9ff9de316e771db57c8a60cbe42bdd027d01559e259887c5f3faa45c7c.neut", "rb") as f: data = bytearray(f.read())
data[0x104] = 0x4c
data[0x105] = 0x01
data[0x15c] = 0x02
with open("cabe2e9ff9de316e771db57c8a60cbe42bdd027d01559e259887c5f3faa45c7c.exe", "wb") as f: f.write(data)
```

Here are the sha256 of the files.
```
83dbffb567a1f7b2fb2ef1dabf7bd61113629f64a9bfb72c7e62a299c6128c95  cabe2e9ff9de316e771db57c8a60cbe42bdd027d01559e259887c5f3faa45c7c.zlib
d559249c6dcebf50b388d9dce55b5ab48de6b342329b0814080c4b48842fadb3  cabe2e9ff9de316e771db57c8a60cbe42bdd027d01559e259887c5f3faa45c7c.neut
cabe2e9ff9de316e771db57c8a60cbe42bdd027d01559e259887c5f3faa45c7c  cabe2e9ff9de316e771db57c8a60cbe42bdd027d01559e259887c5f3faa45c7c.exe
```

I'll trust you to do that safely. :)

**Comment by gdesmar** [comment]
I can search my files to get you a few more examples if it would help.
Sample 384122bbfc512a69bfb1eb03eb97fd7d8368148b4aab80b1827d16f11a030047 is another good one.

> wget -O- sorel-20m.s3.amazonaws.com/09-DEC-2020/binaries/384122bbfc512a69bfb1eb03eb97fd7d8368148b4aab80b1827d16f11a030047 | zlib-flate -uncompress > 384122bbfc512a69bfb1eb03eb97fd7d8368148b4aab80b1827d16f11a030047.neut

With the following code as fix.py
```python
import sys
filename = sys.argv[1]
with open(f"{filename}", "rb") as f: data = bytearray(f.read())
data[0x104] = 0x4c
data[0x105] = 0x01
data[0x15c] = 0x02
with open(f"{filename.split('.')[0]}.exe", "wb") as f: f.write(data)
```

> fix.py 384122bbfc512a69bfb1eb03eb97fd7d8368148b4aab80b1827d16f11a030047.neut

Which should result in the following:
```bash
$ sha256sum 384122bbfc512a69bfb1eb03eb97fd7d8368148b4aab80b1827d16f11a030047.exe
384122bbfc512a69bfb1eb03eb97fd7d8368148b4aab80b1827d16f11a030047  384122bbfc512a69bfb1eb03eb97fd7d8368148b4aab80b1827d16f11a030047.exe
```

**Comment by romainthomas** [comment]
Hi @gdesmar I did not forget this issue. Currently I'm busy on reviewing the whole documentation of LIEF and I'll address this issue after.
