### ISSUE TITLE
lief.PE.Header' object has no attribute 'is_32

### ISSUE THREAD

**Issue by inaryart** [lief-project/LIEF#649]
**Describe the bug**
'lief.PE.Header' object has no attribute 'is_32'

**To Reproduce**
use ` liefBinary.header.is_32`

**Expected behavior**
provide a function or field to determine the number of bits

**Environment (please complete the following information):**
 - System and Version : windows
 - Target format:  lief-0.11.5
 - LIEF commit version: 0.11.5-551ede5

**Additional context**
n/a

**Comment by limitedeternity** [comment]
`liefBinary.abstract.header.is_32`

**Comment by limitedeternity** [comment]
Use `liefBinary.abstract.header.is_32`.
Hint: always explicitly specify whether you want to access an **abstract** representation of binary or a **concrete** one.

**Comment by limitedeternity** [comment]
Use `liefBinary.abstract.header.is_32`.
Hint: always explicitly specify whether you want to access an **abstract** representation of the binary or a **concrete** one.
