### ISSUE TITLE
Add computing/recomputing of PE checksum

### ISSUE THREAD

**Issue by gdesmar** [lief-project/LIEF#660]
I would like to validate the checksum value found in the optional header. It would be better if I could have the real checksum as a value and not only a boolean to tell me if it's right or not. Using sample 202260c2ee4906215108dcbc56306fc688583a9f32c880aa833a0fdf32780067 as an example, we can use PEStudio to see a discrepancy between the stored value and the expected value.
![image](https://user-images.githubusercontent.com/75089569/151173185-88e095ad-3679-4123-990a-8c2b07c397b1.png)
You can get the sample using the following line and script :
> wget -O- sorel-20m.s3.amazonaws.com/09-DEC-2020/binaries/202260c2ee4906215108dcbc56306fc688583a9f32c880aa833a0fdf32780067 | zlib-flate -uncompress > 202260c2ee4906215108
dcbc56306fc688583a9f32c880aa833a0fdf32780067.neut
```python
import sys
filename = sys.argv[1]
with open(f"{filename}", "rb") as f: data = bytearray(f.read())
data[0xe4] = 0x4c
data[0xe5] = 0x01
data[0x13c] = 0x02
with open(f"{filename.split('.')[0]}.exe", "wb") as f: f.write(data)
```

```bash
$ sha256sum *
202260c2ee4906215108dcbc56306fc688583a9f32c880aa833a0fdf32780067  202260c2ee4906215108dcbc56306fc688583a9f32c880aa833a0fdf32780067.exe
a7abab8731a58637c1b62d284f9501cc3a87daacb6e8def2c80cd3d954b3a2f3  202260c2ee4906215108dcbc56306fc688583a9f32c880aa833a0fdf32780067.neut
```

I am not creating or modifying PE files yet, but I believe it would be useful to recompute the checksum found in the optional header to insert a valid value. If it isn't done automatically by the builder, it would be useful to have a way to generate it and set it manually.

Do you think this could be a feature added to LIEF?

**Comment by romainthomas** [comment]
Hi @gdesmar 
Yes this feature would be interesting in LIEF!
