### ISSUE TITLE
When modifying ARM ELF-Executable the resulting file segfaults

### ISSUE THREAD

**Issue by Flole998** [lief-project/LIEF#663]
I have a file:
```ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=XXXXX, stripped```

I am trying to add an additional Segment to this file so I can then add code to that segment later on and jump into it. I am doing it like this:

```
import lief

target = lief.parse("Binary")

segment           = lief.ELF.Segment()
segment.type      = lief.ELF.SEGMENT_TYPES.LOAD
segment.add(lief.ELF.SEGMENT_FLAGS.R)
segment.add(lief.ELF.SEGMENT_FLAGS.X)
segment.content   = [1, 2, 3] * 1024
segment.alignment = 8

target.add(segment)

target.write("Binary_extended")
```

Unfortunately something on the resulting binary is corrupted, it segfaults at some point when it's trying to access a variable. The new segment does not overlap the old one, so that should be fine. I have looked at a hex diff of those 2 files and found quite some differences, a few changes in the ELF header (PHT and SHT offset), ELF offset and symbol table which contain quite some changes. Are all of these changes really necessary? Or could the reason for the segfault be somewhere in those? Right now I am just looking for a way to add an additional executable segment, shouldn't be too hard, right? Also my binary increases it's size from 800kb to 2Mb, there seem to be lot's of 0x00 added at the end.

**Comment by romainthomas** [comment]
Please re-open the issue following the template and providing versions, sample etc
