### ISSUE TITLE
Relocations get written as Little Endian for Big Endian ELFs

### ISSUE THREAD

**Issue by bambu** [lief-project/LIEF#673]
**Describe the bug**
Writing a binary with relocations that is big endian will write the relocations as little endian. This happens just with parsing the file and immediately writing it out.

Example diff using readelf on the original and new elf:
```
Original                                                                     |  Saved with Lief
Relocation section '.rela.text' at offset 0x150c contains 175 entries:       │  Relocation section '.rela.text' at offset 0x150c contains 175 entries:
   Offset     Info    Type            Sym.Value  Sym. Name + Addend          │   Offset     Info    Type            Sym.Value  Sym. Name + Addend
  00000002  00000e06 R_PPC_ADDR16_HA   00000000   memcpy + 0                 │  02000000  060e0000 R_PPC_NONE·······
  0000000e  00000e04 R_PPC_ADDR16_LO   00000000   memcpy + 0                 │  0e000000  040e0000 R_PPC_NONE·······
  0000001e  00001006 R_PPC_ADDR16_HA   00000004   XY_lib + 0                 │  1e000000  06100000 R_PPC_NONE·······
```

**To Reproduce**
The following script should replicate the issue with a big endian binary that has relocations. One thing to note is that the original binary does not have a program header. 

```python
import lief
elf = lief.parse("elf_be_with_relocs")
elf.write("out.elf")
```

**Expected behavior**
Would expect the endianness to be big endian on the `.rela.text` section since it is a big endian binary

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04 / macOS
 - Target format ELF
 - LIEF commit version: 0.11.5-37bc2c9 / 0.11.5-551ede5

**Comment by romainthomas** [comment]
Humm could you try with the master branch and attach the binary?

**Comment by romainthomas** [comment]
Feel free to re-open
