### ISSUE TITLE
PE: Crash is causing by accessing property of a parsed object after the binary object is released

### ISSUE THREAD

**Issue by Sh3idan** [lief-project/LIEF#676]
**Describe the bug**
Once the binary object is released, any property of a saved parsed object (e.g ``section.virtual_address``) cannot be access. It causes a crash.

**To Reproduce**
```py
import lief

def get_executable_sections():
    def _is_executable(s):
        return s.characteristics & 0x20000000 == 0x20000000
    filepath = r"foobar.exe"
    binary = lief.PE.parse(filepath)

    return list(filter(_is_executable, binary.sections))

def main():
    # ``binary = lief.PE.parse(filepath)`` should be here to avoid crash
    for section in get_executable_sections():
        print(f"section va: {section.virtual_address:08X}")

if __name__ == "__main__":
    main()
```

**Expected behavior**
The parsed object and these properties should be independent items.

**Environment (please complete the following information):**
 - System and Version: Windows 10
 - Target format: PE
 - LIEF commit version: 0.11.5-c4774804

**Additional context**

**Comment by romainthomas** [comment]
Hello @Sh3idan 
Actually, this is not an issue. The section life time is tied to the binary object associated with. 
If you want to extract information from the section, you can use the JSON interface from LIEF.
