### ISSUE TITLE
DEBUG conflicts with Xcode keyword

### ISSUE THREAD

**Issue by ccworld1000** [lief-project/LIEF#678]
**Describe the bug**
DEBUG conflicts with Xcode keyword

**To Reproduce**
Run in Xcode13

**Expected behavior**
DEBUG conflicts with Xcode keyword

**Environment (please complete the following information):**
 - System and Version : [macOS 11.6, Xcode13]
 - Target format (Mach-O)
 - LIEF commit version: LIEF-0.11.5-Darwin-x86_64
**Additional context**
LIEF/Abstract/Function.hpp -> enum class FLAGS -> DEBUG

**Comment by ccworld1000** [comment]
What is written above is the answer to the question. The relevant environment will come out as soon as it runs

**Comment by ccworld1000** [comment]
The new version still has this problem

**Comment by jiaxw32** [comment]
> The new version still has this problem

Running in Release Mode resolved my issue
