### ISSUE TITLE
String File Info items are missing or corrupted in 0.12.0

### ISSUE THREAD

**Issue by gdesmar** [lief-project/LIEF#686]
**Describe the bug**
A few items in the String File Info are now missing and others are corrupted.

**To Reproduce**
Download the malware file attached to this issue: [bdfa7195fc318cb4f232c63479fd904887e2989a8bbd57aab9eeb57210a7471a.zip](https://github.com/lief-project/LIEF/files/8372983/bdfa7195fc318cb4f232c63479fd904887e2989a8bbd57aab9eeb57210a7471a.zip)
Extract the file using the password `liefsample`.
Verify that your new file has the right hash:
```bash
$ sha256sum bdfa7195fc318cb4f232c63479fd904887e2989a8bbd57aab9eeb57210a7471a
bdfa7195fc318cb4f232c63479fd904887e2989a8bbd57aab9eeb57210a7471a  bdfa7195fc318cb4f232c63479fd904887e2989a8bbd57aab9eeb57210a7471a
```

Using LIEF 0.11.5
```python
>>> import lief
>>> lief.__version__
'0.11.5-c4774804'
>>> b = lief.parse("bdfa7195fc318cb4f232c63479fd904887e2989a8bbd57aab9eeb57210a7471a")
Unable to find the section associated with BOUND_IMPORT
>>> b.resources_manager.version.string_file_info.langcode_items[0].items
{'OriginalFilename': b'd7x.exe', 'InternalName': b'd7x', 'ProductVersion': b'21.09.2402', 'FileVersion': b'21.09.2402', 'ProductName': b'd7x', 'LegalCopyright': b'd7xTech (formerly Foolish IT)', 'FileDescription': b'd7x (PC Repair Multi-Tool)', 'CompanyName': b'd7xTech (formerly Foolish IT)'}
```

Using LIEF 0.12.0
```python
>>> import lief
>>> lief.__version__
'0.12.0-f8918911'
>>> b = lief.parse("bdfa7195fc318cb4f232c63479fd904887e2989a8bbd57aab9eeb57210a7471a")
Unable to find the section associated with BOUND_IMPORT
>>> b.resources_manager.version.string_file_info.langcode_items[0].items
String.wType should be 0 or 1 instead of 105
String.wType should be 0 or 1 instead of 114
{'r Multi-Tool)': b'`<\x01LegalCopyright', 'CompanyName': b'd7xTech (formerly Foolish IT)'}
```

**Expected behavior**
The previous version was able to extract the right information out of the String File Info, but the new version is able to parse other samples (i.e. a09b7203f9e02a1a3151411390d369be227112ae27594f0ee8dd088e6c4ef7ef) where version 0.11.5 was returning nothing at all. I would prefer for those two sample to have the full list of items from the String File Info.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 18.04
 - Target format : PE

**Additional context**
The attached sample is a malware. Please handle it as such.

**Comment by romainthomas** [comment]
(Still missing an entry)
