### ISSUE TITLE
100% CPU utilization on resources_manager.version

### ISSUE THREAD

**Issue by gdesmar** [lief-project/LIEF#691]
**Describe the bug**
When calling resources_manager.version, the CPU utilization goes to 100% and never returns.

**To Reproduce**
Download the malware file attached to this issue: [1dc4c94163a436c401d163e317e5bdbb55a84600a63ad11805c892d4ad1e5be3.zip](https://github.com/lief-project/LIEF/files/8392529/1dc4c94163a436c401d163e317e5bdbb55a84600a63ad11805c892d4ad1e5be3.zip)
Extract the file using the password `liefsample`.
Verify that your new file has the right hash:
```bash
$ sha256sum 1dc4c94163a436c401d163e317e5bdbb55a84600a63ad11805c892d4ad1e5be3
1dc4c94163a436c401d163e317e5bdbb55a84600a63ad11805c892d4ad1e5be3  1dc4c94163a436c401d163e317e5bdbb55a84600a63ad11805c892d4ad1e5be3
```

Using LIEF 0.11.5
```python
>>> import lief
>>> lief.__version__
'0.11.5-37bc2c9'
>>> b = lief.parse("1dc4c94163a436c401d163e317e5bdbb55a84600a63ad11805c892d4ad1e5be3")
>>> b.resources_manager.version
"key" of the var key should be equal to 'Translation' ()
Try to read 0x2 bytes from 0x364 (366) which is bigger than the binary's size
<lief.PE.ResourceVersion object at 0x7fbe051a7eb0>
>>> b.resources_manager.version.string_file_info
"key" of the var key should be equal to 'Translation' ()
Try to read 0x2 bytes from 0x364 (366) which is bigger than the binary's size
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
lief.not_found: String file info is not present in the current resource
```

Using LIEF 0.12.0
```python
>>> import lief
>>> lief.__version__
'0.12.0-f8918911'
>>> b = lief.parse("1dc4c94163a436c401d163e317e5bdbb55a84600a63ad11805c892d4ad1e5be3")
>>> b.resources_manager.version
String.wType should be 0 or 1 instead of 103
String.wType should be 0 or 1 instead of 114
String.wType should be 0 or 1 instead of 35710
<lief.PE.ResourceVersion object at 0x7fc4d4ffceb0>
>>> b.resources_manager.version.string_file_info.langcode_items[0].items
String.wType should be 0 or 1 instead of 103
String.wType should be 0 or 1 instead of 114
String.wType should be 0 or 1 instead of 35710
{'oduc婍\x90\x03': b'', ' Corporation': b'P&\x01FileDescription', 'Comments': b'Microsoft Firewall'}
```

Using LIEF 0.13.0 (nightly)
```python
>>> import lief
>>> lief.__version__
'0.13.0-946b6655'
>>> b = lief.parse("1dc4c94163a436c401d163e317e5bdbb55a84600a63ad11805c892d4ad1e5be3")
>>> b.resources_manager.version
#Note: This never returns
```

**Expected behavior**
I believed I tested a version between 0.12.0-f8918911 and 0.13.0-946b6655 which had even better results, everything that PEStudio extracts except a different Produc[tName] which is understandably corrupted.
Here is what PEStudio gives : 
![image](https://user-images.githubusercontent.com/75089569/161132258-95b0ba6c-5ace-45bd-b110-bee5378a6993.png)

**Environment**
 - System and Version : Ubuntu 18.04
 - Target format : PE

**Additional context**
The attached sample is a malware. Please handle it as such.

**Comment by romainthomas** [comment]
Thank you for your reporting.

Could I add the samples (neutralized) in the test-suite to avoid regressions?

**Comment by gdesmar** [comment]
> Thank you for your reporting.
> Could I add the samples (neutralized) in the test-suite to avoid regressions?

Absolutely! 
And thanks to you for fixing all of them so fast!
