### ISSUE TITLE
Cannot get __Text segment from a MachO object file

### ISSUE THREAD

**Issue by xiangqianli** [lief-project/LIEF#696]
**Describe the bug**
I have a .o file generated within a .a  MachO static library, with lief, I cannot get __Text segment from object file, while with MachoView the .o file's __Text segment is clear.
![wecom-temp-a819075be4aadb3939d724bb90da1157](https://user-images.githubusercontent.com/15797392/163314122-a20627b4-32f0-4a25-b72a-1cb3569d6ec4.png)
![wecom-temp-a1ba24862c3d0126f8d42397d5dade27](https://user-images.githubusercontent.com/15797392/163314132-0a6c8517-2991-4f5f-a9f5-33e52420f296.png)

but with lief I can get __Text segment from an executable file, does lief not support this ability from object file?

**To Reproduce**
In Python:
![企业微信截图_51ac9d46-64c4-46a1-9fe1-57cabbec7f38](https://user-images.githubusercontent.com/15797392/163315207-d864e080-4879-425e-b6e4-8b4ec0e0804f.png)

> 
> 
> if __name__ == '__main__':
> 
>     fatbinary = lief.MachO.parse("./XQPerson.o", config=lief.MachO.ParserConfig.deep)
>     binary = lief.MachO.FatBinary.take(fatbinary, lief.MachO.CPU_TYPES.ARM64)
>     print_segments(binary)
>     print(binary.get_segment("__TEXT"))

Console Result:
![企业微信截图_b06bc128-fe5a-4652-b267-44fd6504f629](https://user-images.githubusercontent.com/15797392/163314342-c40e7803-2ab4-4184-a939-77a5c83a9723.png)

**Expected behavior**
Get the __Text segment from .o MachO Object file correctly

**Environment (please complete the following information):**
 - System and Version : macOS Big Sur 11.3.1
 - Target format ( Mach-O)
 - LIEF commit version: 0.12.1-c7b3ce3b

**Comment by romainthomas** [comment]
This is on purpose: `LC_SEGMENT` for object files don't have name. On the other hand, you can use `lief.MachO.Section.segment_name`
