### ISSUE TITLE
Allow hooking specific addresses in a binary

### ISSUE THREAD

**Issue by hypervis0r** [lief-project/LIEF#700]
**Is your feature request related to a problem? Please describe.**
In a stripped binary, functions don't have identifiable names. Thus, adding hooks into these functions using `Binary::hook_function` wouldn't work, as `hook_function` takes in a function name.

**Describe the solution you'd like**
I think it would be nice to see an overloaded variant of the `hook_function` API that would allow for specific addresses to be hooked.

**Describe alternatives you've considered**
Looking at how `hook_function` is implemented, I saw that it is basically an `std::map` using the library name and function name as keys. I would just implement this functionality myself, but I'm not sure how the maintainers would want it to be implemented (especially since this would result in some internal ABI changes).

**Additional context**
N/A

**Comment by romainthomas** [comment]
https://github.com/lief-project/LIEF/blob/722ed6c403a681bc43fc9cd8300366d88b381740/include/LIEF/PE/Binary.hpp#L444
