### ISSUE TITLE
LIEF messing with the C++ stringstream

### ISSUE THREAD

**Issue by patacca** [lief-project/LIEF#704]
**Describe the bug**
Apparently LIEF is messing in some way with the standard implementation of `stringstream`, in particular regarding the `operator<<(int)`.
This can potentially modify the behavior of other Python module written in C imported after LIEF.
I am still unsure about what is happening behind the scene but for sure something strange is happening

**To Reproduce**
Requires triton https://github.com/JonathanSalwan/Triton/

**Only triton**
```python
import triton
ctx = triton.TritonContext()
ctx.setArchitecture(triton.ARCH.X86)
i = triton.Instruction(0x100, b'\xc3')
ctx.processing(i)
print(i)
# 0x100: ret
```

**First import triton, then lief**
```python
import triton
import lief
ctx = triton.TritonContext()
ctx.setArchitecture(triton.ARCH.X86)
i = triton.Instruction(0x100, b'\xc3')
ctx.processing(i)
print(i)
# 0x100: ret
```

**First import lief, then triton**
```python
import lief
import triton
ctx = triton.TritonContext()
ctx.setArchitecture(triton.ARCH.X86)
i = triton.Instruction(0x100, b'\xc3')
ctx.processing(i)
print(i)
# 0x
```

As you can see when importing LIEF before triton we do not get anymore the string representation of the disassembled instruction.
This happens because at some point (in triton file `instruction.cpp` line `536`) this line is called:
```c++
// stream is a std::stringstream
stream << "0x" << std::hex << inst.getAddress() << ": " << inst.getDisassembly() << std::dec;
```
And apparently an exception is thrown while trying to add a number (in this case `inst.getAddress()`) to the `stringstream`.
After a little bit of debugging with gdb I think the exception is thrown because the function `num_put_c` is missing. The function `num_put_c` should be responsible for the insertion of the char representation of the int digit.

LIEF is in some way messing with stringstream and it shouldn't.

**Environment (please complete the following information):**
 - System and Version : ArchLinux 5.17.4-arch1-1
 - Python: I tested it on different version, from 3.8.6 up to 3.10.4
 - LIEF commit version: 0.12.1-c7b3ce3b

**Additional context**
I will try to investigate more into this issue

**Comment by romainthomas** [comment]
I think it's because LIEF's wheels are statically linked with `libstdc++`. On the other hand, the `manylinux_XXX` tag requires this static link. I'll check if there is a workaround.

**Comment by patacca** [comment]
Actually it seems that you can link dynamically `libstdc++`
See PEP-599 point 2 of the `manylinux2014` section [here](https://peps.python.org/pep-0599/#the-manylinux2014-policy)

**Comment by romainthomas** [comment]
Ok, thanks for pointing this information. It should, indeed, fix the issue.

**Comment by romainthomas** [comment]
As of 19d395197dc70af8b77a159d085238cb6f222e25 CI wheels are no longer statically linked with `libstdc++`
