### ISSUE TITLE
Some odd logic in Builder.tcc

### ISSUE THREAD

**Issue by ZehMatt** [lief-project/LIEF#731]
https://github.com/lief-project/LIEF/blob/2d0525257a8e89e93ef96be01405fd803c042ee4/src/ELF/Builder.tcc#L1629

Its not exactly clear what this line is trying to achieve, I can only guess that when svas is not empty use sizeof(Elf_Verdef) otherwise zero? 

MSVC has this to say:
```(1629,47): warning C4804: '>': unsafe use of type 'bool' in operation``` 

I would assume the correct line would be:
```cpp
eader.vd_aux     = static_cast<Elf_Word>(svas.empty() == false ? sizeof(Elf_Verdef) : 0);
```
or
```cpp
eader.vd_aux     = static_cast<Elf_Word>(!svas.empty() ? sizeof(Elf_Verdef) : 0);
```

**Comment by romainthomas** [comment]
Yes this is clearly a typo, thank you I'll fix it.
