### ISSUE TITLE
Adding new section with code to Mach-O (for iOS)

### ISSUE THREAD

**Issue by vegedreamgagnoa** [lief-project/LIEF#737]
Hey @romainthomas I would like to add a section into _TEXT segment with its code and I followed a tutorial here: https://lief-project.github.io/doc/stable/tutorials/11_macho_modification.html#adding-section-segment

The section was successfully added into the Mach-O, but somehow the code marked with constructor attribute was not called/executed. And for iOS -- if I change the entrypoint it will lead to fatal crash at startup/launch.

Is there any suggestion? Thanks in advance!

**Comment by vegedreamgagnoa** [comment]
Also when I checked with Hopper, the code that I inserted was not found.

**Comment by romainthomas** [comment]
Ok I'll check it might be a regression from the changes described here: https://lief-project.github.io/blog/2022-05-08-macho/

**Comment by romainthomas** [comment]
@vegedreamgagnoa Could you detail how you added the sections (or if you can share the script) ?

**Comment by vegedreamgagnoa** [comment]
Hey @romainthomas it's not actual issue, just part of my mistake, everything works now!
Could you please head to other's issue that I reported about extending segment resulting in malformed/bad mach-o?
