### ISSUE TITLE
Inaccessible segment created with new loadable section

### ISSUE THREAD

**Issue by MabezDev** [lief-project/LIEF#739]
**Describe the bug**
When adding a new loadable section, a segment is implicitly created but `section.segments` is always empty. How to access the implicitly created segment to customise paddr etc?

**To Reproduce**
```python
section = lief.ELF.Section()
section.type = lief.ELF.SECTION_TYPES.PROGBITS
section.add(lief.ELF.SECTION_FLAGS.ALLOC)
section.name = ".esp-header"
section.content = data
section.size = 0x20
section.virtual_address = 0x42000000
section = elf.add(section, True)

for s in section.segments:
    print(s)

# no output
```

**Expected behavior**
`section.segments` is filled correctly, or some means of manipulating the implicit segment.

**Environment (please complete the following information):**
 - System and Version : Gentoo Linux 2.8
 - Target format : ELF
 - LIEF commit version: `0.12.1-c7b3ce3b`

Edit: copied correct code snippet

**Comment by MabezDev** [comment]
I worked around this with the following code:

```python
segment = elf.segment_from_virtual_address(vaddr)
segment.virtual_address = vaddr
segment.physical_address = paddr
segment.physical_size = len(data)
```
However, imo this is still a bug so I'll keep this open for now.

Awesome project by the way! If my experiments go well I'd like to add Rust bindings eventually :).

**Comment by romainthomas** [comment]
Hello @MabezDev,
Thanks for reporting the issue :) It should be fixed now. 

Regarding the Rust binding I already started to bootstrap them but it's not public yet. If you are interested, we could discuss about it (as I'm not a Rust expert). So feel free to reach me on gitter/twitter/...
