### ISSUE TITLE
Extending segment resulted in malformed mach-O

### ISSUE THREAD

**Issue by vegedreamgagnoa** [lief-project/LIEF#742]
@romainthomas how can I extend __TEXT segment correctly? As whenever I extend this segment it will result in bad/malformed mach-O (EBADMACHO): https://www.osstatus.com/search/results?platform=all&framework=all&search=88 with this error: `underlyingError = <NSError: 0x2824de3a0; domain: NSPOSIXErrorDomain; code: 88>`

**Comment by romainthomas** [comment]
Yes it's normal since the `__TEXT` segment might access data in the `__DATA` segment with relative addressing.
You can only extend the **last** segment.
