### ISSUE TITLE
About LIEF C++ document 

### ISSUE THREAD

**Issue by blahole** [lief-project/LIEF#744]
Can't open the url'subpages: https://lief-project.github.io/doc/latest/api/cpp/index.html

**Comment by romainthomas** [comment]
Thanks, it's weird and I think it comes from an update (not mine) in Circleci

**Comment by blahole** [comment]
OK.Thanks.

**Comment by romainthomas** [comment]
Fixed. It was a side effect [1] of a `git` upgrade in the docker image of the CI.

[1] https://github.blog/2022-04-12-git-security-vulnerability-announced/

**Comment by blahole** [comment]
Thanks.
