### ISSUE TITLE
Any recommendation/documentation how to add/export new symbol to LC_SYMTAB of Mach-O?

### ISSUE THREAD

**Issue by vegedreamgagnoa** [lief-project/LIEF#748]
I'd like to add/export new symbol such as _printf, _open, etc. to LC_SYMTAB, is it possible using LIEF?
Is there any doc/recommendation on how to do this?

@romainthomas

**Comment by vegedreamgagnoa** [comment]
@romainthomas Why marked as incompleted and closed? Could you help just point me to the relevant doc/guideline? It is enough :)
Sorry for ridiculous question..

**Comment by romainthomas** [comment]
Because the answer is in the documentation [lief.MachO.Binary.add_exported_function](https://lief-project.github.io/doc/latest/api/python/macho.html#lief.MachO.Binary.add_exported_function) it can't be clearer ...
