### ISSUE TITLE
Possible Typo 

### ISSUE THREAD

**Issue by avkhadeev** [lief-project/LIEF#753]
Hello! It looks like there is typo in the following : 

https://github.com/lief-project/LIEF/blob/1730a680b422aced19af3ea0258b26a64a751231/src/MachO/BinaryParser.tcc#L3318

probably condition should be 

```
if (cmd.nb_external_define_symbols() > 0 &&
        cmd.idx_external_define_symbol() <= isym  && isym < (cmd.idx_external_define_symbol() + cmd.nb_external_define_symbols()))

**Comment by romainthomas** [comment]
Yes, you are completely right. Thank you for spotting this error
