### ISSUE TITLE
Removing library libc.so makes ELF invalid

### ISSUE THREAD

**Issue by JJTech0130** [lief-project/LIEF#772]
**Describe the bug**
Removing libc.so from the libraries list will cause the ELF to become invalid.

Using `ldd` on it produces the following output:
```
Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!
```

**To Reproduce**
```python3
binary.remove_library("libc.so")
binary.add_library("libc.so.6")
```
and then try to link against it (or even just use `ldd`)

**Expected behavior**
I want to remove `libc.so` and replace it with `libc.so.6`, as that's what it's called on my platform.

**Environment (please complete the following information):**
 - System and Version: `Linux raspberrypi 5.10.63-v8+ #1459 SMP PREEMPT Wed Oct 6 16:42:49 BST 2021 aarch64 GNU/Linux`
 - Target format (PE, ELF, Mach-O): `ELF`
 - LIEF commit version: `0.12.1-c7b3ce3b`

**Additional context**
I'm modifying the attached
[libstoreservicescore.so.zip](https://github.com/lief-project/LIEF/files/9385566/libstoreservicescore.so.zip)
 file.

**Comment by romainthomas** [comment]
Hello @JJTech0130,
Could you add the version of ldd you are using? 

Thank you

**Comment by romainthomas** [comment]
Closing the issue as no answer.
