### ISSUE TITLE
Unable to extend section in ARMv7 ELF

### ISSUE THREAD

**Issue by benny-cz** [lief-project/LIEF#774]
**The issue**
I am trying to extend `.rel.dyn` section in ELF ARMv7 shared library, I encounter no errors in console stdout/stderr, no exceptions, but output ELF doesn't have the section extended. The same problems appears while using both of Python and C/C++ code. Am I doing anything wrong, or I've just found a bug?

**To Reproduce**
The input shared library is built from this code (`empty.asm`):

```
.section .text

imp_dlopen:
 .word 0

imp_exit:
 .word exit(TARGET1)

start:
 MOV PC, LR
```

And was built like this:

```
set GAS_DIR=<...>\android-ndk-r21b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\arm-linux-androideabi\bin

%GAS_DIR%\as.exe empty.asm -o empty.a -I ../../Android/linuxapi/ -k -mlittle-endian -mfpu=neon -mcpu=cortex-a8 -march=armv7 -k

%GAS_DIR%\ld.exe empty.a -o empty.in -shared --emit-relocs
```

Python code which doesn't work:

```
elf = lief.parse("empty.in")
section = elf.get_section(".rel.dyn")
elf.extend(section, 8)
elf.write("empty.out")
```

And C/C++ code which doesn't work:

```
#include <LIEF/LIEF.hpp>

int main()
{
	std::unique_ptr<LIEF::ELF::Binary>   elf = LIEF::ELF::Parser::parse("empty.in");

	auto section = elf->get_section(".rel.dyn");
	elf->extend(*section, 8);

	elf->write("empty.out");

	return 0;
}
```

Running `readelf -a empty.out` gives this result:

```
Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  ...
  [ 4] .rel.dyn          REL             0000016c 00016c 000008 08   A  1   0  4
  ...
```

`000008` bytes means there is still 1 relocation item instead of expected 2 relocation items (16 / 0x10).

**Environment:**
 - Windows 11
 - ARMv7 ELF
 - LIEF commit version: 0.12.1-c7b3ce3b

**Comment by romainthomas** [comment]
Yes actually the extension of `.rel.dyn` is overwritten by the LIEF's builder. For which purpose you need to extend this section?
