### ISSUE TITLE
Unable to modify sections in ELF x86_64

### ISSUE THREAD

**Issue by R3x** [lief-project/LIEF#775]
I am trying to patch sections in an ELF, however, the changes that I make don't seem to reflect in the modified binary. Am I doing something wrong or is this a bug?

```py
def patch_whole_section(section : lief.Section, patch_bytes : bytes) -> bool:
    if section.size < len(patch_bytes):
        raise Exception("Size of patch bytes is greater than the size of the section")
    try:
        # Padding the section with 0x00 bytes
        section.content = [int(byt) for byt in patch_bytes] + [0] * (section.size - len(patch_bytes))
    except Exception as e:
        print(e)
        return False
    return True 

binary = lief.parse(path)
sec = binary.get_section(".interp")
patch_whole_section(sec, b'/tmp/ld')
binary.write(path + "patched")
```

However doing readelf, shows that it's not patched

**Environment (please complete the following information):**
 - System and Version : Ubuntu 22.04
 - PE
 - LIEF commit version:  0.13.0-ad811916 (also tried on the pip version)

**Comment by romainthomas** [comment]
Hello @R3x,

If you want to patch the interpreter, you should do:

```python
binary.interpreter = "/tmp/ld"
```

**Comment by R3x** [comment]
Would it be possible to patch the interpreter using the same API @romainthomas ? I am trying to automate the patching of several sections of the ELF, if I have to patch each section with a different command it's kinda hard.

Basically, I am writing a UI interface so that people can just specify sections and rewrite them.
