### ISSUE TITLE
Missing macOS arm build artifact (whl)

### ISSUE THREAD

**Issue by doronz88** [lief-project/LIEF#778]
**Is your feature request related to a problem? Please describe.**
When intalling using pip on macOS arm (Apple Silicon), the installation rakes a long while to build (and requires the build tools to be installed)

**Describe the solution you'd like**
Adding a macos/arm variant to the ci build matrix

**Comment by romainthomas** [comment]
So far, Github action does not provide the support for Apple Silicon. 
Feel free to re-open it when it will be available.
