### ISSUE TITLE
Where did the 0.12.2 release go?

### ISSUE THREAD

**Issue by SuperSandro2000** [lief-project/LIEF#799]
We where updating lief to 0.12.2 in [nixpkgs](https://github.com/NixOS/nixpkgs/pull/191863) and in the meantime the release tag went away. What happpened?

**Comment by romainthomas** [comment]
Hello @SuperSandro2000 

Sorry for that, actually LIEF 0.12.2 aimed at fixing #770 but when I tagged I missed a to correctly patch the issue (c.f. the comments). That's why I removed the tag.

I'll (re)release this version next week.
