### ISSUE TITLE
Failed to run on Python 2.7.13 MacOS 10.12.4

### ISSUE THREAD

**Issue by heartbleeded** [lief-project/LIEF#8]
I got this error probably due to using ucs4 as default unicode encoding while compiling lief.so

`pip install osx_lief-0.6.0_py2.7.tar.gz
>import lief
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/lief.so, 2): Symbol not found: _PyUnicodeUCS4_AsUTF8String
  Referenced from: /usr/local/lib/python2.7/site-packages/lief.so
  Expected in: flat namespace
 in /usr/local/lib/python2.7/site-packages/lief.so`

**Comment by romainthomas** [comment]
I think it's related to https://github.com/pyenv/pyenv/issues/257#issuecomment-195836492

**Comment by romainthomas** [comment]
@heartbleeded You can check it's working here: https://github.com/lief-project/LIEF/releases/tag/0.6.1RC9

**Comment by heartbleeded** [comment]
Yes, I confirm this fixed. Well done!
