### ISSUE TITLE
Patching address on AArch64 Mach-O binary makes bad executable binary

### ISSUE THREAD

**Issue by Helloyunho** [lief-project/LIEF#802]
**Describe the bug**
Patching the address(modifying asm instruction) on AArch64 Mach-O binary doesn't work properly and it produces a bad executable binary.
I didn't test it with x86_64 binary though.

**To Reproduce**
1. Open Python and read Mach-O binary
2. Remove the signature and patch the address
3. Write the binary and try running it
4. It instantly gets killed
```python
binary = lief.parse("path/to/binary")

binary.remove_signature()

binary.patch_address(address, [0x1F, 0x20, 0x03, 0xD5]) # nop patch

binary.write("path/to/output")
```

**Expected behavior**
It should make a valid binary, not instantly get killed because it's a bad executable.

**Environment (please complete the following information):**
 - System and Version : macOS 12.6
 - Target format: Mach-O
 - LIEF commit version: `0.13.0-b502b8d`

**Additional context**
Ghidra also failed to do this so I don't have high hope for this issue. I'm still finding working alternatives and if I find one I'll mention it here.

**Comment by romainthomas** [comment]
Could you try the `patch_address` before the `remove_signature`?

**Comment by Helloyunho** [comment]
> Could you try the `patch_address` before the `remove_signature`?

Same result.
![CleanShot 2022-09-30 at 14 37 07@2x](https://user-images.githubusercontent.com/10192625/193197916-5973b041-9bfc-46e5-9168-c517ad05a531.png)

**Comment by romainthomas** [comment]
Can you attach the binary?

**Comment by Helloyunho** [comment]
> Can you attach the binary?

No, I'm trying to patch a game.

**Comment by Helloyunho** [comment]
Why is this closed? The issue is not solved yet.

**Comment by romainthomas** [comment]
Given your information it can't be solved.

**Comment by Helloyunho** [comment]
Solved. Forgot the binary needs to be signed 😅
