### ISSUE TITLE
Unable to load certificates having md2WithRSAEncryption

### ISSUE THREAD

**Issue by bhoehl** [lief-project/LIEF#803]
@romainthomas 
hi Romain,

I am using LIEF ( Python ) for validating signatures, especially the authenticode ones.
Using a list of known root certificates and importing them causes two cases in which they can not be imported.
Those are Versign certificates having md2WithRSAEncryption, which is not supported by LIEF as it seems.
Interestingly the oid code for this one is present in the source, tho.

The certificate to load looks like:

```

Subject Identifier: 742c3192e607e424eb4549542be1bbc53e6174e2
Friendly Name: VeriSign Class 3 Public Primary CA
Extended key usages: ['client_auth', 'code_signing', 'email_protection', 'server_auth']
Subject Name MD5: 27b3517667331ce2c1e74002b5ff2298
Disallowed Filetime: 2020-02-02 00:00:00+00:00
Disallowed extended key usages: ['1.3.6.1.4.1.311.94.1.2']
Not before Filetime: 2017-03-01 00:00:00+00:00
-----BEGIN CERTIFICATE-----
MIICPDCCAaUCEHC65B0Q2Sk0tjjKewPMur8wDQYJKoZIhvcNAQECBQAwXzELMAkG
A1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMTcwNQYDVQQLEy5DbGFz
cyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTk2
MDEyOTAwMDAwMFoXDTI4MDgwMTIzNTk1OVowXzELMAkGA1UEBhMCVVMxFzAVBgNV
BAoTDlZlcmlTaWduLCBJbmMuMTcwNQYDVQQLEy5DbGFzcyAzIFB1YmxpYyBQcmlt
YXJ5IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIGfMA0GCSqGSIb3DQEBAQUAA4GN
ADCBiQKBgQDJXFme8huKARS0EN8EQNvjV69qRUCPhAwL0TPZ2RHP7gJYHyX3KqhE
BarsAx94f56TuZoAqiN91qyFomNFx3InzPRMxnVx0jnvT0Lwdd8KkMaOIG+YD/is
I19wKTakyYbnsZogy1Olhec9vn2a/iRFM9x2Fe0PonFkTGUugWhFpwIDAQABMA0G
CSqGSIb3DQEBAgUAA4GBALtMEivPLCYATxQT3ab7/AoRhIzzKBxnki98tsX63/Do
lbwdj2wsqFHMc9ikwFPwTtYmwHYBV4GSXiHx0bH/59AhWM1pF+NEHJwZRDmJXNyc
AA9WjQKZ7aKQRUzkuxCkPfAyAw7xzvjoyVGM5mKf5p/AfbdynMk2OmufTqj/ZA1k
-----END CERTIFICATE-----
```

The c code to reproduce is pretty simple:

```
#include <LIEF/PE/signature/x509.hpp>

using namespace LIEF::PE;

int main(int argc, char **argv) {
  x509::certificates_t certs = x509::parse("<filepath to pem>");
}
```

The reported error with more logging enabled is:

Failed to parse certificate blob: 'X509 - Signature algorithm (oid) is unsupported : OID - OID is not found

I have looked into the source, but could not find a way to add that easily.

Is there a chance to add this one, too ?

Thanks

Bernd

**Comment by romainthomas** [comment]
Hello @bhoehl 

I have the same error, unfortunately the x509 parser is based on MbedTLS which removed the support for MD2:

https://github.com/Mbed-TLS/mbedtls/blob/80ca44f33c53ab2fb8657b0097bf04dbce783fdb/ChangeLog#L717-L719 

Thus, there is nothing I can do for that.
