### ISSUE TITLE
Chained binding handling seems to be incorrect

### ISSUE THREAD

**Issue by dunkyp** [lief-project/LIEF#804]
Given a macho binary which has chainedbindings only the final instance of a binding will be in the binary.chained_fixups.bindings array. 

```
#import <Foundation/Foundation.h>

@interface Test : NSObject
@end

@implementation Test
@end

int main() {

}
```
The section `_DATA` `_objc_data` contains two references to the imported symbol `_OBJC_METACLASS_$_NSObject`. Running the `macho_reader` executable I can see lief correctly finding the bindings 
```          
[  BIND] __DATA@0x100008090: _OBJC_METACLASS_$_NSObject / sign ext: 0
[  BIND] __DATA@0x100008098: _OBJC_METACLASS_$_NSObject / sign ext: 0
```
I exepected to be able to find these bindings using
```
[(binding.symbol.name, hex(binding.address)) for binding in app.dyld_chained_fixups.bindings]
```
but got
```
[('__objc_empty_cache', '0x1000080c8'), ('_OBJC_METACLASS_$_NSObject', '0x100008098'), ('_OBJC_CLASS_$_NSObject', '0x1000080c0')]
```

This appears to be because of the line 
```
std::unique_ptr<ChainedBindingInfo>& binding = chained_fixups_->bindings_[ordinal];
```
which assumes one binding per "ordinal".

 - System and Version : MacOS 12.6 (M1)
 - Target format Mach-O
 - LIEF commit version: 0.13.0-84b09091

**Comment by romainthomas** [comment]
Hi @dunkyp 

I confirm the issue, I'll look for a fix.

**Comment by romainthomas** [comment]
https://github.com/lief-project/LIEF/commit/2b3e40190d48a96dd162515869a5c4869e738a7b should fix the issue (waiting for the CI)

**Comment by dunkyp** [comment]
Brilliant!

**Comment by romainthomas** [comment]
Almost done. It will be merged tomorrow or the day after
