### ISSUE TITLE
bin.get(lief.ELF.DYNAMIC_TAGS.FLAGS) returns None instead of lief.not_found exception

### ISSUE THREAD

**Issue by Wenzel** [lief-project/LIEF#805]
**Describe the bug**
`bin.get(lief.ELF.DYNAMIC_TAGS.FLAGS)` returns `NoneType`

**To Reproduce**
~~~Python3
In [1]: import lief

In [2]: bin = lief.parse('./tests/binaries/elf/rpath_enabled')

In [3]: bin.get(lief.ELF.DYNAMIC_TAGS.FLAGS)
~~~

**Expected behavior**
This API should return a list of flags, or raise `lief.not_found` exception.

**Environment (please complete the following information):**
 - System and Version : [Ubuntu 22.04]
 - Target format (ELF)
 - LIEF commit version: `0.12.2-2169578d`

**Additional context**
I'm facing this issue since I tried to upgrade [checksec.py](https://github.com/Wenzel/checksec.py) from lief `0.11.0` to `12.2`

My CI E2E tests are not passing anymore:
https://github.com/Wenzel/checksec.py/actions/runs/3169897540/jobs/5162117559

And the reason for that is that at this location:
https://github.com/Wenzel/checksec.py/blob/master/checksec/elf.py#L127 (when computing relro), lief returns a None type for the `get` function.

You can check that on one of the faulty binaries:
https://github.com/Wenzel/checksec.py-test-binaries/tree/c672a34bd234f85071cad139852bfbae530e9ecf/elf
![image](https://user-images.githubusercontent.com/964610/193474540-4c86ec2a-45d0-4a94-a7b6-866383c5a442.png)

![image](https://user-images.githubusercontent.com/964610/193474547-ea0ad314-a10c-4479-a7f2-3e48fd42dccd.png)

:arrow_right:  is this expected behavior ?

Thanks for lief ! :tada:

**Comment by romainthomas** [comment]
Hello @Wenzel 
Yes that's the expected behavior since LIEF 0.12. You can find the reasons in the [changelog](https://lief-project.github.io/doc/stable/changelog.html#march-25-2022) and the list of the functions impacted here: https://gist.github.com/romainthomas/37da45b043c5f8b8db6be2767611f625
