### ISSUE TITLE
DEBUG Build (32/64) on Visual Studio 2015 Crashes

### ISSUE THREAD

**Issue by n80fr1n60** [lief-project/LIEF#81]
Building the latest version of LIEF on VS 2015 with CMAKE generated project/solution 
with a DEBUG build results in Crash as soon as this (marked with --> in the below snippet) line is executed...

```
std::cout << "PE Reader" << std::endl;
std::string f_name = std::string("C:\\Users\\XYZ\\Desktop\\xUtility.exe");
 --->  std::unique_ptr<const Binary> binary{Parser::parse(f_name)};
```

Stepping into the function VS only shows: "Error reading characters of string" and then crashes
This behaviour can be seen on 32 and 64-bit DEBUG Builds....

On Release and "Release with Debug" it does not occur...

**Comment by romainthomas** [comment]
Did you try with the latest version of VS (2017) ?

**Comment by n80fr1n60** [comment]
I guess I found the issue, the CMAKE generator sets the "Runtime Library" for the for the DEBUG configuration in a wrong way. in DEBUG the Library has the correct setting **/MDd for Shared** but wrong setting  **MT for Static** 
but the examples have only /MT set as the Runtime Library for either Debug and "ReleaseWithDebug"

so for debug to work:
**DEBUG DLL set Runtime Lib to /MDd and examples to /MTd **
**DEBUG STATIC set Runtime Lib /MTd  and examples to /MTd**
