### ISSUE TITLE
Core dump using any version of lief after processing 4124 files

### ISSUE THREAD

**Issue by better84** [lief-project/LIEF#811]
I am working on a project using [gym-malware](https://github.com/endgameinc/gym-malware) and after processing 4124 samples
(regardless of lief version) I get the following error:

```
free(): invalid next size (normal)
Aborted (core dumped)
```

It does not _appear_ to be a memory issue, as a counter was implemented:
```
    for sha256 in sha256_holdout:
        counter = counter + 1
        if counter < 4120: # 800 old value # 4120
            continue
```
The script (test_agent_kerasrl.py) processes samples 4120-4124, and then upon reaching 4125 the error message above is generated. 

Ideally things would continue to move along until all 5000 (or more) samples are processed.

**Environment (please complete the following information):**
 - Description:  Ubuntu 20.04.5 LTS
 - Release:  20.04
 - Codename: focal
 - Target format: PE
 - LIEF commit version: 0.8 - 0.12 (all versions after 0.7.0)
 - Python version is 3.6.9

**Additional context**
When using lief 0.7.0 I can get to 808 samples and an error `RuntimeError: Invalid UTF-8` is thrown.

Full error (applies to all versions) looks like:
```
###### processing: 6e7580cc6a862b1a028e4ed0d70fca35c3f12dc62af67f9abf7c13c38b26366d number: 4125 / 5000
score=0.9357189536094666 (hidden), label=1.0
*** imports_append ***
Adding GetStdHandle Function of Library KERNEL32.dll
free(): invalid next size (normal)
Aborted (core dumped)
```

**Comment by romainthomas** [comment]
Hello @better84,
At first sight, I would say this issue comes from the memory management in LIEF or Pybind11
Could you attach the samples `4120-4125` ?

**Comment by better84** [comment]
Hi @romainthomas!

Sorry for the delay in my response! I'm not sure how it happened, but I did need to adjust my scipy installation and apparently in doing so the issue _appears_ to be corrected. Additionally, I have changed the methodology in which I modify my samples, and at this time I don't get anywhere near 4125 modified files.

However, I have only attached the file in reference (#4125, remove the '.pdf' prior to analysis, included for upload) as it is the only one I have record of, and it changes when I run the model. I've also included a text file containing the makeup of my environment.
[conda_list_rtx_3060.txt](https://github.com/lief-project/LIEF/files/9835230/conda_list_rtx_3060.txt)

[6e7580cc6a862b1a028e4ed0d70fca35c3f12dc62af67f9abf7c13c38b26366d.pdf](https://github.com/lief-project/LIEF/files/9835223/6e7580cc6a862b1a028e4ed0d70fca35c3f12dc62af67f9abf7c13c38b26366d.pdf)

Please let me know if there's anything glaring that I've missed.

**Comment by romainthomas** [comment]
On my side I don't get the `free()` (while running with ASAN) so I close this issue but feel free to reopen it with this appends again.
