### ISSUE TITLE
`MemoryError: std::bad_alloc` when writing binary

### ISSUE THREAD

**Issue by Frefreak** [lief-project/LIEF#813]
**Describe the bug**
For one specific elf binary, when using `binary.write` it errors out: `MemoryError: std::bad_alloc`

**To Reproduce**

```python
import lief

binary = lief.parse('./asdf')
binary.write('./asdf.modified')
```
result:
```
Traceback (most recent call last):
  File "/home/user/pwn.college/test.py", line 4, in <module>
    binary.write('./asdf.modified')
MemoryError: std::bad_alloc
```

**Expected behavior**
no error

**Environment (please complete the following information):**
 - System and Version : archlinux
 - Target format: ELF
 - LIEF commit version: ``0.13.0-8a555be0`` (also tried pypi latest version)

**Additional context**

binary attached (need to `gzip -d`)
[asdf.gz](https://github.com/lief-project/LIEF/files/9836773/asdf.gz)

**Comment by Frefreak** [comment]
I just saw #812 which is a fresh commit, will try master version.

**Comment by romainthomas** [comment]
Yes I fixed #812 but I would like to highlight that the LIEF builder can be broken it a lot of different ways. 

The LIEF's **parsers** are very sensitive from a security stand point since they process untrusted binary. 
On the other hand, the LIEF's builders assume that the user *"know"* what he is doing.

I'll address these issues but with a less priority that those regarding the parsers. Feel also free to draft a PR.

**Comment by romainthomas** [comment]
Ok for this issue it seems a real internal problem in the builder for ELF non-pie binaries

**Comment by Frefreak** [comment]
So I did some digging and the problem lies in `ELF::Binary::relocate_phdr_table_v1` where loadable segment gaps are being calculated.
In a nutshell the problematic elf binary has the last load segment's **offset** and **file_size** being set to zero:

```Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000400040 0x0000000000400040
                 0x0000000000000310 0x0000000000000310  R      0x8
  INTERP         0x0000000000000350 0x0000000000400350 0x0000000000400350
                 0x000000000000001c 0x000000000000001c  R      0x1
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
  LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
                 0x0000000000000b68 0x0000000000000b68  R      0x1000
  LOAD           0x0000000000001000 0x0000000000401000 0x0000000000401000
                 0x0000000000001425 0x0000000000001425  R E    0x1000
  LOAD           0x0000000000003000 0x0000000000403000 0x0000000000403000
                 0x00000000000009b0 0x00000000000009b0  R      0x1000
  LOAD           0x0000000000003e00 0x0000000000404e00 0x0000000000404e00
                 0x00000000000002f8 0x00000000000002f8  RW     0x1000
  LOAD           0x0000000000000000 0x0000000000410000 0x0000000000410000
                 0x0000000000000000 0x0000000000020000  RW     0x1000
  DYNAMIC        0x0000000000003e20 0x0000000000404e20 0x0000000000404e20
                 0x00000000000001d0 0x00000000000001d0  RW     0x8
  NOTE           0x0000000000000370 0x0000000000400370 0x0000000000400370
                 0x0000000000000020 0x0000000000000020  R      0x8
  NOTE           0x0000000000000390 0x0000000000400390 0x0000000000400390
                 0x0000000000000044 0x0000000000000044  R      0x4
  GNU_PROPERTY   0x0000000000000370 0x0000000000400370 0x0000000000400370
                 0x0000000000000020 0x0000000000000020  R      0x8
  GNU_EH_FRAME   0x0000000000003750 0x0000000000403750 0x0000000000403750
                 0x000000000000007c 0x000000000000007c  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x0000000000003e00 0x0000000000404e00 0x0000000000404e00
                 0x0000000000000200 0x0000000000000200  R      0x1
```

Notice how the 6th (counting from 0) segment (the last load segment) has both **offset** and **file_size** set to zero, causing this part results in a negative (`size_t`, so a very large) gap. Hence this gap is incorrectly chosen to do some works later (which I haven't read and don't understand at all :fearful: )

https://github.com/lief-project/LIEF/blob/100917541f5545ea50922cfd7d5c710ff98f21e5/src/ELF/Binary.cpp#L3061-L3078

I'm not sure if an elf would be considered valid to have the last load segment's offset set to zero or what should we do when in such situation, but to workaround this it seems simply skipping the problematic load segment will do the tricks. With something like

```cpp
    if (adjacent->file_offset() == 0) {
      LIEF_DEBUG("Skipping segment with zero file_size");
      continue;
    }
```
lief can not `write` the binary successfully.

What do you think about the change? If that's OK I would be happy to make a PR.

BTW this only checks `adjacent`, should we also check `current` in case we encounter a load segment with 0 `file_offset` at the middle of a series of load segments? (is this even possible?)

**Comment by romainthomas** [comment]
Hello @Frefreak 
Thank you very much for the details about the root cause of the issue and sorry for my mistake about `size_t`.

I fixed the issue by doing the subtraction on a **signed int** and by checking whether the result is negative.
