### ISSUE TITLE
String offset not found

### ISSUE THREAD

**Issue by ReKreker** [lief-project/LIEF#816]
**Describe the bug**
Cannot find string offset for strange section .note.100 when writing binary
```Can't find string offset for section name '.note.100'
Can't find string offset for section name '.note.100'
Can't find string offset for section name '.note.100'
Can't find string offset for section name '.note.100'
Can't find string offset for section name '.note.100'
Can't find string offset for section name '.note.100'
Can't find string offset for section name '.note.100'
```

**To Reproduce**
1) git clone https://github.com/ReKreker/shooker
2) cd shooker
3) pip3 install .
4) cd example
5) make

**Expected behavior**
Output without this warnings.

**Environment:**
 - System and Version : Fedore 36 + gcc 12.2.1
 - Target format: ELF
 - LIEF commit version: 0.12.2-2169578d

**Comment by romainthomas** [comment]
Could you provide a snippet with the LIEF modifications triggering these warnings? (I compiled the binaries)

**Comment by romainthomas** [comment]
Well, this does not really answer my original question: "Could you provide a standalone script to reproduce the error" (i.e. isolating the modifications).

Thank you
