### ISSUE TITLE
Section Sizes Larger Than File Size

### ISSUE THREAD

**Issue by lkurlandski** [lief-project/LIEF#817]
**Describe the bug**

I am trying to identify the regions of PE malware that correspond to the the .text section, i.e., I want the beginning and end offsets of the .text section. However, after getting the .text section with get_section(".text"), it would appear that the size of the section is actually larger than the size of the binary. This may not be a bug and could be a simple misunderstanding on my part. 

**To Reproduce**

The executable file I am using is a disarmed piece of malware collected by the SOREL research group. Even though the file has been disarmed, I am hesitant to share it right away since there is a solid chance that someone more experienced with this can diagnose the issue without the file. Let me know if this is not the case and I can provide a google drive link for the file.

```
import lief
path = "001856267679fb6001cd00f230043326e1b9fc210874dd4c839761d51f4e9a73"
binary = lief.parse(path)
section = binary.get_section(".text")
with open(path, "rb") as handle:
    raw = handle.read()
print(f".text section size: {section.size}, binary size: {len(raw)}")
# Prints ".text section size: 65536, binary size: 22747"
```

**Expected behavior**

I would expect the .text section's size to be smaller than the size of the file.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04.5
 - Target format: PE
 - LIEF commit version: 0.12.2-2169578d

**Comment by romainthomas** [comment]
@lkurlandski you can send me the sample (or a link to download it) at this address `me@romainthomas.fr`

**Comment by lkurlandski** [comment]
@romainthomas done, thank you!

**Comment by romainthomas** [comment]
I checked the provided file and the information returned by LIEF is correct. So yes, it might look weird but the 
the `.text` section size is larger than the binary size. If the binary is running it means that the Windows PE loader allows this behavior even though it is not intuitive.

I close this issue since it is not related to a parsing issue.

**Comment by lkurlandski** [comment]
I will have to study PE files a little more to understand how this works, but thank you for confirmation that it is not a bug with LIEF!
