### ISSUE TITLE
[PE] Unable to find the section associated with BOUND_IMPORT

### ISSUE THREAD

**Issue by ner0x652** [lief-project/LIEF#82]
I'm writing a PE analysis script, but LIEF(latest Linux build) fails to parse the file(DLL). The DLL is kernel32.dll found on Windows 7 x86-32 bit 6.1.7601 SP1 Build 7601(md5: 5553784d774ca845380650e010bbda2c). The parsing results in 

> Unable to find the section associated with BOUND_IMPORT

Here's my code 
```Python
#!/usr/bin/env python3

import lief
import sys


def show_exports(dll):
    if dll.has_exports:
        for e in dll.exported_functions:
            print(e)
    else:
        print("{0} {1}".format(dll.name, "has no exports"))


def comes_act():
    if len(sys.argv) < 2:
        print("[USAGE]: {0} <executable>".format(sys.argv[0]))
        sys.exit(1)

    try:
        binary = lief.PE.parse(sys.argv[1])
    except lief.bad_format as err:
        print("Error: {0}".format(err))
        sys.exit(1)

        
if __name__ == "__main__":
    comes_act()
```

If any other info is needed I'm ready to help, thank you!

**Comment by romainthomas** [comment]
What is the issue ? (It's *normal* that ``BOUND_IMPORT`` has not section associated with)

**Comment by ner0x652** [comment]
OK, sorry. I thought it isn't <i>normal</i> and I didn't check thoroughly. My fault, thanks!
