### ISSUE TITLE
x86-64 ELF file size became very large after write()

### ISSUE THREAD

**Issue by measu** [lief-project/LIEF#820]
**Describe the bug**
When dealing x86-64 statically linked  ELF file, file size larger than before after write().

**To Reproduce**
```
$ ls --size -h
total 852K
852K input_x64_static.bin

$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
>>> binary = lief.parse("input_x64_static.bin")
>>> binary.write("output")
>>> exit()

$ ls --size -h
total 2.6M
852K input_x64_static.bin  1.7M output
```

**Expected behavior**
I expect output file as same as input file. Because I make no changes to the file, except parse() and write().

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04.5
 - Target format: ELF
 - LIEF commit version: 0.12.3-39115d10

[FilesNeededForReproduce.zip](https://github.com/lief-project/LIEF/files/9976712/FilesNeededForReproduce.zip)

**Comment by romainthomas** [comment]
I confirm that this overhead should not happen. After investigation, the root cause seems to be related to the (re)building of the note sections.

I'll look for a fix in the upcoming weeks.

**Comment by romainthomas** [comment]
The overhead comes from the note sections and fixing this overhead issue is not straightforward. 
One solution consists in tweaking the ELF builder to skip re-building the notes:

```python
import lief
elf = lief.parse("./input_x64_static.bin")
builder = lief.ELF.Builder(elf)
builder.config.notes = False
builder.build()
builder.write("./output")
``` 

```text
-rwxr-x--- 1 romain romain  871896 Nov 10 03:02 input_x64_static.bin
-rw-r----- 1 romain romain  871896 Nov 12 10:36 output
```

**Comment by measu** [comment]
Thank you ! That solved my problem :)
