### ISSUE TITLE
add section size not matching data provided

### ISSUE THREAD

**Issue by izff** [lief-project/LIEF#829]
**Describe the bug**
Add section for existing ELF file, added data size and result elf seciton size are not the same.
Actually, the added section has its size aligned with 0x10B.

**To Reproduce**
This issue can easily be reproduced by running the example "elf_add_section.cpp". In the code, the added data has size 100:
`std::vector<uint8_t> data(100, 0);`
While in resulted ELF file, this added section size is shown to be 0x80 (128).

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04
 - Target format: ELF
 - LIEF commit version: ``0.13-dev``

**Additional context**
By debugging, I came across the code for alignment in the project, in "src/ELF/Binary.tcc" line 413:
`uint64_t segmentsize = align(content.size(), 0x10);`

I dont really understand why this alignment is necessary as I dont know format of ELF file in depth.
Could anyone enlight me on the necessarity of alignment, please?

**Comment by romainthomas** [comment]
Yes it's because the ELF format enforces alignment on segments.
