### ISSUE TITLE
LIEF::ELF::Symbol.section() is always nullptr

### ISSUE THREAD

**Issue by adamjseitz** [lief-project/LIEF#841]
**Describe the bug**

`LIEF::ELF::Symbol`'s `section()` method always returns `nullptr`. The documentation says:

> [Section](https://lief-project.github.io//doc/latest/api/cpp/elf.html#_CPPv4N4LIEF3ELF7SectionE) `*section()`
>> [Section](https://lief-project.github.io//doc/latest/api/cpp/elf.html#classLIEF_1_1ELF_1_1Section) associated with the symbol or a nullptr if it does not exist.

The implementation in `ELF/Symbol.cpp`:

```
Section* Symbol::section() {
  return section_;
}
```

and `section_` appears to be initialized to `nullptr` and never updated.

**To Reproduce**

```cpp
auto binary = LIEF::ELF::Parser::parse(path);

for (auto& symbol : binary.symbols())
{
    assert(symbol.section() == nullptr);
}
```

**Expected behavior**

`symbol.section()` should return a `Section*` to a section if the symbol has a `shndx` that refers to a real section.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04
 - Target format (ELF)
 - LIEF commit version: 0.12.3
 
**Additional context**
N/A

**Comment by romainthomas** [comment]
Indeed this is missing. I'll fix it

**Comment by romainthomas** [comment]
Done
