### ISSUE TITLE
Wrong value returned by has(DLL_CHARACTERISTICS.NO_SEH)

### ISSUE THREAD

**Issue by Wenzel** [lief-project/LIEF#848]
**Describe the bug**
Testing a **non** SafeSEH binary with `bin.optional_header.has(DLL_CHARACTERISTICS.NO_SEH)` returns `False`

**To Reproduce**

~~~python3
import lief
from lief.PE import DLL_CHARACTERISTICS

# from https://github.com/Wenzel/checksec.py-test-binaries/tree/main/pe
bin = lief.parse('./tests/binaries/pe/safe_seh_disabled.exe')
bin.optional_header.has(DLL_CHARACTERISTICS.NO_SEH)
~~~
-> `False`

You can confirm this with `winchecksec`:
![image](https://user-images.githubusercontent.com/964610/209482990-0f96cad0-6e96-4af9-bace-e8764d29522a.png)

**Expected behavior**
It should have returned `True`, confirming that the binary has `NO_SEH`indeed.

**Environment (please complete the following information):**
 - System and Version : `Ubuntu 22.10`
 - Target format PE
 - LIEF commit version: ``0.12.3-39115d10``

**Additional context**
Only test failing after switching [checksec.py](https://github.com/Wenzel/checksec.py) to LIEF `0.12.3`
(and fixing https://github.com/lief-project/LIEF/issues/805)
![image](https://user-images.githubusercontent.com/964610/209482956-c74cdac1-7043-497c-a25c-1482503acf04.png)

Thanks !

**Comment by romainthomas** [comment]
Hello @Wenzel,

Actually the output of `bin.optional_header.has(DLL_CHARACTERISTICS.NO_SEH)` for both version (`0.11.0` and `0.12.3`) is consistent so I think this issues comes from your testsuite. 


##### LIEF 0.11.0

```python
import lief
print(lief.__version__)
pe = lief.parse("./safe_seh_disabled.exe")
print(pe.optional_header.has(lief.PE.DLL_CHARACTERISTICS.NO_SEH))
```  

```
0.11.0-f58605f9
False
```

##### LIEF 0.12.3

```python
import lief
print(lief.__version__)
pe = lief.parse("./safe_seh_disabled.exe")
print(pe.optional_header.has(lief.PE.DLL_CHARACTERISTICS.NO_SEH))
```  

```
0.12.3-39115d10
False
```

Did I miss something?

**Comment by Wenzel** [comment]
Hi @romainthomas 
thanks for the quick feedback, and looking at it

Indeed, the output is the same for both versions of LIEF !
I couldn't setup LIEF `0.11.0` anymore because of a setup.py compatibility issue.


But with what you just say, I spinned a Dockerfile to install checksec and LIEF v0.11.0 on Ubuntu 20.04, and better understand why the behavior has changed on this `SafeSEH`test.

My conclusions are that accessing the `load_configuration.se_handler_table` has changed:

*LIEF 0.11.0*
![image](https://user-images.githubusercontent.com/964610/209673979-dc3e3810-a2d5-4a06-ba57-d35b1aaa6567.png)

This raises an `AttributeError` ([and I was using that behavior to return `False`](https://github.com/Wenzel/checksec.py/blob/master/checksec/pe.py#L88))
*LIEF 0.12.3*
![image](https://user-images.githubusercontent.com/964610/209674138-9a790046-1e66-4121-baad-b20097bed904.png)
This returns a valid value.


If we look at winchecksec [`SafeSEH test`](https://github.com/trailofbits/winchecksec/blob/v3.1.0/checksec.cpp#L226)
~~~Cpp
    // NOTE(ww): a load config under 72/112 bytes implies the absence of the
    // SafeSEH fields.
    if (loadConfigSize_ < 112 &&
        !(imageCharacteristics_ & peparse::IMAGE_FILE_32BIT_MACHINE && loadConfigSize_ >= 72)) {
        return REPORT_EXPLAIN(NotPresent, kSafeSEHDescription,
                              "Image load config is too short to contain a SE handler table.");
    }

    if (isSEH() && loadConfigSEHandlerTable_ != 0 && loadConfigSEHandlerCount_ != 0) {
        return REPORT(Present, kSafeSEHDescription);
    } else {
        return REPORT(NotPresent, kSafeSEHDescription);
    }
~~~

Checking our binary with winchecksec v3.1.0:
~~~JSON
      ....
      "safeSEH": {
        "description": "Binaries with SafeSEH enabled have additional protections for stack-based structured exception handlers.",
        "explanation": "Image load config is too short to contain a SE handler table.",
        "presence": "NotPresent"
      },
~~~

So the `se_handler_table` load config shouldn't return `None` in my opinion.

Tell me what you think !

**Comment by romainthomas** [comment]
Actually the latest version (0.12.0) has the correct behavior which can also be confirmed by using [pegoat-no-safeseh.exe](https://github.com/trailofbits/winchecksec/blob/v3.1.0/test/assets/64/pegoat-no-safeseh.exe) from [winchecksec](https://github.com/trailofbits/winchecksec).

#623 gives the details about the root cause of this change.

**Comment by romainthomas** [comment]
To be re-opened if the issue is still there.

**Comment by Wenzel** [comment]
Hi @romainthomas,

sorry for the late feedback here.
Regarding the [pegoat-no-safeseh.exe](https://github.com/trailofbits/winchecksec/blob/v3.1.0/test/assets/64/pegoat-no-safeseh.exe) binary that you linked, it's an x64 binary, so SafeSEH is simply not applicable there.

If we test the same 32 bits binary:
```Python
In [1]: import lief

In [2]: bin = lief.parse("/home/wenzel/Téléchargements/pegoat-no-safeseh_32bits.exe")

In [3]: bin.optional_header.has(DLL_CHARACTERISTICS.NO_SEH)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In [3], line 1
----> 1 bin.optional_header.has(DLL_CHARACTERISTICS.NO_SEH)

NameError: name 'DLL_CHARACTERISTICS' is not defined

In [4]: from lief.PE import DLL_CHARACTERISTICS

In [5]: bin.optional_header.has(DLL_CHARACTERISTICS.NO_SEH)
Out[5]: False

In [6]: bin.load_configuration.se_handler_table
Out[6]: 0

In [7]: bin.load_configuration.se_handler_count
Out[7]: 0
```

Both `se_handler_table` and `se_handler_count`are null.

However, in my [test binary](https://github.com/Wenzel/checksec.py-test-binaries/blob/main/pe/safe_seh_disabled.exe), these 2 fields when extracted by LIEF have a value:
```Python
In [1]: import lief

In [2]: bin = lief.parse("./tests/binaries/pe/safe_seh_disabled.exe")

In [3]: bin.load_configuration.se_handler_table
Out[3]: 4224800

In [4]: bin.load_configuration.se_handler_count
Out[4]: 2
```

And Winchecksec validates my binary as non `SafeSEH`.
So LIEF parser should have returned NULL for these 2 fields, which is not the case here.

**Comment by romainthomas** [comment]
Actually there are two things:

1. whether the value of `se_handler_table` / `se_handler_count` is set in the load config table
2. the interpretation of these values in the perspective of the architecture (x64 vs x86).

I double checked (c.f. the output from llvm below) and `se_handler_table` / `se_handler_count` is set in your `safe_seh_disabled.exe`. Windows might decide to not enable "SafeSEH" because of the x86 architecture but these fields are present and thus, should be returned to the user.

Output from LLVM:

```bash
$ llvm-readobj --coff-load-config safe_seh_disabled.exe

File: /home/romain/tmp/safe_seh_disabled.exe
Format: COFF-i386
Arch: i386
AddressSize: 32bit
LoadConfig [
  Size: 0xA0
  TimeDateStamp: 1970-01-01 00:00:00 (0x0)
  MajorVersion: 0x0
  MinorVersion: 0x0
  GlobalFlagsClear: 0x0
  GlobalFlagsSet: 0x0
  CriticalSectionDefaultTimeout: 0x0
  DeCommitFreeBlockThreshold: 0x0
  DeCommitTotalFreeThreshold: 0x0
  LockPrefixTable: 0x0
  MaximumAllocationSize: 0x0
  VirtualMemoryThreshold: 0x0
  ProcessHeapFlags: 0x0
  ProcessAffinityMask: 0x0
  CSDVersion: 0x0
  DependentLoadFlags: 0x0
  EditList: 0x0
  SecurityCookie: 0x409034
  SEHandlerTable: 0x407720
  SEHandlerCount: 2
  GuardCFCheckFunction: 0x40B000
  GuardCFCheckDispatch: 0x0
  GuardCFFunctionTable: 0x0
  GuardCFFunctionCount: 0
  GuardFlags: 0x100
  GuardAddressTakenIatEntryTable: 0x0
  GuardAddressTakenIatEntryCount: 0
  GuardLongJumpTargetTable: 0x0
  GuardLongJumpTargetCount: 0
  DynamicValueRelocTable: 0x0
  CHPEMetadataPointer: 0x0
  GuardRFFailureRoutine: 0x0
  GuardRFFailureRoutineFunctionPointer: 0x0
  DynamicValueRelocTableOffset: 0x0
  DynamicValueRelocTableSection: 0
  GuardRFVerifyStackPointerFunctionPointer: 0x0
  HotPatchTableOffset: 0x0
]
SEHTable [
  0x403520
  0x404000
]

```
