### ISSUE TITLE
v0.13.0 release date?

### ISSUE THREAD

**Issue by jorgschulze73** [lief-project/LIEF#859]
Hello Romain, thank you very much for your incredible work on LIEF.

I would like to ask what are the plans to release v0.13.0 with the changes mentioned in [this blog post you wrote](https://lief-project.github.io/blog/2022-05-08-macho/)?

I'm really looking forward the possibility to add new segments to iOS15+ macho files.

Thank you!

**Comment by romainthomas** [comment]
Hi @jorgschulze73
It will be likely released in March 2023.
