### ISSUE TITLE
Macho format file contains __TEXT, __gcc_except_tab segments, add_section will cause the app to crash

### ISSUE THREAD

**Issue by keroushe** [lief-project/LIEF#862]
Macho format file contains __TEXT, __gcc_except_tab segments, add_section will cause the app to crash

Step:

add code
```
@try {
        [self removeObserver:self forKeyPath:@"status"];
    } @catch(id anException){
    }
```

Under normal circumstances, the exception will be caught, but after using add_section, a crash will occur.

![image](https://user-images.githubusercontent.com/18285105/215665242-122be80b-963b-44d7-8088-db8096d9dad2.png)

**Environment :**
 - System and Version : [e.g. MacOS 12.2]
 - Target format (Mach-O)
 - LIEF commit version: master branch

**Comment by romainthomas** [comment]
Please re-open an issue with:

1. A concise title
2. The LIEF modifications you are doing (adding a section where? how?)
3. A sample to reproduce the error (not just "add code")

Thank you!
