### ISSUE TITLE
Saving without modify ELF file increments size

### ISSUE THREAD

**Issue by Trust04zh** [lief-project/LIEF#864]
**Describe the bug**

the problem is just as the title said, the following are the procedure to reproduce and attachments

```c
// world.c
#include <stdio.h>

int main() {
    printf("Hello World.\n");
    return 0;
}
```

```bash
$ gcc world.c -o world
```

```python
import lief.ELF as ELF
binary: ELF.Binary = ELF.parse('world')
binary.write('world.out')
```

`world` and `world.out` attached in the zip file

```bash
$ ls -lh world*
-rwxr-xr-x 1 kali kali 16K Feb  1 01:32 world
-rw-r--r-- 1 kali kali  79 Feb  1 01:31 world.c
-rw-r--r-- 1 kali kali 23K Feb  1 01:32 world.out
```

[world.zip](https://github.com/lief-project/LIEF/files/10553896/world.zip)

**Environment (please complete the following information):**

 - System and Version: x86_64 debian 11

```bash
$ uname -a
Linux kali 6.0.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.7-1kali1 (2022-11-07) x86_64 GNU/Linux
```

 - Target format: ELF
 - LIEF commit version: 0.12.3-39115d10

**Additional context**

A similar case was mentioned in the previous issue (#338, still open) , however, I noticed that in my case the size of an entry in the program header table increased by `0x1000`, which did not appear in the attachment of that issue, so I think they were caused by different reasons and opened the new issue.

Almost all of the extra `0x1000` bytes in the `PHDR` entry are `\x00`.

```bash
$ readelf -l world | head -n10 | tail -n5
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x00000000000002d8 0x00000000000002d8  R      0x8
```

```bash
$ readelf -l world.out | head -n10 | tail -n5
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x00000000000012d8 0x00000000000012d8  R      0x8
```

**Comment by romainthomas** [comment]
Fixed in master
