### ISSUE TITLE
Symbol is missing after parse->write

### ISSUE THREAD

**Issue by brenoguim** [lief-project/LIEF#866]
**Describe the bug**

A simbol disappeared after "parse" followed by "write".

**To Reproduce**

```
import lief
import os

path = '/usr/lib64/'
lib  = 'libQt5Gui.so.5'

l = lief.parse(path + lib)
l.write(lib)

print("before")
os.system("nm -D {} | grep _ZN8QPaletteD1Ev".format(path+lib))
print("after")
os.system("nm -D {} | grep _ZN8QPaletteD1Ev".format(lib))
```
results in the "after" being empty"

**Expected behavior**
I expected the symbol to continue to be present.

**Environment (please complete the following information):**
 - System and Version : CentOS7
 - Target format: ELF
 - LIEF commit version: 0.12.3-39115d10

**Additional context**

**Comment by romainthomas** [comment]
Hi @brenoguim 

Could you try with the nightly packages with this code:

```python
l = lief.ELF.parse(path + lib, , lief.ELF.DYNSYM_COUNT_METHODS.SECTION)
```

**Comment by romainthomas** [comment]
Closing as no replying

**Comment by brenoguim** [comment]
Sorry for the delay. It works on the nightly.
