### ISSUE TITLE
Unable to pip install legacy version

### ISSUE THREAD

**Issue by 60O** [lief-project/LIEF#868]
Unable to install a legacy version of lief

pip install lief==0.9.0

Results in a HTTP 404 error for the download page
URL: https://github.com/lief-project/LIEF/releases/download/0.9.0/lief-0.9.0-py3.8-windows_x64.egg

**Comment by romainthomas** [comment]
Why not using the latest version?

**Comment by Doid-Reyewliz** [comment]
> I need 0.9.0 for compatibility with the ember project https://github.com/elastic/ember

same

**Comment by romainthomas** [comment]
LIEF 0.9.0 was released on June 2018 and Python 3.8 came out in 2019. Hence, if you want to use this specific version of LIEF, please downgrade you Python version.
