### ISSUE TITLE
Section start address modified after adding new section

### ISSUE THREAD

**Issue by ASintzoff** [lief-project/LIEF#872]
**Describe the bug**
A section address is changed when adding another one located in an empty space.
Using any LIEF version starting with 0.12.0, I observe this behaviour with a specific ELF file.

**To Reproduce**
To generate the problematic ELF file, follow the instructions.
Be careful, as during the build, a lot of stuff is done (e.g. RISC-V gcc toolchain build).
If needed, I could upload somewhere the generated `fw_payload.elf` file (1.2 MB).

    git clone https://github.com/openhwgroup/cva6-sdk.git
    cd cva6-sdk/
    git submodule update --init --recursive
    make fw_payload.bin
    ls -l install64/fw_payload.elf

    $ readelf -S fw_payload.elf
    There are 26 section headers, starting at offset 0x1212a0:

    Section Headers:
      [Nr] Name              Type             Address           Offset
           Size              EntSize          Flags  Link  Info  Align
      [ 0]                   NULL             0000000000000000  00000000
           0000000000000000  0000000000000000           0     0     0
      [ 1] .text             PROGBITS         0000000080000000  00000120
           000000000000fe40  0000000000000000 WAX       0     0     8
      [ 2] .rodata           PROGBITS         0000000080010000  00010120
           0000000000001998  0000000000000000   A       0     0     8
      [ 3] .dynstr           STRTAB           0000000080011998  00011ab8
           00000000000001a0  0000000000000000   A       0     0     1
      [ 4] .hash             HASH             0000000080011b38  00011c58
           00000000000000a8  0000000000000004   A      10     0     8
      [ 5] .gnu.hash         GNU_HASH         0000000080011be0  00011d00
           00000000000000b8  0000000000000000   A      10     0     8
      [ 6] .data             PROGBITS         0000000080012000  00012120
           00000000000006c0  0000000000000000  WA       0     0     8
      [ 7] .dynamic          DYNAMIC          00000000800126c0  000127e0
           0000000000000120  0000000000000010  WA       3     0     8
      [ 8] .got              PROGBITS         00000000800127e0  00012900
           00000000000000b0  0000000000000008  WA       0     0     8
      [ 9] .got.plt          PROGBITS         0000000080012890  000129b0
           0000000000000010  0000000000000008  WA       0     0     8
      [10] .dynsym           DYNSYM           00000000800128a0  000129c0
           0000000000000228  0000000000000018   A       3     2     8
      [11] .rela.dyn         RELA             0000000080012ac8  00012be8
           0000000000000888  0000000000000018   A      10     0     8
      [12] .bss              NOBITS           0000000080014000  00013470
           00000000000203a8  0000000000000000  WA       0     0     8
      [13] .payload          PROGBITS         0000000080200000  00013470
           000000000005f838  0000000000000000  AX       0     0     16
      [14] .debug_line       PROGBITS         0000000000000000  00072ca8
           000000000002a4f3  0000000000000000           0     0     1
      [15] .debug_info       PROGBITS         0000000000000000  0009d19b
           000000000002ee9b  0000000000000000           0     0     1
      [16] .debug_abbrev     PROGBITS         0000000000000000  000cc036
           00000000000073a3  0000000000000000           0     0     1
      [17] .debug_aranges    PROGBITS         0000000000000000  000d33e0
           0000000000000930  0000000000000000           0     0     16
      [18] .debug_str        PROGBITS         0000000000000000  000d3d10
           0000000000005086  0000000000000001  MS       0     0     1
      [19] .debug_loc        PROGBITS         0000000000000000  000d8d96
           0000000000034a0e  0000000000000000           0     0     1
      [20] .debug_ranges     PROGBITS         0000000000000000  0010d7a4
           0000000000008660  0000000000000000           0     0     1
      [21] .comment          PROGBITS         0000000000000000  00115e04
           0000000000000020  0000000000000001  MS       0     0     1
      [22] .debug_frame      PROGBITS         0000000000000000  00115e28
           0000000000005b80  0000000000000000           0     0     8
      [23] .symtab           SYMTAB           0000000000000000  0011b9a8
           0000000000003528  0000000000000018          24   225     8
      [24] .strtab           STRTAB           0000000000000000  0011eed0
           00000000000022e7  0000000000000000           0     0     1
      [25] .shstrtab         STRTAB           0000000000000000  001211b7
           00000000000000e7  0000000000000000           0     0     1
    Key to Flags:
      W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
      L (link order), O (extra OS processing required), G (group), T (TLS),
      C (compressed), x (unknown), o (OS specific), E (exclude),
      p (processor specific)

To reproduce the issue

```python
import lief
print(lief.__version__)
elf_binary = lief.parse("fw_payload.elf")

print("before")
for elf_section in elf_binary.sections:
    if elf_section.name.startswith(".payload"):
        print(elf_section)

new_section = lief.ELF.Section(".new_section")
new_section.virtual_address = 0xa0000000
new_section.add(lief.ELF.SECTION_FLAGS.ALLOC)
new_section.size = 0x1000
new_section.content = [0xa5] * 0x1000
elf_binary.add(new_section)

print("after")
for elf_section in elf_binary.sections:
    if elf_section.name.startswith(".payload"):
        print(elf_section)
```

With LIEF 0.11.5, `.payload` section address is not changed.

    0.11.5-37bc2c9
    before
    .payload            PROGBITS       80200000  5f838     13470     6.51828   ALLOC EXECINSTR               LOAD
    after
    .payload            PROGBITS       80200000  5f838     13470     6.51828   ALLOC EXECINSTR               LOAD

With LIEF 0.12.3, `.payload` section address is unexpectedly changed.

    0.12.3-39115d10
    before
    .payload            PROGBITS       80200000  5f838     13470     6.51828   ALLOC EXECINSTR               LOAD
    after
    .payload            PROGBITS       802213a0  5f838     34810     6.51463   ALLOC EXECINSTR               LOAD

**Expected behavior**
No change of start address of `.payload` section.

**Environment (please complete the following information):**
 - System and Version: RedHat 8.7, Python 3.9.13
 - Target format: ELF
 - LIEF commit version: 0.12.3-39115d10

**Additional context**
I try also on Debian 10, Python 3.7.3, LIEF 0.13.0-047facb6.

    0.13.0-047facb6
    before
    .payload            PROGBITS       80200000  5f838     13470     6.51828   ALLOC EXECINSTR               LOAD
    after
    .payload            PROGBITS       802213a0  5f838     34810     6.51463   ALLOC EXECINSTR               LOAD

Unfortunately, I'm not able to install the dev version on my RedHat
as there is no support for `cp39-cp39-manylinux_2_24_x86_64`.
Only compatible tags starting with `cp39-cp39` I have are:

    cp39-cp39-manylinux2014_x86_64
    cp39-cp39-manylinux2010_x86_64
    cp39-cp39-manylinux1_x86_64
    cp39-cp39-linux_x86_64

**Comment by romainthomas** [comment]
Hi @ASintzoff,

Yes if you can upload `fw_payload.elf` it would be helpful.

**Comment by ASintzoff** [comment]
Uploaded [fw_payload.elf.gz](https://github.com/lief-project/LIEF/files/10928817/fw_payload.elf.gz) (434 kB)

**Comment by romainthomas** [comment]
Thank you, I identified the regression and I'm working on it. It is not trivial to fix so it might take a bit of time.
