### ISSUE TITLE
iOS `Logger` cannot write to `/tmp/lief.log`

### ISSUE THREAD

**Issue by kersson** [lief-project/LIEF#875]
**Describe the bug**
This library is not usable on iOS with logging enabled because the `Logger` tries to output to `/tmp/lief.log`, which is not allowed.
https://github.com/lief-project/LIEF/blob/39115d1084d43f929d5c5cf874a0822a901f80d7/src/logging.cpp#L47

The iOS app crashes with the following error:
```
spdlog fatal error: Failed opening file /tmp/lief.log for writing: Operation not permitted
```

**To Reproduce**
Use any function that instantiates the `Logger` on an iOS device (e.g. iPhone or iPad).

**Expected behavior**
Do not try to log to a file in `/tmp` as this is not writeable in iOS.

**Environment:**
 - System and Version: iOS 16.3.1
 - Target format: N/A
 - LIEF commit version: 0.12.3

**Additional context**
The switch to logging to `/tmp/lief.log` on iOS was introduced in 8bb11a2efa13e1497eea99aec6f20d0dff5fbf22 and released in version 0.12.0.

Perhaps these permissions were changed in a recent version of iOS? Otherwise, how did this code ever work?

**Comment by romainthomas** [comment]
Hi @kersson 

Actually my use case of LIEF for iOS was on Jailbroken devices for which you can write in `/tmp/`. I guess a safer approach would be to use the syslog sink from spdlog?

**Comment by kersson** [comment]
Hey @romainthomas. Ah, okay, that explains it! 😄 

It would be nice if there was some way to pass in a custom sink. We use spdlog as well and use custom sinks to put logs in various places (e.g. log files or to network logging services).

If a custom sink is too big of an API change, then perhaps even just allowing the user to set the log file location would be nice.

I've not used syslog before, so I don't know how easy it is to filter/subscribe to specific messages. That is, I wouldn't want to have to manually sift through all the other system stuff just to find the LIEF logs.

**Comment by kersson** [comment]
Thanks so much for the quick fix! ❤️
