### ISSUE TITLE
 'import lief  ' error  on master branch

### ISSUE THREAD

**Issue by loongson-zn** [lief-project/LIEF#885]
**Describe the bug**
`import lief ` error
```
[root@localhost dist]# python3.8
Python 3.8.6 (default, Mar  7 2022, 16:47:42) 
[GCC 8.3.0 20190222 (Loongson 8.3.0-27 vec)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_lief)
>>> 
```
**To Reproduce**

On master branch, `python3.8 setup.py bdist_wheel` ; pip3 install *.wheel;  'import lief  ' error 
But on 0.12.3 tag ,no error
```
(zn-py38) loongson@localhost.16:~/zhangna/LIEF-guanfang/LIEF/dist/master$ arch
x86_64

(zn-py38) loongson@localhost.16:~/zhangna/LIEF-guanfang/LIEF$ git branch -a
  0.12.3
* master
(zn-py38) loongson@localhost.16:~/zhangna/LIEF-guanfang/LIEF$ readelf -s lief.cpython-38-x86_64-linux-gnu.so | grep PyInit
  7352: 00000000001b6650  1395 FUNC    GLOBAL DEFAULT   12 PyInit__lief

(zn-py38) loongson@localhost.16:~/zhangna/LIEF-guanfang/LIEF$ git branch 
* 0.12.3
  master
(zn-py38) loongson@localhost.16:~/zhangna/LIEF-guanfang/LIEF$ readelf -a lief.cpython-38-x86_64-linux-gnu.so| grep PyInit
   435: 00000000001b96a0  1395 FUNC    GLOBAL DEFAULT   12 PyInit_lief
```
**Expected behavior**
A clear and concise description of what you expected to happen (if applicable)

**Environment (please complete the following information):**
 - System and Version : [e.g. Ubuntu 16.04]
 - Target format (PE, ELF, Mach-O)
 - LIEF commit version: ``python -c "import lief;print(lief.__version__)"`` or the one from ``LIEF/config.h``

**Additional context**

**Comment by romainthomas** [comment]
Yes I missed to finish the new documentation but you should now install from the `setup.py` in the `api/python` directory.

**Comment by loongson-zn** [comment]
> Yes I missed to finish the new documentation but you should now install from the `setup.py` in the `api/python` directory.
@romainthomas 
What do you mean? Steps:
1. git clone https://github.com/lief-project/LIEF.git
2. cd LIEF
3. python3 setup.py bdist_wheel  (or mkdir build; cmake .. && make)
4.  product lief.so 
5. On master branch, `readelf -s   lief.so| grep PyInit` , output **one more underline**, have two underline; One v0.12.3 branch, only have one underline


Second，please offer documentation link.

**Comment by loongson-zn** [comment]
> 5.On master branch, readelf -s   lief.so| grep PyInit , output one more underline, have two underline (FUNC PyInit__lief); One v0.12.3 branch, only have one underline (FUNC PyInit_lief )
What I really want to know is why?   @romainthomas

**Comment by loongson-zn** [comment]
yeah, you are right. I need `cd  api/python ` to compile.
