### ISSUE TITLE
Offset mismatch in debug information after dynamic symbol renaming

### ISSUE THREAD

**Issue by nogmorgoth** [lief-project/LIEF#886]
**Describe the bug**
LIEF is not able to correctly modify debug information after renaming a dynamic symbol.
Therefore, debug functionality like breakpoints is broken.

**To Reproduce**
Compile a library libfoo.so containing a dummy "void foo()" function using -g3.
Use lief to rename dynamic symbol _Z3foov to modified name _Z3foov_suffix.
Use objdump to disassembly .text section and to dump debug.info:
	objdump --dwarf=info libfoo.so > debug.info
	objdump -d libfoo.so > debug.assembly
Now it is possible to compare both files and see that addresses are different in debug section and assembly section:
assembly: 0000000000002105 <_Z3foov>:
debug:     <7b9>   DW_AT_linkage_name: (indirect string, offset: 0x4883): _Z3foov
                <7bd>   DW_AT_low_pc      : 0x1105

**Expected behavior**
Addresses in debug sections should match new addresses after renaming dyn symbols.
Debug sections addresses needs to be modified accordingly when dynamic symbols are renamed.

**Environment (please complete the following information):**
 - System and Version : RedHat 7.6
 - Target format: ELF
 - LIEF commit version: 0.12.3-39115d10

**Additional context**
The mismatch found was in .debug_info section. I haven't explored the other debug sections, they probably also have mismatches.

**Comment by romainthomas** [comment]
Yes I agree but it's a non-goal of LIEF to keep the debug information consistent while modifying the binary.
