### ISSUE TITLE
Expose section_string_table_idx in Python

### ISSUE THREAD

**Issue by fzakaria** [lief-project/LIEF#887]
Can we expose section_string_table_idx_ in the Python bindings?

I am not familiar with Python to C bindings but if you give me some pointers, I can contribute the necessary changes.
(I imagine it's straightforward)

**Comment by romainthomas** [comment]
It's already exposed: [lief.ELF.Header.section_name_table_idx](https://lief-project.github.io/doc/latest/api/python/elf.html#lief.ELF.Header.section_name_table_idx)
