### ISSUE TITLE
MACHO: Entrypoint calculation incomplete

### ISSUE THREAD

**Issue by rammy22** [lief-project/LIEF#89]
I've tested LIEF on the micro_macho executable (http://seriot.ch/texts/hello_macho/micro_macho.zip) and it fails to find an entrypoint, although it has one.
```
>>> from lief import MachO
>>> test=MachO.parse('micro_macho')
>>> test[0].has_entrypoint
False
>>> test[0].header.file_type
FILE_TYPES.EXECUTE
```
Per http://seriot.ch/texts/hello_macho/micro_macho.pdf, the entrypoint is at 0x68.

Please fix

**Comment by romainthomas** [comment]
Yes it's because ``LC_UNIXTHREAD`` command is not parsed yet
