### ISSUE TITLE
Doxygen documentation is not working

### ISSUE THREAD

**Issue by tbhaxor** [lief-project/LIEF#902]
**Describe the bug**

Doxygen documents for c++ is not working on the page

**To Reproduce**
Just open this link

https://lief-project.github.io/doc/latest/api/cpp/macho.html#binary

**Expected behavior**

It should show the documentation

**Environment (please complete the following information):**
 - System and Version : [e.g. Ubuntu 16.04] MacOS 13.1
 - Target format (PE, ELF, Mach-O) Mach-O
 - LIEF commit version: ``python -c "import lief;print(lief.__version__)"`` or the one from ``LIEF/config.h`` 0.13.0

It is not a LIEF library bug though, but still take it

**Comment by tbhaxor** [comment]
I checked stable docs works

**Comment by romainthomas** [comment]
Fixed. I forgot an update since the release 0.13.0
