### ISSUE TITLE
aarch64 whl uses higher version libc version(2.32)

### ISSUE THREAD

**Issue by DiamondHunters** [lief-project/LIEF#904]
**Describe the bug**
```
>>> import lief
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rock/.local/lib/python3.8/site-packages/lief/__init__.py", line 2, in <module>
    from . import _lief
ImportError: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/rock/.local/lib/python3.8/site-packages/lief/_lief.cpython-38-aarch64-linux-gnu.so)
```
Using a higher version of glibc in docker?
This leads packages from the pip source only works on ubuntu2204 or higher.
Why not use the same libc version as before :)

**To Reproduce**
1.pip3 install lief (ubuntu 20.04,aarch64)
2.python3 -c "import lief"

**Expected behavior**
normal import
Like lief 0.12.3 wheel, using GLIBC_2.17 and work well on Ubuntu 20.04.

**Environment (please complete the following information):**
 - System and Version : ubuntu 20.04,aarch64

**Additional context**

**Comment by DiamondHunters** [comment]
I think the issue was mistakenly closed :) It should be 903 instead of 904.

**Comment by romainthomas** [comment]
Yes you are right

**Comment by romainthomas** [comment]
Indeed, I had to update the version of gcc (moving to 12.2) but I missed the `libc` version issue.
