### ISSUE TITLE
Reduce compilation objects by specifying the module

### ISSUE THREAD

**Issue by tbhaxor** [lief-project/LIEF#905]
**Describe the bug**

This is not a bug, but a question. I want to use LIEF only on ELF binaries, how can I disable other file formats so that it reduces compile objects and time. Currently it compiles all 500+ objects.

<!--
**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen (if applicable)

**Environment (please complete the following information):**
 - System and Version : [e.g. Ubuntu 16.04]
 - Target format (PE, ELF, Mach-O)
 - LIEF commit version: ``python -c "import lief;print(lief.__version__)"`` or the one from ``LIEF/config.h``

**Additional context**
-!>

**Comment by romainthomas** [comment]
Documentation
