### ISSUE TITLE
use extend function without moving the relocation 

### ISSUE THREAD

**Issue by araout42** [lief-project/LIEF#906]
I need to extend the .text section to add code into it,
when i use it the relocation and symbols are shifted wich break the executable...

for example on the entrypoint of the echo binary with extended text section by 1 byte
![image](https://user-images.githubusercontent.com/41875074/234602871-f0aa8643-c4e8-4fc9-ac96-1310be3ce0b3.png)

![image](https://user-images.githubusercontent.com/41875074/234603047-49ebf730-e97d-460d-b2f5-fabb54a755d1.png)

it mooves the offset ot libc_start_main reloc so the program doesnt call the right place and crash

On the normal echo we have this :
![image](https://user-images.githubusercontent.com/41875074/234603464-d3b33c3d-ec86-4218-8c68-c58f9feac59c.png)

![image](https://user-images.githubusercontent.com/41875074/234603577-800b081d-094e-4247-bd58-32d7adcbb218.png)

I tryed to shift back the relocation by 1 byte...

but it still crash afterward when it tries to find the memcpy function that has also been shifted

Can we extend text section and shift the sections after without mooving the relocations addresses ??

Thank you

**Comment by romainthomas** [comment]
What you are describing is actually the reason why you can't extend the `.text` section.
