### ISSUE TITLE
Possible add or access, to specific function in the python api or c api

### ISSUE THREAD

**Issue by araout42** [lief-project/LIEF#907]
I tried to access these function without success in the python API i searched in the code, and couldnt find them

shift_segments
shift_sections
shift_dynamic_entries
shift_symbols
shift_relocations

Would you consider usefull adding them ?

Thank you ! :)

**Comment by romainthomas** [comment]
@araout42 Please follow the issue template not just API name dropping. If you don't think ahead/detail your need(s), it won't be addressed.
