### ISSUE TITLE
lief.parse('steam').verify_signature() returns VERIFICATION_FLAGS.CERT_NOT_FOUND | VERIFICATION_FLAGS.BAD_SIGNATURE

### ISSUE THREAD

**Issue by keakon** [lief-project/LIEF#912]
**Describe the bug**
`lief.parse('steam.exe').verify_signature()` reports `Can't find certificate for which the issuer is C=US, O=DigiCert\, Inc., CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1`.
Windows says its signature is valid.

**To Reproduce**
```python
b = lief.parse('steam.exe')

for s in b.signatures:
    for c in s.certificates:
        print(c.subject)

print(b.verify_signature())
```
```
C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Trusted Root G4
C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Trusted Root G4
C=US, O=DigiCert, Inc., CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA
C=US, O=DigiCert, Inc., CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1
C=US, O=DigiCert, CN=DigiCert Timestamp 2022 - 2
C=US, ST=Washington, L=Bellevue, O=Valve Corp., CN=Valve Corp.
Can't find certificate for which the issuer is C=US, O=DigiCert\, Inc., CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1
VERIFICATION_FLAGS.CERT_NOT_FOUND | VERIFICATION_FLAGS.BAD_SIGNATURE
```

**Expected behavior**
The result should be OK.

**Environment (please complete the following information):**
 - System and Version : macOS 13.3.1
 - Target format (PE, ELF, Mach-O): PE
 - LIEF commit version:  0.13.0-966a66c7

**Additional context**

**Comment by romainthomas** [comment]
Can you attach the binary?

**Comment by keakon** [comment]
@romainthomas This is the binary: [steam.exe.zip](https://github.com/lief-project/LIEF/files/11411680/steam.exe.zip)
