### ISSUE TITLE
LEIF will not build when getting package form AUR

### ISSUE THREAD

**Issue by ConstantinCezarBegu** [lief-project/LIEF#915]
**Describe the bug**
paru -Syu nvidia-util-nvlax 
OR
paru -Syu leif

resoltys in:

<img width="1421" alt="image" src="https://github.com/lief-project/LIEF/assets/38817297/102b0f1e-c2f8-4a42-8876-141465266010">

**To Reproduce**
paru -Syu nvidia-util-nvlax 
OR
paru -Syu leif

**Expected behavior**
should build successfully.

**Additional context**
all packages that have this package as dependency will fail to build from the AUR...

**Comment by romainthomas** [comment]
Here are the reasons: 

1. No information about the version of LIEF
2. No information about your compiler nor about your environment (distribution, version etc). 
3. LIEF not LEIF
4. result not resoltys

You just dropped a screenshot and the command line without taking the effort to provide a way to reproduce it. Thus, I don't put effort in this kind of issue and they are flagged as incomplete. 

Feel free to re-open a **proper** issue.

**Comment by romainthomas** [comment]
> LEIF was the latest version as of when I have tried to write this.

**LIEF** not LEIF 

> I would recommend a more productive approach: Put a label with missing information

The issue template already mentions the required information, you just discarded them. 

> if author of the issue does not provide more information after X time then close the ticket (could be done by a task)?

I agree and it's how I process in most of the issue expect when I feel that the user just "dropped" the issue with "*fix my issue please*". You can look at the issues that are flagged as [incomplete](https://github.com/lief-project/LIEF/issues?q=is%3Aissue+is%3Aclosed+label%3AIncomplete) to make your opinion.
