### ISSUE TITLE
C++ style comments are not allowed in ISO C90 error in C examples compilation

### ISSUE THREAD

**Issue by roboman2444** [lief-project/LIEF#916]
**Describe the bug**

In compilation. A lot of "C++ style comments are not allowed in ISO C90" errors occur.  Compilation fails.

I assume that going to -std=c99 will fix this.

Here is an example of one of the errors. There are hundreds of occurrences. 
'''
/home/roboman2444/LIEF/api/c/include/LIEF/ELF.h:19:1: error: C++ style comments are not allowed in ISO C90
   19 | //! @defgroup elf_c_api ELF C API
      | ^
'''

**To Reproduce**
Standard compilation steps (cmake, make). On ArchLinux.  Also happens in AUR package building.

**Environment (please complete the following information):**
 - System and Version : Arch Linux up-to-date at the time of this issue.
 - gcc version 13.1.1 20230429 (GCC)
 - cmake version 3.26.3
 - LIEF commit version: 5e5a5bf6325816bc8a2c2c4673a8e52e8689baf2 (current git commit at the time of this issue).
 
**Additional context**

Might be related to #915

**Comment by roboman2444** [comment]
Still has issues, even with the fixes.
`
[100%] Building C object examples/c/CMakeFiles/c_pe_reader.dir/pe_reader.c.o
In file included from /home/roboman2444/LIEF/api/c/include/LIEF/MachO/Binary.h:29,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/MachO.h:21,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/LIEF.h:19,
                 from /home/roboman2444/LIEF/examples/c/elf_reader.c:5:
/home/roboman2444/LIEF/include/LIEF/visibility.h:20:1: error: C++ style comments are not allowed in ISO C90
   20 | // Thanks to https://github.com/aguinet/dragonffi/blob/40f3fecb9530a2ef840f63882c5284ea5e8dc9e8/include/dffi/exports.h
      | ^
/home/roboman2444/LIEF/include/LIEF/visibility.h:20:1: note: (this will be reported only once per input file)
In file included from /home/roboman2444/LIEF/api/c/include/LIEF/MachO/enums.h:25,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/MachO/Header.h:20,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/MachO/Binary.h:31:
/home/roboman2444/LIEF/include/LIEF/MachO/enums.inc:4:40: error: C++ style comments are not allowed in ISO C90
    4 |   _LIEF_EI(MH_MAGIC)    = 0xFEEDFACEu, ///< 32-bit big-endian magic
      |                                        ^
/home/roboman2444/LIEF/include/LIEF/MachO/enums.inc:4:40: note: (this will be reported only once per input file)
In file included from /home/roboman2444/LIEF/api/c/include/LIEF/MachO/Binary.h:29,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/MachO.h:21,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/LIEF.h:19,
                 from /home/roboman2444/LIEF/examples/c/macho_reader.c:5:
/home/roboman2444/LIEF/include/LIEF/visibility.h:20:1: error: C++ style comments are not allowed in ISO C90
   20 | // Thanks to https://github.com/aguinet/dragonffi/blob/40f3fecb9530a2ef840f63882c5284ea5e8dc9e8/include/dffi/exports.h
      | ^
/home/roboman2444/LIEF/include/LIEF/visibility.h:20:1: note: (this will be reported only once per input file)
In file included from /home/roboman2444/LIEF/api/c/include/LIEF/MachO/enums.h:25,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/MachO/Header.h:20,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/MachO/Binary.h:31:
/home/roboman2444/LIEF/include/LIEF/MachO/enums.inc:4:40: error: C++ style comments are not allowed in ISO C90
    4 |   _LIEF_EI(MH_MAGIC)    = 0xFEEDFACEu, ///< 32-bit big-endian magic
      |                                        ^
/home/roboman2444/LIEF/include/LIEF/MachO/enums.inc:4:40: note: (this will be reported only once per input file)
In file included from /home/roboman2444/LIEF/api/c/include/LIEF/PE/enums.h:13,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/PE/Binary.h:31,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/PE.h:21,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/LIEF.h:20:
/home/roboman2444/LIEF/include/LIEF/PE/enums.inc:63:1: error: C++ style comments are not allowed in ISO C90
   63 | /// Storage class tells where and what the symbol represents
      | ^
/home/roboman2444/LIEF/include/LIEF/PE/enums.inc:63:1: note: (this will be reported only once per input file)
In file included from /home/roboman2444/LIEF/api/c/include/LIEF/PE/enums.h:13,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/PE/Binary.h:31,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/PE.h:21,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/LIEF.h:20:
/home/roboman2444/LIEF/include/LIEF/PE/enums.inc:63:1: error: C++ style comments are not allowed in ISO C90
   63 | /// Storage class tells where and what the symbol represents
      | ^
/home/roboman2444/LIEF/include/LIEF/PE/enums.inc:63:1: note: (this will be reported only once per input file)
In file included from /home/roboman2444/LIEF/api/c/include/LIEF/MachO/Binary.h:29,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/MachO.h:21,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/LIEF.h:19,
                 from /home/roboman2444/LIEF/examples/c/pe_reader.c:5:
/home/roboman2444/LIEF/include/LIEF/visibility.h:20:1: error: C++ style comments are not allowed in ISO C90
   20 | // Thanks to https://github.com/aguinet/dragonffi/blob/40f3fecb9530a2ef840f63882c5284ea5e8dc9e8/include/dffi/exports.h
      | ^
/home/roboman2444/LIEF/include/LIEF/visibility.h:20:1: note: (this will be reported only once per input file)
In file included from /home/roboman2444/LIEF/api/c/include/LIEF/MachO/enums.h:25,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/MachO/Header.h:20,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/MachO/Binary.h:31:
/home/roboman2444/LIEF/include/LIEF/MachO/enums.inc:4:40: error: C++ style comments are not allowed in ISO C90
    4 |   _LIEF_EI(MH_MAGIC)    = 0xFEEDFACEu, ///< 32-bit big-endian magic
      |                                        ^
/home/roboman2444/LIEF/include/LIEF/MachO/enums.inc:4:40: note: (this will be reported only once per input file)
In file included from /home/roboman2444/LIEF/api/c/include/LIEF/PE/enums.h:13,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/PE/Binary.h:31,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/PE.h:21,
                 from /home/roboman2444/LIEF/api/c/include/LIEF/LIEF.h:20:
/home/roboman2444/LIEF/include/LIEF/PE/enums.inc:63:1: error: C++ style comments are not allowed in ISO C90
   63 | /// Storage class tells where and what the symbol represents
      | ^
/home/roboman2444/LIEF/include/LIEF/PE/enums.inc:63:1: note: (this will be reported only once per input file)
make[2]: *** [examples/c/CMakeFiles/c_macho_reader.dir/build.make:76: examples/c/CMakeFiles/c_macho_reader.dir/macho_reader.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:958: examples/c/CMakeFiles/c_macho_reader.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [examples/c/CMakeFiles/c_elf_reader.dir/build.make:76: examples/c/CMakeFiles/c_elf_reader.dir/elf_reader.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:904: examples/c/CMakeFiles/c_elf_reader.dir/all] Error 2
make[2]: *** [examples/c/CMakeFiles/c_pe_reader.dir/build.make:76: examples/c/CMakeFiles/c_pe_reader.dir/pe_reader.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:931: examples/c/CMakeFiles/c_pe_reader.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
`

**Comment by roboman2444** [comment]
If you want a simple method to reproduce, try this:
`
sudo docker run --rm --pull=always ghcr.io/greyltc-org/archlinux-aur aur-install lief-git
`

Based on https://github.com/greyltc-org/docker-archlinux-aur

**Comment by romainthomas** [comment]
I welcome PR as well :)
