### ISSUE TITLE
Ability to add/remove Dyld Bindings

### ISSUE THREAD

**Issue by JJTech0130** [lief-project/LIEF#917]
*Please describe what you would like to have in LIEF*.
I need to convert some LAZY bindings into STANDARD bindings, and it seems like that is currently impossible. In order to convert them, you not only have to adjust the class type, but also move it from the LAZY bindings list to the normal bindings list.

This simply requires exposing an API to add and remove items from the internal list, as far as I can tell. 

If there is another way to convert the bindings and I'm not doing this right, that works too.

**Comment by romainthomas** [comment]
@JJTech0130 this is actually far from being "simple". Do you have the control over the sources?

**Comment by JJTech0130** [comment]
Not sure what you mean by “control over the sources”.

**Comment by JJTech0130** [comment]
Well, I ended up just using existing features to move everything over to one stub library, and then automatically generating that stub library. This isn't actually needed for my use-case any more.
