### ISSUE TITLE
0.13.0 fails to build on Arch, missing #include <cstdint>

### ISSUE THREAD

**Issue by dpellegr** [lief-project/LIEF#918]
**Describe the bug**
A missing header on ArchLinux leads to a build error:
```
LIEF-0.13.0/include/LIEF/DEX/Field.hpp:88:3: error: ‘uint32_t’ does not name a type
   88 |   uint32_t access_flags_ = 0;
```

**To Reproduce**
Run the build commands on ArchLinux:
```
cd LIEF-0.13.0/api/python
python ./setup.py build
```

**Expected behavior**
The compilation should not fail

**Environment (please complete the following information):**
 - System and Version : ArchLinux
 - LIEF commit version: 0.13.0

**Comment by romainthomas** [comment]
Which is actually this commit: https://github.com/lief-project/LIEF/commit/23223aaefa495e4f113f06446d21db23e229cd2a
