### ISSUE TITLE
Export symbols not added correctly to MachO dylibs

### ISSUE THREAD

**Issue by adriancable** [lief-project/LIEF#927]
**Describe the bug**
add_exported_function does not seem to modify the exports table quite right. 

**To Reproduce**
Take any dylib. First use `nm -g file` to show the exports, e.g.

```
0000000000007ff8 S _ExtensionVersionNumber
0000000000007f98 S _ExtensionVersionString
```

Now let's say we want to add a new export:

```
bin2lib = lief.parse("file")
bin2lib.add_exported_function(0x7ff8, "_testExport")
bin2lib.write("outfile")
```

The resulting file is missing the added export with `nm -g`:

```
0000000000007ff8 S _ExtensionVersionNumber
0000000000007f98 S _ExtensionVersionString
```

Running `nm` without the `-g` (i.e. show all symbols, not just exported) does list the added symbol, but with ? instead of S as the symbol type: (nm manpage doesn't document what this means - symbol flags are not correctly set?)

```
0000000000007ff8 S _ExtensionVersionNumber
0000000000007f98 S _ExtensionVersionString
0000000000007ff8 ? _testExport
```

So it appears the symbol is defined but not exported correctly. This seems to cause issues under certain circumstances when loading the modified dylib (specifically if I am exporting and then loading Objective C classes).

**Expected behavior**
Symbol is exported correctly and appears with 'S' symbol type via `nm -g`.

**Environment (please complete the following information):**
 - System and Version: macOS 12.4
 - Target format: Mach-O
 - LIEF commit version: 0.14.0-f0c3870d

**Comment by romainthomas** [comment]
```cpp
// clang -shared -o libtest.dylib test.c
#include <stdlib.h>
#include <stdio.h>

int hello() {
  printf("Hello\n");
  return 0;
}
```

```python
import ctypes
lib = ctypes.cdll.LoadLibrary("./libtest.dylib")
print(lib.hello)
```

```python
import lief
lib = lief.parse("./libtest.dylib")
lib.add_exported_function(0x7ff8, "_testExport")
lib.write("./libtest2.dylib")

lib = ctypes.cdll.LoadLibrary("./libtest2.dylib")
print(lib.testExport)
```

**Comment by adriancable** [comment]
@romainthomas - sorry if I wasn't clear in my original issue. Using your code:

```
import lief
lib = lief.parse("./libtest.dylib")
lib.add_exported_function(0x7ff8, "_testExport")
lib.write("./libtest2.dylib")

lib = ctypes.cdll.LoadLibrary("./libtest2.dylib")
print(lib.testExport)
```

output (as expected): `<_FuncPtr object at 0x10077c460>`

But: `nm -g libtest2.dylib`

```
0000000000003ee0 T _main
                 U _printf
```

Note `_testExport` is missing. Now: `nm libtest2.dylib`:

```
0000000000003ee0 T _main
                 U _printf
0000000000007ff8 ? _testExport
```

Note `?` type which means symbol is not correctly exported.

Is the issue now clear?

**Comment by adriancable** [comment]
Ah, I see! Do you know what's wrong about `nm` which enables it to correctly parse the export trie for unmodified dylibs generated by a linker, vs. the export trie as modified by LIEF? I am very happy to raise an issue to `nm` but it would be helpful to 'know what you know' about what it is doing wrong/differently.

**Comment by romainthomas** [comment]
I guess `nm` is not correctly parsing the Mach-O export trie and relies on the `LC_SYMTAB`
