### ISSUE TITLE
MACHO: Segment.content performance

### ISSUE THREAD

**Issue by rammy22** [lief-project/LIEF#93]
For sample 5cfd87c0602fda80ed34b8ffab5a53148e871b66b20106d85ebde2437eebd0bc getting the first byte of every function (all 3701 of them) takes days.
This is the code:
``` python
binary = lief.MachO.parse(
    '5cfd87c0602fda80ed34b8ffab5a53148e871b66b20106d85ebde2437eebd0bc'
)
# quasi infinite loop
first_byte = [binary.segment_from_offset(o).content[o] \
    for o in binary.function_starts.functions]
```
It looks like the Segment's content property is calculated just in time every time it is needed. In my example sample all functions are in the same segment.
``` python
>>> segments = [binary.segment_from_offset(o) for o in binary.function_starts.functions]
>>> segments[0].content == segments[1].content
True
>>> segments[0].content is segments[1].content
False
```
**Is this intended?**
 Looking at the [CPP file](https://github.com/lief-project/LIEF/blob/0236024191a517387055c559afee2cc85d0c00f6/src/MachO/SegmentCommand.cpp#L130) it looks like it is not. Is there some bug in the python wrapper implementation?

Thanks for looking into this!

**Comment by romainthomas** [comment]
You are right, Python binding doesn't return a *rvalue* but a **copy** of the ``std::vector``. 
What I plan to do, is to return an *iterator* over the content.

Related to #58

**Comment by rammy22** [comment]
Why not returning the rvalue then? Changing it to an interator is a breaking change. Also, indexing won't work with an iterator, which is how one would like to access the content, for getting function bytes/code.
