### ISSUE TITLE
Missing macOS (Darwin) arm64 builds since 0.12.3

### ISSUE THREAD

**Issue by kersson** [lief-project/LIEF#931]
Sorry if I missed the explanation, but why aren't macOS arm64 (Apple Silicon) binaries being included with releases anymore? The last release that had them was 0.12.2.

**Comment by romainthomas** [comment]
You are right, I missed them. It will be released along with the `0.13.2` release

**Comment by romainthomas** [comment]
Fixed with [0.13.2](https://github.com/lief-project/LIEF/releases/tag/0.13.2)
