### ISSUE TITLE
No source distribution uploaded to PyPI sinde 0.13

### ISSUE THREAD

**Issue by sscherfke** [lief-project/LIEF#933]
**Describe the bug**
Sinde 0.13 , there is no longer a source distribution available on PyPI

**To Reproduce**
Try to download a source distribution from PyPI

**Expected behavior**
A source distribution is provided for all releases.

**Environment (please complete the following information):**
*does not apply*

**Additional context**
Source distributions are needed for repackaging (e.g., for Conda or Linux packages).

**Comment by sscherfke** [comment]
There is a note in the changelog about this, but no reason is given and no link to docs for an alternate way.

So if you don't plan to bring back sdists, it would be very helpful to add a link to addtional docs to the Changelog. :-)

**Comment by romainthomas** [comment]
You are right PyPI releases do not contain source based distributions anymore (and it won't change).

Why?

- LIEF can still be pip-installed from source:
  `pip install --no-build-isolation git+https://github.com/lief-project/LIEF.git@0.13.2#subdirectory=api/python`

- `sdist` is selected by pip when none of the provided wheels match the environment.
  If that happens, either you have an un-supported Python version and thus, you should take the risk (yourself) to compile and run LIEF
  or you have an un supported system/architecture. Similary: you should take the risk to compile and run LIEF.

- *Source distributions are needed for repackaging (e.g., for Conda or Linux packages)*

   Well if you are repackaging it means that you compile from source to produce a package. Thus the git source should be taken.

**Comment by nightlark** [comment]
One other impact of this change is that piwheels is no longer able to build newer versions of lief: https://www.piwheels.org/project/lief/

piwheels requires the upstream PyPI package to build wheels and unlike repackaging for Conda/Linux, it is tightly coupled to the files released on PyPI -- there is no option to manually upload a sdist or wheel.
