### ISSUE TITLE
`lief.ELF.parse()`: "The provided stream is not supported by the ELF DataHandler" since 0.13.0

### ISSUE THREAD

**Issue by cher-nov** [lief-project/LIEF#935]
**Describe the bug**

Since 0.13.0, LIEF for Python fails with the aforementioned error on a simple application assembled into ELF by [pkg for Node.js](https://www.npmjs.com/package/pkg).
```
C:\Users\*\Desktop\lief_bug>elf_failure.py
parsing ELF...
Unknown stream for Handler
The provided stream is not supported by the ELF DataHandler
> end parsing at 0
```

**To Reproduce**

1. Create `app.js` with the following contents:
```js
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

2. Download [app-linux (34.7 MB)](https://disk.yandex.ru/d/3lvaw2HjGulDaQ) example file. It was obtained using **pkg** like this:
```bash
curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&\
apt-get install -y nodejs npm
npm install -g pkg
pkg app.js
```

3. Create `elf_failure.py` with the following contents and run it using Python 3.x with `lief` package installed:
```python3
#!/usr/bin/env python3

import lief

with open("app-linux", 'rb', 100 * 1024**2) as executable:
    print("parsing ELF...")
    elf = lief.ELF.parse(executable)
    print("> end parsing at", executable.tell())
```

**Expected behavior**
```
C:\Users\*\Desktop\lief_bug>elf_failure.py
parsing ELF...
> end parsing at 36387735
```

**Environment:**
 - System and Version: Debian 11.6
 - Target format: ELF
 - LIEF commit version: `0.13.0-966a66c7`

**Additional context**

Versions up to and including the latest current `0.13.2` are also affected; all versions of `0.12.x` show the expected result.
But if you specify a file name instead of a file object, then everything works in `0.13.x` as well:
```python3
#!/usr/bin/env python3

import lief
print("parsing ELF...")
elf = lief.ELF.parse("app-linux-overlay")
print(elf)
```

**Comment by cher-nov** [comment]
@romainthomas After fixing the bug, ELF is now processed normally, but the file I/O position remains zero. Is it as intended?

**Comment by romainthomas** [comment]
Indeed, this line is not required: https://github.com/lief-project/LIEF/blob/1335cb41be5cb4c1c6808f8154f2f2323ec47ae2/api/python/src/PyIOStream.cpp#L63
