### ISSUE TITLE
MACHO: parse() hangs on sample

### ISSUE THREAD

**Issue by rammy22** [lief-project/LIEF#94]
```python
>>> from lief import MachO
>>> path='0211028c0477846fefe4aa78d906623d0c558d97ab553856bceb6b9c78ff772e'
>>> m = MachO.parse(path)
Command 'DATA_IN_CODE' not parsed
Command 'DYLIB_CODE_SIGN_DRS' not parsed
Command 'CODE_SIGNATURE' not parsed
# parsing hangs. infinite loop?
```

Let me know if you can't find the sample.

**Comment by romainthomas** [comment]
Yes could you provide the sample ?

**Comment by rammy22** [comment]
[0211028c0477846fefe4aa78d906623d0c558d97ab553856bceb6b9c78ff772e.zip](https://github.com/lief-project/LIEF/files/1310057/0211028c0477846fefe4aa78d906623d0c558d97ab553856bceb6b9c78ff772e.zip)

**Comment by romainthomas** [comment]
Ok, the problem comes from dyld info parsing
