### ISSUE TITLE
No documentation for the `LIEF::ELF::Builder::config_t` struct

### ISSUE THREAD

**Issue by mjhouse** [lief-project/LIEF#943]
**Describe the bug**
I can't find any documentation that describes what all of the options do in the `Builder::config_t` struct.

**To Reproduce**
Look at the struct implementation.

**Expected behavior**
There should be documentation for these options.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04
 - Target format: ELF
 - LIEF commit version: 0.13.0-2aad8e8d

**Additional context**
I'm reading libc for an ARM54 system and then, without making any changes, writing it back out. I get a kernel panic when I boot the system because LIEF is changing the output somehow. I'm investigating ways to make the output more closely align with the input, but these options don't have any documentation.

**Comment by romainthomas** [comment]
You are right,  I will complete this documentation soon

**Comment by mjhouse** [comment]
@romainthomas Could you drop the description of those options here as well? It doesn't have to be pretty or neatly organized or anything, I just need to know what they do as soon as possible. Thanks.
