### ISSUE TITLE
Accessing 'abstract' property changes type of lief.ELF.Binary to lief.Binary

### ISSUE THREAD

**Issue by blbelew** [lief-project/LIEF#944]
**Describe the bug**
For an object b of type `lief.ELF.Binary`, simply accessing the `b.abstract` property in any way changes the type of the object. So, for example, if you access e.g. `b.abstract.header.endiannes`, a subsequent access to `b.write` will crash because `lief.Binary` has no `write` method. 

**To Reproduce**
Run the following script, which will crash because `binary` switches from `lief.ELF.Binary` to `lief.Binary`, which has no `write` method.

```python
#!/usr/bin/env python3
import lief

binary = lief.parse("/bin/sh")
binary.write("/dev/null") # succeeds without crashing
binary.abstract

# At this point, binary is no longer a lief.ELF.Binary but a
# lief.Binary, which has no write method. Simply accessing
# "binary.concrete" will switch the object back to lief.ELF.Binary.

#binary.concrete  ## Comment this line, crash. Uncomment this line,  no crash

binary.write("/dev/null")
```

**Expected behavior**
Accessing properties of objects should not change their class. 

**Environment (please complete the following information):**
 - System and Version : Ubuntu 22.04
 - Target format: ELF
 - LIEF commit version:  0.13.2-2d9855fc

**Comment by romainthomas** [comment]
It should have been fixed on `master` could you check with the nightly version?

**Comment by blbelew** [comment]
Thanks for the fast response! The latest nightly ('0.14.0-60ab1f28') installed with `pip install --index-url https://lief.s3-website.fr-par.scw.cloud/latest lief` does fix this problem, so go ahead and close. 

Out of curiosity can you provide the commit/MR that fixed this behavior?

**Comment by romainthomas** [comment]
It's a complete refactoring of the Python binding with this commit: https://github.com/lief-project/LIEF/commit/e37ffa9ec8fe415e83f60841b91f22b42542b464

Especially this: 

https://github.com/lief-project/LIEF/blob/b265280a635cdc5d37a2872e1e1f365d8fe4edbc/api/python/src/Abstract/pyBinary.cpp#L184-L207
