### ISSUE TITLE
RELR* tags UNDEFINED for ELF binaries

### ISSUE THREAD

**Issue by fanquake** [lief-project/LIEF#954]
Using `g++ (Ubuntu 13.1.0-2ubuntu2~23.04) 13.1.0` & `GNU ld (GNU Binutils for Ubuntu) 2.40`.
 
Compiling and linking using `g++ relr.cpp -Wl,-z pack-relative-relocs`:
```bash
int main() { 
	return 0;
}
```
and running the following (pip installed LIEF 0.13.2) on `a.out`:
```python
import lief

binary = lief.parse("a.out")

for entry in binary.dynamic_entries:
    print(entry)
```
gives:
```bash
NEEDED              22        libc.so.6 
<snip> 
VERSYM              502       
UNDEFINED           5c8       
UNDEFINED           18        
UNDEFINED           8         
NULL                0 
```

Using `objdump -x a.out`:
```bash
Dynamic Section:
  NEEDED               libc.so.6
<snip>
  VERSYM               0x0000000000000502
  RELR                 0x00000000000005c8
  RELRSZ               0x0000000000000018
  RELRENT              0x0000000000000008
```

I assume this is because the `DT_RELR*` tags in the LIEF codebase are marked as "Android specific", and currently defined to Android specific values.

**Comment by romainthomas** [comment]
Thank you @fanquake 
I added these new enums in 1ecfbf1fd8c22de5252f4e8b1a2e83199941faf5 and I keep track the packed relocation feature in https://github.com/lief-project/LIEF/issues/111 (yes it has been open since a while now)
