### ISSUE TITLE
Setting Flags of ELF Segments with Multiple Permission Fails

### ISSUE THREAD

**Issue by hkopp** [lief-project/LIEF#956]
**Describe the bug**
I am using the Python bindings of LIEF to manipulate segments in ELF files.

`ELF.SEGMENT_FLAGS.from_value()` only works for the values 0,1,2, and 4. If i want to have a compound flag, e.g., X+R (=1+4) fails.

**To Reproduce**

![1693220876 700879604](https://github.com/lief-project/LIEF/assets/6017673/149db17f-8e05-497e-bfa0-929bb71b828d)

or for copying:
```
import lief
lief._lief.ELF.SEGMENT_FLAGS.from_value(5)
```

**Expected behavior**
I would have expected that i get a segment that is readable and executable at the same time.

**Environment:**
 - System and Version : Fedora 38
 - Target format: ELF
 - LIEF commit version: 0.14.0-1ecfbf1f (nightly build)
 
**Additional context**
I would also be happy for a workaround, i.e., another way to mark segments as both, executable and readable.

**Comment by romainthomas** [comment]
Ack, I'll fix it.

**Comment by hkopp** [comment]
I found a workaround. You can use `lief._lief.ELF.SEGMENT_FLAGS.X | lief._lief.ELF.SEGMENT_FLAGS.R` to get a readable and writable segment. It cannot be printed, but it works. Well.... it's not a solution but a workaround that is helpful for me and may be helpful for others in the meantime.
