### ISSUE TITLE
section() in ELF/Symbols.cpp never set

### ISSUE THREAD

**Issue by fzakaria** [lief-project/LIEF#959]
**Describe the bug**
Symbols.hpp has a `section` method to return the Section pointer.
I can't seem to find anywhere in the file where it's set.
https://github.com/lief-project/LIEF/blob/1ecfbf1fd8c22de5252f4e8b1a2e83199941faf5/src/ELF/Symbol.cpp#L111C10-L111C15

`shndx()` is set during the initialization however.

**Expected behavior**
The section pointer should be returned.

**Comment by romainthomas** [comment]
Here you go: https://github.com/lief-project/LIEF/blob/1ecfbf1fd8c22de5252f4e8b1a2e83199941faf5/src/ELF/Parser.tcc#L1006-L1008

**Comment by fzakaria** [comment]
Thanks for your response @romainthomas 
I'll investigate again -- 

Why I opened the issue is that I was noticing 'section` was NULL for every symbol but `shndx` was not 0 (or other special values).  Couldn't understand why.....

**Comment by fzakaria** [comment]
@romainthomas here is a quick example (see below).
I believe this is still a bug?

```
❯ python
Python 3.10.12 (main, Jun  6 2023, 22:43:10) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import life

>>> ls = lief.parse("/bin/ls")

>>> ls.symbols
<lief._lief.ELF.Binary.it_dyn_static_symbols object at 0x7ff5d76f9070>

>>> [symbol.section for symbol in ls.symbols] 
[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
```

Can I re-open?

**Comment by romainthomas** [comment]
Indeed, it misses the section in the case of exported symbols (`.dynsym`). I'll fix it.

**Comment by fzakaria** [comment]
Okay so i wasn't hallucinating ;)

I enjoy the project btw.
I'm using it as part of https://github.com/fzakaria/sqlelf

**Comment by romainthomas** [comment]
Yes sorry the first issue where a bit confusing. [sqlelf](https://github.com/fzakaria/sqlelf) looks very interesting!
