### ISSUE TITLE
MACHO: segment_from_offset() clarification

### ISSUE THREAD

**Issue by rammy22** [lief-project/LIEF#96]
I have a sample where, given a function offset, segment_from_offset() finds a valid segment, but this segment is not actually containing the that offset. 
My question is: is there a bug in the segment_from_offset()  method or am i missing something?
``` python
>>> from lief import MachO
>>> m = MachO.parse('0631471fea260874583f5a1702ab4331cd693e99c51c36983d045411e9431812')
>>> macho = m[0]
>>> macho.segment_from_offset(0x000012cb)
<_pylief.MachO.SegmentCommand object at 0x103a45780>
>>> macho.segment_from_offset(0x000012cb).content[0x000012cb]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```

**Comment by rammy22** [comment]
[0631471fea260874583f5a1702ab4331cd693e99c51c36983d045411e9431812.zip](https://github.com/lief-project/LIEF/files/1310237/0631471fea260874583f5a1702ab4331cd693e99c51c36983d045411e9431812.zip)

**Comment by romainthomas** [comment]
Yes the *offset* in content is relative to the segment's offset. Thus if should be:

```python
>>> macho.segment_from_offset(0x000012cb).content[0]
```

**Comment by rammy22** [comment]
This can't be correct.
Segment_from_offset() does not modify the segment so content [0] cannot be the the data for all functions in that segment.

**Comment by romainthomas** [comment]
From the documentation (https://github.com/lief-project/LIEF/blob/master/include/LIEF/MachO/Binary.hpp#L149) 
``segment_from_offset`` will return the segment **holding** the offset. Then *content* will return the content of this segment. 
Why it's not correct ?

**Comment by rammy22** [comment]
Assuming I have offset 0x12cb and 0x12f0, both in the same segment, how do I get the data at these 2 offsets? My initial sollution was to use Segment_from_offset(offset).content[offset], which seems to be broken. What would be the correct way to do this?

**Comment by romainthomas** [comment]
You can do:

```python
offset = 0x12cb
segment = binary.segment_from_offset(offset)
delta = offset - segment.file_offset
data = segment.content[delta:]
```
