### ISSUE TITLE
LIEF build doesn't work with Ninja-MultiConfig generator

### ISSUE THREAD

**Issue by starseeker** [lief-project/LIEF#960]
**Describe the bug**
Attempting to compile with Ninja Multi-Config fails immediately

**To Reproduce**
mkdir build && cd build
cmake ../LIEF -G Ninja\ Multi-Config
ninja
ninja: error: 'cmake_object_order_depends_target_LIB_LIEF_RELEASE', needed by 'LIEF/build/mbed_tls/src/lief_mbed_tls/library/aes.c', missing and no known rule to make it

**Expected behavior**
Successful compile

**Environment (please complete the following information):**
 - System and Version : Ubuntu 23.04
 - Target format ELF
 - LIEF commit version: 8ef47cd979631506a1ce8ce16c68f746966e26a8

**Additional context**
Ninja MultiConfig is like Visual Studio or Xcode in that the build type is specified at compile time, not configure time - my guess is more variables need to be populated/specified for that scenario when setting up the LIEF targets.  It may also be that the dependencies aren't set up quite right - by default I believe Ninja will try a Debug build, and yet the error is in looking for a _RELEASE object order.  Similarly, if you specify the release build with ninja -f build-Release.ninja the error is reported for cmake_object_order_depends_target_LIB_LIEF_DEBUG instead.

**Comment by romainthomas** [comment]
I welcome your help on this issue :)

**Comment by starseeker** [comment]
Looking like this might be related:  https://gitlab.kitware.com/cmake/cmake/-/issues/20608

**Comment by starseeker** [comment]
I don't know if this is exactly how you'll want to fix it, but https://github.com/lief-project/LIEF/pull/961 lets the build complete here.

**Comment by romainthomas** [comment]
Done with #961
