### ISSUE TITLE
Python Binding: The `name` attribute in many classes are now of type `object`

### ISSUE THREAD

**Issue by fzakaria** [lief-project/LIEF#965]
I noticed the latest documentation online and the latest source on main has the type `object` for the name attribute.

For instance:
```
property name → object
Section’s name
```

I checked the source and Section's name property in the C++ file is of type string (https://github.com/lief-project/LIEF/blob/master/include/LIEF/Abstract/Section.hpp#L43)

Seems like something is causing the wrong type annotations.

**Comment by romainthomas** [comment]
Actually the correct annotation should be `str | bytes`. `bytes` if somehow the string can't be decoded in Python.
I'll fix it.

**Comment by fzakaria** [comment]
Symbols and sections have a `fullname` attribute that is only str thougu.

**Comment by romainthomas** [comment]
Indeed, I'll fix it as well. It should be `bytes`.
