### ISSUE TITLE
C++ version won't resolve functions size whereas Python will

### ISSUE THREAD

**Issue by h311d1n3r** [lief-project/LIEF#966]
Dear LIEF community,
I'm currently translating one of my project from Python to C++ for efficiency purpose. And this led me to a strange behavior. With the Python API of LIEF, the current code will output `705` on my sample.
```python
import lief

if __name__ == "__main__":
    elf = lief.ELF.parse("./elf_sample")
    ctr = 0
    for f in elf.functions:
        if f.size > 0:
            ctr += 1
    print(ctr)
```
However, with the C++ version, I get 0 running this code...
```c++
#include <LIEF/LIEF.hpp>
#include <iostream>

using namespace std;

int main() {
    unique_ptr<LIEF::Binary> elf = LIEF::Parser::parse("./elf_sample");
    size_t ctr = 0;
    for(LIEF::Function func : elf->ctor_functions()) if(func.size() > 0) ctr++;
    for(LIEF::Function func : elf->exported_functions()) if(func.size() > 0) ctr++;
    for(LIEF::Function func : elf->imported_functions()) if(func.size() > 0) ctr++;
    cout << +ctr << endl;
}
```
Do you have any idea of what could go wrong ?
By the way, thanks for the great tool.

**Comment by romainthomas** [comment]
Well actually you are not iterating on the same objects (`functions` in Python vs `ctor_functions, exported_functions, imported_functions` in C++) so I guess this is the root cause of this issue.

Feel free to re-open the issue if you have a different behavior when using `functions()` in C++

**Comment by h311d1n3r** [comment]
Hey, thanks for your answer, the `functions` function doesn't seem to exist on C++ that's why I've been using other members. Do you have any working example ?

**Comment by h311d1n3r** [comment]
My bad, I was using `LIEF::Parser::parse` instead of `LIEF::ELF::Parser::parse` as I thought it was returning the same type but it was not and the `ELF::Binary` type returned by the second function indeed has a `functions` member.
