### ISSUE TITLE
Failure to write out a working libicuuc .so file when updating rpath

### ISSUE THREAD

**Issue by starseeker** [lief-project/LIEF#969]
**Describe the bug**
When using https://github.com/BRL-CAD/plief (a utility to call LIEF's C++ API for rpath manipulation) to modifiy a libicuuc file, the result is a .so file that produces an undefined symbol error:

$ ./bin/art share/db/moss.g all.g
./bin/art: symbol lookup error: build/lib/libxerces-c-3.2.so: undefined symbol: UCNV_FROM_U_CALLBACK_SUBSTITUTE_73

As controls, setting the same path with patchelf produces a working .so file, and the non-RPATH enabled version will work with LD_LIBRARY_PATH set.

**To Reproduce**
The full software stack to reproduce the art program is rather involved - I've prepared an archive at https://brlcad.org/~starseeker/icu_issue.tar.gz containing the original .so library, the version produced by patchelf, the LIEF altered non-working version, and a log file of the LIEF processing of the original to produce the non-working version.

**Expected behavior**
LIEF should produce an output that works and avoids the undefined symbol issue.

**Environment (please complete the following information):**
 - System and Version :  Ubuntu 23 
 - Target format: ELF
 - LIEF commit version:  2d9855fc7f9d4ce6325245f8b75c98eb7663db60

**Comment by romainthomas** [comment]
> LIEF commit version: https://github.com/lief-project/LIEF/commit/2d9855fc7f9d4ce6325245f8b75c98eb7663db60c

Can you test with the `master` branch?

On my side (with master) it's working:

```python
import lief
import ctypes

lib = ctypes.cdll.LoadLibrary("./icu_issue/libicuuc.so.73.2-original")
print(lib.UCNV_FROM_U_CALLBACK_SUBSTITUTE_73)

icuuc = lief.ELF.parse("./icu_issue/libicuuc.so.73.2-original")
icuuc.add(lief.ELF.DynamicEntryRpath("/home/cyapp/brlcad/build/lib"))
icuuc.write("./libicuuc-issue.so")

lib = ctypes.cdll.LoadLibrary("./libicuuc-issue.so")
print(lib.UCNV_FROM_U_CALLBACK_SUBSTITUTE_73)
```

The latest `print` is working so the symbol is resolved:

```
<CDLL './icu_issue/libicuuc.so.73.2-original', handle 55866e1fbd50 at 0x7f9b6cf6cf90>
<_FuncPtr object at 0x7f9b6c3c4460>
<CDLL './libicuuc-issue', handle 55866e4b37e0 at 0x7f9b6cf61410>
<_FuncPtr object at 0x7f9b6c3c4870>
```

**Comment by starseeker** [comment]
Confirmed - that appears to have fixed it!  Thank you!

**Comment by wkisme** [comment]
Doesn't work on libicuuc.so.70
PRETTY_NAME="Ubuntu 22.04.1 LTS"
LIEF version(download master branch, build and install)
```
python3 -c "import lief;print(lief.__version__)" 
0.13.2-
```

```
prometheus@courage-machine:~/shrinkwrap/shrinkwrap$ python3 -c "import lief;print(lief.__version__)"
0.13.2-
prometheus@courage-machine:~/shrinkwrap/shrinkwrap$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
>>> import ctypes
>>> lib = ctypes.cdll.LoadLibrary("libicuuc.so.70")
>>> print(lib.UCNV_FROM_U_CALLBACK_STOP_70)
<_FuncPtr object at 0x7f6e0820a8c0>
>>>
>>> icuuc = lief.ELF.parse("libicuuc.so.70")
>>> icuuc.write("./libicuuc-issue.so")
>>> lib = ctypes.cdll.LoadLibrary("./libicuuc-issue.so")
>>> print(lib.UCNV_FROM_U_CALLBACK_STOP_70)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: ./libicuuc-issue.so: undefined symbol: UCNV_FROM_U_CALLBACK_STOP_70


```

**Comment by wkisme** [comment]
Hey bro, why delete my comment @lief-project

**Comment by romainthomas** [comment]
1. Bro?
2. I mention in the issue that it is fixed in:
> Can you test with the master branch?
but you still try with LIEF `0.13.2` so your comment is not relevant and does not bring anything new to this issue. 

Thus, make sure you carefully read the issue. Thank you

**Comment by wkisme** [comment]
> 1. Bro?
> 2. I mention in the issue that it is fixed in:
> 
> > Can you test with the master branch?
> 
> but you still try with LIEF `0.13.2` so your comment is not relevant and does not bring anything new to this issue.
> 
> Thus, make sure you carefully read the issue. Thank you

Embarrassed, i got the wrong version code and i think it's the latest version.
I just tested libicuuc.so.70 on Ubuntu 22.04.1 LTS with the latest version, it's okay now.
Sorry for my carelessness.
And thanks for your patience.
