### ISSUE TITLE
Corrupted ELF generated without any modification

### ISSUE THREAD

**Issue by weimingzha0** [lief-project/LIEF#970]
**Describe the bug**
I tried to rename a symbol in libcudart.so, but the resulting shared lib is corrupted.
Even without changing anything, the new lib is corrupted.

```readelf -sw new_lib.so``` shows something like:
```
   164: 00000000000548e0   517 FUNC    GLOBAL DEFAULT   13 cudaMalloc3D@@<corrupt>
   194: 000000000005bd70   478 FUNC    GLOBAL DEFAULT   13 cudaMallocFromPoolAsync_ptsz@@<corrupt>
```
**To Reproduce**
```python
import lief

lib_name='/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudart.so.12'
lib=lief.parse(lib_name)
sym = lib.get_dynamic_symbol('cudaMalloc')
# sym.name='xxxxMalloc' 
lib.write('/tmp/patched.so')
```

Then run readelf:
readelf -św /tmp/patched.so

**Environment (please complete the following information):**
 - System and Version :Ubuntu 18]
 - Target format (ELF)
 - LIEF commit version: 0.13.2-2d9855fc (I also tried C++ version by building from latest source)

**Comment by romainthomas** [comment]
@weimingzha0 this issue is incomplete and does not contain enough information to reproduce the error:

> but the resulting shared lib is corrupted.

Corrupted: crash? missing symbol?

> Steps to reproduce the behavior:
> `lib_name='/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudart.so.12'`

You didn't attach the library isn't? 

Please re-open an issue with all the details and the information needed to reproduce the error.

Thank you

**Comment by weimingzha0** [comment]
Sorry for no providing enough info to reproduce.

If I run readelf on the original, unmodified .so :
```
readelf -sW /usr/lib/libcudart.so.12 |grep cudaMalloc@
   219: 0000000000052230   421 FUNC    GLOBAL DEFAULT   13 cudaMalloc@@libcudart.so.12
```

If I run the same command on generated .so file (just parse and write):
```
readelf -sW /tmp/patched.so |grep cudaMalloc@
   219: 0000000000053230   421 FUNC    GLOBAL DEFAULT   13 cudaMalloc@@<corrupt>
```
You can see the "<corrupt>" after "@@"

If I use "nm" 
```
 nm -D /tmp/patched.so
nm: /tmp/patched.so: .gnu.version_d invalid entry
nm: /tmp/patched.so: no symbols
```

**Comment by weimingzha0** [comment]
I'm attaching the files
[libs.zip](https://github.com/lief-project/LIEF/files/12752342/libs.zip)

**Comment by weimingzha0** [comment]
@romainthomas I don't have permission to reopen it. Please let me know if anything else is needed to reproduce it

**Comment by romainthomas** [comment]
Thank you @weimingzha0 for the new details. I confirm the bug and I'm going to address it quickly.
