### ISSUE TITLE
Segment* add(const Segment& segment, uint64_t base) throws bad alloc

### ISSUE THREAD

**Issue by Oblivichrash** [lief-project/LIEF#972]
**Describe the bug**
I am using C++ to add new segment in ELF file, but is throws bad alloc with the following [sample.zip](https://github.com/lief-project/LIEF/files/12725616/sample.zip):
```
char big_array[0x40000000] = {0};  // .bss section

int main() {
  return 0;
}
```

**To Reproduce**
add segment/section to any ELF file with big .bss section.

**Environment (please complete the following information):**
 - System and Version: Ubuntu 22.04.3 LTS
 - Target format: ELF x86_64-linux-gnu
 - LIEF commit version: 0.13.2(release)

**Comment by romainthomas** [comment]
As stated in the issue template:

> To Reproduce Steps to reproduce the behavior.

It is incomplete so I tried:

```python
import lief
main = lief.ELF.parse("./main")
s = lief.ELF.Segment()
s.type = lief.ELF.SEGMENT_TYPES.LOAD
s.content = [1] * 0x100
main.add(s)
main.write("./main.updated")
```

On my side, `./main.updated` is running correctly.


If the issue persists, please open an issue with **all** the information to reproduce the error.
