### ISSUE TITLE
Adding a section throws bad alloc

### ISSUE THREAD

**Issue by Oblivichrash** [lief-project/LIEF#973]
**Describe the bug**
I am using C++ to add new segment to [sample.zip](https://github.com/lief-project/LIEF/files/12733726/sample.zip)(main), but is throws bad alloc.

**To Reproduce**
Add segment/section to sample.zip(main) or any ELF file with big .bss section:
```cpp
int main(int argc, char* argv[]) {
  if (argc != 3) {
    std::cerr << "Usage: " << argv[0] << " <Input Binary> <Output Binary>" << '\n';
    return -1;
  }

  std::unique_ptr<LIEF::ELF::Binary> binary = LIEF::ELF::Parser::parse(argv[1]);
  LIEF::ELF::Section new_section{".test"};
  std::vector<uint8_t> data(100, 0);
  new_section.content(std::move(data));
  binary->add(new_section);
  binary->write(argv[2]);
}
```
The sample.zip(main) contains a big array:
```cpp
char big_array[0x40000000] = {0};  // .bss section

int main() {
  return 0;
}
```

**Expected behavior**
The `uint64_t LIEF::ELF::Binary::last_offset_section()` returns wrong offset and should be fixed.

**Environment (please complete the following information):**
 - System and Version : Win 7 Pro x64 (Service Pack 1)
 - Target format ELF (x86_64-linux-gnu, Ubuntu 22.04.3 LTS)
 - LIEF commit version: 0.13.2 (release)

**Additional context**

**Comment by romainthomas** [comment]
Can you try with the `master` branch since on my side, it is actually working without any errors?

**Comment by romainthomas** [comment]
The root cause is likely a memory limitation of your system. Because of the large bss section, LIEF needs (at least) `0x40000000` of memory to rebuild the modified executable.

**Comment by Oblivichrash** [comment]
Thank you for replay, I'm using `master` branch now, and tested on Win 11 22H2 with 16GB RAM, add section success, but there is another problem with above sample, the original file size is 15.4 KB, but the output file size is 1.00 GB, it's too large!!! Maybe the .bss section it not handled properly.

**Comment by romainthomas** [comment]
Yes actually the **generic** approach to add an arbitrary number of segments into an ELF binary is to expand the `.bss` section. If you are not happy with that, you could workaround by replacing the `PT_NOTE` segment.
