### ISSUE TITLE
Better integration with pathlib

### ISSUE THREAD

**Issue by ESPR3SS0** [lief-project/LIEF#974]
When calling 
```python
from pathlib import Path
file = Path("/path/to/file")
lief.parse(file)
```
Lief raises a ``` TypeError: PosixPath("...") ```. 

Many large libraries (such as numpy, pandas, and more) support pathlib objects where strings of paths are also supported. Having better pathlib integration would make using lief more seamless with the rest of the python ecosystem. 

Obviously something like:
```
from pathlib import Path
file = Path("/path/to/file")
lief.parse(str(file.resolve()))
```
Can be used as a work around. But not having to do that work around for other major libraries, then having to do so for lief is not as seamless.

**Comment by romainthomas** [comment]
It sounds a good idea
