### ISSUE TITLE
ELF: Adding segment makes unexecutable binaries

### ISSUE THREAD

**Issue by Laxa** [lief-project/LIEF#98]
Tried to make a simple packer using lief, but it turns out I was never able to make a working binary while using lief.ELF.add_segment() function.

Reproduction steps are easy, just follow https://lief.quarkslab.com/doc/tutorials/05_elf_infect_plt_got.html and at step `Injecting the hook`, lief failed to add the segment on debian unstable.

On some other tests, binaries were successfully written but could not be executed. This seems to happen when adding a segment to a static binary.

Here is a sample program:

```
#include <stdio.h>

int     main(void)
{
    puts("Hello World");
    return 0;
}
```
Then:
```
laxa:tmp.eJeAIIAtPd:14:23:41$ gcc hello_world.c -static
laxa:tmp.eJeAIIAtPd:14:24:00$ checksec --file a.out
[*] '/tmp/tmp.eJeAIIAtPd/a.out'
    Arch:     amd64-64-little
    RELRO:    Partial RELRO
    Stack:    No canary found
    NX:       NX enabled
    PIE:      No PIE (0x400000)
```
Then using the following lief script:
```
import lief

binary = lief.parse('a.out')

segment = lief.ELF.Segment()

segment           = lief.ELF.Segment()
segment.type      = lief.ELF.SEGMENT_TYPES.LOAD
segment.flag      = lief.ELF.SEGMENT_FLAGS.PF_R | lief.ELF.SEGMENT_FLAGS.PF_W | lief.ELF.SEGMENT_FLAGS.PF_X
segment.content   = [1, 2, 3]
segment.alignment = 8
segment           = binary.add_segment(segment, base=0xA0000000)

binary.write('a.out.bin')
```
And doing that right after fails:
```
laxa:tmp.eJeAIIAtPd:14:24:31$ python test_lief.py 
laxa:tmp.eJeAIIAtPd:14:25:18$ chmod +x a.out.bin 
laxa:tmp.eJeAIIAtPd:14:25:23$ ./a.out.bin 
Segmentation fault
laxa:tmp.eJeAIIAtPd:14:25:25$ strace ./a.out.bin 
execve("./a.out.bin", ["./a.out.bin"], [/* 51 vars */]) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x400930} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

**Comment by romainthomas** [comment]
Hi 
I figured out where is the problem:
https://github.com/bminor/glibc/blob/bf7730194fed694a9ce821c306683266a5a7b78b/sysdeps/mach/hurd/i386/init-first.c#L124

In fact when we add a segment in a static (or more generally not relocatable) binary, LIEF moves the program headers at the end of the binary. The assumption of the libc is false.

Fist I suggest you to move to the HEAD version of LIEF (v0.8.0 is coming soon)
Then is this is the workaround:

```python
#!/usr/bin/env python
import lief
binary = lief.parse('hello')

segment = lief.ELF.Segment()
segment.type = lief.ELF.SEGMENT_TYPES.LOAD
segment.content = [1, 2, 3]
segment = binary.replace(segment, binary[lief.ELF.SEGMENT_TYPES.NOTE])

binary.write("hello_updated")
```

**Comment by 0xs4r** [comment]
Hi ! I'm currently doing more or less the same thing (small ELF obfuscator), so I'm doing some test using LIEF and a simple hello world.
```C
#include <stdio.h>

int main(){
    puts("hello world");
}
```
Compiled without pie
```bash
gcc -m32 -fno-pie -no-pie hello.c -o hello
```

Replacing the NOTE segment with an updated segment is fully working, the binary does print "hello world" (I used the code you provided here https://github.com/lief-project/LIEF/issues/98#issuecomment-332287809)
However, if I try to add a new LOAD segment within this script 
```python
import lief

binary = lief.parse('hello')

segment = lief.ELF.Segment()

segment           = lief.ELF.Segment()
segment.type      = lief.ELF.SEGMENT_TYPES.LOAD
segment.content   = [0x41, 0x41, 0x41, 0x41]
segment.alignment = 0x1000
#segment = binary.replace(segment, binary[lief.ELF.SEGMENT_TYPES.NOTE])
binary.add(segment)

binary.write('hello_lief')
```
The generated binary is not properly working 
```bash
s4r@temple ~$ ./hello_lief
Inconsistency detected by ld.so: rtld.c: 1263: dl_main: Assertion `GL(dl_rtld_map).l_libname' failed!
```
It looks like it broke something in dynamic linking
