### ISSUE TITLE
PE exports table bad/wrong addresses

### ISSUE THREAD

**Issue by kweatherman** [lief-project/LIEF#980]
The PE export function address output appears to be wrong.
The names and ordinals are fine but if you look at the export functions in IDA Pro, Ghidra, or a tool like [PE-bear](https://github.com/hasherezade/pe-bear) the actual PE loader resolved function addresses are different from leif export table dump.

All the function address will be off by an inconsistent (but align 16) byte offset like 0x120, 0x140, etc., from the actual function address.
And yes this is going by a normalized offset, not factoring the default base address. 

I've looked at the source a little but it's hard to track since it's so OOP and couldn't see an obvious problem.

P.S. The Python [pefile module](https://github.com/erocarrera/pefile) has the same exact problem.

**Comment by ZehMatt** [comment]
How should someone reproduce this when you haven't provided the PE file?

**Comment by romainthomas** [comment]
That's the point :)

**Comment by romainthomas** [comment]
https://github.com/lief-project/LIEF/blob/3ade2736c0aaefe0f9f5f73e34f9826d30df6c21/.github/ISSUE_TEMPLATE/regular-issue.md?plain=1#L27-L33

**Comment by kweatherman** [comment]
It's a good policy to have. As I walked through an example in my code there was unexpected WOW64 redirection 🙄
In my defense, it's too easy to do this since some of the Windows APIs return "C:\Windows\System32" vs "C:\Windows\SysWOW64" even when they shouldn't.

Pardonne ma stupidité mon ami.
