### ISSUE TITLE
The logic of the determine_elf_class() function doesn't seem right.

### ISSUE THREAD

**Issue by y27988** [lief-project/LIEF#984]
**Describe the bug**
when ELF class from machine type ('CLASS64') does not match ELF class from e_ident ('CLASS32'), determine_elf_class() will return ELF class from machine type ('CLASS64') , doesn't seem right.  Because when compile aarch64 machine target file with -mabi=ilp32 option, the file has machine type is AArch64, but real file class is ELF32。

**To Reproduce**
OS: ubuntu 20.04 x86-64
`# sudo apt install gcc-10-aarch64-linux-gnu `
demo.c
```c
int add(int a, int b) {
    return a + b;
}

```
`# aarch64-linux-gnu-gcc-10 -c -mabi=ilp32 -o demo.o demo.c `
`# readelf -h demo.o `
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           AArch64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          464 (bytes into file)
  Flags:                             0x0
  Size of this header:               52 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           40 (bytes)
  Number of section headers:         11
  Section header string table index: 10

the file class is ELF32, machine is AArch64. real class is ELF32.  but the LIEF library thinks it's an ELF64 file.
`# ./elf_reader demo.o `
Parsing binary: demo.o
Machine     'AARCH64'
Machine Swap'UNDEFINED'
LIEF Endianness:   'LSB'
Binary Endianness: 'LSB'
ELF class from machine type ('CLASS64') does not match ELF class from e_ident ('CLASS32'). The binary has been likely modified.
Start parsing
[+] Parsing Header
Parsing Section
  Elf_Shdr#00.offset: 0x28000000000034 
  Can't parse section #00
    Parse section names
The .shstr index is out of range of the section table
== Parse Segments ==
Can't parse segement #7
segments parsed in 13µs
Binary: demo.o
Interpreter: 
== Header ==
Magic:                           7f 45 4c 46 
Class:                           CLASS32
Endianness:                      LSB
Version:                         CURRENT
OS/ABI:                          SYSTEMV
ABI Version:                     0
Machine type:                    AARCH64
File type:                       RELOCATABLE
Object file version:             CURRENT
Entry Point:                     0x0
Program header offset:           0x464
Section header offset:           11258999068426292
Processor Flag:                  655371 
Header size:                     17407
Size of program header:          53504
Number of program header:        4064
Size of section header:          47360
Number of section headers:       3041
Section Name Table idx:          47360

== Sections ==

== Segments ==
NULL              ---       0         0         0         0         10000001b 6         

UNDEFINED         ---       0         4         100000021 3         54        0         

LOAD              ---       800000027 3         54        0         1         10000002c 

UNDEFINED         ---       2c000000540         100000001 100000035 0         80        

NULL              ---       1         10000004a 2         2c000000800         4         

UNDEFINED         r--       40        c00000170 600000008 c00000004 200000001 0         

UNDEFINED         ---       a00000009 1000000004300000009 0         120000015c0         

== Dynamic entries ==
== Dynamics symbols ==
== Exported symbols ==
== Imported symbols ==
== Dynamic Relocations ==
== PLT/GOT Relocations ==

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04 x86-64
 - Target format ELF
 - LIEF commit version: lief-0.12.3

**Additional context**

**Comment by romainthomas** [comment]
I confirm the issue. Out of curiosity how do you link the final executable?

**Comment by romainthomas** [comment]
Resolved with 9961f6629d56a13958818067d89f25d40019eddd

**Comment by y27988** [comment]
> I confirm the issue. Out of curiosity how do you link the final executable?

Linking this file requires a special glibc library, and there are some problems in the production, and I can't link it successfully. But to be sure, there is a file that uses ilp32's ABI, but runs on an armv8-a machine.

**Comment by y27988** [comment]
In readelf.c，The function named "get_file_header" only uses "e_ident[EI_CLASS]" to determine if the file is 32-bit.

I don't know why "machine" is one of the criteria for file types. Is there an official standard that governs it? Or is there a case where e_ident[EI_CLASS] is inconsistent with machine, but the actual type is the type corresponding to "machine"? @romainthomas

**Comment by romainthomas** [comment]
The kernel does :)
