### ISSUE TITLE
VDEX/hash.hpp error marked override but does not

### ISSUE THREAD

**Issue by panjea** [lief-project/LIEF#989]
directly building LIEF without cmake, using my own build scripts, is failing on latest Ubuntu with this error:

```
/LIEF/VDEX/hash.hpp:36:8: error: ‘void LIEF::VDEX::Hash::visit(const LIEF::VDEX::File&)’ marked ‘override’, but does not override
   36 |   void visit(const File& file)     override;
/LIEF/VDEX/hash.hpp:37:8: error: ‘void LIEF::VDEX::Hash::visit(const LIEF::VDEX::Header&)’ marked ‘override’, but does not override
   37 |   void visit(const Header& header) override;

```

LIEF/VDEX/hash.hpp
```
  //void visit(const File& file)     override;
  //void visit(const Header& header) override;
  virtual void visit(const File& file);
  virtual void visit(const Header& header);
```

above fixes the compilation error, but i'm wondering why.  The macro that defines these methods in Visitor.hpp look correct.
LIEF/visitor_macros.hpp
```
#define LIEF_ABSTRACT_VISITABLE(OBJ) \
  virtual void visit(const OBJ&) {}
```

**Comment by romainthomas** [comment]
The class `LIEF::VDEX::Hash` extends `LIEF::Hash`:

https://github.com/lief-project/LIEF/blob/9961f6629d56a13958818067d89f25d40019eddd/include/LIEF/VDEX/hash.hpp#L27-L39

`LIEF::Hash` extends `Visitor`:

https://github.com/lief-project/LIEF/blob/9961f6629d56a13958818067d89f25d40019eddd/include/LIEF/hash.hpp#L31

And in this class, they are virtual:

https://github.com/lief-project/LIEF/blob/9961f6629d56a13958818067d89f25d40019eddd/include/LIEF/Visitor.hpp#L665-L669

> directly building LIEF without cmake, using my own build scripts

Could share the different steps/scripts to reproduce the error?
