### ISSUE TITLE
Publish Wheels for Python 3.12

### ISSUE THREAD

**Issue by ankurvdev** [lief-project/LIEF#990]
Add Wheels for Python 3.12

**Comment by ankurvdev** [comment]
Looks like its already supported.
I was able to build from source.
Just needs to be published to pypi

Edited Title

**Comment by romainthomas** [comment]
The CI is up for Python 3.12 and it will be released along with `LIEF 0.14.0`

**Comment by doronz88** [comment]
Any update on the release schedule for this version?
Currently python projects depending on this package take quite a lot of time to finish installation due to the lack of it.

**Comment by ostefano** [comment]
Hi folks, any update on this?

**Comment by romainthomas** [comment]
Scheduled for next weekend
