### ISSUE TITLE
MachO[armv7]: indirectsymoff chanegd without doing anything

### ISSUE THREAD

**Issue by AvenGeeker** [lief-project/LIEF#993]
**Describe the bug**
I try to rename the mach-o dynamic library's exported symbols，but I got problem in iOS  architecture armv7.
I found that when I just opened a dynamic library with lief and saved it as a new dynamic library without doing anything , I had a problem.

`Traceback (most recent call last):
  File "/Users/geekeraven/tmp/test_lief/test_symbols.py", line 31, in <module>
    test_armv7()
  File "/Users/geekeraven/tmp/test_lief/test_symbols.py", line 27, in test_armv7
    assert checked, err
AssertionError: 
        LC_DYSYMTAB.nindirect out of place:
          Expecting offset: 0x2443b4 while it is 0x2443b8`

**To Reproduce**
1. try it in macOS，python with lief 0.13.2.   pip install lief==0.13.2
2. download the attachment and decompress it. 
[test_lief.zip](https://github.com/lief-project/LIEF/files/13263710/test_lief.zip)
3. cd to "test_lief" folder
4. rum cmd:
`python test_symbols.py `
you can also run "sh compare.sh" in your mac with VS Code
`sh compare.sh`

you will get a check error below:
![image](https://github.com/lief-project/LIEF/assets/46774774/12b3f612-3dc9-4d54-bbd7-7f09fbc4b4df)

if you run with "sh compare.sh"，The otool comparison result is automatically opened:
![image](https://github.com/lief-project/LIEF/assets/46774774/7e2582b2-905e-46d1-bbcf-d9a18ba920d7)

My confusion is that I just open and save and don't do anything, and indirectsymoff changes

**Expected behavior**
There will be no change to indirectsymoff

**Environment (please complete the following information):**
 - Mac
 - Python 3
 - VS Code [optional]

**Additional context**
**the test_symbols.py:**
#!/usr/bin/env python
import os
import lief

def test_armv7():
    bin_path = "./origin_binary_armv7"
    output = "./origin_binary_armv7_2"
    if os.path.exists(output):
        os.remove(output)

    #open a binary
    original = lief.MachO.parse(bin_path)

    #save as new
    original.write(output)

    #check original layout， normal here
    checked, err = lief.MachO.check_layout(original)

    #open new binary
    new = lief.parse(output)

    #check new  layout， **error here**
    checked, err = lief.MachO.check_layout(new)
    
    assert checked, err

if __name__ == '__main__':
    test_armv7()

**the compare.sh:**
##!/bin/bash

CURRENT_DIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd)

original=${CURRENT_DIR}/original.txt
new=${CURRENT_DIR}/new.txt

original_binary=${CURRENT_DIR}/origin_binary_armv7
new_binary=${CURRENT_DIR}/origin_binary_armv7_2

if [ -e "$original" ];then
    rm -rf $original
fi

if [ -e "$new" ];then
    rm -rf $new
fi

res=`python test_symbols.py`

echo $res

otool -l $original_binary >> $original
otool -l $new_binary >> $new

code --diff $original $new

**Comment by AvenGeeker** [comment]
@romainthomas I try to debug in source code，It's not a parser problem, it's a builder problem, nlist_table does 8-bit alignment, but on armv7, it should be 4-bit alignment, and 8-bit alignment will shift the result by 4 bits

![image](https://github.com/lief-project/LIEF/assets/46774774/3d4b9b58-8c10-4170-a537-53dc62b81eb1)

**Comment by romainthomas** [comment]
Thank you very much @AvenGeeker for identifying this fix! It is integrated with commit https://github.com/lief-project/LIEF/commit/6b737986baa3b577bde7d35d8dbacfd328817be2
