### ISSUE TITLE
The MachO parser accepts non-UTF8 symbol names from the exports trie

### ISSUE THREAD

**Issue by PaulDance** [lief-project/LIEF#995]
**Describe the bug**
If one uses the Mach-O parser on a file that has invalid (non-UTF8) symbol names in its dyld exports trie, it ends up being accepted and validated with meaningless export info.

**To Reproduce**

 * Use the exact same Python code and test file than in #994. The compile-time debug options are not mandatory this time, however.
 * The following with-export-info symbol names can be observed from the Python script's output:

```


\x89\xe7\xff8`
\x89\xe7\xff8`
```

while ``str(b"\x89\xe7\xff8`", encoding="utf-8")`` fails on `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte`.

**Expected behavior**

The Mach-O executable file inside the FAT archive should be rejected, or at least the exports trie parsing should fail in this case and avoid including broken symbols in the resulting object. After that, there should not be any symbols with some export info.

Indeed, the symbol names are read from memory using `BinaryStream::read_string`, which only looks for null-terminated strings. However, the comments included in XNU's [`loader.h`](https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/EXTERNAL_HEADERS/mach-o/loader.h#L1366-L1400) state that the exports trie's strings must be null-terminated *and* valid UTF-8, which I should think makes it a "specification" requirement (the only one close enough that I could find, really). LIEF's exports trie parsing should therefore enforce that as well.

**Environment:**
 - System and Version: Debian testing.
 - Target format: Mach-O.
 - LIEF commit version: `0.13.2-`.

**Additional context:**
From what I can see, the only place where `read_string` is used during the exports trie parsing is in the recursive for loop:

```c++
  for (size_t i = 0; i < *nb_children; ++i) {
    auto suffix = stream_->read_string();
```

towards the end of the `BinaryParser::parse_export_trie` method. There should thus not be too much to change for this part.

UTF-8 *might* need to be enforced for strings other than those in the exports trie, but I don't know for now.

**Comment by romainthomas** [comment]
Hello @PaulDance

Thank you so much for providing all these details and taking time to share
you thoughts and propose a solution. Highly (highly) appreciated.

Now regarding the issue itself. I agree that the `TODO` in the code should be replaced by a more comprehensive message and I'm ok with the `LIEF_ERR(...);`
message. But [...] :) I'm do not completely agree with:

> followed by a return make_error_code(lief_errors::read_error);, or something like that.
> After that, there should not be any symbol in the symbols table.

If I'm not wrong, you expect to have -- somehow -- the same representation with LIEF as the Mach-O loader. 

The design choice in LIEF is to provide all the information as long as it is possible to provide them and to avoid making *strong** assumptions about what the loader would do.

The loaders can evolve and nothing could prevent Apple to relax the condition on the library's ordinal even though right now the loader (fails?) to load the binary you provided.

**Comment by PaulDance** [comment]
Thanks for the detailed answer. Indeed, I would have expected the LIEF parser to comply with the "specification". From my point of view, the parsing just ends up being lost in random bytes and the reported data does not make much sense as the original bytes did not either.

However, I understand your design choices and can stand by them. If your decision is final, then this issue can be closed and I'll try to add some additional checks on my end.
