### ISSUE TITLE
Missing LINKEDIT segment after parsing and writing with LIEF

### ISSUE THREAD

**Issue by vmx-joey** [lief-project/LIEF#997]
**Describe the bug**
After parsing and writing a binary with a LINKEDIT segment, the segment is missing in the output binary. The load command is still there. 

**To Reproduce**
The binary can be as simple as 
```
int main()
{

}
```
Compiled then parsed with 
```
    auto binary = LIEF::Parser::parse(input_binary_path);
    binary->write(input_binary_path);
```
And the LINKEDIT segment will not be in the binary anymore.

**Expected behavior**
![Screenshot 2023-11-07 at 14 43 32](https://github.com/lief-project/LIEF/assets/69521990/468d8a38-47c4-4b4a-a512-69bcc8cc29b5)

**Environment (please complete the following information):**
 - System and Version : macOS Ventura 13.6.1
 - Target format Mach-O
 - LIEF commit version: ``0.13.2-2d9855fc``

**Additional context**
Unclear if it's related to this issue https://github.com/lief-project/LIEF/issues/945 and it is because it's a segment without a section name?

**Comment by romainthomas** [comment]
Did you try with the `master` branch? Could you also attach the `input_binary_path` you compiled?

**Comment by vmx-joey** [comment]
I did with the nightly build, CS 0c472ca.

One thing I got wrong, it's not the compiled binary I'm parsing with LIEF, but the dSYM binary produced by dsymutil being ran on the compiled binary.

[main.zip](https://github.com/lief-project/LIEF/files/13284126/main.zip)

`input_binary_path` is therefore the path to this dsym binary attached.

**Comment by romainthomas** [comment]
With this code:

```python
import lief
main = lief.parse("./main")
for seg in main.segments:
    print(seg.name)

main.write("./main.write")
write: lief.MachO.Binary = lief.parse("./main.write")
print("Segment in write")
for l in write.segments:
    print(l.name)
```

It outputs:

```
__PAGEZERO
__TEXT
__LINKEDIT
__DWARF
Segment in write
__PAGEZERO
__TEXT
__LINKEDIT
__DWARF
```

So the `__LINKEDIT` segment is present.

**Comment by vmx-joey** [comment]
```
>>> import lief
>>> main = lief.parse("./main")
>>> for seg in main.segments:
...     print(seg.name)
...
__PAGEZERO
__TEXT
__LINKEDIT
__DWARF
>>> main.write("./main.write")
Can't rebuild LC_SYMTAB: LC_DYSYMTAB not found
>>> write: lief.MachO.Binary = lief.parse("./main.write")
Can't find the segment that contains the LC_SYMTAB.n_list
>>> print("Segment in write")
Segment in write
>>> for l in write.segments:
...     print(l.name)
...
__PAGEZERO
__TEXT
__LINKEDIT
__DWARF
```
Though this is back with the 0.13.2-2d9855fc release again, I'll have to try master. It still says the segment exists here, but in Hopper the data is gone, only the Load Command remains

**Comment by romainthomas** [comment]
Yes let me know if the issue is still there with the nightly wheels.

**Comment by vmx-joey** [comment]
Works on Master, looks like it was fixed here https://github.com/lief-project/LIEF/commit/719249a2a5bd048b30e718a191b4e1d64daaaf65. Do you have any ETA on a 14 release? Thanks

**Comment by romainthomas** [comment]
Likely by the end of the year
