### ISSUE TITLE
`Parser::parse` crashes for PE files on Windows 7

### ISSUE THREAD

**Issue by rdbo** [lief-project/LIEF#998]
----------------------------------

**Description**

When calling `Parser::parse` on Windows 7 for a PE file, the program crashes, giving the error:
```
cannot seek array iterator after end
```
I need this fixed because my memory library relies on LIEF for dumping symbols.

**Context**

LIEF version: latest commit as of now: df97777811ad84134f79694d73cba6c3700c829c
OS: Windows 7 x64
Visual Studio Build Tools 2022 (building for x86)
My contribution to get this premium issue (merged PR that fixes compilation error on Windows): #949 

----------------------------------

Code that crashes (from my rdbo/libmem repo):
```c
#include <LIEF/PE.hpp>

using namespace LIEF::PE;

LM_PRIVATE lm_bool_t
_LM_EnumPeSyms(lm_module_t *pmod,
	       lm_bool_t  (*callback)(lm_symbol_t *psymbol,
				      lm_void_t   *arg),
	       lm_void_t *arg)
{
	lm_symbol_t sym;
	std::unique_ptr<const Binary> binary;

	if (!is_pe(pmod->path))
		return LM_FALSE;

	binary = Parser::parse(pmod->path); /* <----- CRASH HERE, pmod->path is a valid PE */

	for (const ExportEntry &symbol : binary->get_export()->entries()) {
		sym.name = (lm_cstring_t)symbol.name().c_str();
		sym.address = (lm_address_t)LM_OFFSET(pmod->base, symbol.value());
		if (!callback(&sym, arg))
			break;
	}

	return LM_TRUE;
}
```

Error:
![2023-11-19_21-31-18](https://github.com/lief-project/LIEF/assets/57117082/bd6dd3b1-01c1-4f4d-a0a1-a139e95a713c)

**Comment by rdbo** [comment]
NOTE: If I remember correctly, this used to work at commit 50eaed3ae534329ac62a9363554be5f36574c7d0

**Comment by romainthomas** [comment]
Can you attach the binary?

**Comment by rdbo** [comment]
@romainthomas Minimal reproducible exemple below, already compiled.
main.cpp:
```cpp
#include <LIEF/PE.hpp>

using namespace LIEF::PE;

typedef struct {
        char *name;
        void *address;
} symbol_t;

bool enum_symbols(char *path, bool callback(symbol_t *, void *), void *arg)
{
        symbol_t sym;
        std::unique_ptr<const Binary> binary;

        if (!is_pe(path))
                return false;

        binary = Parser::parse(path);

        for (const ExportEntry &symbol : binary->get_export()->entries()) {
                sym.name = (char *)symbol.name().c_str();
                sym.address = (void *)symbol.value();
                if (!callback(&sym, arg))
                        break;
        }

        return true;
}

bool callback(symbol_t *sym, void *arg)
{
        printf("  %s %p\n", sym->name, sym->address);
        return true;
}

int main(int argc, char **argv)
{
        if (argc < 2) {
                printf("missing binary path argument\n");
                return -1;
        }

        printf("Symbols: \n");
        enum_symbols(argv[1], callback, NULL);

        return 0;
}
```

NOTE: The file extension is `tar.xz`, GitHub won't let me upload `tar.xz` and `tar.gz` is too big.
Extract with: `tar -xvf <file>.tar.gz`
[lief-test.tar.gz](https://github.com/lief-project/LIEF/files/13419391/lief-test.tar.gz)

**Comment by rdbo** [comment]
@romainthomas Even in this example, it just crashes upon calling `Parser::parse` with a valid path (`main.exe`).

**Comment by romainthomas** [comment]
It has been fixed [...]

**Comment by rdbo** [comment]
@romainthomas I updated the LIEF library on my minimal test and recompiled on my system, now it's giving a different crash. Also, it no longer crashes in the `Parser::parse`, instead it crashes on `binary->get_export()->entries()`
![2023-11-21_11-06-33](https://github.com/lief-project/LIEF/assets/57117082/d3cb9b41-2c1a-4e97-b6df-40fb36d71e34)

**Comment by rdbo** [comment]
I just tested and the fix worked, but I had to change my code a bit.
`binary->get_export()` will return `NULL` if there are no exports, so I had to add a check for that.
Anyways, thank you for the fix :+1:
